/**
 * Rule: navigation/href-empty-fragment
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:2.1.1, wcag21:2.1.1
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set; and notification of changes to these items
 * > is available to user agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * An `<a>` element with a placeholder href — `href="#"` (bare fragment with no
 * target) or `href=""` (empty, which the HTML spec resolves to the current
 * document URL — so activating reloads the page) — announces as a link but
 * does not navigate meaningfully. The semantic role is wrong: the affordance
 * promises navigation the href can never deliver.
 *
 * Companion rule `navigation/href-javascript-scheme` covers the `javascript:`
 * scheme variants. Splitting these surfaces means an agent suppressing one
 * shape doesn't silently suppress the other — see Q7-NAVIGATION-HREF-RULE-RENAME
 * for the granularity rationale.
 *
 * Distinct from `navigation/link-no-href` (which targets `<a onClick>` without
 * any real navigation target). This rule targets the href VALUE itself,
 * regardless of whether an onClick is attached — a bare `<a href="">Forgot
 * password?</a>` (common in legacy form pages wired up later) is semantically
 * broken even without an event handler.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  findHtmlElementsByTag,
  findJsxElementsByTag,
  getHtmlAttribute,
  getJsxAttribute,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, TsxModule } from "../../types/ast.ts";

type PlaceholderKind = "bare-fragment" | "empty";

/**
 * Classifies a raw href string as `bare-fragment` (`"#"`), `empty` (`""`),
 * or `null` when the value is real navigation. Whitespace is tolerated
 * aggressively — real-world placeholders appear as `"  #  "`, `"   "`.
 *
 * What this function does NOT flag (legitimately navigating):
 *
 *   - `"#fragment-id"` — real in-page navigation; browser scrolls to and
 *     focuses the matching id. Silent.
 *   - Any other scheme (`"mailto:"`, `"tel:"`, `"/path"`, `"https://…"`) —
 *     real navigation. Silent.
 *   - `"javascript:..."` — handled by the companion rule
 *     `navigation/href-javascript-scheme`. Silent here.
 */
function classifyPlaceholder(value: string | null): PlaceholderKind | null {
  if (value === null) return null;
  const trimmed = value.trim();
  if (trimmed === "") return "empty";
  if (trimmed === "#") return "bare-fragment";
  return null;
}

export const rule = defineRule({
  id: "navigation/href-empty-fragment",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:2.1.1", "wcag21:2.1.1"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      'Flags <a> elements with placeholder href values that announce as links but do not navigate meaningfully: bare `href="#"` (no fragment id, nothing to scroll to) and empty `href=""` (which the HTML spec resolves to the current document URL — activating reloads the page rather than navigating). Whitespace is trimmed before matching, so `"  #  "` and `"   "` are flagged. Companion rule `navigation/href-javascript-scheme` covers the `javascript:` scheme variants. Use <button type="button"> for actions, or put a real URL in href for navigation.',
    rationale:
      'Assistive technology decides how to announce a control from its role: `<a>` with an href maps to the link role. The browser treats `href="#"` and `href=""` as links (the first as an in-page anchor, the second as a self-link), but neither shape navigates meaningfully — the user hears \'link,\' activates it, and either nothing happens or the page silently reloads (losing form state). The semantic role contradicts the runtime behavior.\n\nSpecifically the matched shapes:\n\n  - Bare `href="#"` with no fragment id — there is no target to scroll to, so the anchor announces as a link but navigates nowhere. (`href="#section-id"` pointing at a real id is real in-page navigation and stays silent.)\n  - Empty `href=""` — per HTML spec this resolves to the current document URL, so activating the link reloads the page rather than navigating. The `link-no-href` rule only catches the empty case when an onClick is attached (its scope is the `<a onClick>` keyboard-trap pattern); the bare `<a href="">Forgot password?</a>` case (common in legacy form pages wired up later) belongs here.\n  - Whitespace is trimmed before classification, so `"  #  "` matches as bare-fragment and `"   "` matches as empty.\n\nSplit out from the umbrella `navigation/href-placeholder` rule (which previously also covered `javascript:` schemes) so an agent suppressing one shape doesn\'t silently suppress the other — the two surfaces have different fix profiles. JSX expression-form `href={…}` is opaque at static time and intentionally not flagged.',
    goodExample: `<a href="/forgot-password">Forgot password?</a>`,
    badExample: `<a href="">Forgot password?</a>`,
    normativeQuote:
      "For all user interface components … the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#keyboard",
      "https://html.spec.whatwg.org/#the-a-element",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const anchor of findHtmlElementsByTag(doc, "a")) {
    const hrefValue = getHtmlAttribute(anchor, "href");
    const kind = classifyPlaceholder(hrefValue);
    if (!kind) continue;
    emit(buildViolation(anchor.loc.start, kind));
  }
}

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const anchor of findJsxElementsByTag(module, "a")) {
    const attr = getJsxAttribute(anchor, "href");
    if (!attr?.value) continue;
    // Expression-form `href={…}` is opaque at static time — surface only
    // deterministic evidence per the AI-first consumer model.
    if (attr.value.kind !== "StringLiteral") continue;
    const kind = classifyPlaceholder(attr.value.value);
    if (!kind) continue;
    emit(buildViolation(anchor.loc.start, kind));
  }
}

function buildViolation(
  loc: { line: number; column: number },
  kind: PlaceholderKind,
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  if (kind === "empty") {
    return {
      severity: "error",
      location: { filePath: "", line: loc.line, column: loc.column },
      message: `<a href=""> has an empty href — per HTML spec it resolves to the current page URL, so activating the link reloads the page rather than navigating. The anchor announces as a link but its destination is broken.`,
      suggestion: `change \`<a href="">\` to either \`<a href="/real/path">\` (if it should navigate — empty href reloads the current page, almost never the author's intent) or \`<button type="button">\` (if the control triggers an action with a click handler attached elsewhere). Common case: "Forgot password?" links that the author meant to wire up later — supply the real route.`,
    };
  }
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<a href="#"> has no fragment target — the anchor announces as a link but navigates nowhere.`,
    suggestion: `change \`<a href="#">\` to \`<button type="button">\` — a bare \`#\` href announces as a link but navigates nowhere. If the control triggers an action, a <button> is the correct role. If it should navigate to an in-page section, use \`href="#section-id"\` pointing at an actual id on the page.`,
  };
}
