/**
 * Rule: navigation/href-javascript-scheme
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:2.1.1, wcag21:2.1.1
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set; and notification of changes to these items
 * > is available to user agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * An `<a>` element with a `javascript:` scheme href — `javascript:void(0)`,
 * `javascript:void 0`, `javascript:;`, `javascript:`, `javascript:alert(1)`,
 * the case-insensitive `JAVASCRIPT:…` variants, plus the bare-`javascript`-no-colon
 * typo — behaves like a button but announces as a link. Assistive technology
 * says "link," the user expects navigation, the page either no-ops or runs
 * an arbitrary script. The semantic role is wrong.
 *
 * Companion rule `navigation/href-empty-fragment` covers the placeholder-href
 * shapes that don't use the `javascript:` scheme (`href="#"`, `href=""`,
 * whitespace-only). Splitting these surfaces means an agent suppressing one
 * shape doesn't silently suppress the other — see
 * for the granularity rationale.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  findHtmlElementsByTag,
  findJsxElementsByTag,
  getHtmlAttribute,
  getJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";
import { isDomOriginExtension } from "../../utils/path.ts";

/**
 * Returns true when the (trimmed, case-insensitive) href value uses the
 * `javascript:` scheme. The scheme comparison is case-insensitive because
 * URL schemes are case-insensitive per RFC 3986 §3.1 and browsers treat
 * them that way. Whitespace inside the scheme is tolerated (`"javascript: void(0)"`).
 *
 * The bare token `"javascript"` (no colon — technically a relative path) is
 * also matched, because in practice it's always an author typo meant to be
 * `javascript:void(0)`. The fix suggestion is identical.
 */
function isJavascriptScheme(value: string | null): boolean {
  if (value === null) return false;
  const trimmed = value.trim();
  if (trimmed === "") return false;
  const lowered = trimmed.toLowerCase();
  if (lowered === "javascript") return true;
  return /^javascript\s*:/i.test(trimmed);
}

export const rule = defineRule({
  id: "navigation/href-javascript-scheme",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:2.1.1", "wcag21:2.1.1"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx", ".vue", ".svelte"],
  },
  docs: {
    description:
      'Flags <a href="javascript:..."> in any of its forms — `javascript:void(0)`, `javascript:void 0`, `javascript:;`, `javascript:` (empty body), `javascript:alert(1)` and other arbitrary expressions, plus `JAVASCRIPT:…` and other case-insensitive variants (RFC 3986 §3.1). The bare token `javascript` (no colon — almost always an author typo for `javascript:void(0)`) is also flagged. Whitespace is trimmed before matching, so `"  javascript: void(0)  "` matches. Companion rule `navigation/href-empty-fragment` covers the non-scheme placeholder shapes (`href="#"`, `href=""`). Use `<button type="button">` for actions, or put a real URL in href for navigation. JSX expression-form `href={…}` is opaque at static time and intentionally not flagged — the agent reads the source if the call site looks suspicious.',
    rationale:
      "Assistive technology decides how to announce a control from its role: `<a>` with an href maps to the link role. The browser treats every `javascript:` URI as a link (one with an inline script for its destination), but the click never navigates anywhere — the user hears 'link,' activates it, and either nothing happens or an arbitrary script runs. The semantic role contradicts the runtime behavior. Static detection is reliable because the href attribute's string value is the full signal.\n\nSplit out from the umbrella `navigation/href-placeholder` rule so an agent suppressing the JS-scheme variant (often \"we know this is a button styled as a link, this codebase uses jQuery patterns\") doesn't also silently suppress the bare-`#`/empty-href variants (which usually want a real route, not a button). The two shapes have different fix profiles; one rule ID per shape lets the agent triage them independently.",
    goodExample: `<button type="button" onClick={handleClick}>Toggle menu</button>`,
    badExample: `<a href="javascript:void(0)" onClick={handleClick}>Toggle menu</a>`,
    normativeQuote:
      "For all user interface components … the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#keyboard",
      "https://html.spec.whatwg.org/#the-a-element",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      // Belt-and-braces DOM-origin gate: an `<a href="javascript:…">`
      // substring inside a packed plugin or minified `.js` bundle is not a
      // real anchor — it's a string the runtime injects somewhere else, or
      // a JS-API wrapper, or a template literal that a build step
      // interpolates. Only act on JSX nodes parsed out of `.tsx` / `.jsx`
      // (and the JSX-bearing `.mdx` / `.astro` aliases).
      if (!isDomOriginExtension(ctx.filePath)) return;
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

/**
 * Tag/component names whose presence as an ancestor of a flagged anchor
 * indicates the anchor is sitting inside docs-example markup — a
 * demonstration of a (possibly anti-pattern) shape, not a live control
 * the user can click. The agent reads the surrounding source to confirm;
 * this hint just shortens the dismissal path.
 *
 * Reason-enrichment only — emission stays at the existing severity.
 * Per AI-first doctrine ("No heuristic suppression," "Surface, don't
 * suppress"), the rule still fires; the hint is additive context the
 * agent reads per-finding. Matching is case-insensitive on the tag/
 * component name, plus a class-substring probe for the author-defined
 * docs-example wrappers (`example`, `codeblock`, `prism`, `highlight`).
 */
const EXAMPLE_WRAPPER_TAGS: ReadonlyArray<{
  readonly match: (tag: string) => boolean;
  readonly hint: string;
}> = [
  // Component wrappers — case-insensitive match on the tag name.
  { match: (t) => t.toLowerCase() === "example", hint: "<Example> component" },
  { match: (t) => t.toLowerCase() === "codeblock", hint: "<CodeBlock> component" },
  { match: (t) => t.toLowerCase() === "demo", hint: "<Demo> component" },
  { match: (t) => t.toLowerCase() === "playground", hint: "<Playground> component" },
  // Native code-display elements.
  { match: (t) => t.toLowerCase() === "pre", hint: "<pre> block" },
  { match: (t) => t.toLowerCase() === "code", hint: "<code> block" },
  { match: (t) => t.toLowerCase() === "samp", hint: "<samp> block" },
];

/** Class-name substrings (lowercased) that mark a wrapper as docs-example. */
const EXAMPLE_CLASS_SUBSTRINGS = ["example", "codeblock", "prism", "highlight"] as const;

interface ExampleHint {
  readonly hint: string;
}

/**
 * Returns the docs-example hint for the closest ancestor matching the
 * configured tag-or-class set, or `null` if no such ancestor exists.
 * The hint is the short label appended to the rule's reason text — e.g.
 * `"<Example> component"`, `"<pre> block"`, `"wrapper.class~=\"example\""`.
 */
function findHtmlExampleHint(
  anchor: HtmlElement,
  parents: ReadonlyMap<HtmlElement, HtmlElement>,
): ExampleHint | null {
  let cursor: HtmlElement | undefined = parents.get(anchor);
  while (cursor !== undefined) {
    const here = cursor;
    const tagHit = EXAMPLE_WRAPPER_TAGS.find(({ match }) => match(here.tagName));
    if (tagHit) return { hint: tagHit.hint };
    const className = getHtmlAttribute(cursor, "class");
    const classHit = matchExampleClass(className);
    if (classHit !== null) return { hint: `wrapper class="${classHit}"` };
    cursor = parents.get(cursor);
  }
  return null;
}

function findJsxExampleHint(
  anchor: JsxElement,
  parents: ReadonlyMap<JsxElement, JsxElement>,
): ExampleHint | null {
  let cursor: JsxElement | undefined = parents.get(anchor);
  while (cursor !== undefined) {
    const here = cursor;
    const tagHit = EXAMPLE_WRAPPER_TAGS.find(({ match }) => match(here.tagName));
    if (tagHit) return { hint: tagHit.hint };
    // JSX uses `className`; some authors still write `class` (pre-React-strict
    // codebases or non-React JSX). Probe both.
    const attr = getJsxAttribute(cursor, "className") ?? getJsxAttribute(cursor, "class");
    if (attr?.value?.kind === "StringLiteral") {
      const classHit = matchExampleClass(attr.value.value);
      if (classHit !== null) return { hint: `wrapper className="${classHit}"` };
    }
    cursor = parents.get(cursor);
  }
  return null;
}

/**
 * Returns the matched class-name substring (lowercased), or `null`.
 * Matching is whitespace-tokenized + substring-within-token so a token
 * like `prism-highlight` matches both `prism` and `highlight`, while a
 * token like `not-an-example` still matches `example`. The agent verifies
 * by reading the file; this is additive context, not a gate.
 */
function matchExampleClass(value: string | null): string | null {
  if (value === null) return null;
  const lowered = value.toLowerCase();
  for (const needle of EXAMPLE_CLASS_SUBSTRINGS) {
    if (lowered.includes(needle)) return needle;
  }
  return null;
}

/** Builds the parent map for HTML elements in one walk. */
function buildHtmlParentMap(doc: HtmlDocument): Map<HtmlElement, HtmlElement> {
  const out = new Map<HtmlElement, HtmlElement>();
  for (const el of walkHtmlElements(doc)) {
    for (const child of el.children) {
      if (child.kind === "HtmlElement") out.set(child, el);
    }
  }
  return out;
}

/** Builds the parent map for JSX elements in one walk. */
function buildJsxParentMap(module: TsxModule): Map<JsxElement, JsxElement> {
  const out = new Map<JsxElement, JsxElement>();
  for (const el of walkJsxElements(module)) {
    for (const child of el.children) {
      if (child.kind === "JsxElement") out.set(child, el);
    }
  }
  return out;
}

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  const anchors = findHtmlElementsByTag(doc, "a");
  if (anchors.length === 0) return;
  // Build the parent map lazily — only when there's at least one anchor.
  // Pays the walk cost once per file rather than once per anchor.
  let parents: Map<HtmlElement, HtmlElement> | null = null;
  for (const anchor of anchors) {
    const hrefValue = getHtmlAttribute(anchor, "href");
    if (!isJavascriptScheme(hrefValue)) continue;
    parents ??= buildHtmlParentMap(doc);
    const exampleHint = findHtmlExampleHint(anchor, parents);
    emit(buildViolation(anchor.loc.start, hrefValue ?? "", exampleHint));
  }
}

function checkJsx(module: TsxModule, emit: Emit): void {
  const anchors = findJsxElementsByTag(module, "a");
  if (anchors.length === 0) return;
  let parents: Map<JsxElement, JsxElement> | null = null;
  for (const anchor of anchors) {
    const attr = getJsxAttribute(anchor, "href");
    if (!attr?.value) continue;
    // Expression-form `href={…}` is opaque at static time — could be a real
    // URL, a placeholder string, or anything else. Per the AI-first consumer
    // model, surface only deterministic evidence; the agent reads the source
    // if the call site looks suspicious.
    if (attr.value.kind !== "StringLiteral") continue;
    if (!isJavascriptScheme(attr.value.value)) continue;
    parents ??= buildJsxParentMap(module);
    const exampleHint = findJsxExampleHint(anchor, parents);
    emit(buildViolation(anchor.loc.start, attr.value.value, exampleHint));
  }
}

function buildViolation(
  loc: { line: number; column: number },
  rawHref: string,
  exampleHint: ExampleHint | null,
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const display = rawHref.length > 60 ? `${rawHref.slice(0, 60)}…` : rawHref;
  // Reason-enrichment only — severity stays `error`. When the anchor sits
  // inside a docs-example wrapper, the hint is a one-read dismissal signal
  // for the agent (the violation is still real for live consumers, but the
  // demonstration shape often explains why a real codebase has it).
  const exampleSuffix = exampleHint
    ? ` (inside ${exampleHint.hint} — likely demonstration code, verify the anchor renders for real users before fixing)`
    : "";
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<a href="${display}"> uses a javascript: scheme — the anchor announces as a link but does not navigate, contradicting its role.${exampleSuffix}`,
    suggestion: `change \`<a href="${display}">\` to \`<button type="button">\` — this control does not navigate, so it should announce as a button, not a link. If you need anchor-style visuals, style the <button> with CSS instead of giving an anchor a non-URL href. If the handler actually navigates somewhere, put that URL directly in href and drop the javascript: wrapper.${exampleSuffix}`,
  };
}
