/**
 * Rule: navigation/href-empty-fragment
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:2.1.1, wcag21:2.1.1
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set; and notification of changes to these items
 * > is available to user agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * An `<a>` element with a placeholder href — `href="#"` (bare fragment with no
 * target) or `href=""` (empty, which the HTML spec resolves to the current
 * document URL — so activating reloads the page) — announces as a link but
 * does not navigate meaningfully. The semantic role is wrong: the affordance
 * promises navigation the href can never deliver.
 *
 * Companion rule `navigation/href-javascript-scheme` covers the `javascript:`
 * scheme variants. Splitting these surfaces means an agent suppressing one
 * shape doesn't silently suppress the other — see Q7-NAVIGATION-HREF-RULE-RENAME
 * for the granularity rationale.
 *
 * Distinct from `navigation/link-no-href` (which targets `<a onClick>` without
 * any real navigation target). This rule targets the href VALUE itself,
 * regardless of whether an onClick is attached — a bare `<a href="">Forgot
 * password?</a>` (common in legacy form pages wired up later) is semantically
 * broken even without an event handler.
 */

import { defineRule } from "../../api/plugin.ts";
import { getHtmlAttribute, getJsxAttribute } from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlNode,
  JsxElement,
  TsxModule,
} from "../../types/ast.ts";
import { isDomOriginExtension } from "../../utils/path.ts";

type PlaceholderKind = "bare-fragment" | "empty";

/**
 * Pagination-context class tokens. When any ancestor `class` /
 * `className` attribute contains one of these (case-insensitive,
 * substring match on space-split tokens), the placeholder anchor is
 * almost certainly a pagination control — Bootstrap, Tailwind,
 * Foundation, and bespoke designs all converge on these names. The
 * fix path then branches in the suggestion text: for action-only
 * controls (e.g. dynamic page-jump buttons firing client-side scripts)
 * → `<button type="button">`; for navigation controls → supply a real
 * href pointing at the target page.
 *
 * The substring match is intentional: `page-link` is the Bootstrap
 * leaf class, `pagination` / `paginator` are the wrapper-list classes,
 * `pager` is older Bootstrap 3 / common bespoke. A class like
 * `mypagination` will match — that's fine: a class containing the
 * word "pagination" is a pagination context by every reasonable read,
 * and the suggestion text is honest in that frame too.
 */
const PAGINATION_CLASS_TOKENS = [
  "pagination",
  "paginator",
  "pager",
  "page-link",
  "page-item",
] as const;

/**
 * Classifies a raw href string as `bare-fragment` (`"#"`), `empty` (`""`),
 * or `null` when the value is real navigation. Whitespace is tolerated
 * aggressively — real-world placeholders appear as `"  #  "`, `"   "`.
 *
 * What this function does NOT flag (legitimately navigating):
 *
 *   - `"#fragment-id"` — real in-page navigation; browser scrolls to and
 *     focuses the matching id. Silent.
 *   - Any other scheme (`"mailto:"`, `"tel:"`, `"/path"`, `"https://…"`) —
 *     real navigation. Silent.
 *   - `"javascript:..."` — handled by the companion rule
 *     `navigation/href-javascript-scheme`. Silent here.
 */
function classifyPlaceholder(value: string | null): PlaceholderKind | null {
  if (value === null) return null;
  const trimmed = value.trim();
  if (trimmed === "") return "empty";
  if (trimmed === "#") return "bare-fragment";
  return null;
}

export const rule = defineRule({
  id: "navigation/href-empty-fragment",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:2.1.1", "wcag21:2.1.1"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx", ".vue", ".svelte"],
  },
  docs: {
    description:
      'Flags <a> elements with placeholder href values that announce as links but do not navigate meaningfully: bare `href="#"` (no fragment id, nothing to scroll to) and empty `href=""` (which the HTML spec resolves to the current document URL — activating reloads the page rather than navigating). Whitespace is trimmed before matching, so `"  #  "` and `"   "` are flagged. Companion rule `navigation/href-javascript-scheme` covers the `javascript:` scheme variants. Use <button type="button"> for actions, or put a real URL in href for navigation.',
    rationale:
      'Assistive technology decides how to announce a control from its role: `<a>` with an href maps to the link role. The browser treats `href="#"` and `href=""` as links (the first as an in-page anchor, the second as a self-link), but neither shape navigates meaningfully — the user hears \'link,\' activates it, and either nothing happens or the page silently reloads (losing form state). The semantic role contradicts the runtime behavior.\n\nSpecifically the matched shapes:\n\n  - Bare `href="#"` with no fragment id — there is no target to scroll to, so the anchor announces as a link but navigates nowhere. (`href="#section-id"` pointing at a real id is real in-page navigation and stays silent.)\n  - Empty `href=""` — per HTML spec this resolves to the current document URL, so activating the link reloads the page rather than navigating. The `link-no-href` rule only catches the empty case when an onClick is attached (its scope is the `<a onClick>` keyboard-trap pattern); the bare `<a href="">Forgot password?</a>` case (common in legacy form pages wired up later) belongs here.\n  - Whitespace is trimmed before classification, so `"  #  "` matches as bare-fragment and `"   "` matches as empty.\n\nSplit out from the umbrella `navigation/href-placeholder` rule (which previously also covered `javascript:` schemes) so an agent suppressing one shape doesn\'t silently suppress the other — the two surfaces have different fix profiles. JSX expression-form `href={…}` is opaque at static time and intentionally not flagged.',
    goodExample: `<a href="/forgot-password">Forgot password?</a>`,
    badExample: `<a href="">Forgot password?</a>`,
    normativeQuote:
      "For all user interface components … the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#keyboard",
      "https://html.spec.whatwg.org/#the-a-element",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      // Belt-and-braces DOM-origin gate: an `<a href="">` substring inside
      // a packed plugin or minified `.js` bundle is not a real anchor — the
      // surrounding code may be a string-template factory or a build-time
      // interpolation. Only act on JSX nodes parsed out of `.tsx` / `.jsx`
      // (and the JSX-bearing `.mdx` / `.astro` aliases).
      if (!isDomOriginExtension(ctx.filePath)) return;
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

/**
 * `true` when any space-split token of `className` matches a known
 * pagination-context class (case-insensitive substring). Returns the
 * matched token so callers can echo it in suggestion text — the agent
 * sees `pagination` / `pager` / `page-link` directly rather than a
 * boolean. Returns `null` when no token matches.
 */
function matchPaginationClass(className: string | null): string | null {
  if (!className) return null;
  const lowered = className.toLowerCase();
  for (const token of PAGINATION_CLASS_TOKENS) {
    if (lowered.includes(token)) return token;
  }
  return null;
}

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  walkHtmlWithPaginationContext(doc.children, null, emit);
}

function walkHtmlWithPaginationContext(
  nodes: readonly HtmlNode[],
  paginationToken: string | null,
  emit: Emit,
): void {
  for (const child of nodes) {
    if (child.kind !== "HtmlElement") continue;
    const ownToken = matchPaginationClass(getHtmlAttribute(child, "class"));
    const inheritedToken = paginationToken ?? ownToken;
    if (child.tagName.toLowerCase() === "a") {
      const hrefValue = getHtmlAttribute(child, "href");
      const kind = classifyPlaceholder(hrefValue);
      if (kind) emit(buildViolation(child.loc.start, kind, inheritedToken));
    }
    walkHtmlWithPaginationContext(child.children, inheritedToken, emit);
  }
}

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const root of module.jsxElements) {
    walkJsxWithPaginationContext(root, null, emit);
  }
}

function walkJsxWithPaginationContext(
  element: JsxElement,
  paginationToken: string | null,
  emit: Emit,
): void {
  // `className` is JSX's spelling; `class` is a valid alternate (some
  // libraries forward it). Either one is enough to mark context.
  const classAttr =
    getJsxAttributeStringValue(element, "className") ??
    getJsxAttributeStringValue(element, "class");
  const ownToken = matchPaginationClass(classAttr);
  const inheritedToken = paginationToken ?? ownToken;
  if (element.tagName === "a") {
    const hrefAttr = getJsxAttribute(element, "href");
    if (hrefAttr?.value && hrefAttr.value.kind === "StringLiteral") {
      const kind = classifyPlaceholder(hrefAttr.value.value);
      if (kind) emit(buildViolation(element.loc.start, kind, inheritedToken));
    }
    // Expression-form `href={…}` is opaque at static time — surface only
    // deterministic evidence per the AI-first consumer model.
  }
  for (const child of element.children) {
    if (child.kind === "JsxElement") {
      walkJsxWithPaginationContext(child, inheritedToken, emit);
    }
  }
}

function getJsxAttributeStringValue(element: JsxElement, name: string): string | null {
  const attr = getJsxAttribute(element, name);
  if (!attr?.value) return null;
  if (attr.value.kind !== "StringLiteral") return null;
  return attr.value.value;
}

function buildViolation(
  loc: { line: number; column: number },
  kind: PlaceholderKind,
  paginationToken: string | null,
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  if (kind === "empty") {
    return {
      severity: "error",
      location: { filePath: "", line: loc.line, column: loc.column },
      message: `<a href=""> has an empty href — per HTML spec it resolves to the current page URL, so activating the link reloads the page rather than navigating. The anchor announces as a link but its destination is broken.`,
      suggestion: paginationSuggestionEmpty(paginationToken),
    };
  }
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<a href="#"> has no fragment target — the anchor announces as a link but navigates nowhere.`,
    suggestion: paginationSuggestionBareFragment(paginationToken),
  };
}

function paginationSuggestionBareFragment(paginationToken: string | null): string {
  if (paginationToken) {
    return `this anchor sits inside a pagination context (ancestor class contains \`${paginationToken}\`) — the underlying issue is the placeholder \`#\` href, not the accessible name. Two fixes by behavior: (a) if the control performs client-side page navigation (loads page N via JS, no URL change), use \`<button type="button">\` so the role matches the action — buttons announce as buttons and don't promise navigation; (b) if it should navigate to a real page, replace \`#\` with the destination URL (e.g. \`href="?page=2"\` or \`href="/posts/page/2"\`). Don't paper over with \`aria-label\` — a labelled link that goes nowhere is still a link that goes nowhere.`;
  }
  return `change \`<a href="#">\` to \`<button type="button">\` — a bare \`#\` href announces as a link but navigates nowhere. If the control triggers an action, a <button> is the correct role. If it should navigate to an in-page section, use \`href="#section-id"\` pointing at an actual id on the page.`;
}

function paginationSuggestionEmpty(paginationToken: string | null): string {
  if (paginationToken) {
    return `this anchor sits inside a pagination context (ancestor class contains \`${paginationToken}\`) — empty href reloads the current page rather than navigating, which is almost never what a pagination control should do. Two fixes by behavior: (a) if the control performs client-side page navigation, use \`<button type="button">\` so the role matches the action; (b) if it should navigate to a real page, replace the empty href with the destination URL (e.g. \`href="?page=2"\` or \`href="/posts/page/2"\`). Don't paper over with \`aria-label\` — naming a link that reloads the page is still a link that reloads the page.`;
  }
  return `change \`<a href="">\` to either \`<a href="/real/path">\` (if it should navigate — empty href reloads the current page, almost never the author's intent) or \`<button type="button">\` (if the control triggers an action with a click handler attached elsewhere). Common case: "Forgot password?" links that the author meant to wire up later — supply the real route.`;
}
