/**
 * Rule: navigation/link-name-only-symbol
 * Satisfies: wcag22:2.4.4, wcag21:2.4.4, wcag22:4.1.2, wcag21:4.1.2
 * Spec (Link Purpose In Context): https://www.w3.org/TR/WCAG22/#link-purpose-in-context
 * Spec (Name, Role, Value):       https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > The purpose of each link can be determined from the link text alone
 * > or from the link text together with its programmatically determined
 * > link context. (SC 2.4.4)
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined. (SC 4.1.2)
 *
 * Source: https://www.w3.org/TR/WCAG22/#link-purpose-in-context
 *
 * Flags `<a>` (and JSX link wrappers) whose computed accessible name is
 * one or two characters drawn entirely from the Unicode punctuation
 * (`\p{P}`) or symbol (`\p{S}`) categories. Canonical shapes:
 *
 *     <a href="/prev">«</a>          <!-- U+00AB single glyph -->
 *     <a href="/next">›</a>          <!-- U+203A single glyph -->
 *     <a href="/close">×</a>         <!-- U+00D7 multiplication sign as 'close' -->
 *     <a href="/page-3">&lsaquo;</a> <!-- named entity surviving the parser -->
 *     <button-row><a href="/n">+</a> <!-- U+002B plus -->
 *     <a href="/play">▶</a>          <!-- U+25B6 black triangle -->
 *     <a href="/back">←</a>          <!-- U+2190 leftwards arrow -->
 *     <a href="/feedback">★</a>      <!-- U+2605 black star -->
 *     <a href="/heart">♥</a>         <!-- U+2665 heart -->
 *     <a href="/up">↑↑</a>           <!-- two-symbol shape (still no name) -->
 *
 * In every case AT either announces the codepoint as its Unicode-name
 * punctuation ("LEFT-POINTING DOUBLE ANGLE QUOTATION MARK") or skips it
 * entirely — neither hands the user any usable destination cue.
 *
 * Pairs with — and is intentionally broader than — the
 * `review/pagination-glyph-accessible-name` finder, which only fires on
 * the four chevron/guillemet glyphs (« » ‹ ›) used in pagination
 * widgets. This rule covers the same shape *plus* every other one- or
 * two-character symbol/punctuation accessible name (×, +, →, ★, ♥, ▶,
 * etc.) regardless of pagination context — Q4-RULE-PAGINATION-GLYPH-NAME
 * (closed) is the narrow finder; this is the broader rule.
 *
 * Distinct from `navigation/link-descriptive-text`:
 *
 *   - Its generic-phrase path matches a curated dictionary ("click
 *     here", "read more"). A bare `›` isn't in that dictionary, and
 *     adding it would break the dictionary's "phrase" framing.
 *   - Its icon-only path fires when every child is *presentational*
 *     (icon-font span, decorative `<img>`, `aria-hidden` subtree).
 *     A bare glyph character is a plain text node — the icon-only
 *     check stripped-text comparison sees the glyph and passes.
 *
 * Symbol-only links sit in the gap between those two paths: visible
 * text exists, but the text is a punctuation glyph that cannot serve as
 * a destination name.
 *
 * Detection scope (intentionally tight to keep false positives low):
 *
 *   - the anchor must have an `href` (or `to` on JSX link wrappers);
 *     bare `<a>` without href is handled by other rules.
 *   - if `aria-label` (non-empty), `aria-labelledby`, or `title`
 *     (non-empty) is present, the override path supplies a real name —
 *     stay silent. (Same convention as the pagination finder; an exact
 *     duplicate of the visible glyph in `aria-label` is rare enough not
 *     to chase here.)
 *   - if the anchor itself carries `aria-hidden="true"`, it's been
 *     removed from the a11y tree by the author — silent.
 *   - JSX expression children (`<a>{label}</a>`) are opaque at static
 *     time — silent (same gate as the pagination finder).
 *   - subtree text excludes `aria-hidden="true"` descendants (no
 *     contribution to the accessible name) and decoration via
 *     `role="presentation"`/`"none"`.
 *   - `<img>` children with non-empty `alt` contribute the alt text as
 *     name material; an `alt="X"` (single letter) on an image is a
 *     separate failure mode owned by `media/alt-text-placeholder`.
 *   - The four named entities the HTML parser does NOT decode
 *     (`&laquo;` `&raquo;` `&lsaquo;` `&rsaquo;`) plus `&times;` are
 *     locally substituted before the codepoint scan. Numeric entities
 *     (`&#171;` `&#xAB;`) are already decoded by the parser.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  findHtmlElementsByTag,
  findJsxElementsForTag,
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";

/** JSX tags treated as link wrappers. Mirrors `link-descriptive-text`. */
const JSX_LINK_TAGS: ReadonlySet<string> = new Set(["a", "Link", "NavLink", "Anchor"]);

/**
 * Named-entity shorthands the HTML parser leaves un-decoded (the
 * parser's named-entity table is intentionally tiny — see
 * `src/input/parsers/html.ts` `NAMED_ENTITIES`). Numeric entities
 * (`&#171;`, `&#xAB;`) are decoded upstream; only these named shapes
 * survive as literal `&laquo;`-style strings into the text nodes.
 *
 * Local-only decoding: extending the parser's table would affect
 * every text-consuming rule on the project; this surface is too tight
 * to justify a cross-cutting change.
 */
const NAMED_ENTITY_MAP: Readonly<Record<string, string>> = {
  "&laquo;": "«",
  "&raquo;": "»",
  "&lsaquo;": "‹",
  "&rsaquo;": "›",
  "&times;": "×",
  "&plus;": "+",
  "&middot;": "·",
  "&bull;": "•",
};

/** Maximum length (in Unicode codepoints, not UTF-16 code units) of an
 * accessible name we treat as "symbol-only." Two covers paired glyphs
 * ("«‹", "↑↑", "++") that some authors use as pagination/skip controls.
 * Beyond two characters the link almost certainly carries word content
 * (even short ones — "Hi", "OK") and falls outside this rule's scope. */
const MAX_SYMBOL_NAME_LENGTH = 2;

export const rule = defineRule({
  id: "navigation/link-name-only-symbol",
  satisfies: ["wcag22:2.4.4", "wcag21:2.4.4", "wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "warning",
  scope: "node",
  fixClass: "guidance",
  // Opt in: wrapper components declared as rendering `<a>` via the
  // object form of `nativeWrappers` also get checked.
  wrapperTreatsAsElement: "a",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Flags <a> (and JSX link wrappers) whose computed accessible name is one or two characters drawn entirely from Unicode punctuation/symbol categories — chevrons (« » ‹ ›), arrows (← → ↑ ↓), the multiplication sign (×) used as 'close', stars (★ ☆), hearts (♥), bullets (•), or paired variants. Screen readers announce these as punctuation ('LEFT-POINTING DOUBLE ANGLE QUOTATION MARK') or skip them, leaving the link with no usable destination name. Add an aria-label naming the destination (or include a visually-hidden span inside the anchor expanding the glyph into words). Pairs with the pagination-specific review/pagination-glyph-accessible-name finder; this rule is the broader catch.",
    rationale:
      "Assistive technology decides how to announce a link from its accessible name. When the name is one or two punctuation/symbol codepoints, AT either reads the Unicode-category name verbatim ('left-pointing double angle quotation mark', 'multiplication sign') or skips the codepoint entirely — neither outcome tells the user where the link goes. The visual convention (× = close, › = next, ★ = favorite, ↑ = back-to-top) is sighted-only metadata; AT users hear nothing meaningful.\n\nSpecifically the matched shapes:\n\n  - One- or two-codepoint accessible names (after collapsing whitespace and decoding the four named entities the HTML parser leaves intact: &laquo; &raquo; &lsaquo; &rsaquo; plus &times;).\n  - Every codepoint must be in Unicode punctuation (\\p{P}) OR symbol (\\p{S}) — letters and digits exit the rule (a letter is real text; a digit might be a page number labeled by surrounding context).\n  - Anchors with aria-label / aria-labelledby / title overrides stay silent (the override is the real accessible name).\n  - Anchors with aria-hidden='true' on themselves are removed from the a11y tree — silent.\n  - JSX expression children (`<a>{label}</a>`) are opaque to static analysis — silent.\n\nDistinct from the pagination-glyph review finder (which only matches the four chevron/guillemet glyphs in pagination context) — this rule fires on every short symbol-only name regardless of context. Distinct from link-descriptive-text generic-phrase (curated 'click here' dictionary) and icon-only (every child presentational) paths — symbol-only links sit in the gap between those.",
    goodExample: `<a href="/prev" aria-label="Previous page">«</a>`,
    badExample: `<a href="/prev">«</a>`,
    normativeQuote:
      "The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context.",
    references: [
      "https://www.w3.org/TR/WCAG22/#link-purpose-in-context",
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA7",
      "https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA8",
      "https://www.w3.org/WAI/WCAG22/Techniques/general/G91",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, ctx.wrappersForElement, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const a of findHtmlElementsByTag(doc, "a")) {
    if (!hasHtmlAttribute(a, "href")) continue;
    if (getHtmlAttribute(a, "aria-hidden") === "true") continue;
    if (hasAccessibleNameOverrideHtml(a)) continue;

    const visible = visibleAccessibleNameHtml(a);
    const matched = matchSymbolOnly(visible);
    if (!matched) continue;
    emit(buildViolation(a.loc.start.line, a.loc.start.column, matched, "a"));
  }
}

/**
 * Walks the anchor's subtree and returns its visible accessible-name
 * text. Mirrors the WAI name-computation algorithm at the depth this
 * rule needs:
 *
 *   - text nodes contribute their `value`,
 *   - `<img>` with non-empty `alt` contributes the alt text,
 *   - elements with `aria-hidden="true"` or `role="presentation"`/
 *     `"none"` contribute nothing (skipped entirely),
 *   - other elements are recursed into.
 */
function visibleAccessibleNameHtml(root: HtmlElement): string {
  let out = "";
  const visit = (node: HtmlNode): void => {
    if (node.kind === "HtmlText") {
      out += node.value;
      return;
    }
    if (node.kind !== "HtmlElement") return;
    if (isAriaHiddenOrPresentationalHtml(node)) return;
    if (node.tagName.toLowerCase() === "img") {
      const alt = getHtmlAttribute(node, "alt");
      if (alt !== null && alt.trim().length > 0) out += ` ${alt} `;
      return;
    }
    for (const child of node.children) visit(child);
  };
  for (const child of root.children) visit(child);
  return out;
}

function isAriaHiddenOrPresentationalHtml(el: HtmlElement): boolean {
  if (getHtmlAttribute(el, "aria-hidden") === "true") return true;
  const role = (getHtmlAttribute(el, "role") ?? "").toLowerCase();
  return role === "presentation" || role === "none";
}

function hasAccessibleNameOverrideHtml(a: HtmlElement): boolean {
  const ariaLabel = getHtmlAttribute(a, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasHtmlAttribute(a, "aria-labelledby")) return true;
  const title = getHtmlAttribute(a, "title");
  if (title !== null && title.trim().length > 0) return true;
  return false;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, wrappersForA: ReadonlySet<string>, emit: Emit): void {
  const seen = new Set<JsxElement>();
  const wrappers = new Set<string>([...JSX_LINK_TAGS, ...wrappersForA]);
  wrappers.delete("a");
  for (const el of findJsxElementsForTag(module, "a", wrappers)) {
    if (seen.has(el)) continue;
    seen.add(el);
    if (!(hasJsxAttribute(el, "href") || hasJsxAttribute(el, "to"))) continue;
    if (getJsxAttributeString(el, "aria-hidden") === "true") continue;
    if (hasAccessibleNameOverrideJsx(el)) continue;
    // Runtime expression children may carry any name we can't see.
    if (el.children.some((c) => c.kind === "JsxExpression")) continue;

    const visible = visibleAccessibleNameJsx(el);
    const matched = matchSymbolOnly(visible);
    if (!matched) continue;
    emit(buildViolation(el.loc.start.line, el.loc.start.column, matched, el.tagName));
  }
}

function visibleAccessibleNameJsx(root: JsxElement): string {
  let out = "";
  const visit = (node: JsxNode): void => {
    if (node.kind === "JsxText") {
      out += node.value;
      return;
    }
    if (node.kind !== "JsxElement") return;
    if (isAriaHiddenOrPresentationalJsx(node)) return;
    if (node.tagName.toLowerCase() === "img") {
      const alt = getJsxAttributeString(node, "alt");
      if (alt !== null && alt.trim().length > 0) out += ` ${alt} `;
      return;
    }
    for (const child of node.children) visit(child);
  };
  for (const child of root.children) visit(child);
  return out;
}

function isAriaHiddenOrPresentationalJsx(el: JsxElement): boolean {
  if (getJsxAttributeString(el, "aria-hidden") === "true") return true;
  const role = (getJsxAttributeString(el, "role") ?? "").toLowerCase();
  return role === "presentation" || role === "none";
}

function hasAccessibleNameOverrideJsx(a: JsxElement): boolean {
  const ariaLabel = getJsxAttributeString(a, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasJsxAttribute(a, "aria-labelledby")) return true;
  const title = getJsxAttributeString(a, "title");
  if (title !== null && title.trim().length > 0) return true;
  return false;
}

// ---------------------------------------------------------------------------
// Shared
// ---------------------------------------------------------------------------

/**
 * Returns the matched glyph string IFF the visible text — after entity
 * decoding and whitespace collapse — is one or two codepoints, every
 * one of which is in Unicode punctuation (`\p{P}`) or symbol (`\p{S}`).
 * Returns null for any other shape (empty text, longer text, text
 * containing letters/digits/whitespace alongside the symbol).
 *
 * Codepoint counting uses spread (`[...str]`) so surrogate-pair
 * characters (e.g. emoji) count as one codepoint, not two UTF-16 code
 * units. This is a conservative choice: an emoji-only link is also
 * unnameable, but emoji span the General-Category space irregularly
 * and our tight `\p{P}|\p{S}` predicate intentionally excludes them
 * (`\p{Emoji}` would be a separate decision; surface what we're sure
 * about, not what we're guessing).
 */
function matchSymbolOnly(text: string): string | null {
  let normalized = text;
  for (const [entity, decoded] of Object.entries(NAMED_ENTITY_MAP)) {
    if (normalized.includes(entity)) {
      normalized = normalized.split(entity).join(decoded);
    }
  }
  // Collapse all whitespace (incl. NBSP, U+00A0) to nothing so
  // `<a>  ›  </a>` and `<a>›&nbsp;</a>` reduce to the bare glyph.
  const trimmed = normalized.replace(/\s+/gu, "");
  if (trimmed.length === 0) return null;
  // Codepoint count, not UTF-16 length — see fn doc.
  const codepoints = [...trimmed];
  if (codepoints.length === 0 || codepoints.length > MAX_SYMBOL_NAME_LENGTH) return null;
  for (const cp of codepoints) {
    if (!isPunctuationOrSymbol(cp)) return null;
  }
  return trimmed;
}

function isPunctuationOrSymbol(codepoint: string): boolean {
  // `\p{P}` covers all punctuation (open/close quotes, dashes, brackets,
  // etc.); `\p{S}` covers all symbols (math, currency, arrows, geometric
  // shapes, miscellaneous). Together they exclude `\p{L}` (letters),
  // `\p{N}` (numbers), `\p{M}` (marks), `\p{Z}` (separators — already
  // stripped above), and `\p{C}` (controls/format).
  return /[\p{P}\p{S}]/u.test(codepoint);
}

function buildViolation(
  line: number,
  column: number,
  glyph: string,
  tagName: string,
): {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const isPair = [...glyph].length === 2;
  const glyphDescription = isPair ? `the two-character sequence "${glyph}"` : `"${glyph}"`;
  return {
    severity: "warning",
    location: { filePath: "", line, column },
    message:
      `<${tagName}> accessible name is ${glyphDescription} — entirely punctuation/symbol ` +
      "characters. Screen readers announce the codepoint as its Unicode-category name (e.g. " +
      '"left-pointing double angle quotation mark" for « or "multiplication sign" for ×) or ' +
      "skip it, leaving the link with no usable destination cue.",
    suggestion:
      `Add an aria-label to the <${tagName}> naming the destination ` +
      `(e.g. \`aria-label="Previous page"\` for «/‹/←, \`aria-label="Next page"\` for »/›/→, ` +
      `\`aria-label="Close"\` for ×, \`aria-label="Favorite"\` for ★/♥, ` +
      `\`aria-label="Back to top"\` for ↑), or add a visually-hidden span inside the link ` +
      `(e.g. \`<span class="sr-only">Previous page</span>\`) so the glyph stays as visible ` +
      "decoration but the accessible name carries the words.",
  };
}
