/**
 * Rule: forms/submit-not-button-or-input
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:3.3.2, wcag21:3.3.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set; and notification of changes to these items
 * > is available to user agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *         https://www.w3.org/TR/WCAG22/#labels-or-instructions
 *
 * Flags `<form>` elements that have NO submit control of any kind
 * (no `<button>` (default type=submit), no `<button type="submit">`,
 * no `<input type="submit">`, no `<input type="image">`) BUT contain
 * an `<a>` styled as a button — `class` contains a `btn` token, or
 * `role="button"`. The anchor is the apparent submit control to
 * sighted users (it looks like a button, it's the only button-shaped
 * thing in the form), but assistive tech announces it as a link
 * ("link, Login"), keyboard users can't activate it with the form's
 * implicit submit semantics, and `<form action>` / `<form onSubmit>`
 * never fires. Both 4.1.2 (wrong role) and 3.3.2 (no clear submit
 * affordance) apply.
 *
 * Conservative trigger:
 *   - Only fires when the form has NO real submit control AND has at
 *     least one anchor-styled-as-button. A form with both a real
 *     submit button and a button-styled `<a>` (e.g. a "Cancel" link)
 *     is fine — the anchor is genuinely a navigation control.
 *   - JS-only forms (`<form onSubmit>` with neither a button nor an
 *     anchor-styled-as-button) are out of scope here. The canonical
 *     case targeted by this rule is the misleading anchor; pure-JS
 *     submission without ANY button-shaped element gets caught by
 *     other rules (semantics/button-name on `<div onClick>`, etc.).
 */
import { defineRule } from "../../api/plugin.ts";
import {
  findHtmlElementsByTag,
  findJsxElementsByTag,
  getHtmlAttribute,
  getJsxAttributeString,
  htmlTextContent,
  jsxTextContent,
  truncateForEcho,
  walkHtmlElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

export const rule = defineRule({
  id: "forms/submit-not-button-or-input",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:3.3.2", "wcag21:3.3.2"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "A <form> with no <button>/<input type=submit> but containing an <a> styled as a button uses the anchor as the apparent submit control — wrong role for assistive tech.",
    rationale:
      "Sighted users see a button, click it, the form submits. Screen readers announce 'link, Login' — and link activation does not fire the form's submit handler, action attribute, or implicit Enter-on-input submission. The author's HTML even tells you what they meant: in real templates we see comments like 'Change this to a button or input when using this as a form' sitting above an `<a class=\"btn\">`. The anchor was a stand-in that never got swapped. Both 4.1.2 (wrong role) and 3.3.2 (no labeled submit affordance) apply.",
    goodExample: `<form action="/login" method="post">\n  <label>Email <input type="email" name="email"></label>\n  <button type="submit" class="btn btn-primary">Login</button>\n</form>`,
    badExample: `<form action="/login" method="post">\n  <label>Email <input type="email" name="email"></label>\n  <!-- Change this to a button or input when using this as a form -->\n  <a href="index.html" class="btn btn-primary">Login</a>\n</form>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#labels-or-instructions",
      "https://www.w3.org/WAI/WCAG22/Techniques/html/H32",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const form of findHtmlElementsByTag(doc, "form")) {
    if (htmlFormHasRealSubmit(form)) continue;
    const anchor = findHtmlAnchorAsSubmit(form);
    if (anchor === null) continue;
    emit({
      severity: "error",
      location: { filePath: "", line: form.loc.start.line, column: form.loc.start.column },
      message: buildHtmlMessage(form, anchor),
      suggestion: buildHtmlSuggestion(form, anchor),
    });
  }
}

function htmlFormHasRealSubmit(form: HtmlElement): boolean {
  for (const el of walkHtmlElements(form)) {
    const tag = el.tagName.toLowerCase();
    if (tag === "button") {
      // <button> defaults to type="submit"; only type="button" or
      // type="reset" disqualify.
      const type = getHtmlAttribute(el, "type")?.toLowerCase() ?? "submit";
      if (type === "submit") return true;
      continue;
    }
    if (tag === "input") {
      const type = getHtmlAttribute(el, "type")?.toLowerCase();
      if (type === "submit" || type === "image") return true;
    }
  }
  return false;
}

function findHtmlAnchorAsSubmit(form: HtmlElement): HtmlElement | null {
  for (const el of walkHtmlElements(form)) {
    if (el.tagName.toLowerCase() !== "a") continue;
    if (looksLikeButtonHtml(el)) return el;
  }
  return null;
}

function looksLikeButtonHtml(anchor: HtmlElement): boolean {
  const role = getHtmlAttribute(anchor, "role")?.toLowerCase();
  if (role === "button") return true;
  const cls = getHtmlAttribute(anchor, "class");
  if (cls === null) return false;
  return classHasBtnToken(cls);
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const form of findJsxElementsByTag(module, "form")) {
    if (jsxFormHasRealSubmit(form)) continue;
    const anchor = findJsxAnchorAsSubmit(form);
    if (anchor === null) continue;
    emit({
      severity: "error",
      location: { filePath: "", line: form.loc.start.line, column: form.loc.start.column },
      message: buildJsxMessage(form, anchor),
      suggestion: buildJsxSuggestion(form, anchor),
    });
  }
}

function jsxFormHasRealSubmit(form: JsxElement): boolean {
  // Walk the form's descendant JSX subtree looking for a real submit
  // control. We restrict to descendants of *this* form by walking from
  // the form's children, not via `findJsxElementsByTag` (which is
  // module-wide).
  for (const el of walkJsxDescendants(form)) {
    const tag = el.tagName;
    if (tag === "button") {
      const type = getJsxAttributeString(el, "type")?.toLowerCase() ?? "submit";
      if (type === "submit") return true;
      continue;
    }
    if (tag === "input") {
      const type = getJsxAttributeString(el, "type")?.toLowerCase();
      if (type === "submit" || type === "image") return true;
    }
  }
  return false;
}

function findJsxAnchorAsSubmit(form: JsxElement): JsxElement | null {
  for (const el of walkJsxDescendants(form)) {
    if (el.tagName !== "a") continue;
    if (looksLikeButtonJsx(el)) return el;
  }
  return null;
}

function looksLikeButtonJsx(anchor: JsxElement): boolean {
  const role = getJsxAttributeString(anchor, "role")?.toLowerCase();
  if (role === "button") return true;
  // JSX uses className; tolerate the HTML spelling too in case the
  // author wrote raw HTML attributes.
  const cls = getJsxAttributeString(anchor, "className") ?? getJsxAttributeString(anchor, "class");
  if (cls === null) return false;
  return classHasBtnToken(cls);
}

function* walkJsxDescendants(element: JsxElement): Iterable<JsxElement> {
  for (const child of element.children) {
    if (child.kind === "JsxElement") {
      yield child;
      yield* walkJsxDescendants(child);
    }
  }
}

// ---------------------------------------------------------------------------
// Class-token detection
// ---------------------------------------------------------------------------

/**
 * True when `class` contains a whitespace-separated token of `btn` or
 * `btn-*` (Bootstrap, sb-admin-2, AdminLTE — all share this prefix).
 * Not a substring match: `printable-button` does NOT match, `btn-lg`
 * does. The token check exists so identifiers like `unbutton` or
 * `submit-button` (which don't follow Bootstrap's convention but
 * happen to contain the substring) don't cause false positives.
 */
function classHasBtnToken(cls: string): boolean {
  const tokens = cls.trim().split(/\s+/);
  for (const tok of tokens) {
    if (tok === "btn") return true;
    if (tok.startsWith("btn-")) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Message builders
// ---------------------------------------------------------------------------

function buildHtmlMessage(form: HtmlElement, anchor: HtmlElement): string {
  const formDesc = describeHtmlForm(form);
  const anchorDesc = describeHtmlAnchor(anchor);
  return `${formDesc} has no <button>/<input type="submit">, but contains ${anchorDesc} that appears to be the submit control. Screen readers will announce it as a link, and clicking it does not trigger the form's submit handler.`;
}

function buildHtmlSuggestion(form: HtmlElement, anchor: HtmlElement): string {
  const text = truncateForEcho(htmlTextContent(anchor));
  const cls = getHtmlAttribute(anchor, "class");
  const classCopy = cls ? truncateForEcho(cls) : "";
  const buttonOpen = classCopy
    ? `<button type="submit" class="${classCopy}">`
    : `<button type="submit">`;
  const labelText = text.length > 0 ? text : "Submit";
  void form;
  return `Convert the anchor to a real submit control: ${buttonOpen}${labelText}</button>. Keep the visual styling by reusing the same class names. If this control truly navigates rather than submits (e.g. a "Cancel" link that returns to a previous page), add a real <button type="submit"> as the form's primary action and leave the anchor as a navigation link.`;
}

function buildJsxMessage(form: JsxElement, anchor: JsxElement): string {
  const formDesc = describeJsxForm(form);
  const anchorDesc = describeJsxAnchor(anchor);
  return `${formDesc} has no <button>/<input type="submit">, but contains ${anchorDesc} that appears to be the submit control. Screen readers will announce it as a link, and clicking it does not trigger the form's submit handler.`;
}

function buildJsxSuggestion(form: JsxElement, anchor: JsxElement): string {
  const text = truncateForEcho(jsxTextContent(anchor));
  const cls = getJsxAttributeString(anchor, "className") ?? getJsxAttributeString(anchor, "class");
  const classCopy = cls ? truncateForEcho(cls) : "";
  const buttonOpen = classCopy
    ? `<button type="submit" className="${classCopy}">`
    : `<button type="submit">`;
  const labelText = text.length > 0 ? text : "Submit";
  void form;
  return `Convert the anchor to a real submit control: ${buttonOpen}${labelText}</button>. Keep the visual styling by reusing the same class names. If this control truly navigates rather than submits (e.g. a "Cancel" link that returns to a previous page), add a real <button type="submit"> as the form's primary action and leave the anchor as a navigation link.`;
}

function describeHtmlForm(form: HtmlElement): string {
  const id = getHtmlAttribute(form, "id");
  if (id && id.trim().length > 0) return `<form id="${truncateForEcho(id)}">`;
  const action = getHtmlAttribute(form, "action");
  if (action && action.trim().length > 0) return `<form action="${truncateForEcho(action)}">`;
  return "<form>";
}

function describeHtmlAnchor(anchor: HtmlElement): string {
  const text = htmlTextContent(anchor);
  if (text.length > 0) return `an <a> with text "${truncateForEcho(text)}"`;
  const href = getHtmlAttribute(anchor, "href");
  if (href && href.length > 0) return `an <a href="${truncateForEcho(href)}">`;
  return "an <a> styled as a button";
}

function describeJsxForm(form: JsxElement): string {
  const id = getJsxAttributeString(form, "id");
  if (id && id.trim().length > 0) return `<form id="${truncateForEcho(id)}">`;
  const action = getJsxAttributeString(form, "action");
  if (action && action.trim().length > 0) return `<form action="${truncateForEcho(action)}">`;
  return "<form>";
}

function describeJsxAnchor(anchor: JsxElement): string {
  const text = jsxTextContent(anchor);
  if (text.length > 0) return `an <a> with text "${truncateForEcho(text)}"`;
  const href = getJsxAttributeString(anchor, "href");
  if (href && href.length > 0) return `an <a href="${truncateForEcho(href)}">`;
  return "an <a> styled as a button";
}
