/**
 * Rule: semantics/nested-interactive
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set; and notification of changes to these items
 * > is available to user agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags interactive elements nested inside other interactive
 * elements — e.g., a `<button>` inside an `<a href>`, or an
 * `<a href>` inside another `<a href>`. These patterns are invalid
 * per the HTML content model for `<a>` and `<button>` and produce
 * undefined assistive-technology behavior: click events bubble,
 * focus order is ambiguous, and screen readers typically announce
 * the outer element's role while the user is interacting with the
 * inner one, so the inner component's role can no longer be
 * programmatically determined in a consistent way.
 *
 * Document-scoped: builds a child→parent index and walks up the
 * chain from every interactive descendant looking for an interactive
 * ancestor. One violation per (outer, inner) pair.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxAttribute,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";

/**
 * Native HTML tags that are interactive. Some require an extra
 * attribute check (a needs href, input needs type != hidden, audio/
 * video need controls) — `isInteractiveHtml` / `isInteractiveJsx`
 * apply those.
 */
const INTERACTIVE_TAGS: ReadonlySet<string> = new Set([
  "a",
  "button",
  "input",
  "select",
  "textarea",
  "details",
  "audio",
  "video",
]);

/** ARIA roles that expose an interactive widget. */
const INTERACTIVE_ROLES: ReadonlySet<string> = new Set([
  "button",
  "link",
  "checkbox",
  "radio",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "option",
  "switch",
  "tab",
  "treeitem",
  "combobox",
  "searchbox",
  "textbox",
  "slider",
  "spinbutton",
]);

/**
 * ARIA 1.2 composite-widget roles that delegate focus to interactive
 * descendants rather than taking focus themselves. In these patterns
 * the container carries the role semantic but focus lives on the
 * child (roving-tabindex or aria-activedescendant); nesting an
 * `<a href>` or `<button>` inside the container is idiomatic, not a
 * two-focusables-one-control violation. The finding still fires
 * because the DOM shape is unusual and assistive-tech behavior in
 * ad-hoc nestings is not guaranteed — we surface it with additive
 * framing so the consuming agent can dismiss-or-verify in one read
 * (ARIA 1.2 composite-widget patterns: tablist/tab, menu/menuitem,
 * listbox/option, tree/treeitem, grid/gridcell, grid/row).
 *
 * Spec: https://www.w3.org/TR/wai-aria-1.2/#composite
 */
const COMPOSITE_WIDGET_DELEGATING_ROLES: ReadonlySet<string> = new Set([
  "tab",
  "menuitem",
  "option",
  "treeitem",
  "gridcell",
  "row",
]);

/**
 * Event-handler attribute names whose presence on an outer element
 * marks it as materially interactive (a real click/key activator,
 * not just a semantic role wrapper). Attribute names are compared
 * case-insensitively for HTML; JSX preserves camelCase, so both
 * spellings are probed on JSX elements.
 */
const HANDLER_ATTRIBUTES_HTML: readonly string[] = [
  "onclick",
  "onkeydown",
  "onkeyup",
  "onkeypress",
  "onmousedown",
  "onmouseup",
];
const HANDLER_ATTRIBUTES_JSX: readonly string[] = [
  "onClick",
  "onKeyDown",
  "onKeyUp",
  "onKeyPress",
  "onMouseDown",
  "onMouseUp",
];

export const rule = defineRule({
  id: "semantics/nested-interactive",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "document",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Interactive elements (links, buttons, form controls, elements with interactive ARIA roles) must not be nested inside other interactive elements.",
    rationale:
      "Nesting one interactive control inside another is invalid per the HTML content model for <a> and <button>, and the resulting DOM has no well-defined accessibility semantics. Click events bubble to the outer control, focus order is ambiguous, and screen readers typically announce the outer element's role while the user is operating the inner one — so the inner element's name and role can no longer be programmatically determined.",
    goodExample: `<a href="/settings">\n  Settings\n  <svg aria-hidden="true">...</svg>\n</a>`,
    badExample: `<a href="/card">\n  <button type="button">Action</button>\n</a>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element",
      "https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element",
    ],
  },
  afterFile(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
      return;
    }
    if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  const parentOf = buildHtmlParentMap(doc);
  for (const el of walkHtmlElements(doc)) {
    if (!isInteractiveHtml(el)) continue;
    const ancestor = findInteractiveHtmlAncestor(el, parentOf);
    if (!ancestor) continue;
    emit(
      buildHtmlViolation(
        describeHtml(ancestor),
        describeHtml(el),
        ancestor.loc.start.line,
        el.loc.start,
        compositeWidgetRole(getHtmlAttribute(ancestor, "role")),
      ),
    );
  }
}

function findInteractiveHtmlAncestor(
  element: HtmlElement,
  parentOf: ReadonlyMap<HtmlElement, HtmlElement>,
): HtmlElement | null {
  const elementTag = element.tagName.toLowerCase();
  let walkedThroughSummary = elementTag === "summary";
  let parent = parentOf.get(element);
  while (parent) {
    const parentTag = parent.tagName.toLowerCase();
    if (isMateriallyInteractiveHtml(parent)) {
      // <details>'s interactive surface is its <summary>. A descendant
      // that reached <details> without passing through its summary is in
      // the panel body — just flow content, not a nested control.
      const detailsOk = parentTag === "details" && !walkedThroughSummary;
      if (!(detailsOk || isAllowedNativeNesting(elementTag, parentTag))) return parent;
    }
    if (parentTag === "summary") walkedThroughSummary = true;
    parent = parentOf.get(parent);
  }
  return null;
}

/**
 * "Materially interactive" is the outer-ancestor predicate for the
 * nested-interactive check. It is deliberately stricter than
 * {@link isInteractiveHtml} (which also accepts ARIA interactive
 * roles and drives the inner-element detection). For the ancestor
 * side we require one of:
 *
 *   - a native interactive tag (the usual set: button, a[href],
 *     input[type!=hidden], select, textarea, details, summary,
 *     audio/video with controls)
 *   - a numeric `tabindex >= 0` (making the element a focus stop)
 *   - an inline event-handler attribute
 *     (onclick / onkeydown / onkeyup / onkeypress / onmousedown /
 *      onmouseup)
 *
 * An ARIA role alone does NOT qualify. A `<div role="tab">` or
 * `<div role="button">` with no handler, no tabindex, and no native
 * interactive tag is a semantic wrapper, not a focus stop or
 * activator — nesting an `<a href>` or `<button>` inside it is not
 * a two-focusables-one-control violation. This matches the
 * idiomatic Bootstrap-style accordion/collapse markup where the
 * role conveys AT semantics but the inner `<a href>` is the sole
 * activation surface.
 */
function isMateriallyInteractiveHtml(element: HtmlElement): boolean {
  const tag = element.tagName.toLowerCase();
  if (isInteractiveHtmlTag(element, tag)) return true;
  if (hasFocusableTabindexHtml(element)) return true;
  if (hasInlineHandlerHtml(element)) return true;
  return false;
}

function hasFocusableTabindexHtml(element: HtmlElement): boolean {
  const raw = getHtmlAttribute(element, "tabindex");
  if (raw === null) return false;
  const n = Number.parseInt(raw.trim(), 10);
  return Number.isFinite(n) && n >= 0;
}

function hasInlineHandlerHtml(element: HtmlElement): boolean {
  for (const name of HANDLER_ATTRIBUTES_HTML) {
    if (hasHtmlAttribute(element, name)) return true;
  }
  return false;
}

/**
 * Native HTML relationships where the inner "interactive" element is
 * spec-required or spec-allowed to sit inside the outer one:
 *
 *   <details><summary></summary></details>
 *     summary is the defined activation surface for details. This is
 *     not two nested controls — it is one disclosure widget with a
 *     header. Per WHATWG HTML 4.11.2 / 4.11.3.
 *
 *   <details><details></details></details>
 *     details is flow content and may be nested. Each inner details
 *     has its own summary; activation is independent. Per WHATWG HTML
 *     4.11.2 (flow content model).
 *
 * Crucially this is NOT a "heuristic" about what the author might have
 * meant — both nestings are literally defined by the HTML spec. A
 * `<summary>` outside a `<details>` is meaningless; so too is a
 * `<details>`'s activation without its `<summary>`.
 */
function isAllowedNativeNesting(elementTag: string, ancestorTag: string): boolean {
  if (elementTag === "summary" && ancestorTag === "details") return true;
  if (elementTag === "details" && ancestorTag === "details") return true;
  return false;
}

function isInteractiveHtml(element: HtmlElement): boolean {
  const tag = element.tagName.toLowerCase();
  if (isInteractiveHtmlTag(element, tag)) return true;
  const role = getHtmlAttribute(element, "role");
  if (role !== null && INTERACTIVE_ROLES.has(role.toLowerCase())) return true;
  return false;
}

function isInteractiveHtmlTag(element: HtmlElement, tag: string): boolean {
  if (!INTERACTIVE_TAGS.has(tag)) return false;
  if (tag === "a") return hasHtmlAttribute(element, "href");
  if (tag === "input") {
    const type = (getHtmlAttribute(element, "type") ?? "").toLowerCase();
    return type !== "hidden";
  }
  if (tag === "audio" || tag === "video") {
    return hasHtmlAttribute(element, "controls");
  }
  return true;
}

function describeHtml(element: HtmlElement): string {
  const tag = element.tagName.toLowerCase();
  const role = getHtmlAttribute(element, "role");
  if (role !== null && INTERACTIVE_ROLES.has(role.toLowerCase())) {
    // Prefer the explicit role if the element is only interactive by role.
    if (!(INTERACTIVE_TAGS.has(tag) && isInteractiveHtmlTag(element, tag))) {
      return `<${tag} role="${role.toLowerCase()}">`;
    }
  }
  if (tag === "a") return `<a href>`;
  return `<${tag}>`;
}

function buildHtmlParentMap(doc: HtmlDocument): Map<HtmlElement, HtmlElement> {
  const parentOf = new Map<HtmlElement, HtmlElement>();
  const visit = (node: HtmlNode, parent: HtmlElement | null): void => {
    if (node.kind !== "HtmlElement") return;
    if (parent) parentOf.set(node, parent);
    for (const child of node.children) visit(child, node);
  };
  for (const top of doc.children) visit(top, null);
  return parentOf;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  const parentOf = buildJsxParentMap(module);
  for (const el of walkJsxElements(module)) {
    if (isJsxPascalCase(el.tagName)) continue;
    if (!isInteractiveJsx(el)) continue;
    const ancestor = findInteractiveJsxAncestor(el, parentOf);
    if (!ancestor) continue;
    emit(
      buildHtmlViolation(
        describeJsx(ancestor),
        describeJsx(el),
        ancestor.loc.start.line,
        el.loc.start,
        compositeWidgetRole(getJsxAttributeString(ancestor, "role")),
      ),
    );
  }
}

function findInteractiveJsxAncestor(
  element: JsxElement,
  parentOf: ReadonlyMap<JsxElement, JsxElement>,
): JsxElement | null {
  const elementTag = element.tagName.toLowerCase();
  let walkedThroughSummary = elementTag === "summary";
  let parent = parentOf.get(element);
  while (parent) {
    // PascalCase components are opaque — don't traverse through them.
    if (isJsxPascalCase(parent.tagName)) return null;
    const parentTag = parent.tagName.toLowerCase();
    if (isMateriallyInteractiveJsx(parent)) {
      const detailsOk = parentTag === "details" && !walkedThroughSummary;
      if (!(detailsOk || isAllowedNativeNesting(elementTag, parentTag))) return parent;
    }
    if (parentTag === "summary") walkedThroughSummary = true;
    parent = parentOf.get(parent);
  }
  return null;
}

/**
 * JSX counterpart to {@link isMateriallyInteractiveHtml}. See that
 * function's doc comment for the predicate rationale — an ARIA role
 * alone does not qualify as the outer element of a nested-interactive
 * pattern; a native interactive tag, `tabindex >= 0`, or an inline
 * event-handler prop is required.
 */
function isMateriallyInteractiveJsx(element: JsxElement): boolean {
  const tag = element.tagName;
  if (isJsxPascalCase(tag)) return false;
  if (isInteractiveJsxTag(element, tag)) return true;
  if (hasFocusableTabindexJsx(element)) return true;
  if (hasInlineHandlerJsx(element)) return true;
  return false;
}

function hasFocusableTabindexJsx(element: JsxElement): boolean {
  // Accept both JSX's camelCase (`tabIndex`) and the lowercase HTML-style
  // (`tabindex`) authors occasionally copy-paste. Either a string
  // literal (`tabIndex="0"`) or an expression resolvable to a non-
  // negative integer (`tabIndex={0}`) qualifies as a focus stop.
  for (const attr of element.attributes) {
    if (attr.name !== "tabIndex" && attr.name !== "tabindex") continue;
    if (parseJsxTabindexValue(attr.value) >= 0) return true;
  }
  return false;
}

function parseJsxTabindexValue(value: JsxAttribute["value"]): number {
  if (!value) return Number.NaN;
  // Expression `raw` includes the JSX braces (e.g. `{0}`); strip
  // them before parsing as a number.
  const rawSource = value.kind === "StringLiteral" ? value.value : value.raw;
  const stripped = rawSource.trim().replace(/^\{/, "").replace(/\}$/, "").trim();
  const n = Number.parseInt(stripped, 10);
  return Number.isFinite(n) ? n : Number.NaN;
}

function hasInlineHandlerJsx(element: JsxElement): boolean {
  for (const name of HANDLER_ATTRIBUTES_JSX) {
    if (hasJsxAttribute(element, name)) return true;
  }
  // Lowercase HTML-style handler attrs may appear on intrinsic elements
  // when authors copy-paste HTML into JSX; accept those too rather than
  // silently under-counting.
  for (const name of HANDLER_ATTRIBUTES_HTML) {
    if (hasJsxAttribute(element, name)) return true;
  }
  return false;
}

function isInteractiveJsx(element: JsxElement): boolean {
  const tag = element.tagName;
  if (isJsxPascalCase(tag)) return false;
  if (isInteractiveJsxTag(element, tag)) return true;
  const role = getJsxAttributeString(element, "role");
  if (role !== null && INTERACTIVE_ROLES.has(role.toLowerCase())) return true;
  return false;
}

function isInteractiveJsxTag(element: JsxElement, tag: string): boolean {
  if (!INTERACTIVE_TAGS.has(tag)) return false;
  if (tag === "a") return hasJsxAttribute(element, "href");
  if (tag === "input") {
    const type = getJsxAttributeString(element, "type");
    return type !== "hidden";
  }
  if (tag === "audio" || tag === "video") {
    return hasJsxAttribute(element, "controls");
  }
  return true;
}

function describeJsx(element: JsxElement): string {
  const tag = element.tagName;
  const role = getJsxAttributeString(element, "role");
  if (role !== null && INTERACTIVE_ROLES.has(role.toLowerCase())) {
    if (!(INTERACTIVE_TAGS.has(tag) && isInteractiveJsxTag(element, tag))) {
      return `<${tag} role="${role.toLowerCase()}">`;
    }
  }
  if (tag === "a") return `<a href>`;
  return `<${tag}>`;
}

function isJsxPascalCase(tag: string): boolean {
  const first = tag[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

function buildJsxParentMap(module: TsxModule): Map<JsxElement, JsxElement> {
  const parentOf = new Map<JsxElement, JsxElement>();
  const visit = (node: JsxNode, parent: JsxElement | null): void => {
    if (node.kind !== "JsxElement") return;
    if (parent) parentOf.set(node, parent);
    for (const child of node.children) visit(child, node);
  };
  for (const top of module.jsxElements) visit(top, null);
  return parentOf;
}

// ---------------------------------------------------------------------------
// Violation builder
// ---------------------------------------------------------------------------

/**
 * If the outer element's explicit role delegates focus to interactive
 * children per an ARIA 1.2 composite-widget pattern, return the
 * lowercased role so `buildHtmlViolation` can enrich the reason text.
 * Otherwise `null` — no enrichment, default framing.
 */
function compositeWidgetRole(role: string | null): string | null {
  if (role === null) return null;
  const lower = role.toLowerCase();
  return COMPOSITE_WIDGET_DELEGATING_ROLES.has(lower) ? lower : null;
}

function buildHtmlViolation(
  outer: string,
  inner: string,
  outerLine: number,
  loc: { line: number; column: number },
  compositeRole: string | null,
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  // Additive composite-widget framing — candidate stays visible, severity
  // stays "error"; the ARIA 1.2 note lets a consuming agent dismiss-or-
  // verify in one read when the pattern is an idiomatic tablist / menu /
  // listbox / tree / grid composite (focus delegated to children via
  // roving tabindex) rather than a genuine two-focusable nesting bug.
  const compositeNote =
    compositeRole === null
      ? ""
      : ` Note: outer role="${compositeRole}" is an ARIA 1.2 composite-widget role that delegates focus to interactive descendants — if this is a tablist / menu / listbox / tree / grid pattern, verify the container implements roving tabindex (or aria-activedescendant) so only one descendant is in the tab order.`;
  const compositeSuggestion =
    compositeRole === null
      ? ""
      : ` If this is an intentional composite widget (role="${compositeRole}" with focus delegated to the ${inner} via roving tabindex), the nesting is idiomatic — verify the focus-management implementation on the parent rather than flattening the markup, and suppress at source with <!-- ra11y-disable semantics/nested-interactive --> once confirmed.`;
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `${inner} is nested inside ${outer} (opened on line ${outerLine}) — interactive controls must not be nested. Click handling, focus order, and the accessible name/role become undefined.${compositeNote}`,
    suggestion: `Move ${inner} out of ${outer}, or flatten the markup: keep one interactive element and make the other a plain <span>/<div>. If the outer is a card link, place the ${inner} as a sibling and use CSS to overlay it.${compositeSuggestion}`,
  };
}
