/**
 * Rule: semantics/visual-disabled-non-control
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set; and notification of changes to these items
 * > is available to user agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags non-interactive elements (`<div>`, `<span>`, `<a>` without
 * `href`, `<li>` without an interactive role) that look disabled —
 * via a class token like `disabled` / `inactive` / `is-disabled` /
 * `disabled-state`, OR an inline style declaring
 * `cursor: not-allowed` or `pointer-events: none` — but carry no
 * programmatic disabled signal (no `aria-disabled="true"`, no native
 * `disabled` attribute on a host that supports it, no interactive
 * `role` putting them in scope of the disabled state model).
 *
 * Common in template UI toolkits where the same visual class is
 * sprayed onto both real `<button>` controls (which DO support
 * `disabled` natively) and decorative wrappers / list items styled
 * to match. The wrappers visually look disabled to sighted users,
 * but the accessibility tree exposes them as unflagged static
 * content — assistive tech announces nothing. WCAG 4.1.2 requires
 * that user-settable states reach the accessibility tree.
 *
 * Static predicate (provable from the element's own attributes):
 *
 *   1. The element is non-interactive: `<div>`, `<span>`, `<li>`
 *      (without an interactive `role`), or `<a>` without an `href`.
 *      Native interactive controls (`<button>`, `<input>`,
 *      `<select>`, `<textarea>`, `<fieldset>`, `<optgroup>`,
 *      `<option>`) and `<a href>` already have a programmatic
 *      disabled story (the `disabled` attribute, or the focusable
 *      anchor expecting `aria-disabled` + `tabindex="-1"`) — they
 *      are owned by other rules.
 *   2. The element carries one of the visual-disabled signals:
 *        - A class token matching `\b(disabled|is-disabled|inactive|disabled-state)\b`
 *          (whole-word, case-insensitive).
 *        - An inline `style` attribute declaring `cursor: not-allowed`
 *          OR `pointer-events: none`. (`opacity: 0.5` is intentionally
 *          NOT in this list — opacity is too commonly used for
 *          decorative dimming, fade-in animations, hover states,
 *          theming. Including it would cross the heuristic-emission
 *          line: per `docs/kb/architecture/ai-first-consumer.md`, a
 *          predicate that fires on speculation about composition is
 *          dishonest. The two signals we keep — `cursor: not-allowed`
 *          and `pointer-events: none` — are unambiguous "this looks
 *          and behaves like a disabled control" cues authors don't
 *          reach for decoratively.)
 *   3. The element does NOT have any of:
 *        - `aria-disabled="true"` (the programmatic signal).
 *        - A native `disabled` attribute (only valid on
 *          `<button>` / `<input>` / `<select>` / `<textarea>` /
 *          `<fieldset>` / `<optgroup>` / `<option>` — but the
 *          predicate's gate-1 already excluded those tags; this
 *          condition reads "no escape hatch on tags that don't
 *          support it either").
 *        - An interactive `role` (`button`, `link`, `checkbox`,
 *          `radio`, `tab`, `menuitem`, `option`, `switch`,
 *          `combobox`, `slider`, `spinbutton`, `searchbox`,
 *          `textbox`) — when one is set, the element is being
 *          augmented into a real control and `aria-disabled` is
 *          the right escape hatch (which we're already checking).
 *
 * Severity is `warning` (not `error`) because the static predicate
 * cannot prove this isn't intentional visual-only decoration — a
 * "Coming soon" badge styled as `cursor: not-allowed` purely for
 * vibe, a list item dimmed because the section is collapsed, a
 * decorative chip with a `disabled` modifier in a design-system
 * palette demo. The reason text frames the question rather than
 * asserting the violation: per `docs/kb/architecture/ai-first-consumer.md`
 * "Reason text and severity must agree", the agent reading the
 * surrounding code is the correct arbiter, and warning + question-
 * framed reason matches the predicate strength honestly.
 *
 * Out of scope (deliberate):
 *   - `<button>`, `<input>`, etc. — these support `disabled`
 *     natively; using a class without the attribute is a different
 *     failure shape covered by `forms/disabled-without-attribute`-
 *     style rules where they exist.
 *   - `<a class="disabled" href="…">` — focusable anchor with a
 *     class. Owned by `aria/disabled-link-surrogate` (which scopes
 *     to non-interactive `<span>`/`<div>` surrogates) and broader
 *     anchor-disabled patterns. Static analysis on `<a href>` +
 *     class is also covered by other rules; deferring keeps this
 *     rule narrow.
 *   - `opacity: 0.5` and similar single-channel dimming. See above.
 *   - PascalCase JSX components (opaque renders) — unscoped.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

/**
 * Tags whose disabled state, if any, must be exposed via aria-disabled
 * or an interactive role — the rule's "non-interactive host" gate.
 *
 * `a` is included because the rule fires only when there is no `href`
 * (a non-focusable anchor); the JSX/HTML branch checks `href` presence
 * before treating an `<a>` as a candidate.
 *
 * `li` is included because list items are commonly styled as disabled
 * pseudo-controls in menu / nav widgets without role="menuitem" —
 * they are non-focusable bare list items in the absence of an
 * interactive role.
 */
const NON_INTERACTIVE_HOSTS: ReadonlySet<string> = new Set(["div", "span", "a", "li"]);

/**
 * Whole-word class tokens that signal a visually-disabled control.
 * Matched case-insensitively against each token in the class list.
 * The list is intentionally short and exact-match: heuristic-emission
 * is discouraged in `docs/kb/architecture/ai-first-consumer.md`, so
 * we only match tokens that authors reach for when they mean
 * "disabled" — not partial / fuzzy substrings.
 */
const VISUAL_DISABLED_CLASS_TOKENS: ReadonlySet<string> = new Set([
  "disabled",
  "is-disabled",
  "inactive",
  "disabled-state",
]);

/**
 * Roles that turn the element into an interactive control whose
 * disabled state should be exposed via `aria-disabled` (already a
 * pass condition). When the element carries any of these and DOES
 * NOT have `aria-disabled="true"`, the visual-disabled signal still
 * sits unannounced — but the failure is then better described as
 * "interactive role + missing aria-disabled" and gets owned by the
 * paired role-specific rules. We therefore exempt these here to
 * stay narrow.
 */
const INTERACTIVE_ROLES: ReadonlySet<string> = new Set([
  "button",
  "link",
  "checkbox",
  "radio",
  "tab",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "option",
  "switch",
  "combobox",
  "slider",
  "spinbutton",
  "searchbox",
  "textbox",
]);

export const rule = defineRule({
  id: "semantics/visual-disabled-non-control",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "warning",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Non-interactive elements (<div>, <span>, <a> without href, <li> without an interactive role) styled as disabled — via a class token like 'disabled'/'inactive'/'is-disabled'/'disabled-state', or an inline style declaring 'cursor: not-allowed' or 'pointer-events: none' — must expose the disabled state via aria-disabled='true' or an interactive role. Otherwise the visual disabled signal reaches sighted users but never reaches the accessibility tree.",
    rationale:
      'WCAG 4.1.2 requires that component states be programmatically determinable. Template UI toolkits often spray the same `disabled` / `inactive` class — or an inline `cursor: not-allowed` — across both real `<button>` controls (where the native `disabled` attribute also lives) and decorative wrappers, list items, or `<div>` / `<span>` surrogates that LOOK disabled but expose nothing to assistive tech. Sighted users see the greyed-out element; screen-reader users hear it as plain prose, with no signal that it is a disabled control. The fix is `aria-disabled="true"` on the host (plus an interactive role like `role="button"` if the element is standing in for a control), or — when the element is genuinely decorative and not a control at all — renaming the class so the markup honest about intent. Severity is `warning` because the static predicate can\'t rule out intentional visual-only decoration; the agent reading the consumer site is the correct arbiter.',
    goodExample: `<div class="card disabled" aria-disabled="true" role="button" tabindex="-1">Coming soon</div>
<span class="inactive" aria-disabled="true">Filter unavailable</span>
<button class="disabled" disabled>Submit</button>`,
    badExample: `<div class="card disabled">Coming soon</div>
<span class="inactive">Filter unavailable</span>
<li class="is-disabled">Archived</li>
<a class="next disabled-state">Next &rsaquo;</a>
<div style="cursor: not-allowed; opacity: 0.5;">Locked</div>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-disabled",
      "https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA16",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, ctx.filePath, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, ctx.filePath, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

interface VisualDisabledHit {
  /** Which evidence triggered: a class token, or an inline-style declaration. */
  readonly via: "class" | "style";
  /** The author-facing token — class name or `cursor: not-allowed` / `pointer-events: none`. */
  readonly token: string;
}

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, filePath: string, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    const tag = el.tagName.toLowerCase();
    if (!NON_INTERACTIVE_HOSTS.has(tag)) continue;
    if (tag === "a" && hasHtmlAttribute(el, "href")) continue;
    const hit = htmlVisualDisabledEvidence(el);
    if (hit === null) continue;
    if (htmlHasProgrammaticDisabledSignal(el)) continue;
    if (htmlHasInteractiveRole(el)) continue;
    emit(buildViolation(tag, el.loc.start, hit, filePath));
  }
}

function htmlVisualDisabledEvidence(el: HtmlElement): VisualDisabledHit | null {
  const classValue = getHtmlAttribute(el, "class");
  const classHit = classValue === null ? null : firstClassHit(classValue);
  if (classHit !== null) return { via: "class", token: classHit };
  const styleValue = getHtmlAttribute(el, "style");
  const styleHit = styleValue === null ? null : firstStyleHit(styleValue);
  if (styleHit !== null) return { via: "style", token: styleHit };
  return null;
}

function htmlHasProgrammaticDisabledSignal(el: HtmlElement): boolean {
  const ariaDisabled = getHtmlAttribute(el, "aria-disabled");
  if (ariaDisabled !== null && ariaDisabled.trim().toLowerCase() === "true") return true;
  // Native `disabled` is invalid on the non-interactive hosts this rule
  // gates on — but if the author put it there anyway, treat it as
  // intent-to-mark-disabled and pass. The HTML validator will yell
  // about the misplaced attribute on its own.
  if (hasHtmlAttribute(el, "disabled")) return true;
  return false;
}

function htmlHasInteractiveRole(el: HtmlElement): boolean {
  const role = getHtmlAttribute(el, "role");
  if (role === null) return false;
  for (const token of role.split(/\s+/u)) {
    if (INTERACTIVE_ROLES.has(token.trim().toLowerCase())) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, filePath: string, emit: Emit): void {
  for (const el of walkJsxElements(module)) {
    const tag = el.tagName.toLowerCase();
    if (!NON_INTERACTIVE_HOSTS.has(tag)) continue;
    if (isJsxPascalCase(el.tagName)) continue;
    if (tag === "a" && hasJsxAttribute(el, "href")) continue;
    const hit = jsxVisualDisabledEvidence(el);
    if (hit === null) continue;
    if (jsxHasProgrammaticDisabledSignal(el)) continue;
    if (jsxHasInteractiveRole(el)) continue;
    emit(buildViolation(tag, el.loc.start, hit, filePath));
  }
}

function jsxVisualDisabledEvidence(el: JsxElement): VisualDisabledHit | null {
  const classValue = getJsxAttributeString(el, "className") ?? getJsxAttributeString(el, "class");
  const classHit = classValue === null ? null : firstClassHit(classValue);
  if (classHit !== null) return { via: "class", token: classHit };
  // Inline `style="cursor: not-allowed"` only matches when the JSX
  // attribute is a string literal — `style={{ cursor: "not-allowed" }}`
  // is an expression the parser leaves opaque, so we pass on it
  // (per "Don't duplicate capability the agent already has": parsing
  // a JSX object-expression to read its values is the kind of work
  // the agent does better by Read-ing the file).
  const styleValue = getJsxAttributeString(el, "style");
  const styleHit = styleValue === null ? null : firstStyleHit(styleValue);
  if (styleHit !== null) return { via: "style", token: styleHit };
  return null;
}

function jsxHasProgrammaticDisabledSignal(el: JsxElement): boolean {
  const ariaDisabled = getJsxAttributeString(el, "aria-disabled");
  if (ariaDisabled !== null && ariaDisabled.trim().toLowerCase() === "true") return true;
  if (hasJsxAttribute(el, "disabled")) return true;
  return false;
}

function jsxHasInteractiveRole(el: JsxElement): boolean {
  const role = getJsxAttributeString(el, "role");
  if (role === null) return false;
  for (const token of role.split(/\s+/u)) {
    if (INTERACTIVE_ROLES.has(token.trim().toLowerCase())) return true;
  }
  return false;
}

function isJsxPascalCase(tagName: string): boolean {
  const first = tagName[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

// ---------------------------------------------------------------------------
// Shared evidence parsers
// ---------------------------------------------------------------------------

/**
 * Returns the first whole-word class token in the class list that
 * matches one of the visual-disabled markers, preserving the author's
 * casing for the violation message. Splits on ASCII whitespace.
 */
function firstClassHit(classValue: string): string | null {
  for (const raw of classValue.split(/\s+/u)) {
    const token = raw.trim();
    if (token.length === 0) continue;
    if (VISUAL_DISABLED_CLASS_TOKENS.has(token.toLowerCase())) return token;
  }
  return null;
}

/**
 * Returns `cursor: not-allowed` or `pointer-events: none` (whichever
 * appears first) when the inline style declares one. The matcher is
 * intentionally substring-based on a normalized form (lowercased,
 * inner whitespace collapsed) — author shorthand like
 * `cursor:not-allowed` and `cursor : not-allowed` both match.
 */
function firstStyleHit(styleValue: string): string | null {
  const normalized = styleValue.toLowerCase().replace(/\s+/gu, " ");
  if (/cursor\s*:\s*not-allowed\b/u.test(normalized)) return "cursor: not-allowed";
  if (/pointer-events\s*:\s*none\b/u.test(normalized)) return "pointer-events: none";
  return null;
}

// ---------------------------------------------------------------------------
// Violation construction
// ---------------------------------------------------------------------------

function buildViolation(
  tag: string,
  loc: { readonly line: number; readonly column: number },
  hit: VisualDisabledHit,
  filePath: string,
): Parameters<Emit>[0] {
  const evidencePhrase =
    hit.via === "class"
      ? `class token "${hit.token}" signals a disabled control`
      : `inline style "${hit.token}" signals a disabled control`;
  const message =
    `<${tag}> ${evidencePhrase}, but the element has no aria-disabled="true", ` +
    `no native disabled attribute, and no interactive role — sighted users see ` +
    `the disabled affordance, but the accessibility tree exposes plain content ` +
    `with no disabled-state signal.`;
  return {
    severity: "warning",
    location: { filePath, line: loc.line, column: loc.column },
    message,
    suggestion: buildSuggestion(tag, hit),
  };
}

function buildSuggestion(tag: string, hit: VisualDisabledHit): string {
  const evidence =
    hit.via === "class" ? `class token "${hit.token}"` : `inline style declaration "${hit.token}"`;
  const exampleAttrs =
    hit.via === "class"
      ? `class="${hit.token}" aria-disabled="true"`
      : `style="${hit.token}" aria-disabled="true"`;
  return (
    `This <${tag}> uses ${evidence} to look disabled, but assistive tech receives no ` +
    `signal of that state. Three closure paths: ` +
    `(1) if the element is standing in for a real control, add aria-disabled="true" ` +
    `(plus an interactive role like role="button" / role="link" if appropriate, and ` +
    `tabindex="-1" so it stays out of the tab order) — example: ` +
    `<${tag} ${exampleAttrs} role="button" tabindex="-1">…</${tag}>; ` +
    `(2) if the element is decorative and not a control at all (a "Coming soon" ` +
    `card, a dimmed list separator), rename the ${hit.via === "class" ? "class" : "style"} ` +
    `so the markup is honest — disabled-named tokens read as control state to ` +
    `future readers; ` +
    `(3) if a native disabled attribute is what you actually want, swap the host for ` +
    `<button>, <input>, <select>, <textarea>, <fieldset>, <optgroup>, or <option>.`
  );
}
