/**
 * Rule: media/img-empty-alt-in-clickable-group
 * Satisfies: wcag22:1.1.1, wcag21:1.1.1, wcag22:4.1.2, wcag21:4.1.2
 * Spec:
 *   https://www.w3.org/TR/WCAG22/#non-text-content
 *   https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > All non-text content that is presented to the user has a text
 * > alternative that serves the equivalent purpose, except for the
 * > situations listed below: controls, input, time-based media,
 * > tests, sensory, CAPTCHA, decoration/formatting/invisible.
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined.
 *
 * Source:
 *   https://www.w3.org/TR/WCAG22/#non-text-content
 *   https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * `alt=""` is the canonical "this image is decorative — ignore it" marker.
 * It is correct when the image sits in flow content alongside text that
 * already carries the meaning. It is **wrong** when the image is the
 * sole visual content of an interactive widget — a rating tile, a
 * gallery thumbnail link, an icon-only button — and the wrapping
 * control has no other accessible-name source. Marking the image
 * decorative AND giving the control no name leaves the link/button
 * announced by screen readers as "link" / "button" with no payload.
 *
 * The predicate is "image is the only thing the agent could derive a
 * name from, AND the developer told us to ignore it." Two pieces:
 *
 *   1. The image is `<img alt="">` (explicit empty-string alt — not
 *      missing alt, which `media/alt-text-missing` already covers).
 *      `<input type="image" alt="">` and SVG `<image>` are out of scope
 *      here — the alt-empty + clickable-group antipattern is dominated
 *      by raster `<img>` in icon-button / thumbnail-link patterns.
 *
 *   2. The closest interactive ancestor (`<button>`, `<a href>`,
 *      `[role=button]`, `[role=link]`, or any element with an inline
 *      click handler) has no other accessible-name source: no
 *      aria-label, no aria-labelledby, no title, and no sibling
 *      content with text or expression children.
 *
 * Both conditions must hold. Either one alone is benign:
 *
 *   - `<img alt="">` alone — covered by spec exemption (decorative).
 *   - Icon-only `<button aria-label="Save">` — name source is the
 *     parent's aria-label; the empty alt is correct.
 *   - `<a href><img alt="">Tile name</a>` — the sibling text "Tile
 *     name" is the link's accessible name; empty alt is correct.
 *
 * The asymmetric failure mode is "control with no name." Per the
 * AI-first consumer model the finding ships at `warning` (not error)
 * because the predicate hinges on the wrapping control's accessible
 * name being derivable only from the image — a static-evidence claim
 * about composition that the agent reading the file confirms in one
 * read. Speculative emission about composition is heuristic territory;
 * the surface stays honest by capping severity at the level the
 * evidence supports.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  findHtmlElementsByTag,
  findJsxElementsByTag,
  getHtmlAttribute,
  getJsxAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  htmlTextContent,
  walkHtmlElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";

/**
 * Inline event-handler attribute names (HTML lowercase form). Mirrors
 * the predicate used by `semantics/nested-interactive` —
 * an inline handler makes the element a focus / activation surface
 * even without a native interactive tag or ARIA role.
 */
const HANDLER_ATTRIBUTES_HTML: readonly string[] = [
  "onclick",
  "onkeydown",
  "onkeyup",
  "onkeypress",
  "onmousedown",
  "onmouseup",
];

/** JSX camelCase counterparts. JSX preserves casing; both forms appear in the wild. */
const HANDLER_ATTRIBUTES_JSX: readonly string[] = [
  "onClick",
  "onKeyDown",
  "onKeyUp",
  "onKeyPress",
  "onMouseDown",
  "onMouseUp",
];

export const rule = defineRule({
  id: "media/img-empty-alt-in-clickable-group",
  satisfies: ["wcag22:1.1.1", "wcag21:1.1.1", "wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "warning",
  scope: "document",
  // The fix is "give the parent control an accessible name" — that's a
  // prose decision the static scanner cannot author. Tagged
  // `verify-in-source` so `plan.fixesByClass` reflects honest "agent
  // reads adjacent code" expectation rather than the `mechanical` lane.
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      'Flags <img alt=""> when the image is the only visual content of an interactive ancestor (button, link, role=button/link, or onClick host) and that ancestor has no other accessible-name source.',
    rationale:
      'alt="" tells assistive tech to ignore the image. That is correct in flow content, but wrong when the image is the sole visual payload of a clickable widget — the wrapping <button>/<a> is then announced as "button"/"link" with no name, and operating it is opaque to screen-reader users. media/alt-text-missing covers the missing-alt case; this rule covers the "explicitly decorative inside an unnamed control" case.',
    goodExample: `<a href="/profile" aria-label="View profile"><img src="avatar.png" alt="" /></a>`,
    badExample: `<a href="/profile"><img src="avatar.png" alt="" /></a>`,
    normativeQuote:
      "All non-text content that is presented to the user has a text alternative that serves the equivalent purpose. For all user interface components, the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#non-text-content",
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/WAI/tutorials/images/functional/",
    ],
  },
  afterFile(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
      return;
    }
    if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  const parentOf = buildHtmlParentMap(doc);
  for (const img of findHtmlElementsByTag(doc, "img")) {
    if (!hasExplicitEmptyAltHtml(img)) continue;
    const wrapper = findInteractiveAncestorHtml(img, parentOf);
    if (!wrapper) continue;
    if (hasOwnAccessibleNameHtml(wrapper)) continue;
    if (hasSiblingTextContributionHtml(wrapper, img)) continue;
    emit(buildHtmlViolation(img, wrapper));
  }
}

/**
 * True iff the `<img>` carries an explicit `alt=""` (empty-string
 * value). Missing `alt` is a different rule's job
 * (`media/alt-text-missing`); whitespace-only alt (`alt=" "`) is also
 * treated as decorative by browsers and falls under this rule.
 */
function hasExplicitEmptyAltHtml(img: HtmlElement): boolean {
  if (!hasHtmlAttribute(img, "alt")) return false;
  const value = getHtmlAttribute(img, "alt") ?? "";
  return value.trim().length === 0;
}

/**
 * Climbs the DOM from the image and returns the closest ancestor that
 * is a button, anchor with href, element with `role="button"` /
 * `role="link"`, or element carrying an inline click/key handler.
 * Returns null when no interactive wrapper is reached before the root.
 */
function findInteractiveAncestorHtml(
  img: HtmlElement,
  parentOf: ReadonlyMap<HtmlElement, HtmlElement>,
): HtmlElement | null {
  let parent = parentOf.get(img);
  while (parent) {
    if (isInteractiveWrapperHtml(parent)) return parent;
    parent = parentOf.get(parent);
  }
  return null;
}

function isInteractiveWrapperHtml(element: HtmlElement): boolean {
  const tag = element.tagName.toLowerCase();
  if (tag === "button") return true;
  if (tag === "a" && hasHtmlAttribute(element, "href")) return true;
  const role = (getHtmlAttribute(element, "role") ?? "").toLowerCase();
  if (role === "button" || role === "link") return true;
  for (const name of HANDLER_ATTRIBUTES_HTML) {
    if (hasHtmlAttribute(element, name)) return true;
  }
  return false;
}

/**
 * True when the wrapper carries its own accessible-name source —
 * aria-label, aria-labelledby, or title attribute. The wrapper's
 * sibling content is checked separately by
 * {@link hasSiblingTextContributionHtml}.
 */
function hasOwnAccessibleNameHtml(wrapper: HtmlElement): boolean {
  const ariaLabel = getHtmlAttribute(wrapper, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasHtmlAttribute(wrapper, "aria-labelledby")) return true;
  const title = getHtmlAttribute(wrapper, "title");
  if (title !== null && title.trim().length > 0) return true;
  return false;
}

/**
 * True when the wrapper has descendant content (other than the offending
 * image) that contributes to the accessible name — visible text content,
 * or another `<img>` / `<svg>` / `<input>` / element with `aria-label`
 * that would carry a name.
 *
 * The "other than the offending image" carve-out is what makes the
 * predicate honest: a wrapper whose only descendant is this `alt=""`
 * image has nothing else to draw a name from. A wrapper containing
 * `<img alt="">Sibling text</a>` does — the text is the link's name and
 * the empty alt is correct.
 */
function hasSiblingTextContributionHtml(wrapper: HtmlElement, ignore: HtmlElement): boolean {
  // Any descendant text node with non-whitespace content qualifies.
  if (descendantTextWithoutHtml(wrapper, ignore).length > 0) return true;
  // Any sibling element with its own accessible-name source qualifies
  // (e.g., <button><img alt=""><span aria-label="Close">×</span></button>).
  if (hasNamedSiblingElementHtml(wrapper, ignore)) return true;
  return false;
}

/**
 * Concatenated text content of `wrapper`'s descendants, with `ignore`
 * (and its subtree) excluded. Mirrors {@link htmlTextContent} but
 * skips the offending image's branch so its `alt`-derived text (none,
 * since alt is empty) does not count.
 */
function descendantTextWithoutHtml(wrapper: HtmlElement, ignore: HtmlElement): string {
  const chunks: string[] = [];
  const visit = (node: HtmlNode): void => {
    if (node.kind === "HtmlText") {
      chunks.push(node.value);
      return;
    }
    if (node.kind !== "HtmlElement") return;
    if (node === ignore) return;
    for (const child of node.children) visit(child);
  };
  for (const child of wrapper.children) visit(child);
  return chunks.join("").trim();
}

/**
 * True when any descendant of `wrapper` (excluding `ignore`) carries
 * an `aria-label` / `aria-labelledby` / `title` of its own, or is a
 * non-decorative `<img>` / `<svg>` / `<input type="image">` that
 * contributes a name to the wrapper's accessible-name computation.
 */
function hasNamedSiblingElementHtml(wrapper: HtmlElement, ignore: HtmlElement): boolean {
  for (const descendant of walkHtmlElements(wrapper)) {
    if (descendant === wrapper || descendant === ignore) continue;
    if (htmlElementContributesName(descendant)) return true;
  }
  return false;
}

/**
 * True if a single HTML element by itself carries an accessible-name
 * source — used to decide whether a sibling of the offending `<img>`
 * contributes a name to the wrapper's accessible-name computation.
 */
function htmlElementContributesName(element: HtmlElement): boolean {
  if (htmlElementHasOwnNameAttribute(element)) return true;
  const tag = element.tagName.toLowerCase();
  if (tag === "img") return htmlImgHasNonEmptyAlt(element);
  if (tag === "svg") return htmlSvgHasTitleChild(element);
  return false;
}

function htmlElementHasOwnNameAttribute(element: HtmlElement): boolean {
  const ariaLabel = getHtmlAttribute(element, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasHtmlAttribute(element, "aria-labelledby")) return true;
  const title = getHtmlAttribute(element, "title");
  if (title !== null && title.trim().length > 0) return true;
  return false;
}

function htmlImgHasNonEmptyAlt(img: HtmlElement): boolean {
  const alt = getHtmlAttribute(img, "alt");
  return alt !== null && alt.trim().length > 0;
}

function htmlSvgHasTitleChild(svg: HtmlElement): boolean {
  for (const child of svg.children) {
    if (child.kind !== "HtmlElement") continue;
    if (child.tagName.toLowerCase() !== "title") continue;
    if (htmlTextContent(child).length > 0) return true;
  }
  return false;
}

function buildHtmlParentMap(doc: HtmlDocument): Map<HtmlElement, HtmlElement> {
  const parentOf = new Map<HtmlElement, HtmlElement>();
  const visit = (node: HtmlNode, parent: HtmlElement | null): void => {
    if (node.kind !== "HtmlElement") return;
    if (parent) parentOf.set(node, parent);
    for (const child of node.children) visit(child, node);
  };
  for (const top of doc.children) visit(top, null);
  return parentOf;
}

function buildHtmlViolation(
  img: HtmlElement,
  wrapper: HtmlElement,
): {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const wrapperDesc = describeHtmlWrapper(wrapper);
  return {
    severity: "warning",
    location: { filePath: "", line: img.loc.start.line, column: img.loc.start.column },
    message: `<img alt=""> is the only visual content of ${wrapperDesc} (opened on line ${wrapper.loc.start.line}) and the wrapper has no aria-label, aria-labelledby, title, or sibling text — so the control has no accessible name. Screen readers will announce the wrapper's role with no payload.`,
    suggestion: `Either give ${wrapperDesc} an accessible name (e.g., aria-label="…" describing the action / destination, or visible sibling text), or replace the empty alt with descriptive alt text on the <img> so the image becomes the wrapper's name. If the wrapper really has no purpose, remove it.`,
  };
}

function describeHtmlWrapper(wrapper: HtmlElement): string {
  const tag = wrapper.tagName.toLowerCase();
  if (tag === "a") return `<a href>`;
  const role = (getHtmlAttribute(wrapper, "role") ?? "").toLowerCase();
  if (role === "button" || role === "link") return `<${tag} role="${role}">`;
  return `<${tag}>`;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  const parentOf = buildJsxParentMap(module);
  for (const img of findJsxElementsByTag(module, "img")) {
    if (!hasExplicitEmptyAltJsx(img)) continue;
    const wrapper = findInteractiveAncestorJsx(img, parentOf);
    if (!wrapper) continue;
    if (hasOwnAccessibleNameJsx(wrapper)) continue;
    if (hasSiblingTextContributionJsx(wrapper, img)) continue;
    emit(buildJsxViolation(img, wrapper));
  }
}

/**
 * True iff the JSX `<img>` carries an explicit empty-string `alt=""`.
 * Missing alt → `media/alt-text-missing`; expression alt (`alt={x}`)
 * is treated as runtime-derived and skipped here.
 */
function hasExplicitEmptyAltJsx(img: JsxElement): boolean {
  const attr = getJsxAttribute(img, "alt");
  if (!attr) return false;
  if (!attr.value) return false;
  if (attr.value.kind !== "StringLiteral") return false;
  return attr.value.value.trim().length === 0;
}

function findInteractiveAncestorJsx(
  img: JsxElement,
  parentOf: ReadonlyMap<JsxElement, JsxElement>,
): JsxElement | null {
  let parent = parentOf.get(img);
  while (parent) {
    // PascalCase components are opaque — their accessible-name surface
    // depends on the component implementation. Stop the climb rather
    // than guess.
    if (isJsxPascalCase(parent.tagName)) return null;
    if (isInteractiveWrapperJsx(parent)) return parent;
    parent = parentOf.get(parent);
  }
  return null;
}

function isInteractiveWrapperJsx(element: JsxElement): boolean {
  const tag = element.tagName;
  if (tag === "button") return true;
  if (tag === "a" && hasJsxAttribute(element, "href")) return true;
  const role = getJsxAttributeString(element, "role");
  if (role !== null) {
    const lower = role.toLowerCase();
    if (lower === "button" || lower === "link") return true;
  }
  for (const name of HANDLER_ATTRIBUTES_JSX) {
    if (hasJsxAttribute(element, name)) return true;
  }
  // Lowercase HTML-style handlers may appear when authors paste HTML
  // into JSX — accept those too rather than silently under-counting.
  for (const name of HANDLER_ATTRIBUTES_HTML) {
    if (hasJsxAttribute(element, name)) return true;
  }
  return false;
}

function hasOwnAccessibleNameJsx(wrapper: JsxElement): boolean {
  const ariaLabel = getJsxAttributeString(wrapper, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  // Expression-form aria-label (`aria-label={t("save")}`) is treated as
  // runtime-derived — assume a name is provided rather than false-fire.
  const labelAttr = getJsxAttribute(wrapper, "aria-label");
  if (labelAttr?.value?.kind === "Expression") return true;
  if (hasJsxAttribute(wrapper, "aria-labelledby")) return true;
  const title = getJsxAttributeString(wrapper, "title");
  if (title !== null && title.trim().length > 0) return true;
  const titleAttr = getJsxAttribute(wrapper, "title");
  if (titleAttr?.value?.kind === "Expression") return true;
  return false;
}

function hasSiblingTextContributionJsx(wrapper: JsxElement, ignore: JsxElement): boolean {
  if (descendantTextWithoutJsx(wrapper, ignore).length > 0) return true;
  if (hasExpressionChildOutsideJsx(wrapper, ignore)) return true;
  if (hasNamedSiblingElementJsx(wrapper, ignore)) return true;
  return false;
}

/**
 * Concatenated literal text content of `wrapper`'s descendants, with
 * `ignore` (and its subtree) excluded. Expression children
 * (`{label}`) do not count here — they are handled by
 * {@link hasExpressionChildOutsideJsx} which treats any expression
 * outside the offending image as runtime-derived name evidence.
 */
function descendantTextWithoutJsx(wrapper: JsxElement, ignore: JsxElement): string {
  const chunks: string[] = [];
  const visit = (node: JsxNode): void => {
    if (node.kind === "JsxText") {
      chunks.push(node.value);
      return;
    }
    if (node.kind !== "JsxElement") return;
    if (node === ignore) return;
    for (const child of node.children) visit(child);
  };
  for (const child of wrapper.children) visit(child);
  return chunks.join("").trim();
}

/**
 * True when the wrapper has any expression child outside the offending
 * image's subtree. Expression children (`{label}`, `{t("close")}`)
 * commonly carry the wrapper's accessible name at runtime; treating
 * them as names mirrors the false-negative-friendly tradeoff
 * `hasAccessibleNameJsx` makes in `media/alt-text-missing`.
 */
function hasExpressionChildOutsideJsx(wrapper: JsxElement, ignore: JsxElement): boolean {
  let found = false;
  const visit = (node: JsxNode): void => {
    if (found) return;
    if (node.kind === "JsxExpression") {
      found = true;
      return;
    }
    if (node.kind !== "JsxElement") return;
    if (node === ignore) return;
    for (const child of node.children) visit(child);
  };
  for (const child of wrapper.children) visit(child);
  return found;
}

function hasNamedSiblingElementJsx(wrapper: JsxElement, ignore: JsxElement): boolean {
  let found = false;
  const visit = (node: JsxNode): void => {
    if (found) return;
    if (node.kind !== "JsxElement") return;
    if (node === ignore) return;
    if (node !== wrapper && jsxElementContributesName(node)) {
      found = true;
      return;
    }
    for (const child of node.children) visit(child);
  };
  for (const child of wrapper.children) visit(child);
  return found;
}

/**
 * True if a single JSX element by itself carries an accessible-name
 * source — used to decide whether a sibling of the offending `<img>`
 * contributes a name to the wrapper's accessible-name computation.
 * Expression-form aria-label / alt are treated as runtime-derived
 * names (false-negative-friendly tradeoff).
 */
function jsxElementContributesName(element: JsxElement): boolean {
  if (jsxElementHasOwnNameAttribute(element)) return true;
  const tag = element.tagName.toLowerCase();
  if (tag === "img") return jsxImgContributesName(element);
  return false;
}

function jsxElementHasOwnNameAttribute(element: JsxElement): boolean {
  const ariaLabel = getJsxAttributeString(element, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  const labelAttr = getJsxAttribute(element, "aria-label");
  if (labelAttr?.value?.kind === "Expression") return true;
  if (hasJsxAttribute(element, "aria-labelledby")) return true;
  const title = getJsxAttributeString(element, "title");
  if (title !== null && title.trim().length > 0) return true;
  return false;
}

function jsxImgContributesName(img: JsxElement): boolean {
  const alt = getJsxAttributeString(img, "alt");
  if (alt !== null && alt.trim().length > 0) return true;
  const altAttr = getJsxAttribute(img, "alt");
  return altAttr?.value?.kind === "Expression";
}

function buildJsxParentMap(module: TsxModule): Map<JsxElement, JsxElement> {
  const parentOf = new Map<JsxElement, JsxElement>();
  const visit = (node: JsxNode, parent: JsxElement | null): void => {
    if (node.kind !== "JsxElement") return;
    if (parent) parentOf.set(node, parent);
    for (const child of node.children) visit(child, node);
  };
  for (const top of module.jsxElements) visit(top, null);
  return parentOf;
}

function isJsxPascalCase(tag: string): boolean {
  const first = tag[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

function buildJsxViolation(
  img: JsxElement,
  wrapper: JsxElement,
): {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const wrapperDesc = describeJsxWrapper(wrapper);
  return {
    severity: "warning",
    location: { filePath: "", line: img.loc.start.line, column: img.loc.start.column },
    message: `<img alt=""> is the only visual content of ${wrapperDesc} (opened on line ${wrapper.loc.start.line}) and the wrapper has no aria-label, aria-labelledby, title, or sibling text — so the control has no accessible name. Screen readers will announce the wrapper's role with no payload.`,
    suggestion: `Either give ${wrapperDesc} an accessible name (e.g., aria-label="…" describing the action / destination, or visible sibling text / {expression} children), or replace the empty alt with descriptive alt text on the <img> so the image becomes the wrapper's name. If the wrapper really has no purpose, remove it.`,
  };
}

function describeJsxWrapper(wrapper: JsxElement): string {
  const tag = wrapper.tagName;
  if (tag === "a") return `<a href>`;
  const role = getJsxAttributeString(wrapper, "role");
  if (role !== null) {
    const lower = role.toLowerCase();
    if (lower === "button" || lower === "link") return `<${tag} role="${lower}">`;
  }
  return `<${tag}>`;
}
