/**
 * Rule: aria/dialog-role-missing
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links, and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags container elements that carry every behavioural signal of a
 * modal dialog shell — the focus-trap entry-point (`tabindex="-1"`),
 * an accessible name reference (`aria-labelledby` or `aria-label`),
 * managed visibility (`aria-hidden`, regardless of `true`/`false`),
 * and a class-name token in the {modal, dialog, drawer, offcanvas,
 * popover} family — but lack the `role="dialog"` / `role="alertdialog"`
 * declaration that would let assistive tech announce the container as
 * a dialog. `aria-modal` is also accepted as the role-substitute since
 * a `<dialog>` HTML element with `aria-modal="true"` produces the same
 * announcement, and many handcrafted shells drop the role attribute
 * entirely on the assumption that visual chrome (overlay, focus trap)
 * is enough.
 *
 * The five-signal conjunction is high-confidence: every signal in the
 * predicate is independently load-bearing for a real modal shell, and
 * a non-dialog container that carries all five is rare enough to keep
 * false-positives in the "agent dismisses in one read" zone. Per the
 * AI-first consumer doctrine, surface-then-annotate is the correct
 * default — the agent reads the suggestion and decides.
 *
 * Different from `keyboard/handler-missing` (focus-management lane) and
 * from any future focus-trap rule — this is the role-presence lane:
 * does AT have a name + role to announce when focus enters the shell?
 *
 * Class-token trigger set (case-insensitive, hyphen-or-underscore-or-
 * end-of-token boundary): `modal`, `dialog`, `drawer`, `offcanvas`,
 * `popover`. Matches `Modal`, `modal-content`, `offcanvas-body`,
 * `popover_inner` etc. Does NOT match `modally`, `dialoguer`,
 * `drawerless` etc. — the regex is token-bounded.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

/**
 * Whole-token, case-insensitive matcher for the dialog-shell class
 * family. Anchored to the start of a class token (`^`) and bounded on
 * the right by hyphen, underscore, or end-of-string so:
 *   - `modal`, `Modal`, `modal-content`, `modal_body` match
 *   - `modally`, `dialoguer`, `drawerless` do NOT match
 */
const DIALOG_CLASS_TOKEN_RE = /^(modal|dialog|drawer|offcanvas|popover)([-_]|$)/i;

/**
 * The native `<dialog>` element is the canonical role-carrier — it has
 * an implicit `role="dialog"` per HTML — so the rule never fires on it
 * regardless of the surrounding signals.
 */
const ROLE_CARRYING_TAGS: ReadonlySet<string> = new Set(["dialog"]);

export const rule = defineRule({
  id: "aria/dialog-role-missing",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Container with dialog signals (tabindex=-1, aria-labelledby/aria-label, aria-hidden, class with modal|dialog|drawer|offcanvas|popover token) but missing role=dialog/alertdialog and aria-modal.",
    rationale:
      'A handcrafted modal shell that wires up the focus trap (`tabindex="-1"` on the outer container), references a heading for its accessible name (`aria-labelledby`), and toggles visibility with `aria-hidden` looks complete to a sighted user — the overlay, the focus return, the chrome are all there. But screen readers announce the container by its role, and a `<div>` is announced as a generic group. Without `role="dialog"` (or `role="alertdialog"` for confirmations) the user is told they have entered "a region" or nothing at all, instead of hearing "Dialog: Confirm deletion." `aria-modal="true"` on its own is also enough for AT to announce the dialog framing — many implementations rely on the native `<dialog>` element\'s implicit role plus `aria-modal`. This is a direct 4.1.2 gap: the role conveyed visually (a modal dialog) is not exposed programmatically.',
    goodExample: `<div role="dialog" aria-modal="true" aria-labelledby="dlg-title" tabindex="-1" class="modal-content" aria-hidden="false">
  <h2 id="dlg-title">Confirm</h2>
</div>`,
    badExample: `<div tabindex="-1" aria-labelledby="dlg-title" aria-hidden="false" class="modal-content">
  <h2 id="dlg-title">Confirm</h2>
</div>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#dialog",
      "https://www.w3.org/TR/wai-aria-1.2/#alertdialog",
      "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Loc = { readonly line: number; readonly column: number };

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    const candidate = htmlDialogShellCandidate(el);
    if (candidate === null) continue;
    emit(buildViolation(el.tagName, el.loc.start, candidate.hit, candidate.nameSource));
  }
}

/** HTML analogue of {@link jsxDialogShellCandidate}. */
function htmlDialogShellCandidate(el: HtmlElement): JsxCandidate | null {
  if (ROLE_CARRYING_TAGS.has(el.tagName.toLowerCase())) return null;
  if (!htmlHasFocusTrapTabindex(el)) return null;
  if (!hasHtmlAccessibleNameRef(el)) return null;
  if (!hasHtmlAttribute(el, "aria-hidden")) return null;
  const classAttr = getHtmlAttribute(el, "class");
  const hit = classAttr === null ? null : firstDialogClassHit(classAttr);
  if (hit === null) return null;
  if (htmlHasDialogRoleSignal(el)) return null;
  return { hit, nameSource: htmlNameSource(el) };
}

function htmlHasFocusTrapTabindex(el: HtmlElement): boolean {
  const raw = getHtmlAttribute(el, "tabindex");
  if (raw === null) return false;
  return raw.trim() === "-1";
}

function hasHtmlAccessibleNameRef(el: HtmlElement): boolean {
  return hasHtmlAttribute(el, "aria-labelledby") || hasHtmlAttribute(el, "aria-label");
}

function htmlHasDialogRoleSignal(el: HtmlElement): boolean {
  const role = getHtmlAttribute(el, "role");
  if (role !== null && roleMentionsDialog(role)) return true;
  return hasHtmlAttribute(el, "aria-modal");
}

function htmlNameSource(el: HtmlElement): "aria-labelledby" | "aria-label" {
  return hasHtmlAttribute(el, "aria-labelledby") ? "aria-labelledby" : "aria-label";
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const el of walkJsxElements(module)) {
    const candidate = jsxDialogShellCandidate(el);
    if (candidate === null) continue;
    emit(buildViolation(el.tagName, el.loc.start, candidate.hit, candidate.nameSource));
  }
}

interface JsxCandidate {
  readonly hit: string;
  readonly nameSource: "aria-labelledby" | "aria-label";
}

/** Returns the fields needed to build a violation, or null if the JSX element is not a naked dialog shell. */
function jsxDialogShellCandidate(el: JsxElement): JsxCandidate | null {
  if (isComponent(el.tagName)) return null;
  if (ROLE_CARRYING_TAGS.has(el.tagName.toLowerCase())) return null;
  if (!jsxHasFocusTrapTabindex(el)) return null;
  if (!hasJsxAccessibleNameRef(el)) return null;
  if (!hasJsxAttribute(el, "aria-hidden")) return null;
  const classAttr = getJsxAttributeString(el, "className") ?? getJsxAttributeString(el, "class");
  const hit = classAttr === null ? null : firstDialogClassHit(classAttr);
  if (hit === null) return null;
  if (jsxHasDialogRoleSignal(el)) return null;
  return { hit, nameSource: jsxNameSource(el) };
}

function jsxHasFocusTrapTabindex(el: JsxElement): boolean {
  const raw = getJsxAttributeString(el, "tabIndex") ?? getJsxAttributeString(el, "tabindex");
  if (raw === null) return false;
  return raw.trim() === "-1";
}

function hasJsxAccessibleNameRef(el: JsxElement): boolean {
  return hasJsxAttribute(el, "aria-labelledby") || hasJsxAttribute(el, "aria-label");
}

function jsxHasDialogRoleSignal(el: JsxElement): boolean {
  const role = getJsxAttributeString(el, "role");
  if (role !== null && roleMentionsDialog(role)) return true;
  return hasJsxAttribute(el, "aria-modal");
}

function jsxNameSource(el: JsxElement): "aria-labelledby" | "aria-label" {
  return hasJsxAttribute(el, "aria-labelledby") ? "aria-labelledby" : "aria-label";
}

function isComponent(tagName: string): boolean {
  const first = tagName[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function roleMentionsDialog(role: string): boolean {
  for (const tok of role.trim().split(/\s+/u)) {
    const lower = tok.toLowerCase();
    if (lower === "dialog" || lower === "alertdialog") return true;
  }
  return false;
}

/**
 * Returns the first whitespace-separated class token that matches
 * the dialog-shell family, preserving original casing for echo into
 * the violation message. `null` when no token matches.
 */
function firstDialogClassHit(classValue: string): string | null {
  for (const tok of classValue.split(/\s+/u)) {
    if (tok.length === 0) continue;
    if (DIALOG_CLASS_TOKEN_RE.test(tok)) return tok;
  }
  return null;
}

function buildViolation(
  tagName: string,
  loc: Loc,
  classHit: string,
  nameSource: "aria-labelledby" | "aria-label",
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const family = familyFromHit(classHit);
  const suggestedRole = suggestRole(family);
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName} class="${classHit}…"> has dialog signals (tabindex="-1", ${nameSource}, aria-hidden, ${family}-family class) but no role="dialog"/role="alertdialog" and no aria-modal — assistive tech announces it as a generic container instead of a dialog.`,
    suggestion: `Add role="${suggestedRole}" (and aria-modal="true" if this overlay traps focus) to <${tagName}> so the screen reader announces the dialog framing when focus enters the shell. The visible "${family}" class plus the focus-trap tabindex tell sighted users this is a dialog; AT users need the same signal in the accessibility tree.`,
  };
}

function familyFromHit(hit: string): string {
  const match = DIALOG_CLASS_TOKEN_RE.exec(hit);
  return match?.[1]?.toLowerCase() ?? hit.toLowerCase();
}

function suggestRole(family: string): "dialog" | "alertdialog" {
  // `alertdialog` is reserved for confirmations / destructive prompts.
  // The class-token surface alone can't distinguish them, so default to
  // `dialog` and let the agent decide whether the content is alert-shaped.
  // The suggestion text references both options so the agent has the choice.
  void family;
  return "dialog";
}
