/**
 * Rule: aria/expanded-on-disclosure
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 * ARIA authoring practices — disclosure: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags disclosure triggers — a `<button>`, `<a>`, or `role="button"`
 * element that toggles a collapsible region — whose state exposure is
 * incomplete in one of two ways:
 *
 *   1. Missing `aria-expanded`. Without it, assistive technology
 *      cannot programmatically determine or announce whether the
 *      disclosed region is currently open or closed. WCAG 4.1.2
 *      requires that state be programmatically determinable.
 *   2. Present `aria-expanded` but missing `aria-controls` when the
 *      disclosure shape comes from a non-aria-controls signal (e.g.
 *      `data-bs-toggle="dropdown"`, inline classList toggler). The
 *      WAI-ARIA Authoring Practices disclosure pattern specifies
 *      that the trigger should identify the controlled region via
 *      `aria-controls` so assistive tech can announce and navigate
 *      to it; Bootstrap's canonical dropdown pattern ships
 *      `aria-expanded="false"` without `aria-controls`, and the
 *      scanner surfaces that gap honestly rather than silently
 *      passing on `aria-expanded` presence alone.
 *
 * The rule is framework-agnostic: it matches on the *shape* of a
 * disclosure trigger (aria-controls, toggle-style data attributes with
 * disclosure values, inline onclick handlers that toggle a visibility
 * class, or disclosure-pattern class-name tokens like `toggle` /
 * `dropdown-toggle` / `accordion` / `disclosure` / `collapse-toggle` on
 * the trigger itself). Widely-used framework data attributes like
 * `data-bs-toggle="collapse"` / `data-toggle="dropdown"` merely serve
 * as additive evidence hints that the element *is* a disclosure
 * trigger — the rule is not Bootstrap-specific (see CLAUDE.md §14 "no
 * vendor-specific runtime ingest adapters"). Any value from the
 * narrow disclosure set (`collapse`, `dropdown`, `accordion`,
 * `offcanvas`) on a `data-*-toggle` attribute triggers the predicate
 * regardless of prefix.
 *
 * Exclusion list — these widget shapes are NOT disclosure triggers
 * per the WAI-ARIA Authoring Practices, and the rule does not fire on
 * them. Each uses a different ARIA state/property channel that lives
 * (or will live) in its own rule:
 *
 *   - **Tabs** (`data-*-toggle="tab"`, `data-*-toggle="pill"`,
 *     `role="tab"`) — APG §tabs uses `aria-selected` on the active tab,
 *     not `aria-expanded`. Coverage will move to a companion rule
 *     `aria/tab-pattern-roles` (not yet scaffolded; tracked in backlog).
 *   - **Modal / dialog triggers** (`data-*-toggle="modal"`) — APG
 *     §dialog-modal uses `aria-haspopup="dialog"` on the trigger; the
 *     dialog is a separate surface, not a show/hide region of the
 *     trigger's container, so `aria-expanded` does not apply. Coverage
 *     will move to a companion rule `aria/modal-trigger-haspopup` (not
 *     yet scaffolded; tracked in backlog).
 *   - **Popover triggers** (`data-*-toggle="popover"`) — descriptive-
 *     content widget; state exposed via `role="tooltip"` on the popover
 *     body + `aria-describedby` on the trigger. Popover-specific checks
 *     (dismissability, described-by pairing) live in
 *     `src/rules/tooltip/dismissable.ts`.
 *   - **Tooltip triggers** (`data-*-toggle="tooltip"`) — same shape as
 *     popover; `role="tooltip"` + `aria-describedby`, not
 *     `aria-expanded`. Tooltip-specific checks live in
 *     `src/rules/tooltip/dismissable.ts`.
 *
 * Flagging tabs / modals / popovers / tooltips here would emit
 * findings under the wrong WCAG axis and produced high-volume false
 * positives in the field. The companion rules above are tracked
 * separately so the toggle-attribute namespace's other widget kinds
 * get correct findings under the right axes — see CLAUDE.md §14 "no
 * vendor-specific runtime ingest adapters" for the framing.
 *
 * Exemptions:
 *   - `<summary>` inside `<details>`: native disclosure, state is
 *     exposed by the host (`<details open>`), no `aria-expanded` needed.
 *   - Any value on `aria-expanded` (including dynamic expressions and
 *     `"true"` / `"false"`) is acceptable — the rule only flags the
 *     *absence* of the attribute.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  JsxAttributeValue,
  JsxElement,
  TsxModule,
} from "../../types/ast.ts";

/**
 * Values (on `data-*-toggle` / `data-toggle`) that mark the element as
 * a genuine disclosure trigger per the WAI-ARIA Authoring Practices
 * §disclosure pattern (https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/) —
 * i.e. a button whose only job is to toggle the visibility of an
 * adjacent content region whose state must be exposed via
 * `aria-expanded`. Matched case-insensitively and token-exactly — a
 * value like `collapse,show` (multi-token, rare but observed) is split
 * on whitespace/comma.
 *
 * The set is deliberately narrow:
 *
 *   - `collapse` / `dropdown` / `accordion` / `offcanvas` — show/hide a
 *     sibling region; APG-aligned disclosure shape; `aria-expanded` on
 *     the trigger is the correct state channel.
 *
 * Excluded — these widget shapes use a DIFFERENT ARIA attribute and
 * are out of scope for this rule (see header docstring for the full
 * exclusion list and future companion-rule pointers):
 *
 *   - `tab` / `pill` — APG tabs pattern uses `aria-selected` on the
 *     `role="tab"` trigger, not `aria-expanded`. A separate companion
 *     rule (`aria/tab-pattern-roles`, not yet scaffolded) will cover
 *     the role+selected gap.
 *   - `modal` — APG dialog/modal pattern uses `aria-haspopup="dialog"`
 *     on the trigger, not `aria-expanded` (the dialog is not a
 *     show/hide region of the trigger's container; it is a separate
 *     surface). A separate companion rule (`aria/modal-trigger-haspopup`,
 *     not yet scaffolded) will cover that gap.
 *   - `popover` / `tooltip` — both are descriptive-content widgets
 *     whose state is exposed via `role="tooltip"` + `aria-describedby`,
 *     not `aria-expanded`. Tooltip- and popover-specific checks live
 *     in `src/rules/tooltip/dismissable.ts`.
 */
const DISCLOSURE_TOGGLE_VALUES: ReadonlySet<string> = new Set([
  "collapse",
  "dropdown",
  "accordion",
  "offcanvas",
]);

/**
 * Class-token substrings that, when mentioned inside an inline
 * `onclick` / `onClick` body alongside a `classList.*` call, indicate
 * the handler is toggling a visibility state — evidence the element
 * is a disclosure trigger. Whitespace-tolerant substring match on the
 * raw handler source. The list is intentionally small: only the class
 * tokens that are load-bearing for disclosure state across common
 * CSS/JS idioms.
 */
const VISIBILITY_CLASS_TOKENS: readonly string[] = [
  "collapse",
  "show",
  "open",
  "active",
  "expanded",
  "is-open",
  "is-expanded",
  "hidden",
];

/**
 * Class-name tokens on the trigger element itself that mark it as a
 * disclosure-shaped widget even when there is no `aria-controls`,
 * `data-*-toggle`, or inline classList handler to detect. These are the
 * common naming conventions widely used by frameworks and hand-rolled
 * disclosure patterns to identify a control that toggles a collapsible
 * region:
 *
 *   - `toggle` — generic toggle convention (`<button class="toggle">`)
 *   - `dropdown-toggle` — Bootstrap, generic dropdown trigger
 *   - `collapse-toggle` — common collapse trigger naming
 *   - `accordion` — generic accordion-header naming
 *   - `disclosure` — APG-aligned naming
 *
 * Matched as an EXACT whitespace-split token (case-insensitive). A
 * class like `toggle-button-group` does NOT match `toggle`. The
 * conservative bias is intentional: the predicate already fires on
 * stronger signals (data-*-toggle, aria-controls, onclick classList),
 * so the class-only branch only earns its keep when the naming is a
 * recognized disclosure idiom — not on any element that happens to
 * carry a class containing "toggle".
 *
 * Per CLAUDE.md §14 we detect the shape, not the framework — the
 * tokens here are conventions independent of any one library.
 */
const DISCLOSURE_CLASS_TOKENS: readonly string[] = [
  "toggle",
  "dropdown-toggle",
  "collapse-toggle",
  "accordion",
  "disclosure",
];

/** classList method names used to toggle visibility classes. */
const CLASSLIST_METHODS: readonly string[] = ["toggle", "add", "remove"];

/**
 * Class tokens screen-reader conventions use to mark a visually-hidden
 * textual equivalent. When a flagged disclosure trigger carries a
 * direct child with one of these tokens (e.g. Bootstrap's collapse-
 * button ships `<span class="sr-only">Toggle navigation</span>` inside
 * the trigger), that child is almost certainly the accessible name for
 * the control. The rule still fires — the aria-expanded / aria-controls
 * gap is real — but we enrich the reason so the agent knows the label
 * is already in the tree and can verify the accessible name is
 * complete rather than re-invent it. Per the AI-first consumer model
 * (docs/kb/architecture/ai-first-consumer.md — "Enrich reason with
 * dismissal signal; keep candidate in the primary list"), this is
 * reason-text enrichment only, never suppression.
 */
const VISUALLY_HIDDEN_CLASS_TOKENS: readonly string[] = [
  "sr-only",
  "visually-hidden",
  "visuallyhidden",
  "screen-reader-only",
  "screen-reader-text",
  "screenreader-text",
  "u-sr-only",
  "u-visually-hidden",
  "sr-only-focusable",
  "visually-hidden-focusable",
];

/**
 * Which predicate branch matched. Feeds the fix suggestion so the
 * agent can see *why* the rule fired without having to rediscover
 * the evidence from the source.
 */
type PredicateBranch =
  | { readonly kind: "aria-controls"; readonly targetId: string }
  | { readonly kind: "data-toggle"; readonly attrName: string; readonly value: string }
  | { readonly kind: "onclick-classlist"; readonly matchedClass: string }
  | { readonly kind: "disclosure-class"; readonly matchedToken: string };

/**
 * Which gap the rule is flagging. `missing-expanded` is the original
 * finding (the disclosure trigger never surfaces its open/closed
 * state at all). `missing-controls` covers the Bootstrap-canonical
 * case where the trigger has `aria-expanded` but never identifies
 * the controlled region — a disclosure predicate fired from a
 * non-`aria-controls` branch (data-*-toggle or onclick classList),
 * so the element proves it toggles something but doesn't name the
 * target.
 */
type FindingKind = "missing-expanded" | "missing-controls";

/**
 * Evidence that the flagged element already carries a label channel
 * (inline `aria-label`, or a visually-hidden text child). Used only
 * for reason-text enrichment: the rule's predicate is unchanged and
 * the finding still surfaces in the primary list — the enrichment
 * tells the agent "if the hidden child is the disclosure label, verify
 * the accessible name is complete" so dismissal is faster. See
 * docs/kb/architecture/ai-first-consumer.md — reason-text enrichment,
 * never suppression, never bucketing.
 */
interface LabelEvidence {
  readonly ariaLabel: boolean;
  readonly visuallyHiddenClassToken: string | null;
}

const NO_LABEL_EVIDENCE: LabelEvidence = { ariaLabel: false, visuallyHiddenClassToken: null };

export const rule = defineRule({
  id: "aria/expanded-on-disclosure",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  // V1-SUGGEST-FIX-MECHANICAL-LANE-EMIT-EDIT: re-tagged `mechanical` →
  // `verify-in-source`. Neither finding lane is a deterministic single
  // attribute insertion the scanner can ship as `fixPaths.primary.edit`:
  //
  //   - `missing-expanded`: adding `aria-expanded` is part of the fix,
  //     but the value the scanner could emit (`"false"` as the safe
  //     initial collapsed state) is opinionated — many disclosure
  //     triggers render with the panel already expanded, in which case
  //     `"false"` is wrong on first paint. Worse, the WCAG 4.1.2
  //     conformance gap isn't fully closed by attribute insertion alone:
  //     the runtime that toggles `"true"` ↔ `"false"` in lock-step with
  //     the panel's open/closed state has to be wired in source. The
  //     fix needs agent judgment on the host runtime, not a single
  //     mechanical edit.
  //   - `missing-controls`: the `aria-controls="<id>"` value names a
  //     specific id on the controlled region, which the scanner cannot
  //     determine from the trigger alone — the region may not yet exist,
  //     may need an id added, or may be selected at runtime by sibling
  //     class. Never a deterministic source transform.
  //
  // Re-tagging keeps `plan.fixesByClass.mechanical` honest about which
  // findings can be apply-now edits (per the doctrine that composite
  // headline counts must match what `suggest_fix` can actually produce
  // — docs/kb/architecture/ai-first-consumer.md). The rule still carries
  // `meta.mechanicalInPrinciple: true` on `kind: "guidance"` responses
  // because `verify-in-source` is in MECHANICAL_IN_PRINCIPLE_LANES — the
  // family supports a source-edit path even though this lane doesn't
  // ship one. Mirrors the alt-text-missing precedent in commit
  // bd2a67c6.
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Disclosure triggers (buttons / links / role=button that toggle a collapsible region) must carry aria-expanded so assistive tech can announce the open/closed state.",
    rationale:
      "WCAG 4.1.2 requires that a component's state be programmatically determinable. A disclosure trigger with no aria-expanded is announced without its open/closed state — the user can operate the control but cannot tell whether the region they just toggled is now visible or hidden. Real-world evidence: widely-used component libraries ship disclosure triggers (Bootstrap's `data-bs-toggle=\"collapse\"` links, dropdown buttons, accordion headers) without aria-expanded; the static scanner catches these because the shape of a disclosure trigger is detectable even though runtime behavior isn't.",
    goodExample:
      '<button aria-controls="panel-1" aria-expanded="false">Details</button>\n<div id="panel-1" hidden>…</div>',
    badExample:
      '<button aria-controls="panel-1">Details</button>\n<div id="panel-1" hidden>…</div>',
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-expanded",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    if (!isHtmlInteractive(el)) continue;
    if (isSummaryInsideDetails(el)) continue;
    const branch = matchHtmlPredicate(el, doc);
    if (!branch) continue;
    const finding = classifyFinding(branch, hasHtmlAttribute(el, "aria-expanded"));
    if (!finding) continue;
    const labelEvidence = collectHtmlLabelEvidence(el);
    emit({
      severity: "error",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: buildMessage(el.tagName, branch, finding, labelEvidence),
      suggestion: buildSuggestion(el.tagName, branch, finding, labelEvidence),
    });
  }
}

function isHtmlInteractive(el: HtmlElement): boolean {
  const tag = el.tagName.toLowerCase();
  if (tag === "button") return true;
  if (tag === "a") return true;
  const role = getHtmlAttribute(el, "role");
  if (role && role.toLowerCase() === "button") return true;
  return false;
}

/**
 * `<summary>` inside a `<details>` is a native disclosure control. The
 * open/closed state is exposed by the host element (`<details open>`),
 * not by `aria-expanded` on the `<summary>`. We filter `<summary>` out
 * at the native-check level above (interactive check), but also guard
 * here for defensive belt-and-suspenders — keep this predicate honest
 * even if the interactive set grows later.
 */
function isSummaryInsideDetails(el: HtmlElement): boolean {
  return el.tagName.toLowerCase() === "summary";
}

function matchHtmlPredicate(el: HtmlElement, doc: HtmlDocument): PredicateBranch | null {
  const ariaControls = getHtmlAttribute(el, "aria-controls");
  if (ariaControls && ariaControls.trim().length > 0) {
    if (htmlIdExistsInDocument(doc, ariaControls.trim())) {
      return { kind: "aria-controls", targetId: ariaControls.trim() };
    }
  }
  const toggleMatch = findHtmlToggleAttribute(el);
  if (toggleMatch) return toggleMatch;
  const onclickMatch = findHtmlOnclickClasslist(el);
  if (onclickMatch) return onclickMatch;
  const classMatch = findDisclosureClassToken(getHtmlAttribute(el, "class"));
  if (classMatch) return { kind: "disclosure-class", matchedToken: classMatch };
  return null;
}

function htmlIdExistsInDocument(doc: HtmlDocument, id: string): boolean {
  const target = id.split(/\s+/).filter((s) => s.length > 0)[0] ?? "";
  if (target.length === 0) return false;
  for (const el of walkHtmlElements(doc)) {
    if (getHtmlAttribute(el, "id") === target) return true;
  }
  return false;
}

function findHtmlToggleAttribute(el: HtmlElement): PredicateBranch | null {
  for (const attr of el.attributes) {
    const name = attr.name.toLowerCase();
    if (!isToggleAttributeName(name)) continue;
    const raw = attr.value;
    if (raw === null || raw.trim().length === 0) continue;
    for (const token of raw.split(/[\s,]+/)) {
      const lowered = token.trim().toLowerCase();
      if (DISCLOSURE_TOGGLE_VALUES.has(lowered)) {
        return { kind: "data-toggle", attrName: attr.name, value: lowered };
      }
    }
  }
  return null;
}

/**
 * Accepts `data-toggle` and any `data-<prefix>-toggle` form. Keeping
 * the check suffix-based (not framework-prefixed) means the rule
 * fires on `data-bs-toggle="collapse"` (Bootstrap 5), `data-toggle="collapse"`
 * (Bootstrap 4 / generic), `data-ui-toggle="dropdown"` (any custom
 * library) identically. See CLAUDE.md §14 — we detect the shape, not
 * the framework.
 */
function isToggleAttributeName(lowered: string): boolean {
  if (lowered === "data-toggle") return true;
  if (!lowered.startsWith("data-")) return false;
  return lowered.endsWith("-toggle");
}

function findHtmlOnclickClasslist(el: HtmlElement): PredicateBranch | null {
  const onclick = getHtmlAttribute(el, "onclick");
  if (!onclick) return null;
  return inspectHandlerBody(onclick);
}

/**
 * Matches a handler body that does a `classList.toggle|add|remove` of
 * a known visibility class. Returns the first visibility-class token
 * we find so the fix suggestion can cite concrete evidence. The
 * probe is text-level by design: we're shaping a fix, not proving
 * intent, and an agent reading the handler decides from there.
 */
/**
 * Returns the first disclosure-pattern class token present on the
 * element (whitespace-split, case-insensitive, exact-token match).
 * Used as the last-resort predicate branch: when an interactive
 * element has none of the stronger disclosure signals (aria-controls,
 * data-*-toggle, onclick classList) but its own class list contains
 * a recognized disclosure-naming idiom, treat it as a disclosure
 * trigger so the missing-aria-expanded gap surfaces.
 *
 * Token-exact match is intentional: a class like `toggle-button-group`
 * does NOT match the `toggle` token. This bias keeps the branch
 * conservative — it earns its keep on common naming conventions
 * (`<button class="toggle">`, `<button class="dropdown-toggle">`)
 * without firing on every element whose class string contains
 * "toggle" as a substring.
 */
function findDisclosureClassToken(classValue: string | null): string | null {
  if (classValue === null) return null;
  for (const raw of classValue.split(/\s+/)) {
    const token = raw.trim().toLowerCase();
    if (!token) continue;
    if (DISCLOSURE_CLASS_TOKENS.includes(token)) return token;
  }
  return null;
}

function inspectHandlerBody(body: string): PredicateBranch | null {
  const lowered = body.toLowerCase();
  if (!lowered.includes("classlist")) return null;
  let methodSeen = false;
  for (const method of CLASSLIST_METHODS) {
    if (new RegExp(`classlist\\s*\\.\\s*${method}\\s*\\(`, "i").test(body)) {
      methodSeen = true;
      break;
    }
  }
  if (!methodSeen) return null;
  for (const token of VISIBILITY_CLASS_TOKENS) {
    const pattern = new RegExp(`['"\`]${token}['"\`]`, "i");
    if (pattern.test(body)) {
      return { kind: "onclick-classlist", matchedClass: token };
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  const elements = [...walkJsxElements(module)];
  const idIndex = collectJsxIds(elements);
  for (const el of elements) {
    if (isJsxPascalCase(el.tagName)) continue;
    if (!isJsxInteractive(el)) continue;
    const branch = matchJsxPredicate(el, idIndex);
    if (!branch) continue;
    const finding = classifyFinding(branch, hasJsxAttribute(el, "aria-expanded"));
    if (!finding) continue;
    const labelEvidence = collectJsxLabelEvidence(el);
    emit({
      severity: "error",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: buildMessage(el.tagName, branch, finding, labelEvidence),
      suggestion: buildSuggestion(el.tagName, branch, finding, labelEvidence),
    });
  }
}

function collectJsxIds(elements: readonly JsxElement[]): ReadonlySet<string> {
  const out = new Set<string>();
  for (const el of elements) {
    const id = getJsxAttributeString(el, "id");
    if (id && id.length > 0) out.add(id);
  }
  return out;
}

function isJsxInteractive(el: JsxElement): boolean {
  const tag = el.tagName;
  if (tag === "button") return true;
  if (tag === "a") return true;
  const role = getJsxAttributeString(el, "role");
  if (role === "button") return true;
  return false;
}

function isJsxPascalCase(tag: string): boolean {
  const first = tag[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

function matchJsxPredicate(el: JsxElement, idIndex: ReadonlySet<string>): PredicateBranch | null {
  const ariaControls = getJsxAttributeString(el, "aria-controls");
  if (ariaControls && ariaControls.trim().length > 0) {
    const target = ariaControls.trim().split(/\s+/)[0] ?? "";
    if (target.length > 0 && idIndex.has(target)) {
      return { kind: "aria-controls", targetId: target };
    }
  }
  const toggleMatch = findJsxToggleAttribute(el);
  if (toggleMatch) return toggleMatch;
  const onclickMatch = findJsxOnclickClasslist(el);
  if (onclickMatch) return onclickMatch;
  const classValue = getJsxAttributeString(el, "className") ?? getJsxAttributeString(el, "class");
  const classMatch = findDisclosureClassToken(classValue);
  if (classMatch) return { kind: "disclosure-class", matchedToken: classMatch };
  return null;
}

function findJsxToggleAttribute(el: JsxElement): PredicateBranch | null {
  for (const attr of el.attributes) {
    const lowered = attr.name.toLowerCase();
    if (!isToggleAttributeName(lowered)) continue;
    if (!attr.value || attr.value.kind !== "StringLiteral") continue;
    const raw = attr.value.value;
    for (const token of raw.split(/[\s,]+/)) {
      const loweredToken = token.trim().toLowerCase();
      if (DISCLOSURE_TOGGLE_VALUES.has(loweredToken)) {
        return { kind: "data-toggle", attrName: attr.name, value: loweredToken };
      }
    }
  }
  return null;
}

function findJsxOnclickClasslist(el: JsxElement): PredicateBranch | null {
  const attr = getJsxAttribute(el, "onClick") ?? getJsxAttribute(el, "onclick");
  if (!attr?.value) return null;
  const raw = attr.value.kind === "Expression" ? attr.value.raw : attr.value.value;
  return inspectHandlerBody(raw);
}

// ---------------------------------------------------------------------------
// Shared message / suggestion builders
// ---------------------------------------------------------------------------

/**
 * Map (branch, aria-expanded-present?) → which finding (if any) to
 * emit. The logic is deliberately narrow:
 *
 *   - No aria-expanded and any disclosure branch → missing-expanded.
 *   - aria-expanded present and branch is `aria-controls` → nothing
 *     (both attributes are there; the pattern is complete).
 *   - aria-expanded present and branch is a non-`aria-controls`
 *     signal (data-*-toggle, onclick classList) → missing-controls.
 *     The element proves it toggles something but doesn't name the
 *     target — the WAI-ARIA Authoring Practices disclosure pattern
 *     asks the trigger to identify the controlled region.
 */
function classifyFinding(branch: PredicateBranch, hasAriaExpanded: boolean): FindingKind | null {
  if (!hasAriaExpanded) return "missing-expanded";
  if (branch.kind === "aria-controls") return null;
  return "missing-controls";
}

function buildMessage(
  tagName: string,
  branch: PredicateBranch,
  finding: FindingKind,
  labelEvidence: LabelEvidence,
): string {
  const evidence = describeBranch(branch);
  const labelNote = formatLabelNote(labelEvidence);
  if (finding === "missing-controls") {
    return (
      `<${tagName}> has aria-expanded but is missing aria-controls — AT cannot ` +
      `identify which region the trigger controls. (${evidence})${labelNote}`
    );
  }
  return (
    `<${tagName}> looks like a disclosure trigger but has no aria-expanded — AT ` +
    `cannot announce whether the region is open or closed. (${evidence})${labelNote}`
  );
}

function buildSuggestion(
  tagName: string,
  branch: PredicateBranch,
  finding: FindingKind,
  labelEvidence: LabelEvidence,
): string {
  const evidence = describeBranch(branch);
  const labelNote = formatLabelNote(labelEvidence);
  if (finding === "missing-controls") {
    return (
      `Add aria-controls="<id>" to the <${tagName}>, where <id> is the id of the ` +
      `region the trigger shows/hides. The region element will need that id as ` +
      `well. Predicate match: ${evidence}. If the controlled region cannot be ` +
      `reached by id (e.g. it is rendered as a sibling selected by runtime ` +
      `convention) and the trigger is otherwise WCAG 4.1.2 compliant, suppress ` +
      `with a source-level pragma (e.g. <!-- ra11y-disable aria/expanded-on-disclosure -->) ` +
      `so the next scan dismisses it deterministically.${labelNote}`
    );
  }
  return (
    `Add aria-expanded="false" to the <${tagName}> as the initial collapsed state, ` +
    `then toggle it to "true"/"false" in the same runtime that shows/hides the ` +
    `disclosed region. Predicate match: ${evidence}. If this control is not a ` +
    `disclosure trigger, the detection is wrong — suppress with a source-level ` +
    `pragma (e.g. <!-- ra11y-disable aria/expanded-on-disclosure -->) so the ` +
    `next scan dismisses it deterministically.${labelNote}`
  );
}

function describeBranch(branch: PredicateBranch): string {
  if (branch.kind === "aria-controls") {
    return `aria-controls points at an element with id="${branch.targetId}" in the same document`;
  }
  if (branch.kind === "data-toggle") {
    return `${branch.attrName}="${branch.value}" is a disclosure-style toggle value`;
  }
  if (branch.kind === "disclosure-class") {
    return `class includes the disclosure-pattern token "${branch.matchedToken}"`;
  }
  return `inline onclick toggles a visibility class "${branch.matchedClass}" via classList`;
}

// ---------------------------------------------------------------------------
// Label evidence (reason-text enrichment)
// ---------------------------------------------------------------------------

/**
 * Scans a flagged HTML trigger for an inline `aria-label` or a direct
 * element child carrying a visually-hidden class token. Direct-child
 * only: the Bootstrap collapse-button canonical pattern puts the
 * hidden label as an immediate `<span class="sr-only">` child of the
 * `<button>`, and we do not want to mis-classify a deep descendant
 * `.sr-only` (e.g. inside a nested icon's tooltip) as the control's
 * own label. If the label genuinely lives deeper, the agent reads the
 * file and verifies — per doctrine, we point and the agent investigates.
 */
function collectHtmlLabelEvidence(el: HtmlElement): LabelEvidence {
  const ariaLabelValue = getHtmlAttribute(el, "aria-label");
  const ariaLabel = ariaLabelValue !== null && ariaLabelValue.trim().length > 0;
  let visuallyHiddenClassToken: string | null = null;
  for (const child of el.children) {
    if (child.kind !== "HtmlElement") continue;
    const classValue = getHtmlAttribute(child, "class");
    const token = matchVisuallyHiddenClassToken(classValue);
    if (token) {
      visuallyHiddenClassToken = token;
      break;
    }
  }
  if (!(ariaLabel || visuallyHiddenClassToken)) return NO_LABEL_EVIDENCE;
  return { ariaLabel, visuallyHiddenClassToken };
}

/**
 * JSX counterpart of {@link collectHtmlLabelEvidence}. Only literal
 * `className` / `class` string values and literal `aria-label` values
 * are recognized; dynamic expression bindings (`className={cx(...)}`,
 * `aria-label={t("toggle")}`) are deliberately not matched here —
 * doing more than literals duplicates the capability the consuming
 * agent already has (it can read the file and see the binding). See
 * docs/kb/architecture/ai-first-consumer.md — "Don't duplicate
 * capability the agent already has".
 */
function collectJsxLabelEvidence(el: JsxElement): LabelEvidence {
  const ariaLabelValue = jsxLiteralAttributeString(el, "aria-label");
  const ariaLabel = ariaLabelValue !== null && ariaLabelValue.trim().length > 0;
  let visuallyHiddenClassToken: string | null = null;
  for (const child of el.children) {
    if (child.kind !== "JsxElement") continue;
    const classValue =
      jsxLiteralAttributeString(child, "className") ?? jsxLiteralAttributeString(child, "class");
    const token = matchVisuallyHiddenClassToken(classValue);
    if (token) {
      visuallyHiddenClassToken = token;
      break;
    }
  }
  if (!(ariaLabel || visuallyHiddenClassToken)) return NO_LABEL_EVIDENCE;
  return { ariaLabel, visuallyHiddenClassToken };
}

function matchVisuallyHiddenClassToken(classValue: string | null): string | null {
  if (classValue === null) return null;
  for (const token of classValue.toLowerCase().split(/\s+/)) {
    if (!token) continue;
    if (VISUALLY_HIDDEN_CLASS_TOKENS.includes(token)) return token;
  }
  return null;
}

/**
 * Resolves a JSX attribute to its literal string value. Matches
 * `attr="literal"`, `attr='literal'`, and `attr={"literal"}` /
 * `attr={'literal'}` — the same surface the sibling sr-only review
 * finders accept. Non-literal expressions return null.
 */
function jsxLiteralAttributeString(el: JsxElement, name: string): string | null {
  const attr = getJsxAttribute(el, name);
  if (!attr?.value) return null;
  return jsxLiteralValue(attr.value);
}

function jsxLiteralValue(value: JsxAttributeValue): string | null {
  if (value.kind === "StringLiteral") return value.value;
  const trimmed = value.raw.trim();
  if (!(trimmed.startsWith("{") && trimmed.endsWith("}"))) return null;
  const inner = trimmed.slice(1, -1).trim();
  if (
    (inner.startsWith('"') && inner.endsWith('"')) ||
    (inner.startsWith("'") && inner.endsWith("'"))
  ) {
    return inner.slice(1, -1);
  }
  return null;
}

/**
 * Formats the label-evidence suffix appended to the rule's message
 * and suggestion. Returns the empty string when no evidence is
 * present, so the shape stays terse on the no-label majority of
 * disclosure findings. When evidence IS present, the note frames it
 * as a verification prompt — the rule's predicate still fires (the
 * aria-expanded / aria-controls gap is real) but the agent should
 * check that the hidden child IS the intended disclosure label and
 * that the accessible name covers the control's purpose.
 */
function formatLabelNote(evidence: LabelEvidence): string {
  const parts: string[] = [];
  if (evidence.visuallyHiddenClassToken) {
    parts.push(`a visually-hidden text child (.${evidence.visuallyHiddenClassToken})`);
  }
  if (evidence.ariaLabel) parts.push("an inline aria-label");
  if (parts.length === 0) return "";
  const signal = parts.join(" and ");
  return (
    ` (note: element has ${signal} — if that is the disclosure label, ` +
    `verify the accessible name is complete and, if so, the state attribute ` +
    `is all that is missing.)`
  );
}
