/**
 * Rule: aria/expanded-on-disclosure
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 * ARIA authoring practices — disclosure: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags disclosure triggers — a `<button>`, `<a>`, or `role="button"`
 * element that toggles a collapsible region — whose state exposure is
 * incomplete in one of two ways:
 *
 *   1. Missing `aria-expanded`. Without it, assistive technology
 *      cannot programmatically determine or announce whether the
 *      disclosed region is currently open or closed. WCAG 4.1.2
 *      requires that state be programmatically determinable.
 *   2. Present `aria-expanded` but missing `aria-controls` when the
 *      disclosure shape comes from a non-aria-controls signal (e.g.
 *      `data-bs-toggle="dropdown"`, inline classList toggler). The
 *      WAI-ARIA Authoring Practices disclosure pattern specifies
 *      that the trigger should identify the controlled region via
 *      `aria-controls` so assistive tech can announce and navigate
 *      to it; Bootstrap's canonical dropdown pattern ships
 *      `aria-expanded="false"` without `aria-controls`, and the
 *      scanner surfaces that gap honestly rather than silently
 *      passing on `aria-expanded` presence alone.
 *
 * The rule is framework-agnostic: it matches on the *shape* of a
 * disclosure trigger (aria-controls, toggle-style data attributes with
 * collapse/disclosure values, or inline onclick handlers that toggle a
 * visibility class). Widely-used framework data attributes like
 * `data-bs-toggle="collapse"` / `data-toggle="dropdown"` merely serve as
 * additive evidence hints that the element *is* a disclosure trigger —
 * the rule is not Bootstrap-specific (see CLAUDE.md §14 "no
 * vendor-specific runtime ingest adapters"). Any value from the
 * disclosure-ish set (`collapse`, `dropdown`, `accordion`, `offcanvas`,
 * `modal`, `tab`, `pill`, `popover`, `tooltip`) on a `data-*-toggle`
 * attribute triggers the predicate regardless of prefix.
 *
 * Exemptions:
 *   - `<summary>` inside `<details>`: native disclosure, state is
 *     exposed by the host (`<details open>`), no `aria-expanded` needed.
 *   - Any value on `aria-expanded` (including dynamic expressions and
 *     `"true"` / `"false"`) is acceptable — the rule only flags the
 *     *absence* of the attribute.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

/**
 * Values (on `data-*-toggle` / `data-toggle`) that mark the element as
 * a disclosure trigger whose collapsed/expanded state must be exposed
 * via `aria-expanded`. Matched case-insensitively and token-exactly —
 * a value like `collapse,show` (multi-token, rare but observed) is
 * split on whitespace/comma.
 *
 * `modal`, `popover`, and `tooltip` are included: per the ARIA
 * authoring practices they all have open/closed state that a trigger
 * button should announce via `aria-expanded`. `tab` / `pill` cover
 * tab-panel disclosure triggers.
 */
const DISCLOSURE_TOGGLE_VALUES: ReadonlySet<string> = new Set([
  "collapse",
  "dropdown",
  "accordion",
  "offcanvas",
  "modal",
  "tab",
  "pill",
  "popover",
  "tooltip",
]);

/**
 * Class-token substrings that, when mentioned inside an inline
 * `onclick` / `onClick` body alongside a `classList.*` call, indicate
 * the handler is toggling a visibility state — evidence the element
 * is a disclosure trigger. Whitespace-tolerant substring match on the
 * raw handler source. The list is intentionally small: only the class
 * tokens that are load-bearing for disclosure state across common
 * CSS/JS idioms.
 */
const VISIBILITY_CLASS_TOKENS: readonly string[] = [
  "collapse",
  "show",
  "open",
  "active",
  "expanded",
  "is-open",
  "is-expanded",
  "hidden",
];

/** classList method names used to toggle visibility classes. */
const CLASSLIST_METHODS: readonly string[] = ["toggle", "add", "remove"];

/**
 * Which predicate branch matched. Feeds the fix suggestion so the
 * agent can see *why* the rule fired without having to rediscover
 * the evidence from the source.
 */
type PredicateBranch =
  | { readonly kind: "aria-controls"; readonly targetId: string }
  | { readonly kind: "data-toggle"; readonly attrName: string; readonly value: string }
  | { readonly kind: "onclick-classlist"; readonly matchedClass: string };

/**
 * Which gap the rule is flagging. `missing-expanded` is the original
 * finding (the disclosure trigger never surfaces its open/closed
 * state at all). `missing-controls` covers the Bootstrap-canonical
 * case where the trigger has `aria-expanded` but never identifies
 * the controlled region — a disclosure predicate fired from a
 * non-`aria-controls` branch (data-*-toggle or onclick classList),
 * so the element proves it toggles something but doesn't name the
 * target.
 */
type FindingKind = "missing-expanded" | "missing-controls";

export const rule = defineRule({
  id: "aria/expanded-on-disclosure",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  fixClass: "mechanical",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Disclosure triggers (buttons / links / role=button that toggle a collapsible region) must carry aria-expanded so assistive tech can announce the open/closed state.",
    rationale:
      "WCAG 4.1.2 requires that a component's state be programmatically determinable. A disclosure trigger with no aria-expanded is announced without its open/closed state — the user can operate the control but cannot tell whether the region they just toggled is now visible or hidden. Real-world evidence: widely-used component libraries ship disclosure triggers (Bootstrap's `data-bs-toggle=\"collapse\"` links, dropdown buttons, accordion headers) without aria-expanded; the static scanner catches these because the shape of a disclosure trigger is detectable even though runtime behavior isn't.",
    goodExample:
      '<button aria-controls="panel-1" aria-expanded="false">Details</button>\n<div id="panel-1" hidden>…</div>',
    badExample:
      '<button aria-controls="panel-1">Details</button>\n<div id="panel-1" hidden>…</div>',
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-expanded",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    if (!isHtmlInteractive(el)) continue;
    if (isSummaryInsideDetails(el)) continue;
    const branch = matchHtmlPredicate(el, doc);
    if (!branch) continue;
    const finding = classifyFinding(branch, hasHtmlAttribute(el, "aria-expanded"));
    if (!finding) continue;
    emit({
      severity: "error",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: buildMessage(el.tagName, branch, finding),
      suggestion: buildSuggestion(el.tagName, branch, finding),
    });
  }
}

function isHtmlInteractive(el: HtmlElement): boolean {
  const tag = el.tagName.toLowerCase();
  if (tag === "button") return true;
  if (tag === "a") return true;
  const role = getHtmlAttribute(el, "role");
  if (role && role.toLowerCase() === "button") return true;
  return false;
}

/**
 * `<summary>` inside a `<details>` is a native disclosure control. The
 * open/closed state is exposed by the host element (`<details open>`),
 * not by `aria-expanded` on the `<summary>`. We filter `<summary>` out
 * at the native-check level above (interactive check), but also guard
 * here for defensive belt-and-suspenders — keep this predicate honest
 * even if the interactive set grows later.
 */
function isSummaryInsideDetails(el: HtmlElement): boolean {
  return el.tagName.toLowerCase() === "summary";
}

function matchHtmlPredicate(el: HtmlElement, doc: HtmlDocument): PredicateBranch | null {
  const ariaControls = getHtmlAttribute(el, "aria-controls");
  if (ariaControls && ariaControls.trim().length > 0) {
    if (htmlIdExistsInDocument(doc, ariaControls.trim())) {
      return { kind: "aria-controls", targetId: ariaControls.trim() };
    }
  }
  const toggleMatch = findHtmlToggleAttribute(el);
  if (toggleMatch) return toggleMatch;
  const onclickMatch = findHtmlOnclickClasslist(el);
  if (onclickMatch) return onclickMatch;
  return null;
}

function htmlIdExistsInDocument(doc: HtmlDocument, id: string): boolean {
  const target = id.split(/\s+/).filter((s) => s.length > 0)[0] ?? "";
  if (target.length === 0) return false;
  for (const el of walkHtmlElements(doc)) {
    if (getHtmlAttribute(el, "id") === target) return true;
  }
  return false;
}

function findHtmlToggleAttribute(el: HtmlElement): PredicateBranch | null {
  for (const attr of el.attributes) {
    const name = attr.name.toLowerCase();
    if (!isToggleAttributeName(name)) continue;
    const raw = attr.value;
    if (raw === null || raw.trim().length === 0) continue;
    for (const token of raw.split(/[\s,]+/)) {
      const lowered = token.trim().toLowerCase();
      if (DISCLOSURE_TOGGLE_VALUES.has(lowered)) {
        return { kind: "data-toggle", attrName: attr.name, value: lowered };
      }
    }
  }
  return null;
}

/**
 * Accepts `data-toggle` and any `data-<prefix>-toggle` form. Keeping
 * the check suffix-based (not framework-prefixed) means the rule
 * fires on `data-bs-toggle="collapse"` (Bootstrap 5), `data-toggle="collapse"`
 * (Bootstrap 4 / generic), `data-ui-toggle="dropdown"` (any custom
 * library) identically. See CLAUDE.md §14 — we detect the shape, not
 * the framework.
 */
function isToggleAttributeName(lowered: string): boolean {
  if (lowered === "data-toggle") return true;
  if (!lowered.startsWith("data-")) return false;
  return lowered.endsWith("-toggle");
}

function findHtmlOnclickClasslist(el: HtmlElement): PredicateBranch | null {
  const onclick = getHtmlAttribute(el, "onclick");
  if (!onclick) return null;
  return inspectHandlerBody(onclick);
}

/**
 * Matches a handler body that does a `classList.toggle|add|remove` of
 * a known visibility class. Returns the first visibility-class token
 * we find so the fix suggestion can cite concrete evidence. The
 * probe is text-level by design: we're shaping a fix, not proving
 * intent, and an agent reading the handler decides from there.
 */
function inspectHandlerBody(body: string): PredicateBranch | null {
  const lowered = body.toLowerCase();
  if (!lowered.includes("classlist")) return null;
  let methodSeen = false;
  for (const method of CLASSLIST_METHODS) {
    if (new RegExp(`classlist\\s*\\.\\s*${method}\\s*\\(`, "i").test(body)) {
      methodSeen = true;
      break;
    }
  }
  if (!methodSeen) return null;
  for (const token of VISIBILITY_CLASS_TOKENS) {
    const pattern = new RegExp(`['"\`]${token}['"\`]`, "i");
    if (pattern.test(body)) {
      return { kind: "onclick-classlist", matchedClass: token };
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  const elements = [...walkJsxElements(module)];
  const idIndex = collectJsxIds(elements);
  for (const el of elements) {
    if (isJsxPascalCase(el.tagName)) continue;
    if (!isJsxInteractive(el)) continue;
    const branch = matchJsxPredicate(el, idIndex);
    if (!branch) continue;
    const finding = classifyFinding(branch, hasJsxAttribute(el, "aria-expanded"));
    if (!finding) continue;
    emit({
      severity: "error",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: buildMessage(el.tagName, branch, finding),
      suggestion: buildSuggestion(el.tagName, branch, finding),
    });
  }
}

function collectJsxIds(elements: readonly JsxElement[]): ReadonlySet<string> {
  const out = new Set<string>();
  for (const el of elements) {
    const id = getJsxAttributeString(el, "id");
    if (id && id.length > 0) out.add(id);
  }
  return out;
}

function isJsxInteractive(el: JsxElement): boolean {
  const tag = el.tagName;
  if (tag === "button") return true;
  if (tag === "a") return true;
  const role = getJsxAttributeString(el, "role");
  if (role === "button") return true;
  return false;
}

function isJsxPascalCase(tag: string): boolean {
  const first = tag[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

function matchJsxPredicate(el: JsxElement, idIndex: ReadonlySet<string>): PredicateBranch | null {
  const ariaControls = getJsxAttributeString(el, "aria-controls");
  if (ariaControls && ariaControls.trim().length > 0) {
    const target = ariaControls.trim().split(/\s+/)[0] ?? "";
    if (target.length > 0 && idIndex.has(target)) {
      return { kind: "aria-controls", targetId: target };
    }
  }
  const toggleMatch = findJsxToggleAttribute(el);
  if (toggleMatch) return toggleMatch;
  const onclickMatch = findJsxOnclickClasslist(el);
  if (onclickMatch) return onclickMatch;
  return null;
}

function findJsxToggleAttribute(el: JsxElement): PredicateBranch | null {
  for (const attr of el.attributes) {
    const lowered = attr.name.toLowerCase();
    if (!isToggleAttributeName(lowered)) continue;
    if (!attr.value || attr.value.kind !== "StringLiteral") continue;
    const raw = attr.value.value;
    for (const token of raw.split(/[\s,]+/)) {
      const loweredToken = token.trim().toLowerCase();
      if (DISCLOSURE_TOGGLE_VALUES.has(loweredToken)) {
        return { kind: "data-toggle", attrName: attr.name, value: loweredToken };
      }
    }
  }
  return null;
}

function findJsxOnclickClasslist(el: JsxElement): PredicateBranch | null {
  const attr = getJsxAttribute(el, "onClick") ?? getJsxAttribute(el, "onclick");
  if (!attr?.value) return null;
  const raw = attr.value.kind === "Expression" ? attr.value.raw : attr.value.value;
  return inspectHandlerBody(raw);
}

// ---------------------------------------------------------------------------
// Shared message / suggestion builders
// ---------------------------------------------------------------------------

/**
 * Map (branch, aria-expanded-present?) → which finding (if any) to
 * emit. The logic is deliberately narrow:
 *
 *   - No aria-expanded and any disclosure branch → missing-expanded.
 *   - aria-expanded present and branch is `aria-controls` → nothing
 *     (both attributes are there; the pattern is complete).
 *   - aria-expanded present and branch is a non-`aria-controls`
 *     signal (data-*-toggle, onclick classList) → missing-controls.
 *     The element proves it toggles something but doesn't name the
 *     target — the WAI-ARIA Authoring Practices disclosure pattern
 *     asks the trigger to identify the controlled region.
 */
function classifyFinding(branch: PredicateBranch, hasAriaExpanded: boolean): FindingKind | null {
  if (!hasAriaExpanded) return "missing-expanded";
  if (branch.kind === "aria-controls") return null;
  return "missing-controls";
}

function buildMessage(tagName: string, branch: PredicateBranch, finding: FindingKind): string {
  const evidence = describeBranch(branch);
  if (finding === "missing-controls") {
    return (
      `<${tagName}> has aria-expanded but is missing aria-controls — AT cannot ` +
      `identify which region the trigger controls. (${evidence})`
    );
  }
  return (
    `<${tagName}> looks like a disclosure trigger but has no aria-expanded — AT ` +
    `cannot announce whether the region is open or closed. (${evidence})`
  );
}

function buildSuggestion(tagName: string, branch: PredicateBranch, finding: FindingKind): string {
  const evidence = describeBranch(branch);
  if (finding === "missing-controls") {
    return (
      `Add aria-controls="<id>" to the <${tagName}>, where <id> is the id of the ` +
      `region the trigger shows/hides. The region element will need that id as ` +
      `well. Predicate match: ${evidence}. If the controlled region cannot be ` +
      `reached by id (e.g. it is rendered as a sibling selected by runtime ` +
      `convention) and the trigger is otherwise WCAG 4.1.2 compliant, suppress ` +
      `with a source-level pragma (e.g. <!-- ra11y-disable aria/expanded-on-disclosure -->) ` +
      `so the next scan dismisses it deterministically.`
    );
  }
  return (
    `Add aria-expanded="false" to the <${tagName}> as the initial collapsed state, ` +
    `then toggle it to "true"/"false" in the same runtime that shows/hides the ` +
    `disclosed region. Predicate match: ${evidence}. If this control is not a ` +
    `disclosure trigger, the detection is wrong — suppress with a source-level ` +
    `pragma (e.g. <!-- ra11y-disable aria/expanded-on-disclosure -->) so the ` +
    `next scan dismisses it deterministically.`
  );
}

function describeBranch(branch: PredicateBranch): string {
  if (branch.kind === "aria-controls") {
    return `aria-controls points at an element with id="${branch.targetId}" in the same document`;
  }
  if (branch.kind === "data-toggle") {
    return `${branch.attrName}="${branch.value}" is a disclosure-style toggle value`;
  }
  return `inline onclick toggles a visibility class "${branch.matchedClass}" via classList`;
}
