/**
 * Rule: aria/hidden-focus
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:2.1.1, wcag21:2.1.1
 * Spec (Name, Role, Value): https://www.w3.org/TR/WCAG22/#name-role-value
 * Spec (Keyboard): https://www.w3.org/TR/WCAG22/#keyboard
 * ARIA guidance: https://www.w3.org/TR/using-aria/#4thrule
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags elements with `aria-hidden="true"` that remain reachable by
 * keyboard — either because they (a) are natively focusable, (b) carry
 * a `tabindex` value that keeps them in the tab order (`0` or a
 * positive integer — `-1` is fine), or (c) contain a focusable
 * descendant. `aria-hidden` propagates to descendants in the
 * accessibility tree, but focus does NOT — a keyboard user can tab into
 * aria-hidden content and hear silence, producing an unannounced focus
 * point that WCAG 4.1.2 explicitly forbids.
 *
 * The canonical anti-pattern is `<button aria-hidden="true">X</button>`:
 * the button is still in the tab order but assistive tech will not
 * announce it when it gains focus.
 *
 * Also a direct WCAG 2.1.1 Keyboard failure mode: the control is
 * reachable by keyboard but its functionality cannot be operated via
 * keyboard by an AT user, because the focused node has no
 * programmatically determinable name or role to act on — the keyboard
 * user tabs to it and the screen reader says nothing. SC 2.1.1 requires
 * all functionality to be operable through a keyboard interface; a
 * silently-focused aria-hidden control fails that for any user relying
 * on AT announcements to drive keyboard interaction.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";
import type { FixPaths } from "../../types/violation.ts";

/**
 * Class-token substrings that, when present on an otherwise-flagged
 * element, suggest the `aria-hidden` attribute is toggled at runtime
 * by a widget library (Bootstrap modal / dialog / drawer / offcanvas
 * / popover / toast / overlay / backdrop) rather than being a static
 * authoring mistake. Static analysis cannot observe the toggle — the
 * rule still fires at severity `error` (surface-don't-suppress per
 * CLAUDE.md §1 and docs/kb/architecture/ai-first-consumer.md), but
 * the message and `couldBeWrongBecause` are enriched so the agent
 * dismisses in one read.
 *
 * Matching policy: split the element's `class` attribute on
 * whitespace, lowercase each token, and check whether any token
 * *contains* any of the markers as a substring. Token-scoped (not
 * whole-string) so an unrelated class like `product-modality`
 * doesn't match `modal`, while `modal-fullscreen` does. Markers are
 * lowercased once so the check is case-insensitive.
 */
const OVERLAY_CLASS_MARKERS: readonly string[] = [
  "modal",
  "dialog",
  "drawer",
  "offcanvas",
  "popover",
  "toast",
  "overlay",
  "backdrop",
];

/**
 * Structured `couldBeWrongBecause` code pointing at the widget-library
 * runtime-toggle escape hatch. Emitted alongside the message
 * enrichment so agents can also route on the code without parsing the
 * reason prose. See docs/adr/0009-violation-could-be-wrong-because.md.
 */
const RUNTIME_ARIA_HIDDEN_TOGGLE = "runtime_aria_hidden_toggle";

const OVERLAY_NOTE =
  " note: class name suggests a runtime-toggled overlay " +
  "(aria-hidden likely flips when the widget opens); static analysis " +
  "cannot observe the toggle — verify the open-state runtime behavior.";

/**
 * HTML tag names that are natively focusable. Some of these are
 * *conditionally* focusable (only when a specific attribute is present
 * or absent) — see `isConditionallyFocusable` below.
 */
const NATIVELY_FOCUSABLE: ReadonlySet<string> = new Set([
  "a",
  "area",
  "audio",
  "button",
  "details",
  "iframe",
  "input",
  "select",
  "summary",
  "textarea",
  "video",
]);

/** Tags whose focusability depends on another attribute. */
const CONDITIONAL_FOCUSABLE: ReadonlySet<string> = new Set([
  "a",
  "area",
  "audio",
  "input",
  "video",
]);

export const rule = defineRule({
  id: "aria/hidden-focus",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:2.1.1", "wcag21:2.1.1"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      'Elements with aria-hidden="true" must not be focusable and must not contain focusable descendants. Keyboard focus and the accessibility tree must agree.',
    rationale:
      'aria-hidden="true" removes an element and all its descendants from the accessibility tree, but focus order is governed by the DOM and tabindex — not ARIA. If a focusable element is hidden from assistive tech, a keyboard user tabs to it and the screen reader says nothing. This is one of the most frequently-cited ARIA anti-patterns and a direct 4.1.2 failure because the focused component has no programmatically determinable name or role.',
    goodExample: `<span aria-hidden="true" tabindex="-1">Icon</span>`,
    badExample: `<button aria-hidden="true">Close</button>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/using-aria/#4thrule",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  fixPaths: FixPaths;
  couldBeWrongBecause?: readonly string[];
}) => void;

type Violation = {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  fixPaths: FixPaths;
  couldBeWrongBecause?: readonly string[];
};

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    if (!isHtmlAriaHiddenTrue(el)) continue;
    const overlay = hasOverlayMarker(getHtmlAttribute(el, "class"));
    const direct = checkHtmlDirectFocusable(el, overlay);
    if (direct) {
      emit(direct);
      continue;
    }
    const descendant = findHtmlFocusableDescendant(el);
    // HTML attribute quoting is polymorphic (`aria-hidden="true"`,
    // `aria-hidden='true'`, `aria-hidden=true`), so we can't emit a
    // guaranteed-matching oldText without reading the raw source.
    // Ship guidance; let the agent do the one-line edit.
    if (descendant) {
      emit(buildDescendantViolation(el.tagName, descendant.tagName, el.loc.start, false, overlay));
    }
  }
}

function isHtmlAriaHiddenTrue(el: HtmlElement): boolean {
  return getHtmlAttribute(el, "aria-hidden") === "true";
}

function checkHtmlDirectFocusable(el: HtmlElement, overlay: boolean): Violation | null {
  const tag = el.tagName.toLowerCase();
  if (isHtmlElementFocusable(el, tag)) {
    return buildDirectViolation(el.tagName, el.loc.start, false, overlay);
  }
  return null;
}

function isHtmlElementFocusable(el: HtmlElement, tag: string): boolean {
  if (isHtmlTabindexFocusable(el)) return true;
  if (!NATIVELY_FOCUSABLE.has(tag)) return false;
  if (!CONDITIONAL_FOCUSABLE.has(tag)) return true;
  return isHtmlConditionallyFocusable(el, tag);
}

function isHtmlTabindexFocusable(el: HtmlElement): boolean {
  const raw = getHtmlAttribute(el, "tabindex");
  if (raw === null) return false;
  return keepsInTabOrder(raw);
}

function isHtmlConditionallyFocusable(el: HtmlElement, tag: string): boolean {
  if (tag === "a" || tag === "area") return hasHtmlAttribute(el, "href");
  if (tag === "audio" || tag === "video") return hasHtmlAttribute(el, "controls");
  if (tag === "input") {
    const type = getHtmlAttribute(el, "type");
    return type === null || type.toLowerCase() !== "hidden";
  }
  return false;
}

function findHtmlFocusableDescendant(root: HtmlElement): HtmlElement | null {
  for (const child of root.children) {
    const hit = findHtmlFocusableInNode(child);
    if (hit) return hit;
  }
  return null;
}

function findHtmlFocusableInNode(node: HtmlNode): HtmlElement | null {
  if (node.kind !== "HtmlElement") return null;
  const tag = node.tagName.toLowerCase();
  if (isHtmlElementFocusable(node, tag)) return node;
  for (const child of node.children) {
    const hit = findHtmlFocusableInNode(child);
    if (hit) return hit;
  }
  return null;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const el of walkJsxElements(module)) {
    if (isJsxPascalCase(el.tagName)) continue;
    if (!isJsxAriaHiddenTrue(el)) continue;
    const overlay = hasOverlayMarker(
      getJsxAttributeString(el, "className") ?? getJsxAttributeString(el, "class"),
    );
    const direct = checkJsxDirectFocusable(el, overlay);
    if (direct) {
      emit(direct);
      continue;
    }
    const descendant = findJsxFocusableDescendant(el);
    // JSX string-literal attributes use double quotes by convention
    // (and by Prettier default), so `aria-hidden="true"` is a
    // guaranteed source match — safe to emit a mechanical edit.
    if (descendant) {
      emit(buildDescendantViolation(el.tagName, descendant.tagName, el.loc.start, true, overlay));
    }
  }
}

function isJsxAriaHiddenTrue(el: JsxElement): boolean {
  return getJsxAttributeString(el, "aria-hidden") === "true";
}

function checkJsxDirectFocusable(el: JsxElement, overlay: boolean): Violation | null {
  if (isJsxElementFocusable(el)) {
    return buildDirectViolation(el.tagName, el.loc.start, true, overlay);
  }
  return null;
}

function isJsxElementFocusable(el: JsxElement): boolean {
  if (isJsxTabindexFocusable(el)) return true;
  const tag = el.tagName;
  if (!NATIVELY_FOCUSABLE.has(tag)) return false;
  if (!CONDITIONAL_FOCUSABLE.has(tag)) return true;
  return isJsxConditionallyFocusable(el, tag);
}

function isJsxTabindexFocusable(el: JsxElement): boolean {
  const raw = getJsxAttributeString(el, "tabIndex") ?? getJsxAttributeString(el, "tabindex");
  if (raw === null) return false;
  return keepsInTabOrder(raw);
}

function isJsxConditionallyFocusable(el: JsxElement, tag: string): boolean {
  if (tag === "a" || tag === "area") return hasJsxAttribute(el, "href");
  if (tag === "audio" || tag === "video") return hasJsxAttribute(el, "controls");
  if (tag === "input") {
    const type = getJsxAttributeString(el, "type");
    return type === null || type.toLowerCase() !== "hidden";
  }
  return false;
}

function findJsxFocusableDescendant(root: JsxElement): JsxElement | null {
  for (const child of root.children) {
    const hit = findJsxFocusableInNode(child);
    if (hit) return hit;
  }
  return null;
}

function findJsxFocusableInNode(node: JsxNode): JsxElement | null {
  if (node.kind !== "JsxElement") return null;
  // React components (PascalCase) are opaque — we cannot know whether
  // they render focusable content, so we do not descend into them.
  if (isJsxPascalCase(node.tagName)) return null;
  if (isJsxElementFocusable(node)) return node;
  for (const child of node.children) {
    const hit = findJsxFocusableInNode(child);
    if (hit) return hit;
  }
  return null;
}

function isJsxPascalCase(tag: string): boolean {
  const first = tag[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

// ---------------------------------------------------------------------------
// Shared
// ---------------------------------------------------------------------------

/**
 * Per HTML spec: a tabindex of -1 removes the element from the
 * sequential tab order (though it remains programmatically focusable).
 * Any other parseable integer (0, positive, or negative values other
 * than -1) keeps the element reachable via Tab. Non-numeric values are
 * treated as "in tab order" because browsers coerce them to 0.
 */
function keepsInTabOrder(raw: string): boolean {
  const trimmed = raw.trim();
  if (trimmed === "") return false;
  const parsed = Number.parseInt(trimmed, 10);
  if (Number.isNaN(parsed)) return true;
  return parsed !== -1;
}

// ---------------------------------------------------------------------------
// Violation builders
// ---------------------------------------------------------------------------

/**
 * Mechanical oldText/newText for the inert swap. Only safe to emit
 * when the caller can guarantee the source uses `aria-hidden="true"`
 * verbatim — JSX string-literal attrs do (Prettier convention), HTML
 * may use single quotes or unquoted forms. When unsafe, the primary
 * path ships as guidance and the agent does the one-line edit.
 */
const INERT_SWAP = { oldText: 'aria-hidden="true"', newText: "inert" } as const;

function buildDirectViolation(
  tagName: string,
  loc: { line: number; column: number },
  canEdit: boolean,
  overlay: boolean,
): Violation {
  const nonFocusablePath =
    tagName === "a" || tagName === "area"
      ? "make the element non-focusable by removing href (an anchor without href is not in the tab order)"
      : tagName === "input"
        ? 'make the element non-focusable by using type="hidden" (or replacing it with a non-interactive element)'
        : "make the element non-focusable by replacing the native control with an inert element like <span>";
  const fixPaths: FixPaths = {
    primary: {
      label: `replace aria-hidden="true" with the \`inert\` attribute — inert hides the subtree from the accessibility tree AND removes it from the tab order in one declaration (Baseline widely available since 2024)`,
      ...(canEdit ? { edit: { ...INERT_SWAP } } : {}),
    },
    alternatives: [
      {
        label:
          'remove aria-hidden="true" — if the control should remain operable by sighted keyboard users, it must also be in the accessibility tree',
      },
      {
        label: `${nonFocusablePath}, then keep aria-hidden="true" for the decorative case; optionally add tabindex="-1" to belt-and-suspenders the tab-order removal`,
      },
    ],
  };
  const baseMessage = `<${tagName}> has aria-hidden="true" but is still focusable — keyboard users will tab to it and the screen reader will announce nothing.`;
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: overlay ? `${baseMessage}${OVERLAY_NOTE}` : baseMessage,
    suggestion: `Primary fix: ${fixPaths.primary.label}. Alternatives (less likely): (a) ${fixPaths.alternatives[0]?.label}; (b) ${fixPaths.alternatives[1]?.label}.`,
    fixPaths,
    // Conditional spread — `couldBeWrongBecause: []` would be a dishonest
    // empty-vs-unpopulated sentinel per CLAUDE.md §1.
    ...(overlay ? { couldBeWrongBecause: [RUNTIME_ARIA_HIDDEN_TOGGLE] } : {}),
  };
}

function buildDescendantViolation(
  parentTag: string,
  childTag: string,
  loc: { line: number; column: number },
  canEdit: boolean,
  overlay: boolean,
): Violation {
  const fixPaths: FixPaths = {
    primary: {
      label: `replace aria-hidden="true" on the <${parentTag}> with the \`inert\` attribute — inert makes the whole subtree unfocusable AND hidden from AT in one declaration (Baseline widely available since 2024)`,
      ...(canEdit ? { edit: { ...INERT_SWAP } } : {}),
    },
    alternatives: [
      {
        label: `remove aria-hidden="true" from the <${parentTag}> — if any descendant should be reachable, the ancestor cannot be hidden from AT`,
      },
      {
        label: `keep aria-hidden="true" on the <${parentTag}> and add tabindex="-1" (plus \`disabled\` where applicable) to every focusable descendant, starting with the <${childTag}> flagged here`,
      },
    ],
  };
  const baseMessage = `<${parentTag}> has aria-hidden="true" but contains a focusable <${childTag}> descendant — keyboard focus will land inside the hidden subtree and produce silent focus for AT users.`;
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: overlay ? `${baseMessage}${OVERLAY_NOTE}` : baseMessage,
    suggestion: `Primary fix: ${fixPaths.primary.label}. Alternatives (less likely): (a) ${fixPaths.alternatives[0]?.label}; (b) ${fixPaths.alternatives[1]?.label}.`,
    fixPaths,
    ...(overlay ? { couldBeWrongBecause: [RUNTIME_ARIA_HIDDEN_TOGGLE] } : {}),
  };
}

// ---------------------------------------------------------------------------
// Overlay-class marker detection
// ---------------------------------------------------------------------------

/**
 * Returns `true` when `classString` contains at least one whitespace-
 * separated token that, lowercased, includes any of the
 * {@link OVERLAY_CLASS_MARKERS} substrings. Token-scoped substring
 * match: a class like `modal-fullscreen` matches `modal`; a class like
 * `my-custom-dialog` matches `dialog`; a class like `product-modality`
 * does NOT match `modal` (different token) because its own token
 * `product-modality` does not contain `modal`. The check is
 * case-insensitive — CSS class names are case-sensitive per spec but
 * widget libraries universally use lowercase, and the agent reading
 * the file will have no trouble ignoring the framing if the match
 * happens to be accidental (surface-don't-suppress lets the agent
 * verify; misses are the expensive failure).
 */
function hasOverlayMarker(classString: string | null | undefined): boolean {
  if (!classString) return false;
  for (const rawToken of classString.split(/\s+/)) {
    if (rawToken.length === 0) continue;
    const token = rawToken.toLowerCase();
    for (const marker of OVERLAY_CLASS_MARKERS) {
      if (token.includes(marker)) return true;
    }
  }
  return false;
}
