/**
 * Rule: aria/icon-font-hidden
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:1.3.1, wcag21:1.3.1
 * Spec (Name, Role, Value): https://www.w3.org/TR/WCAG22/#name-role-value
 * Spec (Info and Relationships): https://www.w3.org/TR/WCAG22/#info-and-relationships
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set. (SC 4.1.2)
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags icon-font glyph elements (Font Awesome `<i class="fa-*">`,
 * Material Icons `<span class="material-icons">`, Bootstrap Icons
 * `<i class="bi bi-*">`, Ionicons `<ion-icon>` / `<i class="ionicon">`,
 * legacy Glyphicons, Icofont) that sit inside an interactive ancestor
 * whose accessible name already carries the control's label. Without
 * `aria-hidden="true"` (or `role="presentation"` / `role="none"`), many
 * assistive-tech stacks announce the element's Unicode pseudo-content
 * (a private-use-area glyph) on top of the real label — the canonical
 * "double-announcement" anti-pattern described by WAI tutorials.
 *
 * Distinct from `semantics/button-name` and `navigation/link-descriptive-
 * text`: those rules fire when the interactive ancestor has no
 * accessible name at all. THIS rule fires when the ancestor IS named
 * (via visible text, `aria-label`, or `aria-labelledby`) AND the icon
 * child is unannotated — the double-announce risk.
 *
 * Scope of "labeled interactive ancestor":
 *   - `<button>` with a computable accessible name (text content,
 *     `aria-label`, `aria-labelledby`, `title`)
 *   - `<a href>` with a computable accessible name
 *   - `<summary>` with a computable accessible name
 *   - elements carrying `role="button" | "link" | "menuitem" | "tab"`
 *     with a computable accessible name
 *
 * Detection narrowness is deliberate: static analysis cannot know
 * whether an author's glyph is rendered visually or hidden by CSS
 * entirely; we only fire when the icon-font signal is present AND the
 * ancestor is labeled. Agents reading the surrounding file decide
 * whether the icon is decorative or load-bearing.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";

/**
 * Icon-font family signals. Each entry is a predicate over the class-
 * token list (and, for `ion-icon`, tag name). A token matches when it
 * either equals a family marker exactly (e.g. `material-icons`) or is
 * a namespaced glyph slug (e.g. `fa-arrow-left`, `bi-search`,
 * `material-symbols-rounded`). We match token-by-token against the
 * whitespace-split class attribute to avoid substring collisions
 * (e.g. `.favorite` must not match `fa-`).
 */

type IconFontFamily =
  | "font-awesome"
  | "material-icons"
  | "bootstrap-icons"
  | "ionicons"
  | "glyphicons"
  | "icofont";

interface IconFontMatch {
  readonly family: IconFontFamily;
  /** The specific token that triggered detection — echoed in messages. */
  readonly token: string;
}

/** Font Awesome style tokens (v4/v5/v6 weights + pro variants). */
const FA_STYLE_TOKENS: ReadonlySet<string> = new Set([
  "fa",
  "fas",
  "far",
  "fab",
  "fal",
  "fad",
  "fat",
  "fass",
]);

/** Material Icons base class tokens (v1 + Material Symbols family). */
const MATERIAL_EXACT_TOKENS: ReadonlySet<string> = new Set([
  "material-icons",
  "material-icons-outlined",
  "material-icons-round",
  "material-icons-rounded",
  "material-icons-sharp",
  "material-icons-two-tone",
]);

/** Roles on the ancestor that mean "this is an interactive control." */
const INTERACTIVE_ROLES: ReadonlySet<string> = new Set([
  "button",
  "link",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "tab",
]);

/** Native tag names that are always interactive and take an accessible name. */
const INTERACTIVE_TAGS: ReadonlySet<string> = new Set(["button", "summary"]);

export const rule = defineRule({
  id: "aria/icon-font-hidden",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:1.3.1", "wcag21:1.3.1"],
  severity: "info",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      'Icon-font glyph elements (Font Awesome, Material Icons, Bootstrap Icons, Ionicons, Glyphicons, Icofont) inside a labeled interactive ancestor should carry aria-hidden="true" (or role="presentation") to prevent assistive-tech from double-announcing the glyph alongside the control\'s accessible name.',
    rationale:
      "Icon fonts render glyphs through the CSS `::before` pseudo-element, whose content is a private-use-area Unicode codepoint. When the hosting `<i>` or `<span>` sits inside a labeled `<button>` / `<a>` and does not carry aria-hidden, many assistive technologies announce the glyph codepoint (often as garbage or as the family name) alongside the real label — the user hears 'Close, private use character' or the label twice. Hiding the glyph element from the accessibility tree is the WAI-recommended fix because the visible label already conveys the action. Static detection is load-bearing because the antipattern is mechanical (the same `<i class=\"fa-*\">` shape across every icon-font-using codebase) and the fix is a one-attribute addition.",
    goodExample:
      '<button aria-label="Close"><i class="fas fa-times" aria-hidden="true"></i></button>',
    badExample: '<button aria-label="Close"><i class="fas fa-times"></i></button>',
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#info-and-relationships",
      "https://www.w3.org/WAI/tutorials/images/decorative/",
      "https://fontawesome.com/v6/docs/web/dig-deeper/accessibility",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// Icon-font detection
// ---------------------------------------------------------------------------

/**
 * Classifies the given tag + class-attribute pair as an icon-font host
 * or not. Returns the matching family plus the token that drove the
 * detection so downstream messages can echo concrete evidence instead
 * of generic "icon font" phrasing. Null when the element is not an
 * icon-font host.
 *
 * The caller is responsible for hoisting this check behind the "is
 * the element inside a labeled interactive ancestor?" gate — this
 * function has no opinion on ancestry.
 */
function detectIconFont(tagName: string, classValue: string | null): IconFontMatch | null {
  const tagLower = tagName.toLowerCase();
  // Ionicons `<ion-icon>` custom element needs no class to identify.
  if (tagLower === "ion-icon") return { family: "ionicons", token: "ion-icon" };
  if (classValue === null) return null;
  const tokens = classValue.split(/\s+/u).filter((t) => t.length > 0);
  return matchIconFontTokens(tagLower, tokens);
}

function matchIconFontTokens(tagLower: string, tokens: readonly string[]): IconFontMatch | null {
  for (const raw of tokens) {
    const hit = matchIconFontToken(tagLower, raw);
    if (hit !== null) return hit;
  }
  return null;
}

/**
 * Classifies a single class token against each known icon-font family.
 * Split out from the token loop to keep per-function cyclomatic
 * complexity under Biome's `noExcessiveCognitiveComplexity` ceiling —
 * the family list is growing and one long switch ran afoul of the
 * limit. Returns null when the token matches nothing.
 */
function matchIconFontToken(tagLower: string, raw: string): IconFontMatch | null {
  const tok = raw.toLowerCase();
  if (FA_STYLE_TOKENS.has(tok) || tok.startsWith("fa-")) {
    return { family: "font-awesome", token: raw };
  }
  if (MATERIAL_EXACT_TOKENS.has(tok) || tok.startsWith("material-symbols-")) {
    return { family: "material-icons", token: raw };
  }
  // `bi-*` glyph tokens ride alongside the `bi` base class in Bootstrap
  // Icons v1 — the `bi-*` slug is the surer signal (bare `bi` can collide
  // with unrelated class names like `bi` for "business intelligence").
  if (tok.startsWith("bi-") && (tagLower === "i" || tagLower === "span")) {
    return { family: "bootstrap-icons", token: raw };
  }
  if (tok === "glyphicon" || tok.startsWith("glyphicon-")) {
    return { family: "glyphicons", token: raw };
  }
  if (tok === "icofont" || tok.startsWith("icofont-")) {
    return { family: "icofont", token: raw };
  }
  if (tok === "ionicon") return { family: "ionicons", token: raw };
  return null;
}

// ---------------------------------------------------------------------------
// Accessible-name computation (scoped to what the rule needs)
// ---------------------------------------------------------------------------

/**
 * Returns the HTML element's accessible name (best-effort, scoped to
 * the authoring inputs this rule cares about). Order of precedence
 * mirrors the simplified WAI name-computation algorithm:
 *   1. `aria-labelledby` (treated as "named" when attribute is present
 *      — we don't dereference the target here; the rule's gate is "is
 *      the ancestor labeled?", and the author opting into labelledby
 *      counts as an explicit name declaration).
 *   2. `aria-label` with non-empty trimmed value.
 *   3. `title` with non-empty trimmed value.
 *   4. Visible text content. We deliberately subtract text contributed
 *      by icon-font children — a `<button><i class="fa-search"></i></button>`
 *      should NOT count as labeled because it has no real text.
 */
function accessibleNameHtml(el: HtmlElement): string | null {
  if (hasHtmlAttribute(el, "aria-labelledby")) return "aria-labelledby";
  const label = getHtmlAttribute(el, "aria-label");
  if (label !== null && label.trim().length > 0) return label.trim();
  const title = getHtmlAttribute(el, "title");
  if (title !== null && title.trim().length > 0) return title.trim();
  const visible = visibleTextExcludingIconsHtml(el);
  if (visible.trim().length > 0) return visible.trim();
  return null;
}

function visibleTextExcludingIconsHtml(root: HtmlElement): string {
  let out = "";
  for (const child of root.children) {
    out += visibleTextNodeHtml(child);
  }
  return out;
}

function visibleTextNodeHtml(node: HtmlNode): string {
  if (node.kind === "HtmlText") return node.value;
  if (node.kind !== "HtmlElement") return "";
  if (detectIconFont(node.tagName, getHtmlAttribute(node, "class")) !== null) return "";
  return visibleTextExcludingIconsHtml(node);
}

function accessibleNameJsx(el: JsxElement): string | null {
  if (hasJsxAttribute(el, "aria-labelledby")) return "aria-labelledby";
  const label = getJsxAttributeString(el, "aria-label");
  if (label !== null && label.trim().length > 0) return label.trim();
  const title = getJsxAttributeString(el, "title");
  if (title !== null && title.trim().length > 0) return title.trim();
  const visible = visibleTextExcludingIconsJsx(el);
  if (visible.trim().length > 0) return visible.trim();
  // Runtime-valued children (`<button>{label}</button>`) likely carry a
  // name we can't see statically. Treat as labeled — false-positive
  // avoidance dominates false-negatives for the icon-font case.
  for (const child of el.children) {
    if (child.kind === "JsxExpression") return "expression-child";
  }
  return null;
}

function visibleTextExcludingIconsJsx(root: JsxElement): string {
  let out = "";
  for (const child of root.children) {
    out += visibleTextNodeJsx(child);
  }
  return out;
}

function visibleTextNodeJsx(node: JsxNode): string {
  if (node.kind === "JsxText") return node.value;
  if (node.kind !== "JsxElement") return "";
  const classValue =
    getJsxAttributeString(node, "className") ?? getJsxAttributeString(node, "class");
  if (detectIconFont(node.tagName, classValue) !== null) return "";
  return visibleTextExcludingIconsJsx(node);
}

// ---------------------------------------------------------------------------
// Interactive-ancestor predicate
// ---------------------------------------------------------------------------

function isHtmlLabeledInteractive(el: HtmlElement): boolean {
  const tag = el.tagName.toLowerCase();
  const role = (getHtmlAttribute(el, "role") ?? "").toLowerCase();
  const isInteractive =
    INTERACTIVE_TAGS.has(tag) ||
    (tag === "a" && hasHtmlAttribute(el, "href")) ||
    INTERACTIVE_ROLES.has(role);
  if (!isInteractive) return false;
  return accessibleNameHtml(el) !== null;
}

function isJsxLabeledInteractive(el: JsxElement): boolean {
  // Match HTML semantics on the JSX side — authors routinely write
  // lowercase `<a>` / `<button>` / `<summary>` in JSX, and the same
  // native-element rules apply. PascalCase components are opaque: we
  // cannot know their rendered accessible name, so we skip them.
  const tag = el.tagName;
  if (tag.length > 0 && (tag[0] ?? "") >= "A" && (tag[0] ?? "") <= "Z") return false;
  const role = (getJsxAttributeString(el, "role") ?? "").toLowerCase();
  const isInteractive =
    INTERACTIVE_TAGS.has(tag) ||
    (tag === "a" && hasJsxAttribute(el, "href")) ||
    INTERACTIVE_ROLES.has(role);
  if (!isInteractive) return false;
  return accessibleNameJsx(el) !== null;
}

// ---------------------------------------------------------------------------
// Check driver — HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const ancestor of walkHtmlElements(doc)) {
    if (!isHtmlLabeledInteractive(ancestor)) continue;
    const ancestorName = accessibleNameHtml(ancestor) ?? "";
    for (const child of ancestor.children) {
      visitHtmlForIcon(child, ancestor.tagName, ancestorName, emit);
    }
  }
}

function visitHtmlForIcon(
  node: HtmlNode,
  ancestorTag: string,
  ancestorName: string,
  emit: Emit,
): void {
  if (node.kind !== "HtmlElement") return;
  // Descending into a nested labeled interactive would double-report:
  // the outer walk already visits every element, so that nested node
  // will be checked when the loop reaches it.
  if (isHtmlLabeledInteractive(node)) return;
  const classValue = getHtmlAttribute(node, "class");
  const match = detectIconFont(node.tagName, classValue);
  if (match !== null && !isHtmlIconHidden(node)) {
    emit(buildHtmlViolation(node, match, ancestorTag, ancestorName));
  }
  for (const child of node.children) visitHtmlForIcon(child, ancestorTag, ancestorName, emit);
}

function isHtmlIconHidden(el: HtmlElement): boolean {
  if (getHtmlAttribute(el, "aria-hidden") === "true") return true;
  const role = (getHtmlAttribute(el, "role") ?? "").toLowerCase();
  return role === "presentation" || role === "none";
}

function buildHtmlViolation(
  icon: HtmlElement,
  match: IconFontMatch,
  ancestorTag: string,
  ancestorName: string,
): {
  severity: "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  return {
    severity: "info",
    location: { filePath: "", line: icon.loc.start.line, column: icon.loc.start.column },
    message: buildMessage(icon.tagName, match, ancestorTag, ancestorName),
    suggestion: buildSuggestion(icon.tagName, match, ancestorTag, ancestorName),
  };
}

// ---------------------------------------------------------------------------
// Check driver — JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const ancestor of walkJsxElements(module)) {
    if (!isJsxLabeledInteractive(ancestor)) continue;
    const ancestorName = accessibleNameJsx(ancestor) ?? "";
    for (const child of ancestor.children) {
      visitJsxForIcon(child, ancestor.tagName, ancestorName, emit);
    }
  }
}

function visitJsxForIcon(
  node: JsxNode,
  ancestorTag: string,
  ancestorName: string,
  emit: Emit,
): void {
  if (node.kind !== "JsxElement") return;
  if (isJsxLabeledInteractive(node)) return;
  const classValue =
    getJsxAttributeString(node, "className") ?? getJsxAttributeString(node, "class");
  const match = detectIconFont(node.tagName, classValue);
  if (match !== null && !isJsxIconHidden(node)) {
    emit(buildJsxViolation(node, match, ancestorTag, ancestorName));
  }
  for (const child of node.children) visitJsxForIcon(child, ancestorTag, ancestorName, emit);
}

function isJsxIconHidden(el: JsxElement): boolean {
  if (getJsxAttributeString(el, "aria-hidden") === "true") return true;
  const role = (getJsxAttributeString(el, "role") ?? "").toLowerCase();
  return role === "presentation" || role === "none";
}

function buildJsxViolation(
  icon: JsxElement,
  match: IconFontMatch,
  ancestorTag: string,
  ancestorName: string,
): {
  severity: "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  return {
    severity: "info",
    location: { filePath: "", line: icon.loc.start.line, column: icon.loc.start.column },
    message: buildMessage(icon.tagName, match, ancestorTag, ancestorName),
    suggestion: buildSuggestion(icon.tagName, match, ancestorTag, ancestorName),
  };
}

// ---------------------------------------------------------------------------
// Message / suggestion construction
// ---------------------------------------------------------------------------

function familyName(family: IconFontFamily): string {
  switch (family) {
    case "font-awesome":
      return "Font Awesome";
    case "material-icons":
      return "Material Icons";
    case "bootstrap-icons":
      return "Bootstrap Icons";
    case "ionicons":
      return "Ionicons";
    case "glyphicons":
      return "Glyphicons";
    case "icofont":
      return "Icofont";
  }
}

/**
 * Echoes the host ancestor's accessible name back to the agent, capped
 * so a pathological 1 KB `aria-label` doesn't double the response size
 * through the per-finding `message` + `suggestion` fields.
 */
function truncateName(name: string): string {
  const clipped = name.length > 60 ? `${name.slice(0, 57)}…` : name;
  return clipped === "aria-labelledby"
    ? "(name comes from aria-labelledby)"
    : clipped === "expression-child"
      ? "(name comes from a runtime expression child)"
      : `"${clipped}"`;
}

function buildMessage(
  iconTag: string,
  match: IconFontMatch,
  ancestorTag: string,
  ancestorName: string,
): string {
  return (
    `<${iconTag} class="${match.token}"> is a ${familyName(match.family)} glyph inside a ` +
    `labeled <${ancestorTag}> ${truncateName(ancestorName)} and has no aria-hidden — ` +
    `assistive tech may announce the glyph codepoint alongside the real label (double-announce).`
  );
}

function buildSuggestion(
  iconTag: string,
  match: IconFontMatch,
  ancestorTag: string,
  ancestorName: string,
): string {
  const familyLabel = familyName(match.family);
  const parentRef = `<${ancestorTag}> ${truncateName(ancestorName)}`;
  return (
    `Add aria-hidden="true" to the <${iconTag} class="${match.token}"> — the ` +
    `${familyLabel} glyph is purely visual and the parent ${parentRef} already ` +
    `carries the accessible name. Alternative: set role="presentation" on the ` +
    `<${iconTag}> (equivalent effect for icon-only decorative content). If the ` +
    `glyph is NOT decorative and conveys information the label does not, promote ` +
    `it to a real image (<svg><title>…</title></svg> or <img alt="…">) and leave ` +
    `aria-hidden off.`
  );
}
