/**
 * Rule: aria/icon-font-hidden
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:1.3.1, wcag21:1.3.1
 * Spec (Name, Role, Value): https://www.w3.org/TR/WCAG22/#name-role-value
 * Spec (Info and Relationships): https://www.w3.org/TR/WCAG22/#info-and-relationships
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set. (SC 4.1.2)
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags icon-font glyph elements (Font Awesome `<i class="fa-*">`,
 * Material Icons `<span class="material-icons">`, Bootstrap Icons
 * `<i class="bi bi-*">`, Ionicons `<ion-icon>` / `<i class="ionicon">`,
 * legacy Glyphicons, Icofont) that sit inside an interactive ancestor
 * whose accessible name already carries the control's label. Without
 * `aria-hidden="true"` (or `role="presentation"` / `role="none"`), many
 * assistive-tech stacks announce the element's Unicode pseudo-content
 * (a private-use-area glyph) on top of the real label — the canonical
 * "double-announcement" anti-pattern described by WAI tutorials.
 *
 * Distinct from `semantics/button-name` and `navigation/link-descriptive-
 * text`: those rules fire when the interactive ancestor has no
 * accessible name at all. THIS rule fires when the ancestor IS named
 * (via visible text, `aria-label`, or `aria-labelledby`) AND the icon
 * child is unannotated — the double-announce risk.
 *
 * The rule emits a second, sibling kind of finding (variantKey
 * `relies-on-title`) when an interactive ancestor's only "name" candidate
 * is the `title` attribute and it has an icon-font descendant — the
 * `<a href title="Facebook"><i class="fa fa-facebook"></i></a>`
 * social-icon row. Crediting `title` as a real accessible name was
 * teaching an anti-pattern: VoiceOver iOS does not announce `title` for
 * links, several SR/browser pairs surface it only as a tooltip, and the
 * WAI-ARIA APG warns against `title` as a sole name source. The fix
 * (drop `title` from name computation, surface the case as its own
 * finding pointing at `aria-label`) catches the regression instead of
 * propagating it. The second pass lives in
 * `icon-font-hidden.title-relies.ts`; shared helpers used by both
 * passes live in `icon-font-hidden.shared.ts`.
 *
 * Scope of "labeled interactive ancestor":
 *   - `<button>` with a computable accessible name (text content,
 *     `aria-label`, or `aria-labelledby` — `title` is excluded; see
 *     the second pass for why)
 *   - `<a href>` with a computable accessible name
 *   - `<summary>` with a computable accessible name
 *   - elements carrying `role="button" | "link" | "menuitem" | "tab"`
 *     with a computable accessible name
 *
 * Detection narrowness is deliberate: static analysis cannot know
 * whether an author's glyph is rendered visually or hidden by CSS
 * entirely; we only fire when the icon-font signal is present AND the
 * ancestor is labeled. Agents reading the surrounding file decide
 * whether the icon is decorative or load-bearing.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";
import {
  accessibleNameHtml,
  accessibleNameJsx,
  detectIconFont,
  type Emit,
  familyName,
  type IconFontMatch,
  INTERACTIVE_ROLES,
  INTERACTIVE_TAGS,
  isHtmlIconHidden,
  isJsxIconHidden,
} from "./icon-font-hidden.shared.ts";
import {
  checkHtmlTitleOnlyIconRow,
  checkJsxTitleOnlyIconRow,
} from "./icon-font-hidden.title-relies.ts";

export const rule = defineRule({
  id: "aria/icon-font-hidden",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:1.3.1", "wcag21:1.3.1"],
  severity: "info",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      'Icon-font glyph elements (Font Awesome, Material Icons, Bootstrap Icons, Ionicons, Glyphicons, Icofont) inside a labeled interactive ancestor should carry aria-hidden="true" (or role="presentation") to prevent assistive-tech from double-announcing the glyph alongside the control\'s accessible name.',
    rationale:
      "Icon fonts render glyphs through the CSS `::before` pseudo-element, whose content is a private-use-area Unicode codepoint. When the hosting `<i>` or `<span>` sits inside a labeled `<button>` / `<a>` and does not carry aria-hidden, many assistive technologies announce the glyph codepoint (often as garbage or as the family name) alongside the real label — the user hears 'Close, private use character' or the label twice. Hiding the glyph element from the accessibility tree is the WAI-recommended fix because the visible label already conveys the action. Static detection is load-bearing because the antipattern is mechanical (the same `<i class=\"fa-*\">` shape across every icon-font-using codebase) and the fix is a one-attribute addition.",
    goodExample:
      '<button aria-label="Close"><i class="fas fa-times" aria-hidden="true"></i></button>',
    badExample: '<button aria-label="Close"><i class="fas fa-times"></i></button>',
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#info-and-relationships",
      "https://www.w3.org/WAI/tutorials/images/decorative/",
      "https://fontawesome.com/v6/docs/web/dig-deeper/accessibility",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

// ---------------------------------------------------------------------------
// Interactive-ancestor predicate
// ---------------------------------------------------------------------------

function isHtmlLabeledInteractive(el: HtmlElement): boolean {
  const tag = el.tagName.toLowerCase();
  const role = (getHtmlAttribute(el, "role") ?? "").toLowerCase();
  const isInteractive =
    INTERACTIVE_TAGS.has(tag) ||
    (tag === "a" && hasHtmlAttribute(el, "href")) ||
    INTERACTIVE_ROLES.has(role);
  if (!isInteractive) return false;
  return accessibleNameHtml(el) !== null;
}

function isJsxLabeledInteractive(el: JsxElement): boolean {
  // Match HTML semantics on the JSX side — authors routinely write
  // lowercase `<a>` / `<button>` / `<summary>` in JSX, and the same
  // native-element rules apply. PascalCase components are opaque: we
  // cannot know their rendered accessible name, so we skip them.
  const tag = el.tagName;
  if (tag.length > 0 && (tag[0] ?? "") >= "A" && (tag[0] ?? "") <= "Z") return false;
  const role = (getJsxAttributeString(el, "role") ?? "").toLowerCase();
  const isInteractive =
    INTERACTIVE_TAGS.has(tag) ||
    (tag === "a" && hasJsxAttribute(el, "href")) ||
    INTERACTIVE_ROLES.has(role);
  if (!isInteractive) return false;
  return accessibleNameJsx(el) !== null;
}

// ---------------------------------------------------------------------------
// Check driver — HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const ancestor of walkHtmlElements(doc)) {
    if (isHtmlLabeledInteractive(ancestor)) {
      const ancestorName = accessibleNameHtml(ancestor) ?? "";
      for (const child of ancestor.children) {
        visitHtmlForIcon(child, ancestor.tagName, ancestorName, emit);
      }
      continue;
    }
    // Second pass: interactive ancestor that is NOT labeled by a real
    // accessible-name source but DOES carry a `title` attribute and an
    // icon-font descendant — the social-icon row anti-pattern. Emitted
    // as a separate finding kind (variantKey "relies-on-title") so the
    // suggestion text can name the real fix (promote `title` →
    // `aria-label`) instead of teaching the original "add aria-hidden
    // to the icon" guidance, which would regress the link to no
    // reliable accessible name on iOS.
    checkHtmlTitleOnlyIconRow(ancestor, emit);
  }
}

function visitHtmlForIcon(
  node: HtmlNode,
  ancestorTag: string,
  ancestorName: string,
  emit: Emit,
): void {
  if (node.kind !== "HtmlElement") return;
  // Descending into a nested labeled interactive would double-report:
  // the outer walk already visits every element, so that nested node
  // will be checked when the loop reaches it.
  if (isHtmlLabeledInteractive(node)) return;
  const classValue = getHtmlAttribute(node, "class");
  const match = detectIconFont(node.tagName, classValue);
  if (match !== null && !isHtmlIconHidden(node)) {
    emit(buildHtmlViolation(node, match, ancestorTag, ancestorName, classValue));
  }
  for (const child of node.children) visitHtmlForIcon(child, ancestorTag, ancestorName, emit);
}

function buildHtmlViolation(
  icon: HtmlElement,
  match: IconFontMatch,
  ancestorTag: string,
  ancestorName: string,
  classValue: string | null,
): {
  severity: "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  classEvidence?: string;
} {
  return {
    severity: "info",
    location: { filePath: "", line: icon.loc.start.line, column: icon.loc.start.column },
    message: buildMessage(icon.tagName, match, ancestorTag, ancestorName),
    suggestion: buildSuggestion(icon.tagName, match, ancestorTag, ancestorName),
    // Conditional spread — the Ionicons custom-element (`<ion-icon>`)
    // has no class attribute and should flow on the wire without a
    // sentinel-empty `classEvidence: ""` (CLAUDE.md §1 "Ambiguous
    // field shapes are dishonest"). Rule-family rollup skips findings
    // without evidence.
    ...(classValue !== null && classValue.length > 0 ? { classEvidence: classValue } : {}),
  };
}

// ---------------------------------------------------------------------------
// Check driver — JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const ancestor of walkJsxElements(module)) {
    if (isJsxLabeledInteractive(ancestor)) {
      const ancestorName = accessibleNameJsx(ancestor) ?? "";
      for (const child of ancestor.children) {
        visitJsxForIcon(child, ancestor.tagName, ancestorName, emit);
      }
      continue;
    }
    // Mirrors `checkHtmlTitleOnlyIconRow` — see that function for
    // rationale.
    checkJsxTitleOnlyIconRow(ancestor, emit);
  }
}

function visitJsxForIcon(
  node: JsxNode,
  ancestorTag: string,
  ancestorName: string,
  emit: Emit,
): void {
  if (node.kind !== "JsxElement") return;
  if (isJsxLabeledInteractive(node)) return;
  const classValue =
    getJsxAttributeString(node, "className") ?? getJsxAttributeString(node, "class");
  const match = detectIconFont(node.tagName, classValue);
  if (match !== null && !isJsxIconHidden(node)) {
    emit(buildJsxViolation(node, match, ancestorTag, ancestorName, classValue));
  }
  for (const child of node.children) visitJsxForIcon(child, ancestorTag, ancestorName, emit);
}

function buildJsxViolation(
  icon: JsxElement,
  match: IconFontMatch,
  ancestorTag: string,
  ancestorName: string,
  classValue: string | null,
): {
  severity: "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  classEvidence?: string;
} {
  return {
    severity: "info",
    location: { filePath: "", line: icon.loc.start.line, column: icon.loc.start.column },
    message: buildMessage(icon.tagName, match, ancestorTag, ancestorName),
    suggestion: buildSuggestion(icon.tagName, match, ancestorTag, ancestorName),
    // See `buildHtmlViolation` for the conditional-spread rationale.
    ...(classValue !== null && classValue.length > 0 ? { classEvidence: classValue } : {}),
  };
}

// ---------------------------------------------------------------------------
// Message / suggestion construction
// ---------------------------------------------------------------------------

/**
 * Echoes the host ancestor's accessible name back to the agent, capped
 * so a pathological 1 KB `aria-label` doesn't double the response size
 * through the per-finding `message` + `suggestion` fields.
 */
function truncateName(name: string): string {
  const clipped = name.length > 60 ? `${name.slice(0, 57)}…` : name;
  return clipped === "aria-labelledby"
    ? "(name comes from aria-labelledby)"
    : clipped === "expression-child"
      ? "(name comes from a runtime expression child)"
      : `"${clipped}"`;
}

function buildMessage(
  iconTag: string,
  match: IconFontMatch,
  ancestorTag: string,
  ancestorName: string,
): string {
  return (
    `<${iconTag} class="${match.token}"> is a ${familyName(match.family)} glyph inside a ` +
    `labeled <${ancestorTag}> ${truncateName(ancestorName)} and has no aria-hidden — ` +
    `assistive tech may announce the glyph codepoint alongside the real label (double-announce).`
  );
}

function buildSuggestion(
  iconTag: string,
  match: IconFontMatch,
  ancestorTag: string,
  ancestorName: string,
): string {
  const familyLabel = familyName(match.family);
  const parentRef = `<${ancestorTag}> ${truncateName(ancestorName)}`;
  return (
    `Add aria-hidden="true" to the <${iconTag} class="${match.token}"> — the ` +
    `${familyLabel} glyph is purely visual and the parent ${parentRef} already ` +
    `carries the accessible name. Alternative: set role="presentation" on the ` +
    `<${iconTag}> (equivalent effect for icon-only decorative content). If the ` +
    `glyph is NOT decorative and conveys information the label does not, promote ` +
    `it to a real image (<svg><title>…</title></svg> or <img alt="…">) and leave ` +
    `aria-hidden off.`
  );
}
