/**
 * Rule: aria/icon-child-missing-aria-hidden
 * Satisfies: wcag22:1.3.1, wcag21:1.3.1, wcag22:4.1.2, wcag21:4.1.2
 * Spec (Info and Relationships): https://www.w3.org/TR/WCAG22/#info-and-relationships
 * Spec (Name, Role, Value): https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > Information, structure, and relationships conveyed through
 * > presentation can be programmatically determined or are available in
 * > text. (SC 1.3.1)
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set. (SC 4.1.2)
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Pairs with `semantics/button-name` (and `navigation/link-descriptive-
 * text`). Those rules flag the parent `<button>` / `<a href>` for
 * missing accessible name; this rule flags the inner icon-font glyph
 * for the missing `aria-hidden="true"` it will need once the parent's
 * name is fixed.
 *
 * Concrete failure shape: `<button><i class="fa fa-trash"></i></button>`
 * — `button-name` will guide the agent to add `aria-label="Delete"` on
 * the `<button>`. The moment that lands, the inner `<i>` becomes a
 * double-announce risk (the canonical anti-pattern handled by
 * `aria/icon-font-hidden`). Surfacing the icon-side fix at the same
 * scan lets the agent close both halves in one edit pass instead of
 * landing the parent fix and waiting for the next scan to surface the
 * icon-side regression.
 *
 * Boundaries (deliberate non-overlap with sibling rules):
 *   - Parent IS named (visible text, aria-label, aria-labelledby, child
 *     img alt, SVG <title>) — `aria/icon-font-hidden` already fires the
 *     double-announce finding. We do NOT fire (no value-add).
 *   - Parent has only `title` and an icon child — the title-relies
 *     pass of `aria/icon-font-hidden` (variantKey "relies-on-title")
 *     fires its own finding instructing the agent to promote
 *     title → aria-label THEN add aria-hidden. We do NOT fire (would
 *     duplicate that pass's framing).
 *   - Parent has no name and no icon-font descendant — `button-name` /
 *     `link-descriptive-text` cover the parent; nothing for us to add.
 *
 * The interactive ancestor scope is narrower than the labeled-icon
 * pass: only bare `<button>`, `<a href>`, `<summary>`, and elements
 * carrying `role="button" | "link" | "menuitem" | "tab"`. PascalCase
 * components are opaque (we cannot statically know the rendered
 * element) and are skipped on the JSX side.
 *
 * The icon-font-host detection reuses the shared module
 * (`icon-font-hidden.shared.ts`), so Font Awesome / Material Icons /
 * Bootstrap Icons / Ionicons / Glyphicons / Icofont are all matched
 * with one source of truth.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";
import {
  accessibleNameHtml,
  accessibleNameJsx,
  detectIconFont,
  familyName,
  type IconFontMatch,
  INTERACTIVE_ROLES,
  INTERACTIVE_TAGS,
  isHtmlIconHidden,
  isJsxIconHidden,
} from "./icon-font-hidden.shared.ts";

export const rule = defineRule({
  id: "aria/icon-child-missing-aria-hidden",
  satisfies: ["wcag22:1.3.1", "wcag21:1.3.1", "wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "warning",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      'An icon-font glyph (Font Awesome, Material Icons, Bootstrap Icons, Ionicons, Glyphicons, Icofont) inside an unnamed <button>/<a>/role=button needs aria-hidden="true" — once the parent\'s accessible name is added, the unhidden glyph will be double-announced.',
    rationale:
      'Pairs with `semantics/button-name` and `navigation/link-descriptive-text`: those rules surface the parent\'s missing accessible name; this rule surfaces the icon-side fix the agent will need to land in the same edit pass. Without it, the agent fixes `<button><i class="fa fa-trash"></i></button>` to `<button aria-label="Delete"><i class="fa fa-trash"></i></button>` — and the next scan re-flags the icon under `aria/icon-font-hidden` as a double-announce risk. Surfacing both halves at the first scan closes the issue in one edit. Static detection is load-bearing because the antipattern is mechanical: the same `<i class="fa-…">` shape across every icon-font-using codebase, and the fix is a one-attribute addition.',
    goodExample: '<button><i class="fa fa-trash" aria-hidden="true"></i></button>',
    badExample: '<button><i class="fa fa-trash"></i></button>',
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#info-and-relationships",
      "https://www.w3.org/WAI/tutorials/images/decorative/",
      "https://fontawesome.com/v6/docs/web/dig-deeper/accessibility",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

// ---------------------------------------------------------------------------
// Emitter contract
// ---------------------------------------------------------------------------

type Emit = (v: {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  classEvidence?: string;
}) => void;

// ---------------------------------------------------------------------------
// Interactive-ancestor predicate (unnamed branch)
// ---------------------------------------------------------------------------

/**
 * True when the element is interactive (native or via role) AND has no
 * accessible name AND has no `title` attribute. The `title` exclusion
 * defers to `aria/icon-font-hidden` variantKey "relies-on-title", which
 * fires its own dedicated finding for the social-icon row anti-pattern
 * with the right framing (promote title → aria-label THEN add
 * aria-hidden). Firing both rules on the same row would duplicate the
 * agent's triage budget.
 */
function isHtmlUnnamedInteractive(el: HtmlElement): boolean {
  const tag = el.tagName.toLowerCase();
  const role = (getHtmlAttribute(el, "role") ?? "").toLowerCase();
  const isInteractive =
    INTERACTIVE_TAGS.has(tag) ||
    (tag === "a" && hasHtmlAttribute(el, "href")) ||
    INTERACTIVE_ROLES.has(role);
  if (!isInteractive) return false;
  if (accessibleNameHtml(el) !== null) return false;
  const title = getHtmlAttribute(el, "title");
  if (title !== null && title.trim().length > 0) return false;
  return true;
}

function isJsxUnnamedInteractive(el: JsxElement): boolean {
  // PascalCase components are opaque — we cannot know the rendered
  // accessible name, so skip them. Mirrors the labeled-pass scope.
  const tag = el.tagName;
  if (tag.length > 0 && (tag[0] ?? "") >= "A" && (tag[0] ?? "") <= "Z") return false;
  const role = (getJsxAttributeString(el, "role") ?? "").toLowerCase();
  const isInteractive =
    INTERACTIVE_TAGS.has(tag) ||
    (tag === "a" && hasJsxAttribute(el, "href")) ||
    INTERACTIVE_ROLES.has(role);
  if (!isInteractive) return false;
  if (accessibleNameJsx(el) !== null) return false;
  const title = getJsxAttributeString(el, "title");
  if (title !== null && title.trim().length > 0) return false;
  return true;
}

// ---------------------------------------------------------------------------
// Check driver — HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const ancestor of walkHtmlElements(doc)) {
    if (!isHtmlUnnamedInteractive(ancestor)) continue;
    for (const child of ancestor.children) {
      visitHtmlForIcon(child, ancestor.tagName, emit);
    }
  }
}

function visitHtmlForIcon(node: HtmlNode, ancestorTag: string, emit: Emit): void {
  if (node.kind !== "HtmlElement") return;
  // Stop descending into a nested interactive — the outer walk reaches
  // it on its own iteration, with its own name/role evaluation.
  if (isHtmlInteractiveAny(node)) return;
  const classValue = getHtmlAttribute(node, "class");
  const match = detectIconFont(node.tagName, classValue);
  if (match !== null && !isHtmlIconHidden(node)) {
    emit(buildHtmlViolation(node, match, ancestorTag, classValue));
  }
  for (const child of node.children) {
    visitHtmlForIcon(child, ancestorTag, emit);
  }
}

/**
 * Interactive-irrespective-of-name predicate — used as a stop-condition
 * during the descent so we don't pierce a nested interactive boundary.
 * The outer walk visits every element; nested interactives get their
 * own iteration.
 */
function isHtmlInteractiveAny(el: HtmlElement): boolean {
  const tag = el.tagName.toLowerCase();
  const role = (getHtmlAttribute(el, "role") ?? "").toLowerCase();
  return (
    INTERACTIVE_TAGS.has(tag) ||
    (tag === "a" && hasHtmlAttribute(el, "href")) ||
    INTERACTIVE_ROLES.has(role)
  );
}

function buildHtmlViolation(
  icon: HtmlElement,
  match: IconFontMatch,
  ancestorTag: string,
  classValue: string | null,
): {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  classEvidence?: string;
} {
  return {
    severity: "warning",
    location: { filePath: "", line: icon.loc.start.line, column: icon.loc.start.column },
    message: buildMessage(icon.tagName, match, ancestorTag),
    suggestion: buildSuggestion(icon.tagName, match, ancestorTag),
    // Conditional spread per "Ambiguous field shapes are dishonest" —
    // omit when the icon is `<ion-icon>` (no class attribute).
    ...(classValue !== null && classValue.length > 0 ? { classEvidence: classValue } : {}),
  };
}

// ---------------------------------------------------------------------------
// Check driver — JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const ancestor of walkJsxElements(module)) {
    if (!isJsxUnnamedInteractive(ancestor)) continue;
    for (const child of ancestor.children) {
      visitJsxForIcon(child, ancestor.tagName, emit);
    }
  }
}

function visitJsxForIcon(node: JsxNode, ancestorTag: string, emit: Emit): void {
  if (node.kind !== "JsxElement") return;
  if (isJsxInteractiveAny(node)) return;
  const classValue =
    getJsxAttributeString(node, "className") ?? getJsxAttributeString(node, "class");
  const match = detectIconFont(node.tagName, classValue);
  if (match !== null && !isJsxIconHidden(node)) {
    emit(buildJsxViolation(node, match, ancestorTag, classValue));
  }
  for (const child of node.children) {
    visitJsxForIcon(child, ancestorTag, emit);
  }
}

function isJsxInteractiveAny(el: JsxElement): boolean {
  const tag = el.tagName;
  if (tag.length > 0 && (tag[0] ?? "") >= "A" && (tag[0] ?? "") <= "Z") return false;
  const role = (getJsxAttributeString(el, "role") ?? "").toLowerCase();
  return (
    INTERACTIVE_TAGS.has(tag) ||
    (tag === "a" && hasJsxAttribute(el, "href")) ||
    INTERACTIVE_ROLES.has(role)
  );
}

function buildJsxViolation(
  icon: JsxElement,
  match: IconFontMatch,
  ancestorTag: string,
  classValue: string | null,
): {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  classEvidence?: string;
} {
  return {
    severity: "warning",
    location: { filePath: "", line: icon.loc.start.line, column: icon.loc.start.column },
    message: buildMessage(icon.tagName, match, ancestorTag),
    suggestion: buildSuggestion(icon.tagName, match, ancestorTag),
    ...(classValue !== null && classValue.length > 0 ? { classEvidence: classValue } : {}),
  };
}

// ---------------------------------------------------------------------------
// Message / suggestion construction
// ---------------------------------------------------------------------------

function buildMessage(iconTag: string, match: IconFontMatch, ancestorTag: string): string {
  return (
    `<${iconTag} class="${match.token}"> is a ${familyName(match.family)} glyph inside ` +
    `an unnamed <${ancestorTag}> — pair this with the parent's accessible-name fix ` +
    `(semantics/button-name or navigation/link-descriptive-text). Once the parent gets ` +
    `aria-label, the unhidden icon becomes a double-announce risk.`
  );
}

function buildSuggestion(iconTag: string, match: IconFontMatch, ancestorTag: string): string {
  const familyLabel = familyName(match.family);
  return (
    `Add aria-hidden="true" to the <${iconTag} class="${match.token}"> as part of the ` +
    `same edit that adds an accessible name to the <${ancestorTag}>. The ${familyLabel} ` +
    `glyph is purely visual once the parent carries the label, and assistive tech would ` +
    `otherwise announce the private-use-area codepoint alongside the real name. ` +
    `Alternative: set role="presentation" on the <${iconTag}> (equivalent effect for ` +
    `icon-only decorative content). If the glyph is NOT decorative and conveys ` +
    `information the parent label cannot, promote it to a real image ` +
    `(<svg><title>…</title></svg> or <img alt="…">) and leave aria-hidden off.`
  );
}
