/**
 * Rule: aria/labelledby-target-exists
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 * WAI-ARIA 1.2 IDREF definitions: https://www.w3.org/TR/wai-aria-1.2/#idref
 * WAI-ARIA 1.2 IDREF list definitions: https://www.w3.org/TR/wai-aria-1.2/#valuetype_idref_list
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags ARIA IDREF / IDREF-list attributes whose tokens do not resolve
 * to any element's `id` in the same document. A broken reference means
 * the author wrote the attribute but the wire-up is silently dead —
 * screen readers look up the id, miss it, and fall back to whatever
 * name / description the element would have had with no ARIA
 * relationship at all. The failure is invisible to sighted authors who
 * don't run a screen reader during development.
 *
 * Attributes covered (per WAI-ARIA 1.2 §5.4 IDREF value types):
 *
 *   - aria-labelledby   (IDREF list — the element's accessible name)
 *   - aria-describedby  (IDREF list — the element's accessible description)
 *   - aria-controls     (IDREF list — elements whose contents/presence
 *                         this control affects, e.g. a disclosure trigger
 *                         pointing at the panel it toggles)
 *   - aria-owns         (IDREF list — flattens descendants that aren't
 *                         DOM children into the accessibility tree)
 *   - aria-flowto       (IDREF list — recommended reading order override)
 *   - aria-errormessage (IDREF — points at the element holding the
 *                         error text for this input)
 *
 * The IDREF-list attributes (aria-labelledby, aria-describedby,
 * aria-controls, aria-owns, aria-flowto) accept a space-separated list
 * of ids. Each token must resolve independently; one broken token in
 * an otherwise valid list is still a broken link.
 *
 * Scope notes:
 *
 *   1. Document-scoped. Both the reference and the target must live in
 *      the same file. Cross-file id references via bundlers / includes
 *      / SSR are impossible to verify statically — the agent reading
 *      the full repo can check those, we cannot.
 *
 *   2. Case-sensitive match, mirroring the HTML id contract
 *      (`document.getElementById` is case-sensitive per the DOM spec).
 *
 *   3. Empty-string attribute (`aria-labelledby=""`) emits a warning,
 *      not an error. It's syntactically present but semantically
 *      useless — authorial intent is ambiguous (did they mean to blank
 *      it deliberately to null out an inherited reference? did they
 *      forget to fill it in?), so we surface rather than escalate.
 *
 *   4. Expression values in JSX (`aria-labelledby={someId}`) cannot be
 *      statically verified — the identifier might resolve to any
 *      string at runtime. We downgrade these to `info`, cite the raw
 *      expression in the message, and let the agent read the binding.
 *
 *   5. Spread attributes (`{...props}`) pass through without inspection.
 *      The ARIA attributes might land on the element via spread, or
 *      might not. We don't guess.
 *
 *   6. Sibling-conditional rendering (e.g. a React `aria-controls`
 *      pointing at a panel rendered only when open) gets no special
 *      case. If the id literal doesn't appear as an `id=` in the same
 *      file, we flag — the agent reads the file and decides whether
 *      the target is conditionally rendered. Per the AI-first consumer
 *      model, guessing "probably conditional" would be exactly the
 *      heuristic-suppression the project bans.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttribute,
  hasHtmlAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, TsxModule } from "../../types/ast.ts";

/** The six ARIA IDREF / IDREF-list attributes in WAI-ARIA 1.2. */
const IDREF_ATTRS = [
  "aria-labelledby",
  "aria-describedby",
  "aria-controls",
  "aria-owns",
  "aria-flowto",
  "aria-errormessage",
] as const;
type IdrefAttr = (typeof IDREF_ATTRS)[number];

/** The five IDREF-list attributes. `aria-errormessage` is IDREF (single). */
const IDREF_LIST_ATTRS: ReadonlySet<string> = new Set([
  "aria-labelledby",
  "aria-describedby",
  "aria-controls",
  "aria-owns",
  "aria-flowto",
]);

export const rule = defineRule({
  id: "aria/labelledby-target-exists",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "ARIA IDREF attributes (aria-labelledby, aria-describedby, aria-controls, aria-owns, aria-flowto, aria-errormessage) must reference existing element ids in the same document.",
    rationale:
      "WCAG 4.1.2 requires that the name, role, and states of UI components be programmatically determinable. aria-labelledby and aria-describedby ARE the programmatic name and description for the elements that set them; aria-controls, aria-owns, aria-flowto and aria-errormessage wire up relationships that assistive tech walks to expose state. When the referenced id does not exist in the document, the lookup fails silently — the screen reader falls back to the next naming source as if the attribute were never written. Authors who don't run a screen reader during development have no visible signal that the wire-up is dead, which is why this class of bug ships to production in widely-used component libraries. A broken token in an IDREF list is the same silent failure at finer granularity.",
    goodExample:
      '<h2 id="billing-heading">Billing</h2>\n<section aria-labelledby="billing-heading">…</section>',
    badExample:
      '<h2 id="billing-title">Billing</h2>\n<section aria-labelledby="billing-heading">…</section>',
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#idref",
      "https://www.w3.org/TR/wai-aria-1.2/#valuetype_idref_list",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-labelledby",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-describedby",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-controls",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
      return;
    }
    if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Severity = "error" | "warning" | "info";
type Emit = (v: {
  severity: Severity;
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  const ids = collectHtmlIds(doc);
  for (const el of walkHtmlElements(doc)) {
    for (const attr of IDREF_ATTRS) {
      if (!hasHtmlAttribute(el, attr)) continue;
      const raw = getHtmlAttribute(el, attr);
      evaluateLiteral({
        tagName: el.tagName.toLowerCase(),
        attr,
        raw: raw ?? "",
        loc: el.loc.start,
        ids,
        emit,
      });
    }
  }
}

function collectHtmlIds(doc: HtmlDocument): Set<string> {
  const ids = new Set<string>();
  for (const el of walkHtmlElements(doc)) {
    const id = getHtmlAttribute(el, "id");
    if (id !== null && id.length > 0) ids.add(id);
  }
  return ids;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  const ids = collectJsxIds(module);
  for (const el of walkJsxElements(module)) {
    for (const attr of IDREF_ATTRS) {
      const node = getJsxAttribute(el, attr);
      if (node === null) continue;
      const tagName = el.tagName;
      const loc = el.loc.start;
      if (node.value === null) {
        // Shorthand `aria-labelledby` — JSX allows this and it coerces to
        // `aria-labelledby="true"` at runtime, which is never a valid id.
        emit(buildShorthandViolation({ tagName, attr, loc }));
        continue;
      }
      if (node.value.kind === "StringLiteral") {
        evaluateLiteral({
          tagName,
          attr,
          raw: node.value.value,
          loc,
          ids,
          emit,
        });
        continue;
      }
      // Expression value — we can't statically resolve the id. Surface as
      // info so the agent reads the binding.
      emit(buildDynamicNote({ tagName, attr, raw: node.value.raw, loc }));
    }
  }
}

function collectJsxIds(module: TsxModule): Set<string> {
  const ids = new Set<string>();
  for (const el of walkJsxElements(module)) {
    const idAttr = getJsxAttribute(el, "id");
    if (idAttr?.value?.kind !== "StringLiteral") continue;
    const id = idAttr.value.value;
    if (id.length > 0) ids.add(id);
  }
  return ids;
}

// ---------------------------------------------------------------------------
// Literal evaluation (shared between HTML and JSX string-literal values)
// ---------------------------------------------------------------------------

interface LiteralCtx {
  readonly tagName: string;
  readonly attr: IdrefAttr;
  readonly raw: string;
  readonly loc: { line: number; column: number };
  readonly ids: ReadonlySet<string>;
  readonly emit: Emit;
}

function evaluateLiteral(c: LiteralCtx): void {
  if (c.raw.length === 0) {
    c.emit(buildEmptyViolation(c));
    return;
  }
  const tokens = c.raw.split(/\s+/).filter((t) => t.length > 0);
  if (tokens.length === 0) {
    // Whitespace-only value — same "present but useless" failure mode as
    // the empty-string case.
    c.emit(buildEmptyViolation(c));
    return;
  }
  if (!IDREF_LIST_ATTRS.has(c.attr) && tokens.length > 1) {
    // aria-errormessage is IDREF (single). Multiple whitespace-separated
    // tokens are a shape error; only the first is consulted at runtime.
    c.emit(buildMultipleTokensViolation(c, tokens));
    return;
  }
  const missing = tokens.filter((t) => !c.ids.has(t));
  if (missing.length === 0) return;
  c.emit(buildMissingViolation(c, tokens, missing));
}

// ---------------------------------------------------------------------------
// Violation builders
// ---------------------------------------------------------------------------

function buildEmptyViolation(c: LiteralCtx): Parameters<Emit>[0] {
  return {
    severity: "warning",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} ${c.attr}=""> is empty — the attribute is present but names no target, so it contributes no accessible ${nameOrRelation(c.attr)}.`,
    suggestion: `Either remove ${c.attr} entirely, or set it to the id of the element that provides the ${nameOrRelation(c.attr)} (${exampleShape(c.attr)}).`,
  };
}

function buildShorthandViolation(c: {
  tagName: string;
  attr: IdrefAttr;
  loc: { line: number; column: number };
}): Parameters<Emit>[0] {
  return {
    severity: "error",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} ${c.attr}> is used as a shorthand attribute (no value) — in JSX this coerces to \`${c.attr}="true"\`, which is never a valid id reference.`,
    suggestion: `Give ${c.attr} an explicit id reference (${exampleShape(c.attr)}), or remove the attribute if no target exists.`,
  };
}

function buildMissingViolation(
  c: LiteralCtx,
  tokens: readonly string[],
  missing: readonly string[],
): Parameters<Emit>[0] {
  const allBroken = missing.length === tokens.length;
  const isList = IDREF_LIST_ATTRS.has(c.attr);
  const header = allBroken
    ? `<${c.tagName} ${c.attr}="${c.raw}"> references id${plural(missing)} ${quoteList(missing)}, but no element in this file has ${thatMatchingId(missing)}.`
    : `<${c.tagName} ${c.attr}="${c.raw}"> has ${missing.length} broken token${plural(missing)} (${quoteList(missing)}) — the remaining token${plural(tokens.slice(0, tokens.length - missing.length))} resolve${tokens.length - missing.length === 1 ? "s" : ""}, but a broken token in an IDREF list is still a silent wire-up failure for that reference.`;
  const nearestHints = buildNearestHints(missing, c.ids);
  const fixPath = isList
    ? `Either add ${missing.length === 1 ? "an element with" : "elements with"} ${idList(missing)} to the same file, or ${nearestHints.length > 0 ? `correct the token${plural(missing)} (${nearestHints})` : `fix the reference${plural(missing)} to point at an id that exists`}.`
    : `Either add an element with ${idList(missing)} to the same file, or ${nearestHints.length > 0 ? `correct the reference (${nearestHints})` : `change ${c.attr} to point at an existing id`}.`;
  return {
    severity: "error",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: header,
    suggestion: `${fixPath} Cross-file references (ids rendered by other components or templates) are out of scope for this check — if the target lives in a sibling file and this wire-up is verified at the integration level, use a \`{/* ra11y-disable aria/labelledby-target-exists */}\` or \`<!-- ra11y-disable aria/labelledby-target-exists -->\` comment to suppress at the call site.`,
  };
}

function buildMultipleTokensViolation(
  c: LiteralCtx,
  tokens: readonly string[],
): Parameters<Emit>[0] {
  const first = tokens[0] ?? "";
  const rest = tokens.slice(1);
  return {
    severity: "error",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} ${c.attr}="${c.raw}"> — ${c.attr} is IDREF (single value) per WAI-ARIA 1.2, but the value contains ${tokens.length} whitespace-separated tokens. Only "${first}" will be consulted at runtime; ${quoteList(rest)} ${rest.length === 1 ? "is" : "are"} ignored.`,
    suggestion: `Pick the one id you mean — likely the element holding the error text for this control — and drop the rest (e.g. ${c.attr}="${first}"). If you meant to name multiple related elements, use aria-describedby instead (which does accept an IDREF list).`,
  };
}

function buildDynamicNote(c: {
  tagName: string;
  attr: IdrefAttr;
  raw: string;
  loc: { line: number; column: number };
}): Parameters<Emit>[0] {
  return {
    severity: "info",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} ${c.attr}=${c.raw}> uses a JSX expression — the scanner cannot statically verify that the resolved id ${IDREF_LIST_ATTRS.has(c.attr) ? "or ids exist" : "exists"} in the rendered DOM.`,
    suggestion: `Verify at the binding site that ${c.raw} resolves to ${IDREF_LIST_ATTRS.has(c.attr) ? "a space-separated list of ids, each of which" : "an id that"} actually renders on the page. Common pattern: derive the id from a React \`useId()\` call and render both the target element and the reference from the same hook value so they stay in lockstep.`,
  };
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function plural<T>(items: readonly T[]): string {
  return items.length === 1 ? "" : "s";
}

function quoteList(items: readonly string[]): string {
  return items.map((t) => `"${t}"`).join(", ");
}

function idList(items: readonly string[]): string {
  return items.map((t) => `id="${t}"`).join(" or ");
}

function thatMatchingId(missing: readonly string[]): string {
  return missing.length === 1 ? "that id" : "any of those ids";
}

function nameOrRelation(attr: IdrefAttr): string {
  switch (attr) {
    case "aria-labelledby":
      return "name";
    case "aria-describedby":
      return "description";
    case "aria-errormessage":
      return "error message";
    case "aria-controls":
    case "aria-owns":
    case "aria-flowto":
      return "relationship";
  }
}

function exampleShape(attr: IdrefAttr): string {
  if (IDREF_LIST_ATTRS.has(attr)) {
    return `e.g. ${attr}="heading-id" or ${attr}="heading-id description-id" for a space-separated list`;
  }
  return `e.g. ${attr}="error-msg-id"`;
}

/**
 * Produces a short "did you mean X?" hint for each broken token, when an
 * existing id is within Levenshtein distance 2. The hint composes into
 * the suggestion text so the agent's next read is a single fix. The
 * typical typo-distance bound matches what we use in
 * `forms/label-for-id-mismatch`.
 */
function buildNearestHints(missing: readonly string[], ids: ReadonlySet<string>): string {
  const pairs: string[] = [];
  for (const m of missing) {
    const nearest = findNearestId(m, ids);
    if (nearest !== null) pairs.push(`did you mean "${nearest}" instead of "${m}"?`);
  }
  return pairs.join("; ");
}

function findNearestId(target: string, ids: ReadonlySet<string>): string | null {
  let best: string | null = null;
  let bestDist = Number.POSITIVE_INFINITY;
  for (const id of ids) {
    const d = levenshtein(target, id);
    if (d < bestDist) {
      bestDist = d;
      best = id;
    }
  }
  const MAX_TYPO_DISTANCE = 2;
  return bestDist <= MAX_TYPO_DISTANCE ? best : null;
}

/** Standard Levenshtein edit distance. O(n*m) space and time. */
function levenshtein(a: string, b: string): number {
  if (a === b) return 0;
  if (a.length === 0) return b.length;
  if (b.length === 0) return a.length;
  const m = a.length;
  const n = b.length;
  let prev = new Array<number>(n + 1);
  let curr = new Array<number>(n + 1);
  for (let j = 0; j <= n; j += 1) prev[j] = j;
  for (let i = 1; i <= m; i += 1) {
    curr[0] = i;
    for (let j = 1; j <= n; j += 1) {
      const cost = a.charCodeAt(i - 1) === b.charCodeAt(j - 1) ? 0 : 1;
      const del = (prev[j] ?? 0) + 1;
      const ins = (curr[j - 1] ?? 0) + 1;
      const sub = (prev[j - 1] ?? 0) + cost;
      curr[j] = Math.min(del, ins, sub);
    }
    const tmp = prev;
    prev = curr;
    curr = tmp;
  }
  return prev[n] ?? 0;
}
