/**
 * Rule: aria/popover-trigger-missing-haspopup
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links, and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Fires on a Bootstrap-style popover or tooltip trigger — an element
 * carrying `data-toggle="popover"` / `data-toggle="tooltip"`
 * (Bootstrap 4 / generic) or `data-bs-toggle="popover"` /
 * `data-bs-toggle="tooltip"` (Bootstrap 5) — that is missing the ARIA
 * properties the WAI-ARIA Authoring Practices require to make the
 * trigger's relationship with the popup announceable:
 *
 *   - **Popover triggers** (`value="popover"`): a popover is an
 *     additional surface that opens on activation; APG models it as a
 *     dialog-shaped widget. The trigger must declare `aria-haspopup`
 *     so AT announces "popup" (or "dialog") and the user knows another
 *     surface is reachable on activation. Without it, AT announces
 *     "Help, button" with no signal that activation reveals additional
 *     content. Emit when `aria-haspopup` is absent.
 *   - **Tooltip triggers** (`value="tooltip"`): a tooltip provides an
 *     accessible *description* (not name) for the trigger. The
 *     programmatic relationship is established by `aria-describedby`
 *     pointing at the tooltip element id, OR by Bootstrap's
 *     library-specific behavior of reading the trigger's `title`
 *     attribute as the tooltip's text content (Bootstrap then renders
 *     the tooltip and wires the relationship at runtime). Emit when
 *     BOTH `aria-describedby` and `title` are absent — without either,
 *     the trigger has no programmatic description channel and the
 *     tooltip text never reaches AT.
 *
 * Coordination with sibling rules:
 *
 *   - `aria/expanded-on-disclosure` excludes `popover` and `tooltip`
 *     from its `DISCLOSURE_TOGGLE_VALUES` set on purpose — those widget
 *     shapes use `aria-haspopup` / `aria-describedby`, not
 *     `aria-expanded`. This rule fills the gap that left.
 *   - `aria/dropdown-toggle-triple-aria-missing` fires only on
 *     `value="dropdown"` (a different APG widget, the menu-button
 *     pattern). This rule fires only on `value="popover"` /
 *     `value="tooltip"` — no overlap.
 *   - `tooltip/dismissable` (WCAG 1.4.13) fires when an interactive
 *     element carries `title="…"` and that title is the *displayed
 *     content* of a browser-native tooltip. When a Bootstrap tooltip
 *     trigger uses `title` as the *content channel for the JS-rendered
 *     tooltip*, the dismissable rule downgrades severity (via the
 *     `tooltip_js_enhancer_present` `couldBeWrongBecause` code) — the
 *     two rules are on different axes (1.4.13 dismissability vs 4.1.2
 *     name/role/value) and can co-fire on the same element when
 *     warranted.
 *
 * Predicate-shape exemptions (deterministic from in-file evidence):
 *
 *   - When a popover trigger ALREADY carries `aria-haspopup` of any
 *     value, the rule abstains. The APG-canonical value is `"dialog"`,
 *     but accepting any value avoids fighting the agent over a
 *     judgement call ("dialog" vs "menu" vs "true") that does not
 *     belong on this rule.
 *   - When a tooltip trigger carries either `aria-describedby` or
 *     `title`, the rule abstains. Either channel is sufficient to
 *     establish the programmatic description link.
 *   - PascalCase JSX components (composed widgets like `<Tooltip>`)
 *     are skipped — the underlying host element is opaque to the
 *     scanner per "Don't duplicate capability the agent already has."
 */

import { defineRule } from "../../api/plugin.ts";
import {
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

export const rule = defineRule({
  id: "aria/popover-trigger-missing-haspopup",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "warning",
  scope: "node",
  // The fix is one or two attribute additions per finding
  // (`aria-haspopup="dialog"` on popovers; `aria-describedby="<id>"` on
  // tooltips, with the id naming the tooltip element). The
  // `aria-describedby` value names a specific id the scanner cannot
  // determine from the trigger alone (the tooltip body is rendered at
  // runtime by Bootstrap), so this is `verify-in-source` rather than a
  // mechanical edit. Per the AI-first consumer model
  // ("Per-call shape must agree with per-class plan tally"), we tag
  // `verify-in-source` so `plan.fixesByClass.mechanical` does not
  // promise an apply-now edit the per-call surface cannot honor.
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      'Bootstrap-style popover/tooltip trigger (data-*-toggle="popover" or "tooltip") missing the ARIA properties (aria-haspopup for popover; aria-describedby or title for tooltip) needed to make the trigger-popup relationship programmatically determinable.',
    rationale:
      'WCAG 4.1.2 requires that a UI component\'s name, role, and properties be programmatically determinable. The WAI-ARIA Authoring Practices model popovers as dialog-shaped widgets (https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/) — the trigger must declare `aria-haspopup` so AT announces that activation reveals an additional surface. Tooltips are description-shaped (https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/) — the programmatic link from trigger to tooltip text is established via `aria-describedby` pointing at the tooltip element id, OR (with Bootstrap specifically) via the trigger\'s `title` attribute, which the library copies into the tooltip body and wires at runtime. Bootstrap-style triggers — both `data-toggle="popover"|"tooltip"` (v4 / generic) and `data-bs-toggle="popover"|"tooltip"` (v5) — are widely shipped without those properties; the visual UI works for sighted users (hover and click reveal the popup), but AT users hear "Help, button" with no signal that there is a popup to open or what it says. This rule fires on the data-attribute-shape (deterministic in-file evidence), gated per-value: popover triggers without `aria-haspopup` emit; tooltip triggers without both `aria-describedby` AND `title` emit. The sibling rule `aria/expanded-on-disclosure` deliberately excludes the popover/tooltip values; this rule fills that gap.',
    goodExample: `<button type="button"
        class="btn"
        data-bs-toggle="popover"
        data-bs-content="Saves the draft to your account."
        aria-haspopup="dialog"
        aria-controls="save-popover">
  Save
</button>
<button type="button"
        class="btn"
        data-bs-toggle="tooltip"
        title="Permanently delete this record">
  Delete
</button>`,
    badExample: `<button type="button" data-bs-toggle="popover" data-bs-content="Help text">
  ?
</button>
<a href="#" data-toggle="tooltip">Hover me</a>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links, and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/",
      "https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-haspopup",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-describedby",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
      return;
    }
    if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

interface Emission {
  readonly severity: "warning";
  readonly location: { readonly filePath: string; readonly line: number; readonly column: number };
  readonly message: string;
  readonly suggestion: string;
}
type Emit = (v: Emission) => void;

type WidgetKind = "popover" | "tooltip";

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    const kind = htmlWidgetKind(el);
    if (kind === null) continue;
    if (htmlIsCompliant(el, kind)) continue;
    emit({
      severity: "warning",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: buildMessage(el.tagName, kind),
      suggestion: buildSuggestion(el.tagName, kind),
    });
  }
}

function htmlWidgetKind(el: HtmlElement): WidgetKind | null {
  for (const attr of el.attributes) {
    if (!isToggleAttributeName(attr.name.toLowerCase())) continue;
    const kind = matchWidgetValue(attr.value);
    if (kind !== null) return kind;
  }
  return null;
}

function htmlIsCompliant(el: HtmlElement, kind: WidgetKind): boolean {
  if (kind === "popover") return hasHtmlAttribute(el, "aria-haspopup");
  // tooltip: either aria-describedby or title is sufficient.
  return hasHtmlAttribute(el, "aria-describedby") || hasHtmlAttribute(el, "title");
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const el of walkJsxElements(module)) {
    if (isJsxPascalCase(el.tagName)) continue;
    const kind = jsxWidgetKind(el);
    if (kind === null) continue;
    if (jsxIsCompliant(el, kind)) continue;
    emit({
      severity: "warning",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: buildMessage(el.tagName, kind),
      suggestion: buildSuggestion(el.tagName, kind),
    });
  }
}

function jsxWidgetKind(el: JsxElement): WidgetKind | null {
  for (const attr of el.attributes) {
    const lowered = attr.name.toLowerCase();
    if (!isToggleAttributeName(lowered)) continue;
    if (!attr.value || attr.value.kind !== "StringLiteral") continue;
    const kind = matchWidgetValue(attr.value.value);
    if (kind !== null) return kind;
  }
  return null;
}

function jsxIsCompliant(el: JsxElement, kind: WidgetKind): boolean {
  if (kind === "popover") return hasJsxAttribute(el, "aria-haspopup");
  return hasJsxAttribute(el, "aria-describedby") || hasJsxAttribute(el, "title");
}

function isJsxPascalCase(tag: string): boolean {
  const first = tag[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/**
 * Accepts `data-toggle` (Bootstrap 4 / generic) and any
 * `data-<prefix>-toggle` form (Bootstrap 5 ships `data-bs-toggle`;
 * other libraries follow the same suffix convention). Suffix-based,
 * not framework-prefixed — per CLAUDE.md §14, detect the shape, not
 * the framework. Mirrors the predicate in
 * `aria/dropdown-toggle-triple-aria-missing` and
 * `aria/expanded-on-disclosure` so the three rules agree on the
 * attribute-name surface they fire from.
 */
function isToggleAttributeName(lowered: string): boolean {
  if (lowered === "data-toggle") return true;
  if (!lowered.startsWith("data-")) return false;
  return lowered.endsWith("-toggle");
}

/**
 * Returns `"popover"` or `"tooltip"` when the attribute value contains
 * the matching token (case-insensitive, whitespace/comma-tokenized) —
 * mirrors the tolerance applied by the dropdown-toggle-triple sibling
 * and the disclosure rule. When both tokens are present (rare —
 * observed only in hand-rolled libraries), `"popover"` wins because
 * the popover predicate is the stricter of the two.
 */
function matchWidgetValue(raw: string | null): WidgetKind | null {
  if (raw === null) return null;
  let sawTooltip = false;
  for (const token of raw.split(/[\s,]+/)) {
    const lowered = token.trim().toLowerCase();
    if (lowered === "popover") return "popover";
    if (lowered === "tooltip") sawTooltip = true;
  }
  return sawTooltip ? "tooltip" : null;
}

function buildMessage(tagName: string, kind: WidgetKind): string {
  if (kind === "popover") {
    return (
      `<${tagName}> is a popover trigger (data-*-toggle="popover") but is missing ` +
      `aria-haspopup — assistive tech will announce a button with no signal that ` +
      `activation reveals an additional dialog-shaped surface.`
    );
  }
  return (
    `<${tagName}> is a tooltip trigger (data-*-toggle="tooltip") but has neither ` +
    `aria-describedby nor title — there is no programmatic description channel for ` +
    `the tooltip text to reach assistive tech.`
  );
}

function buildSuggestion(tagName: string, kind: WidgetKind): string {
  if (kind === "popover") {
    return (
      `Add aria-haspopup="dialog" to the <${tagName}> (the WAI-ARIA Authoring ` +
      `Practices model popovers as dialog-shaped widgets — see ` +
      `https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/). When the popover ` +
      `region has a stable id, also add aria-controls="<popover-id>" so AT can ` +
      `navigate to the controlled region. If this control is not actually a ` +
      `popover trigger, suppress with a source-level pragma ` +
      `(e.g. <!-- ra11y-disable aria/popover-trigger-missing-haspopup -->) so the ` +
      `next scan dismisses it deterministically.`
    );
  }
  return (
    `Add aria-describedby="<tooltip-id>" pointing at the tooltip element ` +
    `(rendered with role="tooltip"), OR add a title attribute carrying the ` +
    `tooltip text — Bootstrap reads title as the tooltip content and wires the ` +
    `relationship at runtime. See https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/ ` +
    `for the canonical tooltip pattern. Note: if you add title and this trigger ` +
    `does not actually have a JS tooltip enhancer wired up, tooltip/dismissable ` +
    `(WCAG 1.4.13) will fire on the bare title — verify the runtime widget is ` +
    `active. If this control is not actually a tooltip trigger, suppress with a ` +
    `source-level pragma (e.g. <!-- ra11y-disable aria/popover-trigger-missing-haspopup -->) ` +
    `so the next scan dismisses it deterministically.`
  );
}
