/**
 * Rule: aria/progressbar-value-range
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 * ARIA authoring practices — progressbar: https://www.w3.org/WAI/ARIA/apg/patterns/meter/
 * WAI-ARIA 1.2 progressbar role: https://www.w3.org/TR/wai-aria-1.2/#progressbar
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags `role="progressbar"` elements (and native `<progress>`) whose
 * value exposure is broken in one of these ways:
 *
 *   1. Missing `aria-valuenow` on a determinate progressbar. Without it,
 *      assistive tech announces the role but cannot convey progress.
 *      The spec allows `aria-valuenow` to be omitted only when the
 *      current value is unknown (indeterminate progressbar) — we detect
 *      that signal via `aria-busy="true"` or via the native `<progress>`
 *      element with no `value` attribute.
 *   2. Invalid bounds: `aria-valuemin > aria-valuemax`. The scale is
 *      upside-down; any `aria-valuenow` the author picks is meaningless.
 *   3. Out-of-range `aria-valuenow`: below `aria-valuemin` or above
 *      `aria-valuemax`. Assistive tech reads the value as written,
 *      producing announcements like "150%" or "-3 of 100".
 *   4. Non-numeric string literal on a numeric value attribute
 *      (`aria-valuenow="fifty"`). The WAI-ARIA 1.2 value descriptor is
 *      `<number>`; strings that don't parse as numbers violate the
 *      contract.
 *
 * Dynamic values (JSX expression attributes like `aria-valuenow={pct}`)
 * cannot be statically verified. The rule downgrades these to an info
 * note that cites the raw expression — the agent reads the source and
 * decides. Spreads (`{...props}`) are handled the same way.
 *
 * Indeterminate progressbar: both the ARIA spec and the HTML5
 * `<progress>` element explicitly permit omitting the current value
 * when progress is unknown. The rule honors that:
 *   - `role="progressbar"` + `aria-busy="true"` and no `aria-valuenow` →
 *     treated as indeterminate; no violation for the missing attribute.
 *   - `<progress>` with no `value` attribute → treated as indeterminate.
 *
 * This rule does NOT flag the absence of `aria-valuemin` / `aria-valuemax`
 * alone. WAI-ARIA 1.2 defaults them to 0 and 100 respectively when
 * omitted (on progressbar), so a bare `aria-valuenow="30"` is valid.
 * Out-of-range checks use those defaults when the bounds are omitted.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  JsxAttribute,
  JsxElement,
  TsxModule,
} from "../../types/ast.ts";

/** Attribute name → human label for error messages. */
const VALUE_ATTRS = ["aria-valuenow", "aria-valuemin", "aria-valuemax"] as const;
type ValueAttr = (typeof VALUE_ATTRS)[number];

export const rule = defineRule({
  id: "aria/progressbar-value-range",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Progressbars (role='progressbar' or native <progress>) must declare coherent aria-valuenow / aria-valuemin / aria-valuemax values so assistive tech can announce progress.",
    rationale:
      "WCAG 4.1.2 requires that the value of a user-interface component be programmatically determinable. A progressbar with no aria-valuenow is announced as 'progress bar, (blank)'. A progressbar with aria-valuenow=150 and aria-valuemax=100 is announced as '150 percent' — a meaningless reading that confuses users and defeats the purpose of the widget. Widely-used component libraries (Bootstrap's .progress pattern) ship examples with both shapes; the scanner catches them because the invariant is statically checkable against literal attribute values.",
    goodExample:
      '<div role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" aria-label="Upload"></div>',
    badExample: '<div role="progressbar" aria-valuenow="150" aria-valuemax="100"></div>',
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#progressbar",
      "https://www.w3.org/WAI/ARIA/apg/patterns/meter/",
      "https://html.spec.whatwg.org/multipage/form-elements.html#the-progress-element",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Severity = "error" | "warning" | "info";
type Loc = { line: number; column: number };
type Emit = (v: {
  severity: Severity;
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

/**
 * Parsed numeric value for one of the three value attributes. `"literal"`
 * carries a number we can reason about; `"invalid"` is a string literal
 * the author wrote that isn't a number; `"dynamic"` is a JSX expression
 * we can't statically read; `"absent"` is attribute not present.
 */
type ValueRead =
  | { readonly kind: "literal"; readonly value: number; readonly raw: string }
  | { readonly kind: "invalid"; readonly raw: string }
  | { readonly kind: "dynamic"; readonly raw: string }
  | { readonly kind: "absent" };

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    const kind = htmlProgressbarKind(el);
    if (!kind) continue;
    const isNative = kind === "native";
    evaluate(
      {
        tagName: el.tagName.toLowerCase(),
        isNativeProgress: isNative,
        loc: el.loc.start,
        valuenow: isNative
          ? readHtmlValueAttr(el, "value")
          : readHtmlValueAttr(el, "aria-valuenow"),
        valuemin: isNative ? { kind: "absent" } : readHtmlValueAttr(el, "aria-valuemin"),
        valuemax: isNative ? readHtmlValueAttr(el, "max") : readHtmlValueAttr(el, "aria-valuemax"),
        ariaBusy: getHtmlAttribute(el, "aria-busy")?.toLowerCase() === "true",
        hasSpread: false,
      },
      emit,
    );
  }
}

function htmlProgressbarKind(el: HtmlElement): "role" | "native" | null {
  const tag = el.tagName.toLowerCase();
  if (tag === "progress") return "native";
  const role = getHtmlAttribute(el, "role")?.toLowerCase();
  if (role === "progressbar") return "role";
  return null;
}

function readHtmlValueAttr(el: HtmlElement, name: string): ValueRead {
  if (!hasHtmlAttribute(el, name)) return { kind: "absent" };
  const raw = getHtmlAttribute(el, name);
  if (raw === null || raw.trim().length === 0) return { kind: "invalid", raw: raw ?? "" };
  return parseNumericLiteral(raw.trim());
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const el of walkJsxElements(module)) {
    const kind = jsxProgressbarKind(el);
    if (!kind) continue;
    const isNative = kind === "native";
    evaluate(
      {
        tagName: el.tagName,
        isNativeProgress: isNative,
        loc: el.loc.start,
        valuenow: isNative ? readJsxValueAttr(el, "value") : readJsxValueAttr(el, "aria-valuenow"),
        valuemin: isNative ? { kind: "absent" } : readJsxValueAttr(el, "aria-valuemin"),
        valuemax: isNative ? readJsxValueAttr(el, "max") : readJsxValueAttr(el, "aria-valuemax"),
        ariaBusy: getJsxAttributeString(el, "aria-busy")?.toLowerCase() === "true",
        hasSpread: el.hasSpreadProps,
      },
      emit,
    );
  }
}

function jsxProgressbarKind(el: JsxElement): "role" | "native" | null {
  if (el.tagName === "progress") return "native";
  const role = getJsxAttributeString(el, "role")?.toLowerCase();
  if (role === "progressbar") return "role";
  return null;
}

function readJsxValueAttr(el: JsxElement, name: string): ValueRead {
  const attr = getJsxAttribute(el, name);
  if (!attr) return { kind: "absent" };
  return readJsxAttrValue(attr);
}

function readJsxAttrValue(attr: JsxAttribute): ValueRead {
  if (attr.value === null) return { kind: "invalid", raw: "" };
  if (attr.value.kind === "StringLiteral") {
    if (attr.value.value.trim().length === 0) return { kind: "invalid", raw: attr.value.value };
    return parseNumericLiteral(attr.value.value.trim());
  }
  // Expression — strip one pair of outer braces, check for a pure numeric
  // literal (e.g. {50}, {-3.14}). Anything else is dynamic.
  const inner = stripBraces(attr.value.raw).trim();
  const literal = parseNumericLiteral(inner);
  if (literal.kind === "literal") return literal;
  return { kind: "dynamic", raw: attr.value.raw };
}

function stripBraces(raw: string): string {
  let out = raw;
  if (out.startsWith("{")) out = out.slice(1);
  if (out.endsWith("}")) out = out.slice(0, -1);
  return out;
}

// ---------------------------------------------------------------------------
// Shared evaluator
// ---------------------------------------------------------------------------

interface Ctx {
  readonly tagName: string;
  readonly isNativeProgress: boolean;
  readonly loc: Loc;
  /**
   * Unified "current value" — `aria-valuenow` for role=progressbar,
   * `value` for native <progress>.
   */
  readonly valuenow: ValueRead;
  /** `aria-valuemin`; unused for native `<progress>` (always absent). */
  readonly valuemin: ValueRead;
  /** `aria-valuemax` for role=progressbar, `max` for native <progress>. */
  readonly valuemax: ValueRead;
  readonly ariaBusy: boolean;
  readonly hasSpread: boolean;
}

function evaluate(c: Ctx, emit: Emit): void {
  emitInvalidLiterals(c, emit);
  emitMissingOrDynamicValuenow(c, emit);
  emitBoundsAndRange(c, emit);
}

/** Flags any of the three value attributes that carry a non-numeric string. */
function emitInvalidLiterals(c: Ctx, emit: Emit): void {
  for (const name of VALUE_ATTRS) {
    const read = c[attrField(name)];
    if (read.kind === "invalid") {
      emit(buildInvalidLiteralViolation(c, displayAttrName(c, name), read.raw));
    }
  }
}

/**
 * Handles the three mutually exclusive states of the current-value
 * attribute: absent (missing or indeterminate), dynamic (JSX expression —
 * info note), or a literal we can reason about (handled downstream).
 */
function emitMissingOrDynamicValuenow(c: Ctx, emit: Emit): void {
  if (c.valuenow.kind === "dynamic") {
    emit(buildDynamicNote(c, displayAttrName(c, "aria-valuenow"), c.valuenow.raw));
    return;
  }
  if (c.valuenow.kind !== "absent") return;
  // Indeterminate exemption: aria-busy="true" (role=progressbar) or a
  // native <progress> with no `value` attribute.
  if (c.ariaBusy || c.isNativeProgress) return;
  if (c.hasSpread) {
    emit(buildSpreadNote(c));
    return;
  }
  emit(buildMissingValuenowViolation(c));
}

/** Flags inverted bounds and out-of-range literal values. */
function emitBoundsAndRange(c: Ctx, emit: Emit): void {
  const min = c.valuemin.kind === "literal" ? c.valuemin.value : null;
  const max = c.valuemax.kind === "literal" ? c.valuemax.value : null;
  if (min !== null && max !== null && min > max) {
    emit(buildInvalidBoundsViolation(c, min, max));
  }
  if (c.valuenow.kind !== "literal") return;
  // Default scale: ARIA 1.2 progressbar defaults to 0..100 when
  // aria-valuemin / aria-valuemax are omitted. Native <progress>
  // defaults to 0..1 when `max` is omitted (HTML5 spec).
  const effectiveMin = min ?? 0;
  const effectiveMax = max ?? (c.isNativeProgress ? 1 : 100);
  // If the author's explicit bounds are themselves invalid (min>max),
  // skip the range check — the invalid-bounds violation above already
  // carries the signal.
  if (effectiveMin > effectiveMax) return;
  if (c.valuenow.value < effectiveMin) {
    emit(buildBelowMinViolation(c, c.valuenow.value, effectiveMin, min !== null));
    return;
  }
  if (c.valuenow.value > effectiveMax) {
    emit(buildAboveMaxViolation(c, c.valuenow.value, effectiveMax, max !== null));
  }
}

function attrField(name: ValueAttr): "valuenow" | "valuemin" | "valuemax" {
  if (name === "aria-valuenow") return "valuenow";
  if (name === "aria-valuemin") return "valuemin";
  return "valuemax";
}

/**
 * Remaps the ARIA attribute name to the native `<progress>` equivalent
 * when we're inside a native element so error messages cite what the
 * author actually wrote. `aria-valuenow` → `value`, `aria-valuemax` → `max`.
 * `aria-valuemin` is never read on native `<progress>` (no equivalent),
 * but keeping the mapping symmetric costs nothing.
 */
function displayAttrName(c: Ctx, name: string): string {
  if (!c.isNativeProgress) return name;
  if (name === "aria-valuenow") return "value";
  if (name === "aria-valuemax") return "max";
  return name;
}

// ---------------------------------------------------------------------------
// Numeric parsing
// ---------------------------------------------------------------------------

/**
 * Parses an attribute value string as a number per WAI-ARIA's `<number>`
 * descriptor. Accepts integers and decimals (positive, negative, leading
 * sign, leading/trailing whitespace already stripped by the caller).
 * Rejects bare strings like `"fifty"`, empty strings, and scientific
 * notation (`1e2`) — the spec calls for a decimal `<number>`.
 */
function parseNumericLiteral(raw: string): ValueRead {
  if (raw.length === 0) return { kind: "invalid", raw };
  if (!/^-?\d+(?:\.\d+)?$/.test(raw)) return { kind: "invalid", raw };
  const value = Number.parseFloat(raw);
  if (!Number.isFinite(value)) return { kind: "invalid", raw };
  return { kind: "literal", value, raw };
}

// ---------------------------------------------------------------------------
// Violation builders
// ---------------------------------------------------------------------------

function buildInvalidLiteralViolation(c: Ctx, attrName: string, raw: string): Parameters<Emit>[0] {
  const displayValue = raw.length > 0 ? `"${raw}"` : "(empty)";
  return {
    severity: "error",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} ${attrName}=${displayValue}> — ${attrName} expects a number per WAI-ARIA 1.2 (\`<number>\` value descriptor); a non-numeric string is ignored by assistive tech.`,
    suggestion: `Replace ${attrName}=${displayValue} with a numeric literal (e.g. ${attrName}="30") or drive it from a runtime expression that resolves to a number (${suggestJsxExpr(c, attrName)}).`,
  };
}

function buildMissingValuenowViolation(c: Ctx): Parameters<Emit>[0] {
  const boundsNote = describeBoundsForMissing(c);
  const selector = c.isNativeProgress ? `<${c.tagName}>` : `<${c.tagName} role="progressbar">`;
  const fixAttr = displayAttrName(c, "aria-valuenow");
  return {
    severity: "error",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `${selector} is missing ${fixAttr} and is not marked indeterminate — assistive tech announces the progressbar with no current value.`,
    suggestion: `Add ${fixAttr}="<number>" to expose the current progress${boundsNote}. If the progress is genuinely unknown (loading state before the first byte, for example), mark the element indeterminate instead: ${indeterminateHint(c)}.`,
  };
}

function describeBoundsForMissing(c: Ctx): string {
  const min = c.valuemin.kind === "literal" ? c.valuemin.value : null;
  const max = c.valuemax.kind === "literal" ? c.valuemax.value : null;
  const defaultMax = c.isNativeProgress ? 1 : 100;
  if (min !== null && max !== null) return ` within the declared scale (${min}..${max})`;
  if (max !== null) return ` within the declared scale (0..${max})`;
  if (min !== null) return ` within the declared scale (${min}..${defaultMax})`;
  if (c.isNativeProgress) {
    return " (HTML5 <progress> defaults to 0..1 when `max` is omitted)";
  }
  return " (ARIA 1.2 defaults to 0..100 when aria-valuemin/aria-valuemax are omitted)";
}

function indeterminateHint(c: Ctx): string {
  if (c.isNativeProgress) {
    return `remove the \`value\` attribute (<progress> with no value is the native indeterminate form)`;
  }
  return `set aria-busy="true" and omit aria-valuenow`;
}

function buildInvalidBoundsViolation(c: Ctx, min: number, max: number): Parameters<Emit>[0] {
  return {
    severity: "error",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} role="progressbar"> has aria-valuemin=${min} > aria-valuemax=${max} — the scale is inverted and any aria-valuenow is meaningless.`,
    suggestion: `Swap the bounds so aria-valuemin <= aria-valuemax, or drop whichever is wrong. The canonical shape is aria-valuemin="0" aria-valuemax="100" aria-valuenow="<current>".`,
  };
}

function buildBelowMinViolation(
  c: Ctx,
  now: number,
  effectiveMin: number,
  explicitMin: boolean,
): Parameters<Emit>[0] {
  const minSource = explicitMin
    ? `aria-valuemin=${effectiveMin}`
    : `the ARIA 1.2 default minimum of ${effectiveMin}`;
  return {
    severity: "error",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} role="progressbar"> has aria-valuenow=${now} below ${minSource} — assistive tech will announce a negative/out-of-scale value.`,
    suggestion: `Either raise aria-valuenow to >= ${effectiveMin} to match the actual progress, or lower aria-valuemin to ${now} so the scale includes the current value.`,
  };
}

function buildAboveMaxViolation(
  c: Ctx,
  now: number,
  effectiveMax: number,
  explicitMax: boolean,
): Parameters<Emit>[0] {
  const selector = c.isNativeProgress ? `<${c.tagName}>` : `<${c.tagName} role="progressbar">`;
  const maxSource = explicitMax
    ? `aria-valuemax=${effectiveMax}`
    : `the ARIA 1.2 default maximum of ${effectiveMax}`;
  return {
    severity: "error",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `${selector} has aria-valuenow=${now} above ${maxSource} — assistive tech will announce a value past the end of the scale (e.g. "${now} percent").`,
    suggestion: `Either raise aria-valuemax to >= ${now} (the scale needs to include the current value), or reduce aria-valuenow to match the actual progress within 0..${effectiveMax}.`,
  };
}

function buildDynamicNote(c: Ctx, attrName: string, raw: string): Parameters<Emit>[0] {
  return {
    severity: "info",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} ${attrName}=${raw}> uses a JSX expression — the scanner cannot statically verify the numeric value or whether it stays within aria-valuemin/aria-valuemax at runtime.`,
    suggestion: `Verify at the binding site that ${raw} resolves to a finite number within the declared scale. If the expression can exceed the scale, clamp it before passing to the attribute: Math.max(min, Math.min(max, value)).`,
  };
}

function buildSpreadNote(c: Ctx): Parameters<Emit>[0] {
  return {
    severity: "info",
    location: { filePath: "", line: c.loc.line, column: c.loc.column },
    message: `<${c.tagName} role="progressbar"> has no static aria-valuenow but receives {...spread} props — whether the current value is exposed depends on what the caller passes.`,
    suggestion: `If this wrapper component is only consumed by callers that pass aria-valuenow through the spread, this is fine — add {/* ra11y-disable aria/progressbar-value-range */} at the top of the file to silence this info note. Otherwise require callers to pass aria-valuenow explicitly, or set aria-busy={true} when the progress is genuinely indeterminate.`,
  };
}

function suggestJsxExpr(c: Ctx, attrName: string): string {
  return c.isNativeProgress ? `e.g. ${attrName}={progress}` : `e.g. ${attrName}={Math.round(pct)}`;
}
