/**
 * Rule: aria/progressbar-value-range
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Skeleton — detection logic lands in the follow-up commit. The rule
 * will flag role="progressbar" / native <progress> elements with missing
 * or incoherent aria-valuenow / aria-valuemin / aria-valuemax values.
 */

import { defineRule } from "../../api/plugin.ts";

export const rule = defineRule({
  id: "aria/progressbar-value-range",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Progressbars (role='progressbar' or native <progress>) must declare coherent aria-valuenow / aria-valuemin / aria-valuemax values so assistive tech can announce progress.",
    rationale:
      "WCAG 4.1.2 requires that the value of a user-interface component be programmatically determinable. A progressbar with no aria-valuenow is announced as 'progress bar, (blank)'. A progressbar with aria-valuenow=150 and aria-valuemax=100 is announced as '150 percent' — a meaningless reading.",
    goodExample:
      '<div role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" aria-label="Upload"></div>',
    badExample: '<div role="progressbar" aria-valuenow="150" aria-valuemax="100"></div>',
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#progressbar",
      "https://www.w3.org/WAI/ARIA/apg/patterns/meter/",
      "https://html.spec.whatwg.org/multipage/form-elements.html#the-progress-element",
    ],
  },
  check(ctx) {
    // Logic lands in the follow-up commit.
    void ctx;
  },
});
