/**
 * Rule: aria/redundant-role-on-host-element
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined […].
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags `role="X"` that *re-declares* the host element's implicit ARIA
 * role — `<button role="button">`, `<nav role="navigation">`,
 * `<main role="main">`, `<a href role="link">`, `<form role="form">`,
 * `<img alt="…" role="img">`. WAI-ARIA 1.2 §host_general_role names this
 * an antipattern: the explicit role is a no-op against the implicit
 * one, so its presence is dead weight that obscures intent and risks
 * being copied onto an element where it *would* break things (e.g., the
 * author refactors `<button role="button">` to `<a role="button">`,
 * which is the conflicting-role case the sibling rule catches).
 *
 * The companion rule `aria/conflicting-role` flags the *contradictory*
 * cases (`<button role="link">`, `<nav role="main">`). This rule covers
 * the *redundant* cases, which the companion rule deliberately leaves
 * out of scope.
 *
 * Conservative scope — only the unambiguous always-redundant pairs:
 *
 * - `<nav role="navigation">`
 * - `<main role="main">`
 * - `<button role="button">`
 * - `<a href role="link">` (the implicit role is "link" only when href
 *   is present; without href the anchor is a styled container with no
 *   implicit role, so no redundancy)
 * - `<img alt="…" role="img">` (only with non-empty alt; an `<img>`
 *   with `alt=""` has implicit role "presentation", and `role="img"`
 *   on it is a *contradiction* the conflicting-role rule owns — though
 *   that pair is currently outside the conflict matrix too, so static
 *   analysis stays quiet there)
 * - `<form role="form">` (treated as always-redundant — the strict
 *   spec says `<form>` only has implicit role "form" when it has an
 *   accessible name, but the named-form caveat is too subtle for
 *   static analysis and `role="form"` on an unnamed `<form>` is still
 *   an antipattern in practice)
 *
 * Deliberately out of scope:
 *
 * - `<header>` / `<footer>` — implicit role depends on document
 *   position (top-level vs. nested in `<article>`/`<section>`).
 * - `<section role="region">` — implicit role depends on the section
 *   having an accessible name.
 * - Generic / non-host pairs like `<div role="button">` — the host
 *   has no implicit role to be redundant against; this is correct
 *   ARIA augmentation, not redundancy.
 * - Conflicts (`<button role="link">`) — owned by aria/conflicting-role.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlAttribute,
  HtmlDocument,
  HtmlElement,
  JsxAttribute,
  JsxElement,
  TsxModule,
} from "../../types/ast.ts";
import type { FixPaths } from "../../types/violation.ts";

export const rule = defineRule({
  id: "aria/redundant-role-on-host-element",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "warning",
  scope: "node",
  fixClass: "mechanical",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Flags `role` attributes that duplicate the host element's implicit ARIA role (e.g., role='button' on <button>, role='navigation' on <nav>). Redundant roles are dead weight and risk being copy-pasted onto elements where they would break.",
    rationale:
      "Every native HTML element has an implicit ARIA role (per WAI-ARIA 1.2 §host_general_role and the HTML-ARIA mapping). Re-declaring that role with role='X' is a no-op for assistive tech, but it obscures intent and makes future refactors fragile — the author who copies role='button' from a <button> onto an <a> creates a real WCAG 4.1.2 conflict (the conflicting-role rule will catch it, but the redundancy is the gateway). Removing the redundant role keeps the markup honest.",
    goodExample: `<button type="button">Save</button>
<nav aria-label="Primary">…</nav>
<main>…</main>
<a href="/docs">Read the docs</a>
<img src="hero.jpg" alt="Team photo">
<form action="/submit">…</form>`,
    badExample: `<button type="button" role="button">Save</button>
<nav role="navigation">…</nav>
<main role="main">…</main>
<a href="/docs" role="link">Read the docs</a>
<img src="hero.jpg" alt="Team photo" role="img">
<form action="/submit" role="form">…</form>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#host_general_role",
      "https://www.w3.org/TR/html-aria/",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, ctx.source, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, ctx.source, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  fixPaths: FixPaths;
}) => void;

/**
 * Always-redundant `(tagName → implicit role)` pairs. The lookup is
 * case-insensitive on the tag name. Tags whose implicit role is
 * context-dependent (header, footer, section) are deliberately absent.
 */
const ALWAYS_REDUNDANT: ReadonlyMap<string, string> = new Map([
  ["nav", "navigation"],
  ["main", "main"],
  ["button", "button"],
  ["form", "form"],
]);

function checkHtml(doc: HtmlDocument, source: string, emit: Emit): void {
  for (const element of walkHtmlElements(doc)) {
    const role = getHtmlAttribute(element, "role");
    if (!role || role.trim().length === 0) continue;
    const explicit = firstToken(role);
    if (explicit === null) continue;
    const tag = element.tagName.toLowerCase();
    const implicit = htmlImplicitRole(tag, element);
    if (implicit === null) continue;
    if (explicit !== implicit) continue;
    const roleAttr = getHtmlRoleAttribute(element);
    const edit = roleAttr === null ? null : buildHtmlRoleRemovalEdit(roleAttr, source);
    emit(buildViolation(tag, implicit, element.loc.start, edit));
  }
}

function checkJsx(module: TsxModule, source: string, emit: Emit): void {
  for (const element of walkJsxElements(module)) {
    const role = getJsxAttributeString(element, "role");
    if (!role || role.trim().length === 0) continue;
    const explicit = firstToken(role);
    if (explicit === null) continue;
    const tag = element.tagName.toLowerCase();
    const implicit = jsxImplicitRole(tag, element);
    if (implicit === null) continue;
    if (explicit !== implicit) continue;
    const roleAttr = getJsxRoleAttribute(element);
    const edit = roleAttr === null ? null : buildJsxRoleRemovalEdit(roleAttr, source);
    emit(buildViolation(tag, implicit, element.loc.start, edit));
  }
}

/**
 * Deterministic mechanical-edit pair for removing the redundant `role`
 * attribute. `oldText` captures the attribute *with* its single leading
 * whitespace character so the replacement leaves the remainder of the
 * open tag cleanly spaced (`<nav role="navigation">` → `<nav>`, not
 * `<nav >`). When the leading byte is not ASCII whitespace (e.g. the
 * role attribute sits immediately after `<tag`), we fall back to the
 * attribute range alone and let `widenToUniqueAnchor` pick up the rest
 * in the suggest_fix assembly layer.
 *
 * Shared by the HTML and JSX branches — the extraction shape is the
 * same for both parsers because `HtmlAttribute` and `JsxAttribute`
 * both carry a `range: { start, end }` byte-offset pair.
 */
function buildHtmlRoleRemovalEdit(
  attr: HtmlAttribute,
  source: string,
): { readonly oldText: string; readonly newText: string } {
  return buildAttributeRemovalEditFromRange(attr.range.start, attr.range.end, source);
}

function buildJsxRoleRemovalEdit(
  attr: JsxAttribute,
  source: string,
): { readonly oldText: string; readonly newText: string } {
  return buildAttributeRemovalEditFromRange(attr.range.start, attr.range.end, source);
}

function buildAttributeRemovalEditFromRange(
  start: number,
  end: number,
  source: string,
): { readonly oldText: string; readonly newText: string } {
  const prevChar = start > 0 ? source.charCodeAt(start - 1) : -1;
  const isPrevAsciiWs =
    prevChar === 0x20 /* space */ ||
    prevChar === 0x09 /* tab */ ||
    prevChar === 0x0a /* LF */ ||
    prevChar === 0x0d; /* CR */
  const widenStart = isPrevAsciiWs ? start - 1 : start;
  const oldText = source.slice(widenStart, end);
  return { oldText, newText: "" };
}

function getHtmlRoleAttribute(element: HtmlElement): HtmlAttribute | null {
  for (const attr of element.attributes) {
    if (attr.name.toLowerCase() === "role") return attr;
  }
  return null;
}

function getJsxRoleAttribute(element: JsxElement): JsxAttribute | null {
  for (const attr of element.attributes) {
    if (attr.name.toLowerCase() === "role") return attr;
  }
  return null;
}

/**
 * Resolves the implicit role of an HTML element for the conservative
 * subset this rule covers. Returns null when the tag has no implicit
 * role under our pairs, or when context-dependent attributes (href on
 * <a>, alt on <img>) don't satisfy the implicit-role precondition.
 */
function htmlImplicitRole(tag: string, element: HtmlElement): string | null {
  const fixed = ALWAYS_REDUNDANT.get(tag);
  if (fixed) return fixed;
  if (tag === "a") {
    return hasHtmlAttribute(element, "href") ? "link" : null;
  }
  if (tag === "img") {
    const alt = getHtmlAttribute(element, "alt");
    // Only the named <img> has implicit role "img"; alt="" is
    // "presentation" and missing alt is also conventionally treated as
    // unnamed (the alt-text rules own that), so we require a non-empty
    // alt to flag the role="img" redundancy honestly.
    if (alt !== null && alt.trim().length > 0) return "img";
    return null;
  }
  return null;
}

function jsxImplicitRole(tag: string, element: JsxElement): string | null {
  const fixed = ALWAYS_REDUNDANT.get(tag);
  if (fixed) return fixed;
  if (tag === "a") {
    // For JSX, an href expression (e.g. `href={url}`) still counts as
    // "the element has an href" — same convention as conflicting-role.
    return hasJsxAttribute(element, "href") ? "link" : null;
  }
  if (tag === "img") {
    const alt = getJsxAttributeString(element, "alt");
    if (alt !== null && alt.trim().length > 0) return "img";
    return null;
  }
  return null;
}

/**
 * The first non-empty token of the role attribute. ARIA allows a
 * space-separated fallback chain; redundancy is checked against the
 * first (primary) token. Lowercased so `role="BUTTON"` matches.
 */
function firstToken(roleValue: string): string | null {
  for (const raw of roleValue.split(/\s+/)) {
    const token = raw.trim();
    if (token.length > 0) return token.toLowerCase();
  }
  return null;
}

function buildViolation(
  tag: string,
  implicit: string,
  loc: { line: number; column: number },
  edit: { readonly oldText: string; readonly newText: string } | null,
): {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  fixPaths: FixPaths;
} {
  // Q7-SUGGEST-FIX-EDIT-LANE-UNREACHABLE: emit `fixPaths.primary.edit`
  // so `suggest_fix` returns `kind: "edit"` with a concrete
  // oldText/newText pair. The edit is deterministic — we have the
  // attribute's byte range, the target value is empty, and removal is
  // safe for every pair in the `ALWAYS_REDUNDANT` table. When the
  // edit couldn't be synthesized (shouldn't happen in practice but
  // defensive), the primary path ships guidance only.
  const fixPaths: FixPaths = {
    primary: {
      label: `remove redundant role="${implicit}" from <${tag}>`,
      ...(edit === null ? {} : { edit }),
    },
    alternatives: [],
  };
  return {
    severity: "warning",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tag}> already has implicit role="${implicit}"; the explicit role="${implicit}" is redundant.`,
    suggestion: remediationSuggestion(tag, implicit),
    fixPaths,
  };
}

function remediationSuggestion(tag: string, implicit: string): string {
  if (tag === "a") {
    return `<a href> already exposes role="link" to assistive tech. Remove role="link" — keeping it adds no information and risks being copy-pasted onto a non-link element where it would break.`;
  }
  if (tag === "img") {
    return `<img> with non-empty alt already exposes role="img" to assistive tech. Remove role="img" — the implicit role is what AT will use.`;
  }
  if (tag === "form") {
    return `<form> already exposes role="form" to assistive tech (when it has an accessible name). Remove role="form" — and if the form needs to be a discoverable landmark, give it an aria-label or aria-labelledby instead of re-stating the role.`;
  }
  return `<${tag}> already exposes role="${implicit}" to assistive tech. Remove role="${implicit}" — the implicit role is what AT will use.`;
}
