/**
 * Rule: aria/tab-widget-roles
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:1.3.1, wcag21:1.3.1
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 * Spec: https://www.w3.org/TR/WCAG22/#info-and-relationships
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links, and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Composite-widget invariant: a tab-widget pattern is recognised when
 * any of these idiom signals fire on at least one element in the file:
 *
 *   - `data-toggle="tab"` (Bootstrap 4 tabs idiom)
 *   - `data-bs-toggle="tab"` (Bootstrap 5 tabs idiom)
 *   - any element already carries `role="tab"`
 *
 * When the pattern is detected, the WAI-ARIA tabs role triple — the
 * full programmatic-role contract that lets assistive tech announce the
 * widget as "tabs / tab / panel" — must be present on every member:
 *
 *   (a) the parent of every tab member carries `role="tablist"`
 *   (b) every tab member carries `role="tab"` AND `aria-selected="…"`
 *   (c) any panel referenced by a tab (`aria-controls="panel-id"` or,
 *       in the Bootstrap idiom, `href="#panel-id"`) carries
 *       `role="tabpanel"` on the resolved element
 *
 * This is the composite-widget complement to `aria/tab-controls-missing`,
 * which checks the reciprocal-pair *wiring* (aria-controls /
 * aria-labelledby) once the role triple is in place. The two rules can
 * co-fire on the same case — that's intentional: a half-built tab
 * widget reads to assistive tech as both "wrong roles" and "broken
 * wiring," and the agent benefits from seeing both signals separately
 * so it can sequence the fix.
 *
 * Document-scope caveat. The tabpanel role check resolves panel ids
 * within the parsed file only — a tab whose `aria-controls` (or
 * `href="#…"`) points at a panel in a sibling React component, Jekyll
 * include, or ERB partial cannot be statically verified. We surface
 * that gap as `couldBeWrongBecause` on fragment-classified files (and
 * always on JSX modules, which are file-scoped by design) rather than
 * suppressing the finding — the agent reading the composed parent is
 * the correct arbiter, but it needs the "panel-may-live-elsewhere"
 * signal to know to look. Mirrors the posture in
 * `aria/tab-controls-missing` and the doctrine in
 * `docs/kb/architecture/ai-first-consumer.md` (surface, don't
 * suppress).
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import { isFragmentFile } from "../../engine/layout-partial.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  TsxModule,
} from "../../types/ast.ts";

/**
 * Structured `couldBeWrongBecause` code attached to fragment-file emits
 * where panel-id resolution can't be confirmed. Mirrors the pattern in
 * `aria/tab-controls-missing`.
 */
const FRAGMENT_CROSS_FILE_CODE =
  "tab-widget-panel-may-live-in-sibling-template-id-resolution-is-file-scoped";

/** Idiom-trigger attribute names that mark an element as a tab member. */
const TAB_TOGGLE_ATTRS: readonly string[] = ["data-toggle", "data-bs-toggle"];

export const rule = defineRule({
  id: "aria/tab-widget-roles",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:1.3.1", "wcag21:1.3.1"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  // Panel ids may live in a sibling partial / include / JSX component;
  // declaring `crossFileCapable: false` surfaces that gap as
  // `coverageConfidence: "medium"` per ADR 0026.
  crossFileCapable: false,
  docs: {
    description:
      "Tab-widget idioms (data-toggle=tab, data-bs-toggle=tab, role=tab) must declare the full WAI-ARIA tabs role triple — role=tablist on the parent, role=tab plus aria-selected on every member, and role=tabpanel on every controlled panel.",
    rationale:
      'A tab widget assembled out of `<ul><li><a data-toggle="tab">…</a></li></ul>` (Bootstrap 4) or `<button data-bs-toggle="tab">…</button>` (Bootstrap 5) renders correctly to a sighted user — the active tab is highlighted, clicking switches panels, the layout looks right. But the WAI-ARIA tabs pattern is a programmatic-role contract: assistive tech announces the widget as "tablist, tab 1 of 3, selected" only when the role triple (tablist parent + role=tab member + role=tabpanel target) and the `aria-selected` state are all present. A half-implemented widget — `data-toggle="tab"` providing the JavaScript hook but no roles or selection state — is announced as "list, link, link, link" with no relationship between the links and the panels. Screen-reader users hear three unrelated links and a generic block of text below; keyboard users get focus order but no "tabs" semantics, so the standard arrow-key tab navigation isn\'t hinted. This rule fires the moment any tab-idiom signal is seen, and reports the specific role-triple gaps so the fix is mechanical: add the missing roles, add aria-selected, point aria-controls at the panel.',
    goodExample: `<div role="tablist">
  <button role="tab" aria-selected="true" aria-controls="panel-1" id="tab-1">Tab 1</button>
  <button role="tab" aria-selected="false" aria-controls="panel-2" id="tab-2">Tab 2</button>
</div>
<div role="tabpanel" id="panel-1" aria-labelledby="tab-1">Panel 1 content</div>
<div role="tabpanel" id="panel-2" aria-labelledby="tab-2">Panel 2 content</div>`,
    badExample: `<ul>
  <li><a data-toggle="tab" href="#panel-1">Tab 1</a></li>
  <li><a data-toggle="tab" href="#panel-2">Tab 2</a></li>
</ul>
<div id="panel-1">Panel 1</div>
<div id="panel-2">Panel 2</div>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#info-and-relationships",
      "https://www.w3.org/TR/wai-aria-1.2/#tablist",
      "https://www.w3.org/TR/wai-aria-1.2/#tab",
      "https://www.w3.org/TR/wai-aria-1.2/#tabpanel",
      "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      const doc = ctx.ast as HtmlDocument;
      const fragment = isFragmentFile(doc, ctx.source, ctx.filePath);
      // Cross-file-candidate signal: a tab-pattern member is a token
      // whose reciprocal half (the panel) might live in a sibling
      // file. Files with zero tab members carry no cross-file
      // question — confidence stays `"high"`.
      if (collectHtmlTabMembers(doc).length > 0) ctx.markCrossFileCandidate?.();
      checkHtml(doc, fragment, (v) => ctx.emit(v));
      return;
    }
    if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      // JSX modules are file-scoped by design — treat as a fragment so
      // the same panel-may-live-elsewhere enrichment fires.
      const module = ctx.ast as TsxModule;
      if (collectJsxTabMembers(module).length > 0) ctx.markCrossFileCandidate?.();
      checkJsx(module, true, (v) => ctx.emit(v));
    }
  },
});

type Severity = "error" | "warning" | "info";
type Emit = (v: {
  severity: Severity;
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  couldBeWrongBecause?: readonly string[];
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, fragment: boolean, emit: Emit): void {
  const members = collectHtmlTabMembers(doc);
  if (members.length === 0) return;
  const parentMap = buildHtmlParentMap(doc);
  const idIndex = buildHtmlIdIndex(doc);
  const reportedParents = new Set<HtmlElement>();
  for (const member of members) {
    const gaps = diagnoseHtmlMember(member, parentMap, idIndex);
    if (gaps.length === 0) continue;
    emit(buildHtmlMemberEmit(member, gaps, fragment));
    const parent = parentMap.get(member);
    if (
      parent &&
      parent !== "document" &&
      !reportedParents.has(parent) &&
      !hasTablistRole(parent)
    ) {
      // The parent-level emission is implicit in the per-member
      // `parent-missing-role-tablist` gap; we only need to flag once
      // per parent so the agent doesn't see N copies.
      reportedParents.add(parent);
    }
  }
}

/**
 * A tab member is any element carrying any of the idiom-trigger
 * attributes (data-toggle="tab" / data-bs-toggle="tab") OR an explicit
 * `role="tab"`. We accept the role itself as a trigger so a
 * half-implemented widget that already added roles to *some* members
 * still gets caught (e.g. role=tab without aria-selected).
 */
function collectHtmlTabMembers(doc: HtmlDocument): readonly HtmlElement[] {
  const out: HtmlElement[] = [];
  for (const el of walkHtmlElements(doc)) {
    if (isHtmlTabMember(el)) out.push(el);
  }
  return out;
}

function isHtmlTabMember(el: HtmlElement): boolean {
  if (roleOf(getHtmlAttribute(el, "role")) === "tab") return true;
  for (const attr of TAB_TOGGLE_ATTRS) {
    const raw = getHtmlAttribute(el, attr);
    if (raw !== null && raw.trim().toLowerCase() === "tab") return true;
  }
  return false;
}

function buildHtmlParentMap(doc: HtmlDocument): Map<HtmlElement, HtmlElement | "document"> {
  const parents = new Map<HtmlElement, HtmlElement | "document">();
  const visit = (children: readonly HtmlNode[], parent: HtmlElement | "document"): void => {
    for (const child of children) {
      if (child.kind !== "HtmlElement") continue;
      parents.set(child, parent);
      visit(child.children, child);
    }
  };
  visit(doc.children, "document");
  return parents;
}

function buildHtmlIdIndex(doc: HtmlDocument): ReadonlyMap<string, HtmlElement> {
  const out = new Map<string, HtmlElement>();
  for (const el of walkHtmlElements(doc)) {
    const id = getHtmlAttribute(el, "id");
    if (id !== null && id.length > 0 && !out.has(id)) out.set(id, el);
  }
  return out;
}

type Gap =
  | "missing-role-tab"
  | "missing-aria-selected"
  | "parent-missing-role-tablist"
  | "panel-missing-role-tabpanel";

function diagnoseHtmlMember(
  member: HtmlElement,
  parentMap: Map<HtmlElement, HtmlElement | "document">,
  idIndex: ReadonlyMap<string, HtmlElement>,
): readonly Gap[] {
  const gaps: Gap[] = [];
  if (roleOf(getHtmlAttribute(member, "role")) !== "tab") gaps.push("missing-role-tab");
  if (!hasHtmlAttribute(member, "aria-selected")) gaps.push("missing-aria-selected");
  const parent = parentMap.get(member);
  if (parent && parent !== "document" && !hasTablistRole(parent)) {
    gaps.push("parent-missing-role-tablist");
  }
  if (htmlPanelTargetMissingRole(member, idIndex)) gaps.push("panel-missing-role-tabpanel");
  return gaps;
}

function hasTablistRole(el: HtmlElement): boolean {
  return roleOf(getHtmlAttribute(el, "role")) === "tablist";
}

/**
 * Returns true when the member references a panel id (via
 * `aria-controls` or, in the Bootstrap idiom, `href="#panel-id"`) that
 * resolves to an in-file element WITHOUT `role="tabpanel"`. Returns
 * false when there is no reference, when the reference dangles
 * (handled by `aria/tab-controls-missing`), or when the target is
 * already a tabpanel.
 */
function htmlPanelTargetMissingRole(
  member: HtmlElement,
  idIndex: ReadonlyMap<string, HtmlElement>,
): boolean {
  const tokens = htmlPanelIdrefTokens(member);
  if (tokens.length === 0) return false;
  for (const token of tokens) {
    const target = idIndex.get(token);
    if (!target) continue; // dangling — let tab-controls-missing speak
    if (roleOf(getHtmlAttribute(target, "role")) !== "tabpanel") return true;
  }
  return false;
}

function htmlPanelIdrefTokens(el: HtmlElement): readonly string[] {
  const tokens: string[] = [];
  const ariaControls = getHtmlAttribute(el, "aria-controls");
  if (ariaControls !== null) {
    for (const token of splitIdrefList(ariaControls)) tokens.push(token);
  }
  const href = getHtmlAttribute(el, "href");
  if (href?.startsWith("#") && href.length > 1) {
    tokens.push(href.slice(1));
  }
  return tokens;
}

function buildHtmlMemberEmit(
  member: HtmlElement,
  gaps: readonly Gap[],
  fragment: boolean,
): Parameters<Emit>[0] {
  const idiomLabel = htmlMemberIdiomLabel(member);
  const tagName = member.tagName;
  const description = describeGaps(gaps);
  const fragmentSuffix = fragment
    ? " This file looks like a fragment / partial / component template — the panel(s) referenced by this tab may render in a sibling file (layout, include, route component) the scanner does not see in this scope."
    : "";
  const severity: Severity = severityForGaps(gaps, fragment);
  const baseEmit = {
    severity,
    location: { filePath: "", line: member.loc.start.line, column: member.loc.start.column },
    message: `<${tagName}${idiomLabel}> looks like a tab in a tab-widget pattern but the WAI-ARIA tabs role triple is incomplete: ${description}.${fragmentSuffix}`,
    suggestion: buildHtmlSuggestion(tagName, idiomLabel, gaps, member),
  };
  if (gapsTouchPanelRoleAcrossFile(gaps) || fragment) {
    return { ...baseEmit, couldBeWrongBecause: [FRAGMENT_CROSS_FILE_CODE] };
  }
  return baseEmit;
}

function htmlMemberIdiomLabel(member: HtmlElement): string {
  for (const attr of TAB_TOGGLE_ATTRS) {
    const raw = getHtmlAttribute(member, attr);
    if (raw !== null && raw.trim().toLowerCase() === "tab") return ` ${attr}="${raw}"`;
  }
  const role = getHtmlAttribute(member, "role");
  if (role !== null) return ` role="${role}"`;
  return "";
}

function buildHtmlSuggestion(
  tagName: string,
  idiomLabel: string,
  gaps: readonly Gap[],
  member: HtmlElement,
): string {
  const fixes: string[] = [];
  if (gaps.includes("missing-role-tab")) {
    fixes.push(`add role="tab" to <${tagName}${idiomLabel}>`);
  }
  if (gaps.includes("missing-aria-selected")) {
    fixes.push(
      'add aria-selected="true" to the active tab and aria-selected="false" to every other tab member',
    );
  }
  if (gaps.includes("parent-missing-role-tablist")) {
    fixes.push('add role="tablist" to the parent element that contains every tab member');
  }
  if (gaps.includes("panel-missing-role-tabpanel")) {
    const panelHint = htmlPanelHint(member);
    fixes.push(
      `add role="tabpanel" to the panel element ${panelHint} this tab activates (in the tabs pattern, every tab points at a tabpanel by id)`,
    );
  }
  const numbered = fixes.map((f, i) => `(${i + 1}) ${f}`).join("; ");
  return `Restore the WAI-ARIA tabs role triple: ${numbered}. Pair these with id+aria-controls wiring on the tab and aria-labelledby on each tabpanel — the WAI-ARIA Authoring Practices tabs pattern is the canonical reference.`;
}

function htmlPanelHint(member: HtmlElement): string {
  const tokens = htmlPanelIdrefTokens(member);
  if (tokens.length === 0) return "";
  return `with id="${tokens[0] ?? ""}"`;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, fragment: boolean, emit: Emit): void {
  const members = collectJsxTabMembers(module);
  if (members.length === 0) return;
  const parentMap = buildJsxParentMap(module);
  const idIndex = buildJsxIdIndex(module);
  for (const member of members) {
    const gaps = diagnoseJsxMember(member, parentMap, idIndex);
    if (gaps.length === 0) continue;
    emit(buildJsxMemberEmit(member, gaps, fragment));
  }
}

function collectJsxTabMembers(module: TsxModule): readonly JsxElement[] {
  const out: JsxElement[] = [];
  for (const el of walkJsxElements(module)) {
    if (isComponent(el.tagName)) continue;
    if (isJsxTabMember(el)) out.push(el);
  }
  return out;
}

function isJsxTabMember(el: JsxElement): boolean {
  if (roleOf(getJsxAttributeString(el, "role")) === "tab") return true;
  for (const attr of TAB_TOGGLE_ATTRS) {
    const raw = getJsxAttributeString(el, attr);
    if (raw !== null && raw.trim().toLowerCase() === "tab") return true;
  }
  return false;
}

function buildJsxParentMap(module: TsxModule): Map<JsxElement, JsxElement | "module"> {
  const parents = new Map<JsxElement, JsxElement | "module">();
  // Walk depth-first; for each element, set its children's parent to it.
  for (const top of module.jsxElements) {
    if (!parents.has(top)) parents.set(top, "module");
    visitJsxChildren(top, parents);
  }
  return parents;
}

function visitJsxChildren(el: JsxElement, parents: Map<JsxElement, JsxElement | "module">): void {
  for (const child of el.children) {
    if (child.kind !== "JsxElement") continue;
    parents.set(child, el);
    visitJsxChildren(child, parents);
  }
}

function buildJsxIdIndex(module: TsxModule): ReadonlyMap<string, JsxElement> {
  const out = new Map<string, JsxElement>();
  for (const el of walkJsxElements(module)) {
    if (isComponent(el.tagName)) continue;
    const id = getJsxAttributeString(el, "id");
    if (id !== null && id.length > 0 && !out.has(id)) out.set(id, el);
  }
  return out;
}

function diagnoseJsxMember(
  member: JsxElement,
  parentMap: Map<JsxElement, JsxElement | "module">,
  idIndex: ReadonlyMap<string, JsxElement>,
): readonly Gap[] {
  const gaps: Gap[] = [];
  if (roleOf(getJsxAttributeString(member, "role")) !== "tab") gaps.push("missing-role-tab");
  if (!hasJsxAttribute(member, "aria-selected")) gaps.push("missing-aria-selected");
  const parent = parentMap.get(member);
  if (parent && parent !== "module") {
    if (isComponent(parent.tagName)) {
      // Composed parent — can't classify; suppress this gap (the
      // wrapping component might supply role=tablist itself). The
      // remaining gaps still surface.
    } else if (roleOf(getJsxAttributeString(parent, "role")) !== "tablist") {
      gaps.push("parent-missing-role-tablist");
    }
  }
  if (jsxPanelTargetMissingRole(member, idIndex)) gaps.push("panel-missing-role-tabpanel");
  return gaps;
}

function jsxPanelTargetMissingRole(
  member: JsxElement,
  idIndex: ReadonlyMap<string, JsxElement>,
): boolean {
  const tokens = jsxPanelIdrefTokens(member);
  if (tokens.length === 0) return false;
  for (const token of tokens) {
    const target = idIndex.get(token);
    if (!target) continue;
    if (roleOf(getJsxAttributeString(target, "role")) !== "tabpanel") return true;
  }
  return false;
}

function jsxPanelIdrefTokens(el: JsxElement): readonly string[] {
  const tokens: string[] = [];
  const ariaControls = getJsxAttributeString(el, "aria-controls");
  if (ariaControls !== null) {
    for (const token of splitIdrefList(ariaControls)) tokens.push(token);
  }
  const href = getJsxAttributeString(el, "href");
  if (href?.startsWith("#") && href.length > 1) {
    tokens.push(href.slice(1));
  }
  return tokens;
}

function buildJsxMemberEmit(
  member: JsxElement,
  gaps: readonly Gap[],
  fragment: boolean,
): Parameters<Emit>[0] {
  const tagName = member.tagName;
  const idiomLabel = jsxMemberIdiomLabel(member);
  const description = describeGaps(gaps);
  const fragmentSuffix = fragment
    ? " JSX modules are file-scoped — the panel(s) referenced by this tab may render in a sibling component the scanner does not see in this scope."
    : "";
  const severity: Severity = severityForGaps(gaps, fragment);
  const tokens = jsxPanelIdrefTokens(member);
  const panelHint = tokens.length > 0 ? `with id="${tokens[0] ?? ""}"` : "";
  const baseEmit = {
    severity,
    location: { filePath: "", line: member.loc.start.line, column: member.loc.start.column },
    message: `<${tagName}${idiomLabel}> looks like a tab in a tab-widget pattern but the WAI-ARIA tabs role triple is incomplete: ${description}.${fragmentSuffix}`,
    suggestion: buildJsxSuggestion(tagName, idiomLabel, gaps, panelHint),
  };
  if (gapsTouchPanelRoleAcrossFile(gaps) || fragment) {
    return { ...baseEmit, couldBeWrongBecause: [FRAGMENT_CROSS_FILE_CODE] };
  }
  return baseEmit;
}

function jsxMemberIdiomLabel(member: JsxElement): string {
  for (const attr of TAB_TOGGLE_ATTRS) {
    const raw = getJsxAttributeString(member, attr);
    if (raw !== null && raw.trim().toLowerCase() === "tab") return ` ${attr}="${raw}"`;
  }
  const role = getJsxAttributeString(member, "role");
  if (role !== null) return ` role="${role}"`;
  return "";
}

function buildJsxSuggestion(
  tagName: string,
  idiomLabel: string,
  gaps: readonly Gap[],
  panelHint: string,
): string {
  const fixes: string[] = [];
  if (gaps.includes("missing-role-tab")) {
    fixes.push(`add role="tab" to <${tagName}${idiomLabel}>`);
  }
  if (gaps.includes("missing-aria-selected")) {
    fixes.push(
      "add aria-selected={isActive ? 'true' : 'false'} (or a literal) to every tab member, true on the active one and false on the rest",
    );
  }
  if (gaps.includes("parent-missing-role-tablist")) {
    fixes.push('add role="tablist" to the parent element that contains every tab member');
  }
  if (gaps.includes("panel-missing-role-tabpanel")) {
    fixes.push(
      `add role="tabpanel" to the panel element ${panelHint} this tab activates`.trimEnd(),
    );
  }
  const numbered = fixes.map((f, i) => `(${i + 1}) ${f}`).join("; ");
  return `Restore the WAI-ARIA tabs role triple: ${numbered}. The WAI-ARIA Authoring Practices tabs pattern (https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) is the canonical reference; pair the role triple with id+aria-controls on each tab and aria-labelledby on each tabpanel.`;
}

function isComponent(tagName: string): boolean {
  const first = tagName[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/**
 * Returns the first whitespace-separated `role` token if it matches a
 * known tabs-pattern role, else null. WAI-ARIA permits a
 * space-separated list of fallback roles; the first listed is the one
 * assistive tech uses.
 */
function roleOf(raw: string | null): "tab" | "tabpanel" | "tablist" | null {
  if (raw === null) return null;
  for (const tok of raw.trim().split(/\s+/u)) {
    const lower = tok.toLowerCase();
    if (lower === "tab") return "tab";
    if (lower === "tabpanel") return "tabpanel";
    if (lower === "tablist") return "tablist";
    if (lower.length > 0) return null;
  }
  return null;
}

function splitIdrefList(raw: string): readonly string[] {
  return raw.split(/\s+/u).filter((t) => t.length > 0);
}

function describeGaps(gaps: readonly Gap[]): string {
  const phrases = gaps.map((g) => {
    if (g === "missing-role-tab") return 'no role="tab" on the member';
    if (g === "missing-aria-selected") return "no aria-selected state";
    if (g === "parent-missing-role-tablist") return 'parent has no role="tablist"';
    return 'the controlled panel has no role="tabpanel"';
  });
  if (phrases.length === 1) return phrases[0] ?? "";
  if (phrases.length === 2) return `${phrases[0]} and ${phrases[1]}`;
  return `${phrases.slice(0, -1).join(", ")}, and ${phrases[phrases.length - 1]}`;
}

function gapsTouchPanelRoleAcrossFile(gaps: readonly Gap[]): boolean {
  return gaps.includes("panel-missing-role-tabpanel");
}

/**
 * Severity policy. The role-triple gaps directly visible on the tab
 * member itself (missing role=tab, missing aria-selected, parent
 * missing role=tablist) stay at `error` even on fragment files —
 * they belong on the same template regardless of where the panel
 * renders. The panel-role gap downgrades to `info` on fragments
 * because the panel may live in a sibling file.
 */
function severityForGaps(gaps: readonly Gap[], fragment: boolean): Severity {
  if (!fragment) return "error";
  // On fragments, only emit info if the *only* gap touches the panel
  // (which we can't fully see). Any in-template gap stays at error.
  const hasInTemplateGap = gaps.some(
    (g) =>
      g === "missing-role-tab" ||
      g === "missing-aria-selected" ||
      g === "parent-missing-role-tablist",
  );
  return hasInTemplateGap ? "error" : "info";
}
