/**
 * Rule: aria/tab-controls-missing
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:1.3.1, wcag21:1.3.1
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 * Spec: https://www.w3.org/TR/WCAG22/#info-and-relationships
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links, and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * The WAI-ARIA "tabs" pattern is a reciprocal pair: every `role="tab"`
 * names its panel via `aria-controls="<panel-id>"`, and every
 * `role="tabpanel"` names the tab that owns it via
 * `aria-labelledby="<tab-id>"` (or, equivalently, the tab references
 * the panel and a sibling-pair test passes). This rule encodes three
 * branches of that invariant against the same parsed file:
 *
 *   Branch A — `[role="tab"]` with NO `aria-controls` attribute. The
 *   tab declares it triggers a panel, but assistive tech has no idea
 *   which DOM node is the panel — `aria-controls` is the only
 *   programmatic wire-up. (`aria-owns` is for parent-child flattening,
 *   not the trigger-target relationship a tabs pattern requires.)
 *
 *   Branch B — `[role="tab"]` with `aria-controls="xxx"` but no
 *   element in the same document carries `id="xxx"` AND
 *   `role="tabpanel"`. The reference is dangling, points at the wrong
 *   element shape, or the panel was renamed and the tab forgot. The
 *   tab will announce something, but the panel is not the thing that
 *   gets announced as related.
 *
 *   Branch C — `[role="tabpanel"]` with NO `aria-labelledby` AND no
 *   tab in the same document references this panel id via
 *   `aria-controls`. The panel has no accessible name and is not
 *   reachable via the tab's relationship — for screen-reader users,
 *   the panel content is just "an unnamed region." (When a tab DOES
 *   reference the panel via `aria-controls`, the missing
 *   `aria-labelledby` is a weaker style nit — the relationship still
 *   resolves in one direction — so we suppress branch C in that case.)
 *
 * The branches share an in-file id index built once per check call so
 * the cost is O(elements + tabs) rather than per-tab linear scan.
 *
 * Document-scope caveat. The id resolution is local to the parsed
 * file — a `role="tab"` whose `aria-controls` points at a panel in a
 * sibling React component, a Jekyll include, or an ERB partial cannot
 * be statically verified. For HTML fragment files (no `<html>` or
 * `<body>`, or front-matter / `_partials/` / `components/` paths) the
 * cross-file gap is the most likely explanation; we still surface
 * branches B and C on those files but downgrade severity from `error`
 * to `info` and emit a `couldBeWrongBecause` code so the agent reads
 * the composed parent before treating the finding as actionable.
 * Branch A (the attribute is entirely absent) stays at `error` even on
 * fragments — `aria-controls` belongs on the tab in the same template
 * regardless of where the panel lives. JSX modules don't have a
 * document-envelope concept; their reference resolution is
 * file-scoped by design and the same fragment-style enrichment fires
 * on branches B and C. This mirrors the pattern from
 * `semantics/landmark-main` and the doctrine in
 * `docs/kb/architecture/ai-first-consumer.md` — surface, don't
 * suppress; attach `couldBeWrongBecause` so the agent routes to the
 * right read in one step.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import { isFragmentFile } from "../../engine/layout-partial.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

/**
 * Structured `couldBeWrongBecause` code attached to fragment-file
 * emits where cross-file id resolution can't be confirmed. Mirrors the
 * pattern in `semantics/landmark-main` (`partial-or-layout-composed`)
 * and `aria/hidden-focus` (`runtime-aria-hidden-toggle`).
 */
const FRAGMENT_CROSS_FILE_CODE =
  "tab-controls-target-may-live-in-sibling-template-id-resolution-is-file-scoped";

export const rule = defineRule({
  id: "aria/tab-controls-missing",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2", "wcag22:1.3.1", "wcag21:1.3.1"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  // Same caveat as `aria/labelledby-target-exists`: id targets may
  // live in a sibling partial / include / JSX component. Declaring
  // `crossFileCapable: false` surfaces that gap as
  // `coverageConfidence: "medium"` per ADR 0026.
  crossFileCapable: false,
  docs: {
    description:
      "role=tab elements must reference their panel via aria-controls; role=tabpanel elements must be labelled by a tab via aria-labelledby (reciprocal-pair invariant).",
    rationale:
      "The WAI-ARIA tabs pattern is a reciprocal-pair contract: each tab declares its panel via aria-controls, each panel names the tab that owns it via aria-labelledby. Without aria-controls on the tab, assistive tech has no programmatic way to know which DOM node the tab activates — keyboard users can press Right-arrow between tabs but the panel relationship is invisible. Without aria-labelledby on the panel (and no tab pointing back), the panel content reads as 'an unnamed region' instead of being announced as 'Tab Name, panel'. The reciprocal half of the pair is also enforced — a dangling aria-controls token (target id absent or not a tabpanel) is the same silent wire-up failure as a broken aria-labelledby token: the author wrote the attribute, but nothing resolves at runtime, and sighted authors who don't run a screen reader during development have no signal. The three branches together cover the failure modes the WAI-ARIA Authoring Practices documents as the most common tabs-pattern bugs.",
    goodExample: `<div role="tablist">
  <button role="tab" aria-selected="true" aria-controls="panel-1" id="tab-1">Tab 1</button>
  <button role="tab" aria-selected="false" aria-controls="panel-2" id="tab-2">Tab 2</button>
</div>
<div role="tabpanel" id="panel-1" aria-labelledby="tab-1">Panel 1 content</div>
<div role="tabpanel" id="panel-2" aria-labelledby="tab-2">Panel 2 content</div>`,
    badExample: `<div role="tablist">
  <button role="tab" aria-selected="true">Tab 1</button>
</div>
<div role="tabpanel">Panel 1 content</div>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#info-and-relationships",
      "https://www.w3.org/TR/wai-aria-1.2/#tab",
      "https://www.w3.org/TR/wai-aria-1.2/#tabpanel",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-controls",
      "https://www.w3.org/TR/wai-aria-1.2/#aria-labelledby",
      "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      const doc = ctx.ast as HtmlDocument;
      const fragment = isFragmentFile(doc, ctx.source, ctx.filePath);
      checkHtml(doc, fragment, (v) => ctx.emit(v));
      return;
    }
    if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      // JSX modules are file-scoped by design; no document-envelope
      // concept. Treat them as the JSX analogue of an HTML fragment so
      // the same cross-file `couldBeWrongBecause` enrichment fires —
      // the panel might render in a sibling component the scanner
      // doesn't see.
      checkJsx(ctx.ast as TsxModule, true, (v) => ctx.emit(v));
    }
  },
});

type Severity = "error" | "warning" | "info";
type Loc = { readonly line: number; readonly column: number };
type Emit = (v: {
  severity: Severity;
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  couldBeWrongBecause?: readonly string[];
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

interface HtmlIndex {
  /** Every element that carries a non-empty `id`, indexed by id. */
  readonly idToElement: ReadonlyMap<string, HtmlElement>;
  /**
   * For each panel id referenced by some tab's `aria-controls`, the
   * list of tab ids that name it. A tab with no id contributes the
   * empty string — the presence of any entry under a panel id is
   * what suppresses branch C, not the tab id itself.
   */
  readonly panelIdToReferencingTabIds: ReadonlyMap<string, readonly string[]>;
}

function checkHtml(doc: HtmlDocument, fragment: boolean, emit: Emit): void {
  const index = buildHtmlIndex(doc);
  for (const el of walkHtmlElements(doc)) {
    const role = roleOf(getHtmlAttribute(el, "role"));
    if (role === "tab") {
      checkHtmlTab(el, index, fragment, emit);
      continue;
    }
    if (role === "tabpanel") {
      checkHtmlTabpanel(el, index, fragment, emit);
    }
  }
}

function buildHtmlIndex(doc: HtmlDocument): HtmlIndex {
  const idToElement = new Map<string, HtmlElement>();
  const panelIdToReferencingTabIds = new Map<string, string[]>();
  for (const el of walkHtmlElements(doc)) {
    indexHtmlElement(el, idToElement, panelIdToReferencingTabIds);
  }
  return { idToElement, panelIdToReferencingTabIds };
}

function indexHtmlElement(
  el: HtmlElement,
  idToElement: Map<string, HtmlElement>,
  panelIdToReferencingTabIds: Map<string, string[]>,
): void {
  const id = getHtmlAttribute(el, "id");
  if (id !== null && id.length > 0 && !idToElement.has(id)) {
    // First-write-wins mirrors the DOM contract — duplicate ids are a
    // separate parsing rule; here we resolve to the first.
    idToElement.set(id, el);
  }
  if (roleOf(getHtmlAttribute(el, "role")) !== "tab") return;
  const ariaControls = getHtmlAttribute(el, "aria-controls");
  if (ariaControls === null) return;
  const tabId = getHtmlAttribute(el, "id") ?? "";
  for (const token of splitIdrefList(ariaControls)) {
    appendTabIdReference(panelIdToReferencingTabIds, token, tabId);
  }
}

function checkHtmlTab(el: HtmlElement, index: HtmlIndex, fragment: boolean, emit: Emit): void {
  if (!hasHtmlAttribute(el, "aria-controls")) {
    // Branch A: missing attribute entirely. Stays at `error` even on
    // fragments — the attribute belongs on the tab in this template
    // regardless of where the panel renders.
    emit(buildBranchAEmit(el.tagName, el.loc.start, false));
    return;
  }
  const ariaControls = getHtmlAttribute(el, "aria-controls") ?? "";
  const tokens = splitIdrefList(ariaControls);
  if (tokens.length === 0) {
    emit(buildBranchAEmit(el.tagName, el.loc.start, true));
    return;
  }
  // Branch B: every aria-controls token must resolve to a tabpanel in
  // this file. A token that resolves to an element with the wrong role
  // is treated the same as a missing target — the tabs pattern wants a
  // panel.
  const dangling: string[] = [];
  const wrongRole: { token: string; role: string }[] = [];
  for (const token of tokens) {
    const target = index.idToElement.get(token);
    if (!target) {
      dangling.push(token);
      continue;
    }
    if (roleOf(getHtmlAttribute(target, "role")) !== "tabpanel") {
      const rawRole = getHtmlAttribute(target, "role");
      wrongRole.push({ token, role: rawRole ?? `<${target.tagName.toLowerCase()}>` });
    }
  }
  if (dangling.length > 0 || wrongRole.length > 0) {
    emit(buildBranchBEmit(el.tagName, el.loc.start, ariaControls, dangling, wrongRole, fragment));
  }
}

function checkHtmlTabpanel(el: HtmlElement, index: HtmlIndex, fragment: boolean, emit: Emit): void {
  if (hasHtmlAttribute(el, "aria-labelledby")) return;
  const panelId = getHtmlAttribute(el, "id") ?? "";
  // If any tab in this file points at this panel via aria-controls,
  // the relationship resolves in one direction — branch C is suppressed
  // (the panel still lacks an accessible name, but the WAI-ARIA spec
  // accepts the tab→panel link as the relationship anchor).
  if (panelId.length > 0 && index.panelIdToReferencingTabIds.has(panelId)) return;
  emit(buildBranchCEmit(el.tagName, el.loc.start, panelId, fragment));
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

interface JsxIndex {
  readonly idToElement: ReadonlyMap<string, JsxElement>;
  readonly panelIdToReferencingTabIds: ReadonlyMap<string, readonly string[]>;
}

function checkJsx(module: TsxModule, fragment: boolean, emit: Emit): void {
  const index = buildJsxIndex(module);
  for (const el of walkJsxElements(module)) {
    if (isComponent(el.tagName)) continue;
    const role = roleOf(getJsxAttributeString(el, "role"));
    if (role === "tab") {
      checkJsxTab(el, index, fragment, emit);
      continue;
    }
    if (role === "tabpanel") {
      checkJsxTabpanel(el, index, fragment, emit);
    }
  }
}

function buildJsxIndex(module: TsxModule): JsxIndex {
  const idToElement = new Map<string, JsxElement>();
  const panelIdToReferencingTabIds = new Map<string, string[]>();
  for (const el of walkJsxElements(module)) {
    if (isComponent(el.tagName)) continue;
    indexJsxElement(el, idToElement, panelIdToReferencingTabIds);
  }
  return { idToElement, panelIdToReferencingTabIds };
}

function indexJsxElement(
  el: JsxElement,
  idToElement: Map<string, JsxElement>,
  panelIdToReferencingTabIds: Map<string, string[]>,
): void {
  const id = getJsxAttributeString(el, "id");
  if (id !== null && id.length > 0 && !idToElement.has(id)) idToElement.set(id, el);
  if (roleOf(getJsxAttributeString(el, "role")) !== "tab") return;
  const ariaControls = getJsxAttributeString(el, "aria-controls");
  if (ariaControls === null) return;
  const tabId = getJsxAttributeString(el, "id") ?? "";
  for (const token of splitIdrefList(ariaControls)) {
    appendTabIdReference(panelIdToReferencingTabIds, token, tabId);
  }
}

function appendTabIdReference(
  panelIdToReferencingTabIds: Map<string, string[]>,
  panelId: string,
  tabId: string,
): void {
  const list = panelIdToReferencingTabIds.get(panelId);
  if (list) list.push(tabId);
  else panelIdToReferencingTabIds.set(panelId, [tabId]);
}

function checkJsxTab(el: JsxElement, index: JsxIndex, fragment: boolean, emit: Emit): void {
  if (!hasJsxAttribute(el, "aria-controls")) {
    emit(buildBranchAEmit(el.tagName, el.loc.start, false));
    return;
  }
  const ariaControls = getJsxAttributeString(el, "aria-controls");
  if (ariaControls === null) {
    // JSX expression (`aria-controls={panelId}`). The scanner can't
    // statically resolve the binding — surface as info so the agent
    // reads it; this is the same posture
    // `aria/labelledby-target-exists` takes for dynamic IDREFs.
    emit(buildJsxDynamicNote(el.tagName, el.loc.start));
    return;
  }
  const tokens = splitIdrefList(ariaControls);
  if (tokens.length === 0) {
    emit(buildBranchAEmit(el.tagName, el.loc.start, true));
    return;
  }
  const dangling: string[] = [];
  const wrongRole: { token: string; role: string }[] = [];
  for (const token of tokens) {
    const target = index.idToElement.get(token);
    if (!target) {
      dangling.push(token);
      continue;
    }
    if (roleOf(getJsxAttributeString(target, "role")) !== "tabpanel") {
      const rawRole = getJsxAttributeString(target, "role");
      wrongRole.push({ token, role: rawRole ?? `<${target.tagName}>` });
    }
  }
  if (dangling.length > 0 || wrongRole.length > 0) {
    emit(buildBranchBEmit(el.tagName, el.loc.start, ariaControls, dangling, wrongRole, fragment));
  }
}

function checkJsxTabpanel(el: JsxElement, index: JsxIndex, fragment: boolean, emit: Emit): void {
  if (hasJsxAttribute(el, "aria-labelledby")) return;
  const panelId = getJsxAttributeString(el, "id") ?? "";
  if (panelId.length > 0 && index.panelIdToReferencingTabIds.has(panelId)) return;
  emit(buildBranchCEmit(el.tagName, el.loc.start, panelId, fragment));
}

function isComponent(tagName: string): boolean {
  const first = tagName[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/**
 * Returns the first whitespace-separated `role` token if it matches a
 * known tabs-pattern role (`tab`, `tabpanel`), else null. WAI-ARIA
 * permits a space-separated list of fallback roles; the first listed
 * is the one assistive tech uses.
 */
function roleOf(raw: string | null): "tab" | "tabpanel" | null {
  if (raw === null) return null;
  for (const tok of raw.trim().split(/\s+/u)) {
    const lower = tok.toLowerCase();
    if (lower === "tab") return "tab";
    if (lower === "tabpanel") return "tabpanel";
    if (lower.length > 0) return null;
  }
  return null;
}

function splitIdrefList(raw: string): readonly string[] {
  return raw.split(/\s+/u).filter((t) => t.length > 0);
}

// ---------------------------------------------------------------------------
// Violation builders
// ---------------------------------------------------------------------------

function buildBranchAEmit(tagName: string, loc: Loc, emptyValue: boolean): Parameters<Emit>[0] {
  const valueClause = emptyValue
    ? ' (aria-controls=""): the attribute is present but names no panel id'
    : "";
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName} role="tab"> has no aria-controls attribute${valueClause} — assistive tech has no programmatic link to the panel this tab activates, so screen-reader users can hear the tab name but not the relationship to its panel.`,
    suggestion: `Add aria-controls="<panel-id>" to <${tagName}>, where <panel-id> matches the id on the matching <… role="tabpanel" id="<panel-id>">. The reciprocal half — aria-labelledby on the panel pointing back at this tab's id — is the canonical WAI-ARIA tabs wiring; pair them in the same edit.`,
  };
}

function buildBranchBEmit(
  tagName: string,
  loc: Loc,
  ariaControls: string,
  dangling: readonly string[],
  wrongRole: readonly { token: string; role: string }[],
  fragment: boolean,
): Parameters<Emit>[0] {
  const parts: string[] = [];
  if (dangling.length > 0) {
    parts.push(
      `${dangling.length === 1 ? "the token" : "tokens"} ${quoteList(dangling)} ${dangling.length === 1 ? "does" : "do"} not match any element's id in this file`,
    );
  }
  if (wrongRole.length > 0) {
    const wrongList = wrongRole
      .map((w) => `"${w.token}" resolves to an element with role="${w.role}", not role="tabpanel"`)
      .join("; ");
    parts.push(wrongList);
  }
  const breakdown = parts.join("; ");
  const fragmentSuffix = fragment
    ? " This file looks like a fragment / partial / component template — the panel may render in a sibling file (layout, include, route component) the scanner does not see in this scope."
    : "";
  const severity: Severity = fragment ? "info" : "error";
  const allBrokenTokens = [...dangling, ...wrongRole.map((w) => w.token)];
  const baseEmit = {
    severity,
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName} role="tab" aria-controls="${ariaControls}"> — ${breakdown}.${fragmentSuffix}`,
    suggestion: fragment
      ? `Verify the panel id${allBrokenTokens.length === 1 ? "" : "s"} ${quoteList(allBrokenTokens)} resolve${allBrokenTokens.length === 1 ? "s" : ""} to a <… role="tabpanel" id="…"> in the composed parent / sibling file. If the wire-up is verified at the integration level, suppress at the call site with a <!-- ra11y-disable aria/tab-controls-missing --> comment.`
      : `Either rename the tab's aria-controls to point at the existing tabpanel's id, or add role="tabpanel" id="${dangling[0] ?? wrongRole[0]?.token ?? "<panel-id>"}" to the element you intended as the panel. Each tab must reference a tabpanel by id; cross-file references are not supported by this rule (see <!-- ra11y-disable aria/tab-controls-missing --> if the target lives in a sibling file).`,
  };
  if (fragment) {
    return { ...baseEmit, couldBeWrongBecause: [FRAGMENT_CROSS_FILE_CODE] };
  }
  return baseEmit;
}

function buildBranchCEmit(
  tagName: string,
  loc: Loc,
  panelId: string,
  fragment: boolean,
): Parameters<Emit>[0] {
  const idClause = panelId.length > 0 ? ` id="${panelId}"` : "";
  const fragmentSuffix = fragment
    ? " This file looks like a fragment / partial / component template — the matching tab may render in a sibling file (layout, include, route component) the scanner does not see in this scope."
    : "";
  const severity: Severity = fragment ? "info" : "error";
  const fixIdRef = panelId.length > 0 ? panelId : "<panel-id>";
  const baseEmit = {
    severity,
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName} role="tabpanel"${idClause}> has no aria-labelledby attribute and no <… role="tab" aria-controls="${fixIdRef}"> in this file references it — the panel has no accessible name and assistive tech cannot announce which tab owns it.${fragmentSuffix}`,
    suggestion: fragment
      ? `Verify a <… role="tab" aria-controls="${fixIdRef}"> exists in the composed parent / sibling file (the tab's aria-controls is the reciprocal half of the relationship). If only the panel renders in this fragment and the tab is supplied at composition time, also add aria-labelledby="<tab-id>" so the panel carries an accessible name regardless of relationship resolution.`
      : `Add aria-labelledby="<tab-id>" to <${tagName}>, where <tab-id> matches the id on the <… role="tab"> that activates this panel. The reciprocal half — aria-controls="${fixIdRef}" on the tab pointing at this panel — is the canonical WAI-ARIA tabs wiring; pair them in the same edit.`,
  };
  if (fragment) {
    return { ...baseEmit, couldBeWrongBecause: [FRAGMENT_CROSS_FILE_CODE] };
  }
  return baseEmit;
}

function buildJsxDynamicNote(tagName: string, loc: Loc): Parameters<Emit>[0] {
  return {
    severity: "info",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName} role="tab" aria-controls={…}> uses a JSX expression — the scanner cannot statically resolve the panel id to verify a matching <… role="tabpanel"> exists in this file.`,
    suggestion: `Verify at the binding site that the expression resolves to the id of a <… role="tabpanel"> rendered alongside this tab. Common pattern: derive both the tab's aria-controls and the panel's id from the same useId() / generated value so they stay in lockstep.`,
  };
}

function quoteList(items: readonly string[]): string {
  return items.map((t) => `"${t}"`).join(", ");
}
