/**
 * Rule: aria/tablist-on-non-tab-container
 * Satisfies: wcag22:1.3.1, wcag21:1.3.1, wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#info-and-relationships
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > Information, structure, and relationships conveyed through
 * > presentation can be programmatically determined or are available
 * > in text.
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links, and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#info-and-relationships
 *
 * Fires when an element with `role="tablist"` contains zero descendants
 * carrying `role="tab"` at any depth. The canonical misuse is a panels
 * container — `<div class="tab-content" role="tablist">` housing children
 * marked `role="tabpanel"` — where the author put the `tablist` role on
 * the wrong half of the widget. Assistive tech then announces "tablist"
 * but tabs through panels instead of tab labels, breaking the entire
 * widget's programmatic relationship.
 *
 * Different from `aria/tab-widget-roles`, which fires from the tab
 * member's side (a `data-toggle="tab"` element with no `role="tab"`
 * etc.) — this rule fires from the *tablist* side, and is the
 * deterministic complement: a container that claims `role="tablist"`
 * must contain at least one element claiming `role="tab"`. The two
 * rules can co-fire on a half-built widget; that is intentional (each
 * surfaces a different gap so the agent can sequence the fix).
 *
 * Cross-file caveat. JSX modules and HTML fragments are file-scoped —
 * the tab member could live inside a sibling component or include the
 * scanner does not see in this scope. The rule sets
 * `crossFileCapable: false` and adds a structured
 * `couldBeWrongBecause` token on JSX and on HTML fragments so per-rule
 * coverage degrades to `medium` and per-finding consumers see the
 * limitation. The rule still emits at `error` on the in-template
 * structural fact that `role="tablist"` has no `role="tab"` descendant
 * — that fact is provable from this file alone — and the cross-file
 * code lets the agent verify whether a sibling carries the tab member.
 *
 * Spec links:
 *   - WAI-ARIA tablist role: https://www.w3.org/TR/wai-aria-1.2/#tablist
 *   - "Required Owned Elements" — tablist owns one or more tab
 *     elements: https://www.w3.org/TR/wai-aria-1.2/#mustContain
 *   - APG tabs pattern: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import { isFragmentFile } from "../../engine/layout-partial.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";

/**
 * Structured `couldBeWrongBecause` code attached to fragment / JSX
 * emissions where the tab member could conceivably live in a sibling
 * file. Mirrors the cross-file token shape used by `aria/tab-widget-roles`.
 */
const FRAGMENT_CROSS_FILE_CODE =
  "tablist-tab-may-live-in-sibling-template-id-resolution-is-file-scoped";

export const rule = defineRule({
  id: "aria/tablist-on-non-tab-container",
  satisfies: ["wcag22:1.3.1", "wcag21:1.3.1", "wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  // The tab member could conceivably live inside a sibling component or
  // include we do not see in this scope; declaring `crossFileCapable:
  // false` surfaces that gap as `coverageConfidence: "medium"` per ADR
  // 0026, and the cross-file code below carries it through to per-finding
  // `couldBeWrongBecause`.
  crossFileCapable: false,
  docs: {
    description:
      'role="tablist" element has no role="tab" descendant at any depth — assistive tech announces a tablist but the children are not tabs. Common misuse: putting role="tablist" on the panels container instead of the tab strip.',
    rationale:
      'The WAI-ARIA tabs pattern is a programmatic-role contract: a `tablist` is the container of one or more `tab` elements; each `tab` controls a `tabpanel`. The "Required Owned Elements" clause of the tablist role makes this normative — `role="tablist"` MUST contain at least one element with `role="tab"`. When the role lands on the wrong half of the widget (the canonical case is `<div class="tab-content" role="tablist">` housing `role="tabpanel"` children), screen readers announce "tab list" and then expose the panel content as if each panel were a tab. Keyboard users press the standard arrow-key tab-cycling shortcut and find themselves cycling through panel bodies instead of switching tabs. The visual layout still works for sighted users — the tabs above and the panels below render correctly — but the entire programmatic structure is inverted. This rule fires the moment we see a `role="tablist"` whose subtree contains zero `role="tab"` elements, since that is provable from this file alone.',
    goodExample: `<div role="tablist">
  <button role="tab" aria-selected="true" aria-controls="panel-1" id="tab-1">Tab 1</button>
  <button role="tab" aria-selected="false" aria-controls="panel-2" id="tab-2">Tab 2</button>
</div>
<div role="tabpanel" id="panel-1" aria-labelledby="tab-1">Panel 1</div>
<div role="tabpanel" id="panel-2" aria-labelledby="tab-2">Panel 2</div>`,
    badExample: `<div class="tab-content" role="tablist">
  <div role="tabpanel" id="panel-1">Panel 1</div>
  <div role="tabpanel" id="panel-2">Panel 2</div>
</div>`,
    normativeQuote:
      "Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.",
    references: [
      "https://www.w3.org/TR/WCAG22/#info-and-relationships",
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#tablist",
      "https://www.w3.org/TR/wai-aria-1.2/#tab",
      "https://www.w3.org/TR/wai-aria-1.2/#mustContain",
      "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(
        ctx.ast as HtmlDocument,
        ctx.source,
        ctx.filePath,
        ctx.markCrossFileCandidate,
        (v) => ctx.emit(v),
      );
      return;
    }
    if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, ctx.markCrossFileCandidate, (v) => ctx.emit(v));
    }
  },
});

function checkHtml(
  doc: HtmlDocument,
  source: string,
  filePath: string,
  markCrossFileCandidate: (() => void) | undefined,
  emit: Emit,
): void {
  const fragment = isFragmentFile(doc, source, filePath);
  const tablists = collectHtmlTablists(doc);
  if (tablists.length > 0) markCrossFileCandidate?.();
  for (const tablist of tablists) {
    const diagnosis = diagnoseHtmlTablist(tablist);
    if (diagnosis === null) continue;
    emit(buildHtmlEmit(tablist, diagnosis, fragment));
  }
}

function checkJsx(
  module: TsxModule,
  markCrossFileCandidate: (() => void) | undefined,
  emit: Emit,
): void {
  const tablists = collectJsxTablists(module);
  if (tablists.length > 0) markCrossFileCandidate?.();
  for (const tablist of tablists) {
    const diagnosis = diagnoseJsxTablist(tablist);
    if (diagnosis === null) continue;
    // JSX modules are file-scoped by design — treat as a fragment so
    // the cross-file enrichment fires.
    emit(buildJsxEmit(tablist, diagnosis, true));
  }
}

type Severity = "error" | "warning" | "info";
interface Emission {
  readonly severity: Severity;
  readonly location: { readonly filePath: string; readonly line: number; readonly column: number };
  readonly message: string;
  readonly suggestion: string;
  readonly couldBeWrongBecause?: readonly string[];
}
type Emit = (v: Emission) => void;

interface Diagnosis {
  /** Whether at least one descendant carries `role="tabpanel"`. */
  readonly hasTabpanelDescendant: boolean;
}

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function collectHtmlTablists(doc: HtmlDocument): readonly HtmlElement[] {
  const out: HtmlElement[] = [];
  for (const el of walkHtmlElements(doc)) {
    if (roleOf(getHtmlAttribute(el, "role")) === "tablist") out.push(el);
  }
  return out;
}

/**
 * Returns a {@link Diagnosis} when the tablist has zero `role="tab"`
 * descendants at any depth, else `null` (the rule does not fire).
 */
function diagnoseHtmlTablist(tablist: HtmlElement): Diagnosis | null {
  let hasTab = false;
  let hasTabpanel = false;
  for (const descendant of htmlDescendants(tablist)) {
    const role = roleOf(getHtmlAttribute(descendant, "role"));
    if (role === "tab") hasTab = true;
    else if (role === "tabpanel") hasTabpanel = true;
    if (hasTab) return null;
  }
  return { hasTabpanelDescendant: hasTabpanel };
}

function* htmlDescendants(root: HtmlElement): Iterable<HtmlElement> {
  yield* walkHtmlChildren(root.children);
}

function* walkHtmlChildren(nodes: readonly HtmlNode[]): Iterable<HtmlElement> {
  for (const node of nodes) {
    if (node.kind !== "HtmlElement") continue;
    yield node;
    yield* walkHtmlChildren(node.children);
  }
}

function buildHtmlEmit(tablist: HtmlElement, d: Diagnosis, fragment: boolean): Emission {
  const tagName = tablist.tagName;
  const directTabpanelChild = htmlDirectTabpanelChild(tablist);
  const reasonExtra = directTabpanelChild
    ? ` Worse, a direct child carries role="tabpanel" — the role looks like it landed on the panels container instead of the tab strip.`
    : d.hasTabpanelDescendant
      ? ` A descendant carries role="tabpanel"; the role may have been placed on the panels container instead of the tab strip.`
      : "";
  const fragmentSuffix = fragment
    ? " This file looks like a fragment / partial / component template — the tab strip may render in a sibling file the scanner does not see in this scope."
    : "";
  const base: Emission = {
    severity: "error",
    location: { filePath: "", line: tablist.loc.start.line, column: tablist.loc.start.column },
    message: `<${tagName} role="tablist"> has no descendant carrying role="tab" — assistive tech will announce a tablist but the children are not tabs.${reasonExtra}${fragmentSuffix}`,
    suggestion: buildSuggestion(tagName, d, directTabpanelChild !== null),
  };
  if (fragment) {
    return { ...base, couldBeWrongBecause: [FRAGMENT_CROSS_FILE_CODE] };
  }
  return base;
}

function htmlDirectTabpanelChild(tablist: HtmlElement): HtmlElement | null {
  for (const child of tablist.children) {
    if (child.kind !== "HtmlElement") continue;
    if (roleOf(getHtmlAttribute(child, "role")) === "tabpanel") return child;
  }
  return null;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function collectJsxTablists(module: TsxModule): readonly JsxElement[] {
  const out: JsxElement[] = [];
  for (const el of walkJsxElements(module)) {
    if (isComponent(el.tagName)) continue;
    if (roleOf(getJsxAttributeString(el, "role")) === "tablist") out.push(el);
  }
  return out;
}

function diagnoseJsxTablist(tablist: JsxElement): Diagnosis | null {
  let hasTab = false;
  let hasTabpanel = false;
  for (const descendant of jsxDescendants(tablist)) {
    if (isComponent(descendant.tagName)) {
      // A composed (Capitalized) descendant might wrap a `role="tab"`
      // member we cannot see — treat that subtree as opaque and let the
      // cross-file `couldBeWrongBecause` token carry the gap.
      return null;
    }
    const role = roleOf(getJsxAttributeString(descendant, "role"));
    if (role === "tab") hasTab = true;
    else if (role === "tabpanel") hasTabpanel = true;
    if (hasTab) return null;
  }
  return { hasTabpanelDescendant: hasTabpanel };
}

function* jsxDescendants(root: JsxElement): Iterable<JsxElement> {
  yield* walkJsxChildren(root.children);
}

function* walkJsxChildren(nodes: readonly JsxNode[]): Iterable<JsxElement> {
  for (const node of nodes) {
    if (node.kind !== "JsxElement") continue;
    yield node;
    yield* walkJsxChildren(node.children);
  }
}

function buildJsxEmit(tablist: JsxElement, d: Diagnosis, fragment: boolean): Emission {
  const tagName = tablist.tagName;
  const directTabpanelChild = jsxDirectTabpanelChild(tablist);
  const reasonExtra = directTabpanelChild
    ? ` Worse, a direct child carries role="tabpanel" — the role looks like it landed on the panels container instead of the tab strip.`
    : d.hasTabpanelDescendant
      ? ` A descendant carries role="tabpanel"; the role may have been placed on the panels container instead of the tab strip.`
      : "";
  const fragmentSuffix = fragment
    ? " JSX modules are file-scoped — the tab strip may render in a sibling component the scanner does not see in this scope."
    : "";
  const base: Emission = {
    severity: "error",
    location: { filePath: "", line: tablist.loc.start.line, column: tablist.loc.start.column },
    message: `<${tagName} role="tablist"> has no descendant carrying role="tab" — assistive tech will announce a tablist but the children are not tabs.${reasonExtra}${fragmentSuffix}`,
    suggestion: buildSuggestion(tagName, d, directTabpanelChild !== null),
  };
  if (fragment) {
    return { ...base, couldBeWrongBecause: [FRAGMENT_CROSS_FILE_CODE] };
  }
  return base;
}

function jsxDirectTabpanelChild(tablist: JsxElement): JsxElement | null {
  for (const child of tablist.children) {
    if (child.kind !== "JsxElement") continue;
    if (roleOf(getJsxAttributeString(child, "role")) === "tabpanel") return child;
  }
  return null;
}

function isComponent(tagName: string): boolean {
  const first = tagName[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/**
 * Returns the first whitespace-separated `role` token if it matches a
 * tabs-pattern role we recognize, else null. WAI-ARIA permits a
 * space-separated list of fallback roles; the first listed is the one
 * assistive tech uses.
 */
function roleOf(raw: string | null): "tab" | "tabpanel" | "tablist" | null {
  if (raw === null) return null;
  for (const tok of raw.trim().split(/\s+/u)) {
    const lower = tok.toLowerCase();
    if (lower === "tab") return "tab";
    if (lower === "tabpanel") return "tabpanel";
    if (lower === "tablist") return "tablist";
    if (lower.length > 0) return null;
  }
  return null;
}

function buildSuggestion(tagName: string, d: Diagnosis, directTabpanelChild: boolean): string {
  if (directTabpanelChild) {
    return `Move role="tablist" off <${tagName}> — its direct children are tabpanels, not tabs. Put role="tablist" on the element that wraps the tab buttons (the strip the user clicks to switch panels), and give each tab button role="tab" with aria-selected and aria-controls pointing at the corresponding tabpanel id. The WAI-ARIA Authoring Practices tabs pattern (https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) is the canonical reference.`;
  }
  if (d.hasTabpanelDescendant) {
    return `<${tagName} role="tablist"> contains tabpanel descendants but no role="tab" — the role may have landed on the panels container instead of the tab strip. Either move role="tablist" to the element that wraps the tab buttons and give each button role="tab", or remove role="tablist" from <${tagName}> if it is not actually a tab strip. See https://www.w3.org/WAI/ARIA/apg/patterns/tabs/.`;
  }
  return `Either add role="tab" to each child element that acts as a tab button (paired with aria-selected and aria-controls pointing at the matching tabpanel id), or remove role="tablist" from <${tagName}> if this container is not actually a tab strip. The tablist role is a contract: assistive tech announces "tab list, N tabs" and lets the user arrow-cycle through them, which only works when role="tab" descendants exist. See https://www.w3.org/WAI/ARIA/apg/patterns/tabs/.`;
}
