/**
 * Integration invariant: an authored static-asset under `public/`
 * (the Astro / Vite / Next / Nuxt static-assets convention) does NOT
 * land under `meta.scannedBuildArtifacts` via the build-dir-segment
 * classifier. The `public/` segment was previously listed in
 * {@link import("../../src/mcp/build-artifacts.ts").BUILD_DIR_MARKERS}
 * and emitted a `likely-bundler-output-dir` verdict — a heuristic-
 * mislabeled meta sub-field per `docs/kb/architecture/ai-first-consumer.md`
 * because `public/` is the canonical home for *user-authored* files
 * (favicons, brand marks, hero images) copied as-is to the build root,
 * not generated bytes.
 *
 * The fix dropped `public/` from the build-dir-segment list so authored
 * files there reach the agent's triage surface as ordinary findings
 * (or no findings, if no rule fires) rather than silently landing under
 * `scannedBuildArtifacts`, which downstream tools treat as
 * "not user-fixable."
 *
 * Pinned invariants on a `public/` corpus with no other classifier
 * signals (no `.min.` infix, no hashed filename, no sourcemap pair):
 *   - `meta.scannedBuildArtifacts` is undefined OR contains no entry
 *     whose path lies under `public/` and whose classification is
 *     `likely-bundler-output-dir`.
 *   - The deterministic vendor signals still classify when applicable:
 *     a `.min.css` file under `public/` still earns `definite-min-infix`
 *     via the path-anchored `.min.` predicate (sibling test below).
 */

import { describe, expect, it } from "bun:test";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { posixJoin } from "../helpers/path.ts";

const PROJECT_ROOT = posixJoin(import.meta.dir, "..", "..");

type JsonRpcResponse = Record<string, unknown>;

async function mcpSession(
  messages: readonly Record<string, unknown>[],
): Promise<JsonRpcResponse[]> {
  const proc = Bun.spawn(["bun", "run", "src/cli.ts", "--mcp"], {
    stdin: "pipe",
    stdout: "pipe",
    stderr: "pipe",
    cwd: PROJECT_ROOT,
  });
  const payload = `${messages.map((m) => JSON.stringify(m)).join("\n")}\n`;
  proc.stdin.write(payload);
  proc.stdin.end();
  const text = await new Response(proc.stdout).text();
  proc.kill();
  return text
    .trim()
    .split("\n")
    .filter((l) => l.length > 0)
    .map((l) => JSON.parse(l) as JsonRpcResponse);
}

function initMsg(id: number): Record<string, unknown> {
  return {
    jsonrpc: "2.0",
    id,
    method: "initialize",
    params: {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "test-agent", version: "1.0" },
    },
  };
}

function toolCall(
  id: number,
  name: string,
  args: Record<string, unknown>,
): Record<string, unknown> {
  return { jsonrpc: "2.0", id, method: "tools/call", params: { name, arguments: args } };
}

function bodyOf(response: JsonRpcResponse): Record<string, unknown> {
  const result = response.result as { content: Array<{ text: string }> };
  return JSON.parse(result.content[0].text) as Record<string, unknown>;
}

interface BuildArtifactClassificationItem {
  readonly kind: string;
  readonly classification: string;
  readonly signal?: { readonly kind: string; readonly value: string };
}

interface BuildArtifactClassifiedEntry {
  readonly path: string;
  readonly classifications: readonly BuildArtifactClassificationItem[];
}

interface BuildArtifactGroupEntry {
  readonly pathHint?: string;
  readonly classifications?: readonly BuildArtifactClassificationItem[];
}

interface ScannedBuildArtifactsEnvelope {
  readonly classified?: readonly BuildArtifactClassifiedEntry[];
  readonly grouped?: readonly BuildArtifactGroupEntry[];
}

function flatten(envelope: ScannedBuildArtifactsEnvelope | undefined): {
  readonly classified: readonly BuildArtifactClassifiedEntry[];
  readonly grouped: readonly BuildArtifactGroupEntry[];
} {
  return {
    classified: envelope?.classified ?? [],
    grouped: envelope?.grouped ?? [],
  };
}

describe("public/ as static-assets convention (not bundler-output)", () => {
  it("does NOT classify an authored .css file under public/ as `likely-bundler-output-dir`", async () => {
    const root = mkdtempSync(posixJoin(tmpdir(), "ra11y-public-static-assets-"));
    try {
      // Authored static asset shape — Astro/Vite/Next/Nuxt repos place
      // brand marks, favicons, and hand-written stylesheets here for
      // copy-as-is delivery. No `.min.` infix, no hashed filename, no
      // sourcemap sibling — the only path-segment signal that would
      // have classified the file pre-fix was `public/` itself.
      mkdirSync(posixJoin(root, "public"), { recursive: true });
      writeFileSync(
        posixJoin(root, "public", "brand.css"),
        ".brand { color: #112233; background-color: #ffeedd; }\n",
      );
      // An HTML page so the project also has a parseable input — keeps
      // the scan from short-circuiting on zero files.
      writeFileSync(
        posixJoin(root, "page.html"),
        '<!DOCTYPE html><html lang="en"><body><main><p>hi</p></main></body></html>\n',
      );

      const responses = await mcpSession([
        initMsg(1),
        toolCall(2, "scan_project", { cwd: root, additionalPaths: ["public"] }),
      ]);
      const scan = responses.find((r) => r.id === 2) as JsonRpcResponse;
      const body = bodyOf(scan);
      const meta = body.meta as Record<string, unknown> | undefined;
      const sba = meta?.scannedBuildArtifacts as ScannedBuildArtifactsEnvelope | undefined;
      const { classified, grouped } = flatten(sba);

      // No classified entry under `public/` should carry the
      // `likely-bundler-output-dir` verdict from the
      // `build-dir-segment` signal where `value === "public/"`. The
      // honest verdict is "no classification on this file," not "a
      // classification with a different reason."
      const offenders = classified.flatMap((e) => {
        if (typeof e.path !== "string" || !e.path.includes("public/")) return [];
        return e.classifications.filter(
          (c) =>
            c.classification === "likely-bundler-output-dir" &&
            c.signal?.kind === "build-dir-segment" &&
            c.signal?.value === "public/",
        );
      });
      expect(offenders).toEqual([]);

      // Same invariant on grouped entries (which carry pathHint
      // instead of a per-path entry).
      const groupedOffenders = grouped.flatMap((g) => {
        if (typeof g.pathHint !== "string" || !g.pathHint.includes("public/")) return [];
        return (g.classifications ?? []).filter(
          (c) =>
            c.classification === "likely-bundler-output-dir" &&
            c.signal?.kind === "build-dir-segment" &&
            c.signal?.value === "public/",
        );
      });
      expect(groupedOffenders).toEqual([]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("DOES still classify a `.min.css` under public/ via the deterministic `.min.` infix", async () => {
    // Symmetric guard: dropping `public/` from the build-dir-segment
    // list must NOT regress the deterministic vendor signals. A
    // minified vendor bundle that happens to live under `public/`
    // (a common shipping pattern for `bootstrap.min.css`,
    // `tailwind.min.css`) still earns `definite-min-infix` via the
    // path-anchored `.min.` predicate — that signal is independent
    // of the directory marker and survives the doctrine bar.
    const root = mkdtempSync(posixJoin(tmpdir(), "ra11y-public-min-vendor-"));
    try {
      mkdirSync(posixJoin(root, "public"), { recursive: true });
      writeFileSync(
        posixJoin(root, "public", "bootstrap.min.css"),
        ".faded { color: #444444; background-color: #5a5a5a; }\n",
      );
      writeFileSync(
        posixJoin(root, "page.html"),
        '<!DOCTYPE html><html lang="en"><body><main><p>hi</p></main></body></html>\n',
      );
      const responses = await mcpSession([
        initMsg(1),
        toolCall(2, "scan_project", { cwd: root, additionalPaths: ["public"] }),
      ]);
      const scan = responses.find((r) => r.id === 2) as JsonRpcResponse;
      const body = bodyOf(scan);
      const meta = body.meta as Record<string, unknown> | undefined;
      const sba = meta?.scannedBuildArtifacts as ScannedBuildArtifactsEnvelope | undefined;
      const { classified } = flatten(sba);
      const entry = classified.find(
        (e) => typeof e.path === "string" && e.path.endsWith("bootstrap.min.css"),
      );
      expect(entry, "bootstrap.min.css should be in scannedBuildArtifacts").toBeDefined();
      const minInfix = entry?.classifications.find(
        (c) => c.classification === "definite-min-infix",
      );
      expect(
        minInfix,
        "bootstrap.min.css should classify via .min. infix predicate",
      ).toBeDefined();
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
