/**
 * Cross-surface invariant: `scan_file` and `scan_project` on the
 * identical minified vendor stylesheet must classify the file the
 * same way — `meta.scannedBuildArtifacts` populated on both, AND
 * `plan.violationsByScanKind` populated on both with findings routed
 * into the `buildArtifact` lane (not the `source` lane).
 *
 * Pre-fix bug: `scan_file` on a vendor `.min.css` (e.g.
 * `bootstrap.min.css`) emitted N error+warning findings classified
 * silently under the `source` lane (`plan.violationsByScanKind` was
 * `undefined`), while `scan_project` on the same path classified the
 * file as a build artifact and split the findings into the
 * `buildArtifact` lane. An agent calling `scan_file` got a different
 * mental model of the same input than `scan_project` would have given
 * — the `buildArtifact` lane label is the load-bearing signal that
 * tells the agent "this file is generated bytes; the productive
 * triage is `propose_config` exclude, not a fix attempt."
 *
 * Doctrine: `docs/kb/architecture/ai-first-consumer.md` "Per-tool lane
 * and warning-set classification must agree." The closure: `scan_file`
 * routes the same `collectBuildArtifacts` predicate against its single
 * parsed file and threads the resulting vendor path set through
 * `withViolationsByScanKind` so the per-kind plan stamp matches what
 * `scan_project` produces.
 *
 * End-to-end through the MCP server (stdio JSON-RPC) so the assertion
 * exercises the full response-assembly path on both tools.
 */

import { describe, expect, it } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const PROJECT_ROOT = join(import.meta.dir, "..", "..");

type JsonRpcResponse = Record<string, unknown>;

async function mcpSession(
  messages: readonly Record<string, unknown>[],
): Promise<JsonRpcResponse[]> {
  const proc = Bun.spawn(["bun", "run", "src/cli.ts", "--mcp"], {
    stdin: "pipe",
    stdout: "pipe",
    stderr: "pipe",
    cwd: PROJECT_ROOT,
  });
  const payload = `${messages.map((m) => JSON.stringify(m)).join("\n")}\n`;
  proc.stdin.write(payload);
  proc.stdin.end();
  const text = await new Response(proc.stdout).text();
  proc.kill();
  return text
    .trim()
    .split("\n")
    .filter((l) => l.length > 0)
    .map((l) => JSON.parse(l) as JsonRpcResponse);
}

function initMsg(id: number): Record<string, unknown> {
  return {
    jsonrpc: "2.0",
    id,
    method: "initialize",
    params: {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "test-agent", version: "1.0" },
    },
  };
}

function toolCall(
  id: number,
  name: string,
  args: Record<string, unknown>,
): Record<string, unknown> {
  return { jsonrpc: "2.0", id, method: "tools/call", params: { name, arguments: args } };
}

function bodyOf(response: JsonRpcResponse): Record<string, unknown> {
  const result = response.result as { content: Array<{ text: string }> };
  return JSON.parse(result.content[0].text) as Record<string, unknown>;
}

describe("scan_file vs scan_project: build-artifact lane parity", () => {
  it("classifies a minified vendor stylesheet under the buildArtifact lane on both surfaces", async () => {
    const root = mkdtempSync(join(tmpdir(), "ra11y-scan-file-lane-parity-"));
    try {
      // Minified vendor stylesheet — `.min.` infix is the canonical
      // path-deterministic minified marker the classifier reads as
      // `definite-min-infix`. Carries one contrast violation so both
      // surfaces have a finding to route into the per-kind lane.
      const vendorPath = join(root, "bootstrap.min.css");
      writeFileSync(vendorPath, ".faded { color: #444444; background-color: #5a5a5a; }\n");
      const responses = await mcpSession([
        initMsg(1),
        toolCall(2, "scan_file", { path: vendorPath }),
        toolCall(3, "scan_project", { cwd: root }),
      ]);
      const scanFile = responses.find((r) => r.id === 2);
      const scanProject = responses.find((r) => r.id === 3);
      expect(scanFile).toBeDefined();
      expect(scanProject).toBeDefined();
      const scanFileBody = bodyOf(scanFile as JsonRpcResponse);
      const scanProjectBody = bodyOf(scanProject as JsonRpcResponse);

      // Both surfaces must carry `meta.scannedBuildArtifacts` —
      // sibling assertion that the classifier ran and identified
      // the file on both surfaces. The `applyCrossSurfaceWarnings`
      // helper closed the meta-side gap; this fix closes the plan
      // side.
      const scanFileMeta = scanFileBody["meta"] as Record<string, unknown> | undefined;
      const scanProjectMeta = scanProjectBody["meta"] as Record<string, unknown> | undefined;
      expect(scanFileMeta?.["scannedBuildArtifacts"]).toBeDefined();
      expect(scanProjectMeta?.["scannedBuildArtifacts"]).toBeDefined();

      // Both surfaces must populate `plan.violationsByScanKind` —
      // the load-bearing structural signal the AI-first doctrine
      // pins. Pre-fix, `scan_file` shipped `plan.violationsByScanKind:
      // undefined` (silent drop into the `source` lane).
      const scanFilePlan = scanFileBody["plan"] as Record<string, unknown> | undefined;
      const scanProjectPlan = scanProjectBody["plan"] as Record<string, unknown> | undefined;
      const scanFileLanes = scanFilePlan?.["violationsByScanKind"] as
        | { source: number; buildArtifact: number }
        | undefined;
      const scanProjectLanes = scanProjectPlan?.["violationsByScanKind"] as
        | { source: number; buildArtifact: number }
        | undefined;
      expect(scanFileLanes).toBeDefined();
      expect(scanProjectLanes).toBeDefined();

      // Both surfaces must route the contrast violation into the
      // `buildArtifact` lane — the file IS a build artifact, so the
      // honest split puts every error+warning finding there. Source
      // lane is zero on both because the only scanned file is the
      // vendor stylesheet itself (scan_file scans only the file
      // passed; scan_project on this single-file root scans only it).
      expect(scanFileLanes?.buildArtifact).toBeGreaterThan(0);
      expect(scanFileLanes?.source).toBe(0);
      expect(scanProjectLanes?.buildArtifact).toBeGreaterThan(0);
      expect(scanProjectLanes?.source).toBe(0);

      // Cross-surface count parity: the per-kind tallies match
      // exactly between the two surfaces on identical input. Drift
      // here is the silent-miss failure mode the cross-surface count
      // invariant exists to prevent.
      expect(scanFileLanes?.buildArtifact).toBe(scanProjectLanes?.buildArtifact ?? -1);
      expect(scanFileLanes?.source).toBe(scanProjectLanes?.source ?? -1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("omits plan.violationsByScanKind on scan_file when the file is not a build artifact (present-when-meaningful)", async () => {
    const root = mkdtempSync(join(tmpdir(), "ra11y-scan-file-lane-clean-"));
    try {
      // Authored CSS with a contrast violation — no build-artifact
      // signal in the path or content, so the classifier produces an
      // empty path set and the per-kind stamp is omitted per
      // CLAUDE.md §1 "Ambiguous field shapes are dishonest." Mirrors
      // the `scan_project` no-artifacts assertion in
      // `mcp-scan-project-violations-by-scan-kind.test.ts` so both
      // surfaces share the present-when-meaningful contract.
      const sourcePath = join(root, "site.css");
      writeFileSync(sourcePath, ".muted { color: #555555; background-color: #4a4a4a; }\n");
      const responses = await mcpSession([
        initMsg(1),
        toolCall(2, "scan_file", { path: sourcePath }),
      ]);
      const scanFile = responses.find((r) => r.id === 2);
      expect(scanFile).toBeDefined();
      const body = bodyOf(scanFile as JsonRpcResponse);
      const plan = body["plan"] as Record<string, unknown> | undefined;
      const meta = body["meta"] as Record<string, unknown> | undefined;
      // The classifier ran (the absence of `meta.scannedBuildArtifacts`
      // confirms it produced nothing) — the omission is honest, not a
      // wiring miss.
      expect(meta?.["scannedBuildArtifacts"]).toBeUndefined();
      // Field is absent on the no-artifacts common case, matching
      // `scan_project`'s behavior on the same shape.
      expect(plan?.["violationsByScanKind"]).toBeUndefined();
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
