/**
 * Per-finding confidence parity with build-artifact classification.
 *
 * Sibling of {@link import("./per-finding-confidence-parity.ts")} but
 * keyed on per-FILE evidence (`scannedBuildArtifacts` membership) rather
 * than per-RULE coverage degradation. Same shape, different axis:
 * agents read `meta.scannedBuildArtifacts` to know "this file is
 * generated bytes, not authored source," then read per-finding
 * `confidence` / `couldBeWrongBecause` to know how much weight each
 * finding inside that file deserves. Without this enrichment the two
 * surfaces disagree silently — the agent sees a file under
 * `scannedBuildArtifacts` AND a `confidence: "high"` finding inside it
 * from the same scan, exactly the contradictory shape the doctrine
 * names.
 *
 * Doctrine source: docs/kb/architecture/ai-first-consumer.md
 *   "Per-finding confidence must reflect per-rule coverage limitations."
 *   The same invariant applies one axis over: per-finding confidence
 *   must reflect per-file evidence-strength downgrades the response
 *   already surfaces on a sibling field.
 *
 * Scope is narrow: only `keyboard/handler-missing` is currently
 * enriched. The rule's external-JS handler grammar and HTML-attribute
 * grammar both fire deterministically inside bundled JS distributions
 * (jQuery, Bootstrap, livereload, etc.) where the click attach is part
 * of a framework's event-delegation machinery — Bootstrap wires
 * `data-bs-toggle` clicks via a single document-level listener, jQuery
 * `$(selector).on('click', …)` does similar — and the receiver's
 * keyboard wiring lives in the same delegation table out of view of a
 * static `addEventListener` / inline-attribute scan. The static
 * predicate is honest at the rule's evidence horizon (no keyboard
 * sibling on this attach site); the file's classification (definite-
 * vendor-distribution, definite-min-infix, likely-minified-by-line-
 * stats) is honest at the corpus level. Mediating between them with a
 * `confidence: "low"` + `couldBeWrongBecause:
 * ["fired_inside_bundled_js_likely_framework_event_delegation"]` is the
 * cross-surface honest shape — the rule still emits (surface, don't
 * suppress), the agent reads the bundled-JS context and decides.
 *
 * Other rules can opt in by extending {@link RULES_GATED_ON_BUILD_ARTIFACT_PATH}
 * — same shape, different reason code per rule. The set is intentionally
 * narrow; broad opt-in would re-introduce the silent-miss failure mode
 * the doctrine warns against ("under-surfacing → a real violation never
 * reaches the agent"). Every entry below names a rule whose static
 * predicate is structurally weaker on minified/bundled bytes than on
 * authored source — not "the bytes look noisy."
 */

import type { AgentFinding } from "../output/agent-response/types.ts";
import type { FindingBucket } from "./per-finding-confidence-parity.ts";

/**
 * Rule-ID → reason-code map for build-artifact-gated downgrade. Each
 * entry names a rule whose static evidence model is structurally bounded
 * inside generated/bundled bytes — typically because the rule fires on
 * a click-attach site whose paired keyboard wiring lives in a framework
 * event-delegation table the rule cannot see. The reason code is the
 * snake_case identifier the agent matches on `couldBeWrongBecause`.
 *
 * `keyboard/handler-missing`: same-file `.click()` attach with no paired
 * `keydown`/`keyup` is the canonical false-positive shape inside jQuery
 * bundles, Bootstrap dist, livereload, and similar — the framework
 * registers ONE document-level click listener and dispatches via
 * delegation to selectors written elsewhere in the bundle, so the
 * file-local keyboard sibling never appears.
 */
const RULES_GATED_ON_BUILD_ARTIFACT_PATH: ReadonlyMap<string, string> = new Map<string, string>([
  ["keyboard/handler-missing", "fired_inside_bundled_js_likely_framework_event_delegation"],
]);

/**
 * Walks per-file findings and downgrades `confidence` to `"low"` plus
 * appends the per-rule reason code into `couldBeWrongBecause` for any
 * finding from {@link RULES_GATED_ON_BUILD_ARTIFACT_PATH} whose hosting
 * file is in `buildArtifactPaths`. Returns the input array reference
 * unchanged when `buildArtifactPaths` is empty (no-op fast path) — the
 * common case on authored-source repos stays cheap.
 *
 * Per CLAUDE.md §1 "Ambiguous field shapes are dishonest": when a
 * finding already carries the propagated code, the finding is returned
 * unchanged — the agent's `couldBeWrongBecause` array stays dedup-
 * stable. Confidence is only re-stamped when the rewrite actually
 * changes the value (a finding already at `"low"` or `"medium"` keeps
 * its existing label; only the `"high"` → `"low"` transition shifts).
 *
 * Returns a fresh top-level array when any finding was rewritten;
 * unchanged buckets ride the original reference.
 */
export function enrichFindingsWithBuildArtifactPath<T extends FindingBucket>(
  fileEntries: readonly T[],
  buildArtifactPaths: ReadonlySet<string>,
): readonly T[] {
  if (buildArtifactPaths.size === 0) return fileEntries;
  let mutatedAny = false;
  const out = fileEntries.map((file) => {
    if (!buildArtifactPaths.has(file.path)) return file;
    let bucketMutated = false;
    const findings = file.findings.map((finding) => {
      const code = RULES_GATED_ON_BUILD_ARTIFACT_PATH.get(finding.ruleId);
      if (code === undefined) return finding;
      const existing = finding.couldBeWrongBecause;
      const alreadyHasCode = existing?.includes(code) === true;
      const alreadyDowngraded = finding.confidence === "low";
      if (alreadyHasCode && alreadyDowngraded) return finding;
      bucketMutated = true;
      const next: AgentFinding = {
        ...finding,
        confidence: "low",
        couldBeWrongBecause: alreadyHasCode
          ? (existing as readonly string[])
          : existing === undefined || existing.length === 0
            ? [code]
            : [...existing, code],
      };
      return next;
    });
    if (!bucketMutated) return file;
    mutatedAny = true;
    return { ...file, findings };
  });
  return mutatedAny ? out : fileEntries;
}
