/**
 * Rule: keyboard/handler-missing
 * Satisfies: wcag22:2.1.1, wcag21:2.1.1, wcag22:4.1.2, wcag21:4.1.2
 * Spec:
 *   - https://www.w3.org/TR/WCAG22/#keyboard
 *   - https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > All functionality of the content is operable through a keyboard
 * > interface without requiring specific timings for individual
 * > keystrokes. (SC 2.1.1 Keyboard)
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined. (SC 4.1.2 Name,
 * > Role, Value)
 *
 * Source: https://www.w3.org/TR/WCAG22/#keyboard
 *
 * Flags JSX/HTML elements that declare interactive behavior on a
 * non-interactive element without a keyboard pathway. Two failure
 * grammars are covered:
 *
 * 1. Event-handler grammar — `onclick="…"` in HTML or `onClick={…}`
 *    in JSX on a bare `<div>`/`<span>` with no `onkeydown`/`onkeyup`.
 *    Mouse users can click it; keyboard users can't reach it or
 *    press Enter to activate it.
 * 2. Attribute-interaction grammar — Bootstrap's `data-bs-dismiss`
 *    (always a click trigger) and `data-bs-toggle` with a disclosure
 *    value (`modal`, `tooltip`, `popover`, `collapse`, `offcanvas`,
 *    `dropdown`, `tab`, `pill`) declare interactive behavior at the
 *    attribute level. Bootstrap's JS wires up the click handler, but
 *    on a bare `<div>`/`<span>` the element is never focusable and
 *    Enter/Space never activate it. Putting these attributes on a
 *    `<button>` or `<a href>` is fine — both are focusable and
 *    keyboard-activate natively. Two BS attribute shapes are
 *    deliberately exempt from this grammar:
 *      - `data-bs-toggle="buttons"` — the value is a *container*
 *        signal that wires toggle behavior on child <input> controls,
 *        not on the host. Flagging the container would push the agent
 *        toward `<button>` wrappers that nest interactive descendants.
 *      - `data-bs-ride="carousel"` (and `data-bs-ride="true"`, plus
 *        the BS4 `data-ride` predecessor) — auto-init signal to
 *        Bootstrap's JS that instantiates the Carousel component on
 *        the host. The host never becomes focusable; the keyboard
 *        triggers are child <button> control elements.
 *    Both exemptions are guarded by real-world fixtures
 *    (`btn-group/`, `carousel-ride/`).
 * 3. External-JS handler grammar — vanilla-JS apps attach click
 *    handlers in a standalone `.js`/`.ts` file via
 *    `el.addEventListener('click', fn)` or `el.onclick = fn` after
 *    grabbing the element with `document.querySelector` /
 *    `document.getElementById` / `document.getElementsByClassName`.
 *    When the same variable isn't also wired up to a keyboard event
 *    (`keydown` / `keyup` / `keypress`, or an `.onkeydown` /
 *    `.onkeyup` assignment) anywhere in the same source file, the
 *    target is keyboard-unreachable for the same reason. Static
 *    scope is deliberately same-file: the agent reading the cited
 *    line can trace the selector across files faster than an
 *    in-process cross-file resolver could, and a silent wrong
 *    cross-file guess is worse than pointing honestly. One same-file
 *    suppression IS in scope: when the click-attach target was bound
 *    from `document.createElement('button'|'a'|'input'|'select'|
 *    'textarea'|'summary')`, the receiver IS a native interactive
 *    element and the missing keyboard sibling is not a finding —
 *    buttons/anchors/inputs are focusable and Enter/Space activate
 *    them by construction. The createElement tag is provable from the
 *    code in the same file, so the suppression is deterministic, not
 *    heuristic.
 * 4. Drag grammar — `draggable="true"` on a bare `<div>`/`<span>`
 *    declares a drag operation at the attribute level. Mouse users
 *    can grab and drop; keyboard users can't. Composes with
 *    `pointer/drag-alternative` (SC 2.5.7): a draggable element
 *    without keyboard wiring violates BOTH 2.1.1 (no keyboard way to
 *    activate) AND 2.5.7 (no single-pointer-without-drag
 *    alternative). Each rule emits its own finding with its own fix
 *    path — tabIndex+onKeyDown for 2.1.1, a sibling button or click
 *    handler for 2.5.7 — per the AI-first doctrine that two honest
 *    findings are better than silent suppression.
 *
 * Non-interactive means: any element that isn't a native interactive
 * element (a[href], button, input, select, textarea, summary) and
 * doesn't have role="button" / role="link". `<a>` with any non-null
 * href value — including `href="#"` — is focusable and Enter
 * activates it, so it's exempt from the attribute-interaction check
 * even though the URL is degenerate. `<a>` without href is flagged
 * separately because it is not focusable at all.
 *
 * Test-file substrate gate: when the input file path matches a test
 * shape (`*.test.{js,ts,jsx,tsx}`, `*.spec.{js,ts,jsx,tsx}`, or any
 * path containing a `__tests__` / `__mocks__` / `tests` segment), the
 * rule omits emission for the whole file. The runtime narrative
 * (focus, Enter/Space, keyboard reachability) presumes a rendered
 * consumer page; test files have no rendered DOM, so the message
 * "keyboard users can't activate the target" is meaningless on this
 * substrate. The path shape is deterministic (provable from the
 * string alone), so the gate is the symmetric twin of "no heuristic
 * emission" — fact, not heuristic. See `src/utils/path.ts`'s
 * `isTestFilePath` for the predicate.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  findHtmlElementsByTag,
  findJsxElementsByTag,
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, TsxModule } from "../../types/ast.ts";
import { isTestFilePath } from "../../utils/path.ts";
import {
  type CrossFileEnrichable,
  detectExternalScriptSrc,
  detectSiblingModuleImport,
  enrichExternalJsFinding,
  enrichForCrossFileScript,
} from "./handler-missing-cross-file.ts";
import { findExternalJsHandlerMissing } from "./handler-missing-external-js.ts";

/** HTML tags that are natively interactive and therefore exempt. */
const NATIVELY_INTERACTIVE_TAGS: ReadonlySet<string> = new Set([
  "a",
  "button",
  "input",
  "select",
  "textarea",
  "summary",
]);

/**
 * Disclosure values for `data-bs-toggle` (Bootstrap 5) /
 * `data-toggle` (Bootstrap 4) — when one of these appears as the
 * attribute value, the host element IS the click trigger (Bootstrap's
 * JS wires a click handler on the host that opens/dismisses the named
 * widget). On a bare `<div>`/`<span>` with no keyboard wiring, the
 * widget is invisible to keyboard users — that's the SC 2.1.1
 * failure this rule targets.
 *
 * Container values like `buttons` are NOT in this set: the host is a
 * group container whose interactive behavior is wired on child
 * `<input type="checkbox"|"radio">` controls, never on the container
 * itself. Flagging the container would push the agent toward
 * `<button>` wrappers that nest interactive descendants — a worse
 * a11y bug than the false positive that motivated the reading. See
 * the FP locked in by tests/fixtures/real-world/btn-group/.
 *
 * The allowlist is intentional: heuristic-suppression is the wrong
 * move (false-positive on a misnamed value), but explicit
 * value-based grammar is correct here — every entry below is a
 * proven Bootstrap disclosure idiom whose host element is the
 * trigger by design.
 */
const DISCLOSURE_TOGGLE_VALUES: ReadonlySet<string> = new Set([
  "modal",
  "tooltip",
  "popover",
  "collapse",
  "offcanvas",
  "dropdown",
  "tab",
  "pill", // Bootstrap nav-pills uses `data-bs-toggle="pill"` — same trigger semantics as "tab".
]);

/**
 * Attributes that ALWAYS declare a click trigger on the host element,
 * regardless of value. `data-bs-dismiss="modal"` and the BS4
 * `data-dismiss` predecessor wire a click-to-close handler on the host
 * that closes the named widget — putting them on a bare <div>/<span>
 * leaves the dismiss invisible to keyboard users.
 *
 * Attributes excluded from this list and handled separately:
 *   - `data-bs-toggle` / `data-toggle` — value-dependent (only
 *     disclosure values trigger; container values like `buttons`
 *     exempt the host).
 *   - `data-bs-ride` / `data-ride` — auto-init signals to Bootstrap's
 *     JS, NOT click triggers. The host (e.g. a carousel <div>) never
 *     receives focus and Enter/Space on it does nothing; the
 *     keyboard-operable controls are child <button>s. See the FP
 *     locked in by tests/fixtures/real-world/carousel-ride/.
 *   - `data-bs-target` / `data-target` — reference attributes (point
 *     at the controlled widget); they do not by themselves wire a
 *     click handler. The trigger comes from the sibling `data-bs-toggle`.
 *
 * Attributes are lowercased; HTML attribute comparison is already
 * case-insensitive via `getHtmlAttribute`.
 */
const ALWAYS_INTERACTIVE_ATTRIBUTES: readonly string[] = ["data-bs-dismiss", "data-dismiss"];

/** Attributes whose value determines whether the host is a click trigger. */
const VALUE_DEPENDENT_TOGGLE_ATTRIBUTES: readonly string[] = ["data-bs-toggle", "data-toggle"];

export const rule = defineRule({
  id: "keyboard/handler-missing",
  satisfies: ["wcag22:2.1.1", "wcag21:2.1.1", "wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx", ".ts", ".js"],
  },
  // SC 2.1.1 ("operable through a keyboard interface") spans
  // cross-file wiring: a click handler may be attached from a sibling
  // `.js` file via `addEventListener` after a `document.querySelector`
  // grab. The external-JS grammar scans the JS file it was invoked
  // against, but the HTML-on-this-call perspective is bounded to the
  // current document — the scanner cannot resolve across files in one
  // invocation. Declaring `crossFileCapable: false` downgrades a
  // clean tally on HTML substrates to `coverageConfidence: "medium"`
  // with `reason: "cross_file_listener_resolution_not_attempted_by_rule"`
  // per ADR 0026 — honest "the rule ran but its evidence was bounded"
  // in place of a silent-miss `"high"`.
  crossFileCapable: false,
  docs: {
    description:
      "Elements that declare click or toggle behavior (onClick, data-bs-toggle, etc.) must be reachable by keyboard: use a native button/link or add tabIndex plus an onKeyDown/onKeyUp that handles Enter and Space.",
    rationale:
      "Mouse users can click anywhere; keyboard users can't. An onClick on a bare <div>, or a Bootstrap-style data-bs-dismiss / data-bs-toggle (with a disclosure value like modal/dropdown/collapse/tab/tooltip/popover/offcanvas/pill) on a <div> or <span>, means the functionality is invisible to people who navigate with the keyboard — blind users, motor-impaired users, and anyone without a mouse. The attribute-based grammar is especially dangerous because the interaction still works for mouse users (Bootstrap's JS listens for click), so the bug is silent during sighted testing. The fix is almost always to host the attribute on a <button> instead. Two BS attribute shapes are exempt from this grammar: `data-bs-toggle=\"buttons\"` (a group-container value that wires interactivity on child <input> controls, not the host) and `data-bs-ride` of any value (auto-init signal that instantiates the Carousel component on the host but never makes the host itself a click trigger). Pause/stop concerns for `data-bs-ride` carousels live in motion/pause-stop-hide (SC 2.2.2), not here.",
    goodExample: `<button type="button" data-bs-toggle="modal" data-bs-target="#my-modal">Open</button>`,
    badExample: `<div data-bs-toggle="modal" data-bs-target="#my-modal">Open</div>`,
    normativeQuote: "All functionality of the content is operable through a keyboard interface.",
    references: [
      "https://www.w3.org/TR/WCAG22/#keyboard",
      "https://www.w3.org/WAI/WCAG22/Techniques/general/G202",
      "https://www.w3.org/WAI/ARIA/apg/patterns/button/",
    ],
  },
  check(ctx) {
    // Test-file substrate gate — `*.test.{js,ts,jsx,tsx}`,
    // `*.spec.{...}`, and `__tests__/` / `__mocks__/` / `tests/`
    // segments. The rule's narrative ("keyboard users can't activate
    // the target") is a runtime claim about a rendered DOM; a test
    // file or test fixture has no rendered consumer page, so the
    // emission would budget the agent's attention against a runtime
    // failure mode that doesn't apply to this substrate. The path
    // shape is *deterministic* (provable from the string alone), so
    // omitting on this predicate is not heuristic suppression — it's
    // the symmetric twin of "no heuristic emission" (per AI-first
    // doctrine), pointing at fact rather than guess.
    if (isTestFilePath(ctx.filePath)) return;
    if (ctx.language === "html") {
      const doc = ctx.ast as HtmlDocument;
      const externalScript = detectExternalScriptSrc(doc);
      // Cross-file-candidate signal: an external `<script src>` is the
      // exact token whose body might wire the keyboard handler. Bump
      // the tracker once when the document carries one — files with
      // no external script have no cross-file question for the rule
      // to have missed (per-rule-coverage stays at `"high"`).
      if (externalScript !== null && ctx.markCrossFileCandidate) ctx.markCrossFileCandidate();
      checkHtml(doc, (v) => ctx.emit(enrichForCrossFileScript(v, externalScript)));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      const siblingImport = detectSiblingModuleImport(ctx.source);
      // Same gate, JSX axis: a sibling-module import is the cross-file
      // candidate. Bump only when one is detected.
      if (siblingImport !== null && ctx.markCrossFileCandidate) ctx.markCrossFileCandidate();
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(enrichForCrossFileScript(v, siblingImport)));
    }
  },
  afterFile(ctx) {
    // External-JS handler grammar — fires on JSX/TSX/TS/JS files that
    // attach click listeners to a variable via `addEventListener` or
    // `.onclick = …`. Independent of the JSX-node walk because the
    // TSX parser only exposes JSX elements, not arbitrary JS
    // expressions; the detector scans `ctx.source` directly.
    if (
      ctx.language !== "tsx" &&
      ctx.language !== "jsx" &&
      ctx.language !== "ts" &&
      ctx.language !== "js"
    ) {
      return;
    }
    // Same test-file gate as `check()` — a `.spec.js` file with
    // `addEventListener('click', …)` is exercising a click handler in
    // the suite, not declaring a runtime click trigger on a rendered
    // page. Without this gate the external-JS grammar fires on every
    // unit test that covers a click path, narrating "keyboard users
    // can't activate the target" against a substrate where there is
    // no DOM in play. See the doctrine cite on `check()`.
    if (isTestFilePath(ctx.filePath)) return;
    const siblingImport = detectSiblingModuleImport(ctx.source);
    for (const finding of findExternalJsHandlerMissing(ctx.source)) {
      const base = {
        severity: "error" as const,
        location: { filePath: ctx.filePath, line: finding.line, column: finding.column },
        message: finding.message,
        suggestion: finding.suggestion,
      };
      // Q9 dynamic-creation extension: when the click-attach target was
      // bound from `document.createElement('<non-interactive-tag>')` in
      // this same file, the receiver's kind is provable from the code
      // here — no HTML grep is needed. Skip the unconditional
      // cross-file downgrade (which would stamp `confidence: "medium"`
      // and downgrade severity to `warning`) so the finding's
      // attention-budget signals reflect the in-file evidence the rule
      // actually has. The reason text and message already cite the
      // `createElement('<tag>')` evidence, so `severity: "error"` /
      // `confidence: "high"` (no stamp) agree with the suggestion-text
      // channel per the doctrine "Reason / priority / fix-description
      // must agree across all three channels."
      if (finding.inFileResolvedTag !== undefined) {
        ctx.emit(base);
        continue;
      }
      // External-JS click attaches without an in-file createElement
      // binding always resolve their target against the DOM — an HTML
      // file separate from this `.js`/`.ts` source — so the per-
      // finding `confidence` cannot honestly be `"high"` from a JS-only
      // read. The receiver might be a native `<button>` / `<a href>`
      // (no 2.1.1 failure) or a bare `<div>` (real failure), and only
      // the HTML knows. Stamp `confidence: "medium"` unconditionally to
      // mirror the per-rule `coverageConfidence: "medium"` the engine
      // records for this rule (`crossFileCapable: false`); when a
      // sibling-module import is also present the suggestion is
      // additionally enriched with the named follow-up file. See
      // doctrine: "Per-finding confidence must reflect per-rule
      // coverage limitations" in docs/kb/architecture/ai-first-
      // consumer.md.
      //
      // Bump `markCrossFileCandidate` on this branch so the per-rule
      // coverage cascade sees the candidate token and downgrades the
      // aggregate row to `coverageConfidence: "medium"` with reason
      // `cross_file_listener_resolution_not_attempted_by_rule` — the
      // same code the per-finding emission carries on
      // `couldBeWrongBecause`. Without this bump a vanilla-JS-only
      // corpus (no JSX `import` from a sibling module, no HTML
      // `<script src>`) emits findings at `confidence: "medium"` while
      // the rule's per-rule row stays at `"high"` — the contradictory
      // shape doctrine "Per-finding confidence must reflect per-rule
      // coverage limitations" warns against. The per-element branch
      // (HTML `<script src>` + JSX sibling-module import) already bumps;
      // this bump closes the parallel gap on the external-JS
      // afterFile-emission branch.
      ctx.markCrossFileCandidate?.();
      ctx.emit(enrichExternalJsFinding(base, siblingImport));
    }
  },
});

type Emit = (v: CrossFileEnrichable) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    const violation = checkOneHtmlElement(el);
    if (violation) emit(violation);
  }
  for (const anchor of findHtmlElementsByTag(doc, "a")) {
    const violation = checkOneHtmlAnchor(anchor);
    if (violation) emit(violation);
  }
}

function checkOneHtmlElement(el: import("../../types/ast.ts").HtmlElement): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} | null {
  const tag = el.tagName.toLowerCase();
  const hasClick = hasHtmlAttribute(el, "onclick");
  const interactiveAttr = findInteractiveHtmlAttribute(el);
  const hasDraggable = getHtmlAttribute(el, "draggable") === "true";
  if (!hasClick && interactiveAttr === null && !hasDraggable) return null;
  if (isNativelyInteractive(tag)) return null;
  // role="button"/etc. does NOT exempt — see module doc comment.
  if (hasHtmlAttribute(el, "onkeydown") || hasHtmlAttribute(el, "onkeyup")) return null;
  const role = getHtmlAttribute(el, "role") ?? null;
  if (hasClick) {
    return {
      severity: "error",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: `<${el.tagName}> has onclick but no keyboard handler — keyboard users can't activate it.`,
      suggestion: buildSuggestion(el.tagName, role),
    };
  }
  if (interactiveAttr !== null) {
    // Attribute-interaction grammar (Bootstrap `data-bs-toggle`, etc.).
    const attr = interactiveAttr;
    return {
      severity: "error",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: `<${el.tagName}> declares interactive behavior via ${attr.name}="${attr.value}" but is not keyboard-focusable — keyboard users can't reach or activate it.`,
      suggestion: buildAttributeSuggestion(el.tagName, attr.name, attr.value, role),
    };
  }
  // Drag grammar — `draggable="true"` with no keyboard pathway.
  return {
    severity: "error",
    location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
    message: `<${el.tagName}> has draggable="true" but no keyboard handler — keyboard users can't perform the drag operation.`,
    suggestion: buildDraggableSuggestion(el.tagName, role),
  };
}

function checkOneHtmlAnchor(anchor: import("../../types/ast.ts").HtmlElement): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} | null {
  // <a> with any href value (including href="#") is focusable and
  // Enter-activates natively; only href-less anchors are a keyboard
  // problem here.
  if (hasHtmlAttribute(anchor, "href")) return null;
  const hasClick = hasHtmlAttribute(anchor, "onclick");
  const interactiveAttr = findInteractiveHtmlAttribute(anchor);
  if (!hasClick && interactiveAttr === null) return null;
  if (hasHtmlAttribute(anchor, "onkeydown") || hasHtmlAttribute(anchor, "onkeyup")) return null;
  if (hasClick) {
    return {
      severity: "error",
      location: { filePath: "", line: anchor.loc.start.line, column: anchor.loc.start.column },
      message: `<a> without href but with onclick is not keyboard-focusable. Add href, change to <button>, or set tabindex.`,
      suggestion:
        'Replace with <button type="button"> if the element triggers an action, or add a real href if it navigates.',
    };
  }
  const attr = interactiveAttr as NonNullable<typeof interactiveAttr>;
  return {
    severity: "error",
    location: { filePath: "", line: anchor.loc.start.line, column: anchor.loc.start.column },
    message: `<a> without href declares interactive behavior via ${attr.name}="${attr.value}" but is not keyboard-focusable.`,
    suggestion: `Add href (even href="#") to make the link focusable, or replace with <button type="button"> — Bootstrap and similar libraries still wire the ${attr.name} handler to either element.`,
  };
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const el of walkJsxElements(module)) {
    const violation = checkOneJsxElement(el);
    if (violation) emit(violation);
  }
  for (const anchor of findJsxElementsByTag(module, "a")) {
    const violation = checkOneJsxAnchor(anchor);
    if (violation) emit(violation);
  }
}

function checkOneJsxElement(el: import("../../types/ast.ts").JsxElement): {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} | null {
  const hasClick = hasJsxAttribute(el, "onClick");
  const interactiveAttr = findInteractiveJsxAttribute(el);
  const hasDraggable = getJsxAttributeString(el, "draggable") === "true";
  if (!hasClick && interactiveAttr === null && !hasDraggable) return null;
  if (isNativelyInteractive(el.tagName.toLowerCase())) return null;
  if (hasJsxAttribute(el, "onKeyDown") || hasJsxAttribute(el, "onKeyUp")) return null;
  // Backdrop pattern: a div/span with onClick but no text content, no
  // aria-label, no role — this is a click-to-dismiss overlay, not a
  // button. Keyboard dismiss is via Escape on the parent dialog.
  if (hasClick && isBackdropPattern(el)) return null;
  // PascalCase components (ActionButton, IconButton, etc.) are custom
  // components whose internals this rule can't see. Trust them by
  // default — "we can't verify" is not a finding. Users whose codebase
  // has a genuinely broken custom component can surface it by scanning
  // that component's source file, where the issue is on a real DOM
  // element. Registering a wrapper in nativeWrappers is for explicit
  // allow-listing when desired.
  if (isPascalCaseComponent(el.tagName)) return null;
  const role = getJsxAttributeString(el, "role");
  if (hasClick) {
    return {
      severity: "error",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: `<${el.tagName}> has onClick but no keyboard handler — keyboard users can't activate it.`,
      suggestion: buildSuggestion(el.tagName, role),
    };
  }
  if (interactiveAttr !== null) {
    const attr = interactiveAttr;
    return {
      severity: "error",
      location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
      message: `<${el.tagName}> declares interactive behavior via ${attr.name}${attr.value === null ? "" : `="${attr.value}"`} but is not keyboard-focusable — keyboard users can't reach or activate it.`,
      suggestion: buildAttributeSuggestion(el.tagName, attr.name, attr.value, role),
    };
  }
  // Drag grammar — `draggable="true"` with no keyboard pathway.
  return {
    severity: "error",
    location: { filePath: "", line: el.loc.start.line, column: el.loc.start.column },
    message: `<${el.tagName}> has draggable="true" but no keyboard handler — keyboard users can't perform the drag operation.`,
    suggestion: buildDraggableSuggestion(el.tagName, role),
  };
}

function checkOneJsxAnchor(anchor: import("../../types/ast.ts").JsxElement): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} | null {
  if (hasJsxAttribute(anchor, "href")) return null;
  const hasClick = hasJsxAttribute(anchor, "onClick");
  const interactiveAttr = findInteractiveJsxAttribute(anchor);
  if (!hasClick && interactiveAttr === null) return null;
  if (hasJsxAttribute(anchor, "onKeyDown") || hasJsxAttribute(anchor, "onKeyUp")) return null;
  if (hasClick) {
    return {
      severity: "error",
      location: { filePath: "", line: anchor.loc.start.line, column: anchor.loc.start.column },
      message: `<a> without href but with onClick is not keyboard-focusable.`,
      suggestion:
        'Replace with <button type="button"> if it triggers an action, or add a real href if it navigates.',
    };
  }
  const attr = interactiveAttr as NonNullable<typeof interactiveAttr>;
  return {
    severity: "error",
    location: { filePath: "", line: anchor.loc.start.line, column: anchor.loc.start.column },
    message: `<a> without href declares interactive behavior via ${attr.name}${attr.value === null ? "" : `="${attr.value}"`} but is not keyboard-focusable.`,
    suggestion: `Add href (even href="#") to make the link focusable, or replace with <button type="button"> — Bootstrap and similar libraries still wire the ${attr.name} handler to either element.`,
  };
}

// ---------------------------------------------------------------------------
// Shared
// ---------------------------------------------------------------------------

function isNativelyInteractive(tagName: string): boolean {
  return NATIVELY_INTERACTIVE_TAGS.has(tagName);
}

function isPascalCaseComponent(tagName: string): boolean {
  const first = tagName[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

/**
 * Detects the modal backdrop pattern: a div with onClick that wraps a
 * dialog element. The onClick is click-to-dismiss on the backdrop
 * overlay — keyboard users close via Escape on the dialog itself.
 * This is a standard ARIA modal pattern, not a keyboard-operability gap.
 */
function isBackdropPattern(el: import("../../types/ast.ts").JsxElement): boolean {
  const tag = el.tagName.toLowerCase();
  if (tag !== "div" && tag !== "span") return false;
  if (hasJsxAttribute(el, "role")) return false;
  // Check if any child has role="dialog" or role="alertdialog"
  return hasDialogChild(el);
}

function hasDialogChild(el: import("../../types/ast.ts").JsxElement): boolean {
  for (const child of el.children) {
    if (child.kind !== "JsxElement") continue;
    const role = getJsxAttributeString(child, "role");
    if (role === "dialog" || role === "alertdialog") return true;
    if (child.tagName === "dialog") return true;
  }
  return false;
}

function buildSuggestion(tagName: string, role: string | null): string {
  if (role) {
    return `This <${tagName}> has role="${role}" but no keyboard handler. Add onKeyDown/onKeyUp handling Enter and Space keys, and ensure the element has tabIndex={0} so it's focusable.`;
  }
  const tag = tagName.toLowerCase();
  if (tag === "canvas") {
    return `The <canvas> is a rendering surface — changing it to <button> would lose the drawing target. Two options: (a) wrap the <canvas> in a <button type="button"> and move the click handler to the button (agent decides based on whether the click represents a canvas-area gesture or a single action), or (b) keep the <canvas> and add role="button" + tabIndex={0} + onKeyDown handling Enter and Space on the canvas itself.`;
  }
  if (tag === "section" || tag === "header" || tag === "footer") {
    return `<${tagName}> is a landmark, not a widget — making the landmark itself click-activatable conflates page structure with interactive controls and hides the action from assistive-tech landmark navigation. Move the onClick to a child interactive element (<button type="button"> inside the <${tagName}>) rather than putting role="button" on the landmark. Screen-reader users navigate landmarks to orient; they navigate buttons to act.`;
  }
  if (tag === "p") {
    return `Two shapes depending on intent: if the whole paragraph is the control (e.g. a tappable call-to-action), replace <p> with <button type="button"> — the button element permits phrasing-content children. If only part of the paragraph is interactive (a word, a span inside surrounding prose), wrap the interactive inline content in a child <button type="button"> and leave the surrounding <p> as non-interactive prose.`;
  }
  return `The simplest fix is to change <${tagName}> to <button type="button"> — buttons are focusable, announce as "button" to screen readers, and fire onClick on Enter/Space automatically.`;
}

function buildAttributeSuggestion(
  tagName: string,
  attrName: string,
  attrValue: string | null,
  role: string | null,
): string {
  const valueClause = attrValue === null ? "" : `="${attrValue}"`;
  if (role) {
    return `This <${tagName}> has role="${role}" and ${attrName}${valueClause} but is not keyboard-focusable. Change to <button type="button"> (preserves ${attrName} — the toggle library still wires it) or add tabIndex={0} plus onKeyDown handling Enter and Space.`;
  }
  const tag = tagName.toLowerCase();
  if (tag === "canvas") {
    return `<canvas> is a rendering surface — converting to <button> loses the drawing target. Move the ${attrName}${valueClause} attribute to a wrapping <button type="button"> around the <canvas>, or keep the <canvas> and add role="button" + tabIndex={0} + onKeyDown (Bootstrap and similar libraries wire the ${attrName} behavior off the attribute wherever it lives).`;
  }
  if (tag === "section" || tag === "header" || tag === "footer") {
    return `<${tagName}> is a landmark, not a widget — hosting ${attrName}${valueClause} on the landmark itself conflates page structure with interactive controls. Move the attribute (and the toggle/dismiss/ride behavior it declares) to a child <button type="button"> inside the <${tagName}>. Keyboard and screen-reader users then reach the control via button navigation, and the landmark stays a landmark.`;
  }
  if (tag === "p") {
    return `Two shapes: if the whole paragraph is the control, replace <p> with <button type="button"> and keep ${attrName}${valueClause} on the button. If only part of the paragraph is interactive, wrap that inline content in a child <button type="button"> and move ${attrName}${valueClause} onto it — Bootstrap and similar libraries wire the behavior off the attribute wherever it lives.`;
  }
  return `The simplest fix is to change <${tagName}> to <button type="button"> and keep the ${attrName} attribute — Bootstrap and similar libraries wire the toggle/dismiss/ride behavior off the attribute, so the interaction still works and keyboard users get native focus + Enter/Space activation.`;
}

function buildDraggableSuggestion(tagName: string, role: string | null): string {
  const roleClause = role ? ` with role="${role}"` : "";
  return (
    `This <${tagName}>${roleClause} has draggable="true" but no keyboard pathway. ` +
    `Add tabIndex={0} so the element is focusable, plus onKeyDown handling Enter/Space or arrow keys to trigger the same operation the drag performs. ` +
    `This rule addresses SC 2.1.1 (keyboard operability); the companion rule pointer/drag-alternative addresses SC 2.5.7 (single-pointer alternative) — both criteria need to be satisfied, typically by a sibling "Move up/down" <button type="button"> that shares the same handler the keyboard path invokes.`
  );
}

/**
 * Returns the first interactive-behavior attribute on an HTML element,
 * or null if none is present. Two grammars are checked:
 *   1. ALWAYS-interactive attributes (`data-bs-dismiss`,
 *      `data-dismiss`) — present at any value → trigger.
 *   2. Value-dependent toggle attributes (`data-bs-toggle`,
 *      `data-toggle`) — only the disclosure values in
 *      {@link DISCLOSURE_TOGGLE_VALUES} make the host a trigger.
 *      Container values like `buttons` and unknown/empty values are
 *      treated as not-a-trigger; explicit grammar guards against the
 *      btn-group FP without inviting heuristic-suppression for
 *      misnamed values.
 *
 * Uses a case-insensitive lookup for the attribute name (HTML
 * attribute matching) and a case-sensitive lookup for the value
 * (Bootstrap's documented values are all lowercase).
 */
function findInteractiveHtmlAttribute(
  el: import("../../types/ast.ts").HtmlElement,
): { readonly name: string; readonly value: string | null } | null {
  for (const name of ALWAYS_INTERACTIVE_ATTRIBUTES) {
    if (hasHtmlAttribute(el, name)) {
      return { name, value: getHtmlAttribute(el, name) };
    }
  }
  for (const name of VALUE_DEPENDENT_TOGGLE_ATTRIBUTES) {
    if (!hasHtmlAttribute(el, name)) continue;
    const value = getHtmlAttribute(el, name);
    if (value !== null && DISCLOSURE_TOGGLE_VALUES.has(value.toLowerCase())) {
      return { name, value };
    }
  }
  return null;
}

/**
 * Returns the first interactive-behavior attribute on a JSX element,
 * or null if none is present. Mirrors {@link findInteractiveHtmlAttribute}
 * — see that function for the two-grammar split (always-interactive
 * vs value-dependent toggles). JSX preserves the original attribute
 * casing — `data-bs-toggle="modal"` in source stays that way in the
 * AST — so the attribute-name lookup is case-sensitive against the
 * lower-case lists; the value comparison case-folds before checking
 * the disclosure set.
 */
function findInteractiveJsxAttribute(
  el: import("../../types/ast.ts").JsxElement,
): { readonly name: string; readonly value: string | null } | null {
  for (const name of ALWAYS_INTERACTIVE_ATTRIBUTES) {
    if (hasJsxAttribute(el, name)) {
      return { name, value: getJsxAttributeString(el, name) };
    }
  }
  for (const name of VALUE_DEPENDENT_TOGGLE_ATTRIBUTES) {
    if (!hasJsxAttribute(el, name)) continue;
    const value = getJsxAttributeString(el, name);
    if (value !== null && DISCLOSURE_TOGGLE_VALUES.has(value.toLowerCase())) {
      return { name, value };
    }
  }
  return null;
}

// External-JS handler grammar (addEventListener / .onclick =) lives in
// handler-missing-external-js.ts — extracted to keep this file under
// the scripts/check-limits.ts file budget. See that module's doc
// comment for the same-file resolution scope and the createElement
// gate.
