/**
 * Rule: keyboard/interactive-div-role-missing
 * Satisfies: wcag22:4.1.2, wcag22:2.1.1, wcag21:4.1.2, wcag21:2.1.1,
 *            section508:4.1.2, section508:2.1.1,
 *            en301549:9.4.1.2, en301549:9.2.1.1
 * Spec:
 *   - https://www.w3.org/TR/WCAG22/#name-role-value
 *   - https://www.w3.org/TR/WCAG22/#keyboard
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies. (SC 4.1.2 Name, Role, Value)
 *
 * > All functionality of the content is operable through a keyboard
 * > interface without requiring specific timings for individual
 * > keystrokes. (SC 2.1.1 Keyboard)
 *
 * Cross-file rule. The failing pattern looks like this:
 *
 *   <!-- index.html -->
 *   <div class="action">Save</div>
 *   <script src="./app.js"></script>
 *
 *   // app.js
 *   document.querySelector('.action').addEventListener('click', save);
 *
 * The `<div class="action">` is wired to a click handler in `app.js`
 * but the host has no `role="button"` (or other interactive role), no
 * `tabindex` (so it isn't focusable), and no accessible name
 * (`aria-label` / `aria-labelledby`). Sighted mouse users can click it;
 * keyboard users can't reach it; screen-reader users hear no role
 * announcement — the conjoined SC 4.1.2 + 2.1.1 failure this rule
 * targets.
 *
 * The sibling `keyboard/handler-missing` rule fires when a JS file
 * attaches a click handler with no keyboard handler in the same file.
 * THIS rule fires when the JS handler resolves to a *non-interactive
 * HTML element*: even if the JS were to add a keydown listener, the
 * element is still neither focusable nor announced as a button. The
 * fix is on the HTML side — either change the tag to `<button>` or
 * add `role="button" tabindex="0"` plus an accessible name.
 *
 * Detection strategy:
 *
 *   1. Walk every scanned `.js` / `.ts` / `.jsx` / `.tsx` source string
 *      for the JS-side click-attach pattern. Two shapes:
 *        a. Inline:   `document.querySelector('.foo').addEventListener('click', …)`
 *        b. Captured: `const el = document.querySelector('.foo'); el.addEventListener('click', …)`
 *      The selector is captured verbatim so the HTML half can resolve
 *      it. Supported selector shapes are id (`#x`), class (`.x`),
 *      tag (`x`), attribute (`[data-x]`), and `getElementById('x')` /
 *      `getElementsByClassName('x')`. Compound selectors fall through
 *      to the agent.
 *
 *   2. For each captured selector, walk every scanned `.html` / `.htm`
 *      file for a matching element. If the matched element is
 *      *non-interactive* (`<div>`, `<span>`, `<li>`, `<img>` and
 *      similar) AND lacks `role="button"` / `role="link"` /
 *      `role="checkbox"` / etc., AND lacks `tabindex`, AND has no
 *      accessible name (`aria-label` / `aria-labelledby`), emit a
 *      finding at the HTML element's location.
 *
 * The emission lives at the HTML element because that's the file the
 * agent edits to fix it (change `<div class="action">` to `<button
 * class="action" type="button">`). The suggestion text names the JS
 * site so the agent can verify the trace before changing the markup.
 *
 * crossFileCapable: true — this rule's design DOES attempt cross-file
 * resolution between JS selectors and HTML elements in the same scan.
 * Per docs/kb/architecture/ai-first-consumer.md "Reason-token suffixes
 * must name the actual predicate, not an input-specific hiccup": when
 * only one half of the pair reaches the scan (HTML present, JS absent
 * or vice versa) we record the limitation as `_limited_on_this_input`,
 * NOT `_not_attempted_by_rule`.
 *
 * Per-finding confidence:
 *   - `"high"` when the selector resolves unambiguously to exactly one
 *     element across all scanned HTML files (id selector with one
 *     match, or class/tag/attribute selector with exactly one match).
 *   - `"medium"` for `querySelectorAll`, class selectors that match
 *     multiple elements, attribute selectors with non-unique matches,
 *     or any compound shape — paired with a `couldBeWrongBecause`
 *     entry naming the limitation. Per the AI-first doctrine
 *     ("Per-finding confidence must reflect per-rule coverage
 *     limitations"), the limitation propagates to per-finding
 *     `confidence`.
 *
 * Severity: `warning`. The rule is statically deterministic about
 * "this element has no role/tabindex/accessible-name and is the
 * target of a click handler", but the agent reading the file may know
 * the page wraps the div in a parent button, or that the page uses a
 * framework whose listener wiring isn't visible here. `warning` +
 * `confidence: medium` for ambiguous selectors matches the predicate
 * strength the rule can honestly express.
 *
 * Out of scope (deliberate):
 *   - JSX `<div onClick={…}>` — handled by `keyboard/handler-missing`
 *     which inspects JSX attributes directly.
 *   - React/Vue/Angular event prop wiring (bound at render).
 *   - Selectors with descendant combinators (`#x .y`), pseudo-classes
 *     (`:hover`, `:nth-child`), or `:is()` / `:where()` — too many
 *     ways to be misled. The agent reading the file resolves these
 *     faster.
 *   - Native interactive elements (`<button>`, `<a href>`, `<input>`,
 *     `<select>`, `<textarea>`, `<summary>`) — these are focusable
 *     and keyboard-activatable by construction; click handlers on
 *     them are fine.
 */

import { defineRule } from "../../api/plugin.ts";
import { getHtmlAttribute, hasHtmlAttribute, walkHtmlElements } from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement } from "../../types/ast.ts";
import type { Language, ProjectRuleFile } from "../../types/rule.ts";
import { findClickAttachmentSites } from "./interactive-div-role-missing-js-targets.ts";

/**
 * Structured `couldBeWrongBecause` code. Suffix `_limited_on_this_input`
 * is correct here per docs/kb/architecture/ai-first-consumer.md
 * "Reason-token suffixes must name the actual predicate" — the rule's
 * design DOES attempt cross-file resolution; the limitation is on THIS
 * input where the static trace cannot reduce ambiguity (selector
 * matches multiple elements, captured-variable reassignment, conditional
 * paths).
 */
const CROSS_FILE_HTML_TARGET_RESOLUTION_LIMITED =
  "cross_file_html_target_resolution_limited_on_this_input";

/**
 * Tag names whose elements are natively interactive — focusable and
 * keyboard-activatable by construction. A click handler resolved to
 * one of these is a non-finding for this rule (the keyboard pathway
 * is satisfied by the platform). Mirrors the `NATIVELY_INTERACTIVE_TAGS`
 * set in `keyboard/handler-missing.ts`.
 */
const NATIVELY_INTERACTIVE_TAGS: ReadonlySet<string> = new Set([
  "a",
  "button",
  "input",
  "select",
  "textarea",
  "summary",
  "details",
  "label",
  "option",
]);

/**
 * Roles whose declaration on an element makes the element
 * focusable-and-activatable in the WAI-ARIA model. A `<div role="button">`
 * with a `tabindex` and accessible name is the documented escape hatch
 * for SC 4.1.2 + 2.1.1; the agent that already did the work shouldn't
 * see a finding.
 *
 * The list is the WAI-ARIA 1.2 widget-role inventory at
 * https://www.w3.org/TR/wai-aria-1.2/#widget_roles.
 */
const INTERACTIVE_ARIA_ROLES: ReadonlySet<string> = new Set([
  "button",
  "checkbox",
  "gridcell",
  "link",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "option",
  "radio",
  "scrollbar",
  "searchbox",
  "separator",
  "slider",
  "spinbutton",
  "switch",
  "tab",
  "tabpanel",
  "textbox",
  "treeitem",
  "combobox",
  "listbox",
  "menu",
  "menubar",
  "radiogroup",
  "tablist",
  "tree",
  "treegrid",
]);

/** Languages whose source we scan for the JS-side click-attach pattern. */
const JS_LIKE_LANGUAGES: ReadonlySet<Language> = new Set<Language>(["js", "ts", "jsx", "tsx"]);

export const rule = defineRule({
  id: "keyboard/interactive-div-role-missing",
  satisfies: [
    "wcag22:4.1.2",
    "wcag22:2.1.1",
    "wcag21:4.1.2",
    "wcag21:2.1.1",
    "section508:4.1.2",
    "section508:2.1.1",
    "en301549:9.4.1.2",
    "en301549:9.2.1.1",
  ],
  severity: "warning",
  scope: "project",
  fixClass: "verify-in-source",
  // crossFileCapable: true. The rule's design DOES attempt cross-file
  // resolution (JS click-attach selectors → HTML host elements) in the
  // same scan. Per ADR 0026 and docs/kb/architecture/ai-first-consumer.md
  // "Reason-token suffixes must name the actual predicate", a rule
  // declaring `crossFileCapable: true` does NOT downgrade per-rule
  // coverage to `"medium"` by default — the scanner trusts the rule
  // ran with full evidence. Per-finding `confidence: "medium"` is
  // stamped on individual findings whose static trace cannot reduce
  // selector ambiguity.
  crossFileCapable: true,
  appliesTo: {
    // The rule walks both halves; the engine's eligibility gate is
    // satisfied when either extension is present. We list every JS-like
    // and HTML extension so per-rule coverage telemetry credits both
    // file kinds correctly.
    fileExtensions: [".html", ".htm", ".tsx", ".jsx", ".ts", ".js"],
  },
  docs: {
    description:
      "When a JS file binds a click handler (via document.querySelector / getElementById / etc.) to a non-interactive element (<div>, <span>, <li>, <img>) and the resolved HTML element has no role, tabindex, or accessible name, emit a finding so the agent can change the markup to <button> or add the missing ARIA wiring.",
    rationale:
      "A vanilla-JS app calling `document.querySelector('.action').addEventListener('click', save)` against a `<div class=\"action\">` produces an interaction sighted mouse users can perform but keyboard and screen-reader users cannot — the host element is neither focusable (no `tabindex`) nor announced as a button (no `role`). This rule pairs JS click-attach sites with their HTML targets and emits at the HTML element, since that's the file the agent edits to fix it. The suggestion names the JS site so the agent can verify the resolution before changing the markup. Two SCs are violated simultaneously: 4.1.2 (the role isn't programmatically determined) and 2.1.1 (the element isn't keyboard-operable).",
    goodExample: `<!-- index.html -->\n<button type="button" class="action">Save</button>\n<script src="./app.js"></script>\n\n// app.js\ndocument.querySelector('.action').addEventListener('click', save);`,
    badExample: `<!-- index.html -->\n<div class="action">Save</div>\n<script src="./app.js"></script>\n\n// app.js\ndocument.querySelector('.action').addEventListener('click', save);`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/WCAG22/#keyboard",
      "https://www.w3.org/WAI/WCAG22/Techniques/general/G108",
      "https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA4",
    ],
    knownLimitations: [
      "Only simple selectors are resolved: `#id`, `.class`, `tag`, `[attr]`, plus `getElementById` / `getElementsByClassName`. Compound selectors (descendant, pseudo-class, `:is()` / `:where()`) and dynamic / runtime-built selectors fall through to the agent.",
      "JSX `<div onClick={…}>` is handled by `keyboard/handler-missing`, not this rule. This rule targets the cross-file pattern where the click-attach lives in JS and the host element is declared in HTML.",
      "When the JS half references a selector for which no scanned HTML carries a matching element, no finding is emitted — the rule has nowhere to point.",
    ],
  },
  afterProject(ctx) {
    const sitesBySelector = collectClickAttachSitesBySelector(ctx.files);
    if (sitesBySelector.size === 0) return;
    const matches = resolveSelectorsAcrossHtml(ctx.files, sitesBySelector);
    for (const match of matches) {
      ctx.emit(buildHtmlFinding(match));
    }
  },
});

// ---------------------------------------------------------------------------
// JS half — collect (selector, sites) from every scanned JS-like file.
// ---------------------------------------------------------------------------

/**
 * Where a click handler was attached on the JS side — file:line:column
 * plus the receiver shape so the suggestion can name the exact call
 * the agent grep'd to find this finding.
 */
interface ClickSite {
  readonly filePath: string;
  readonly line: number;
  readonly column: number;
  readonly shape: "addEventListener" | "onclick";
}

/**
 * The JS detector returns `(selector, site)` pairs; we group by
 * selector so the HTML walk can report every JS site that targets a
 * given HTML element. A selector that resolves to multiple HTML
 * elements (e.g. `.action` matching 3 divs) emits one finding per
 * matched element.
 */
interface CapturedSelector {
  /** The selector string verbatim (`.action`, `#save`, `[data-toggle]`). */
  readonly selector: string;
  /** The shape the selector was captured in. */
  readonly kind: "id" | "class" | "tag" | "attribute";
  /** The exact match name (id value, class name, tag name, attribute name). */
  readonly value: string;
}

interface ClickAttachRecord {
  readonly captured: CapturedSelector;
  readonly sites: readonly ClickSite[];
}

function collectClickAttachSitesBySelector(
  files: ReadonlyArray<ProjectRuleFile>,
): ReadonlyMap<string, ClickAttachRecord> {
  const out = new Map<string, ClickAttachRecord>();
  for (const file of files) {
    if (!JS_LIKE_LANGUAGES.has(file.language)) continue;
    for (const site of findClickAttachmentSites(file)) {
      const key = `${site.captured.kind}:${site.captured.value}`;
      const existing = out.get(key);
      const newSite: ClickSite = {
        filePath: file.filePath,
        line: site.line,
        column: site.column,
        shape: site.shape,
      };
      if (existing === undefined) {
        out.set(key, { captured: site.captured, sites: [newSite] });
      } else {
        out.set(key, { captured: existing.captured, sites: [...existing.sites, newSite] });
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// HTML half — for each captured selector, walk every HTML file and find
// non-interactive elements that match.
// ---------------------------------------------------------------------------

/** A successful pairing of a JS click-attach selector with an HTML host. */
interface SelectorMatch {
  readonly htmlFilePath: string;
  readonly element: HtmlElement;
  readonly captured: CapturedSelector;
  readonly sites: readonly ClickSite[];
  /** Total HTML elements this selector resolved to across all scanned HTML. */
  readonly totalMatchesAcrossHtml: number;
}

function resolveSelectorsAcrossHtml(
  files: ReadonlyArray<ProjectRuleFile>,
  sitesBySelector: ReadonlyMap<string, ClickAttachRecord>,
): readonly SelectorMatch[] {
  const matchesPerKey = new Map<string, SelectorMatch[]>();
  for (const file of files) {
    if (file.language !== "html") continue;
    collectHtmlMatches(file, sitesBySelector, matchesPerKey);
  }
  return stampPerSelectorTotals(matchesPerKey);
}

/** Walk one HTML file, append every flaggable selector match to `out`. */
function collectHtmlMatches(
  file: ProjectRuleFile,
  sitesBySelector: ReadonlyMap<string, ClickAttachRecord>,
  out: Map<string, SelectorMatch[]>,
): void {
  const doc = file.ast as HtmlDocument;
  for (const el of walkHtmlElements(doc)) {
    if (!isFlaggable(el)) continue;
    for (const [key, record] of sitesBySelector) {
      if (!htmlElementMatchesSelector(el, record.captured)) continue;
      const list = out.get(key) ?? [];
      list.push({
        htmlFilePath: file.filePath,
        element: el,
        captured: record.captured,
        sites: record.sites,
        // Filled in by stampPerSelectorTotals once all files are walked.
        totalMatchesAcrossHtml: 0,
      });
      out.set(key, list);
    }
  }
}

/**
 * Stamps the per-selector total onto each match. Confidence downgrades
 * to `"medium"` when a selector resolved to >1 HTML host (the rule
 * cannot tell which the JS site actually targeted).
 */
function stampPerSelectorTotals(
  matchesPerKey: ReadonlyMap<string, readonly SelectorMatch[]>,
): readonly SelectorMatch[] {
  const stamped: SelectorMatch[] = [];
  for (const [, list] of matchesPerKey) {
    const total = list.length;
    for (const m of list) {
      stamped.push({ ...m, totalMatchesAcrossHtml: total });
    }
  }
  return stamped;
}

/**
 * Walks the HTML element's attributes to decide whether the captured
 * selector targets it. Only simple-selector matches; compound selectors
 * stay off-table per the doctrine note in the module header.
 */
function htmlElementMatchesSelector(el: HtmlElement, captured: CapturedSelector): boolean {
  switch (captured.kind) {
    case "id":
      return getHtmlAttribute(el, "id") === captured.value;
    case "tag":
      return el.tagName.toLowerCase() === captured.value.toLowerCase();
    case "class": {
      const classAttr = getHtmlAttribute(el, "class");
      if (classAttr === null) return false;
      for (const token of classAttr.split(/\s+/u).filter(Boolean)) {
        if (token === captured.value) return true;
      }
      return false;
    }
    case "attribute":
      return hasHtmlAttribute(el, captured.value);
    default:
      return false;
  }
}

/**
 * Returns true when the matched element is a non-interactive host that
 * lacks a role, tabindex, or accessible name — the conjoined SC 4.1.2 +
 * 2.1.1 failure pattern. Returns false (= no finding) when:
 *
 *   - The tag is natively interactive (`<button>`, `<a href>`, `<input>`,
 *     `<select>`, `<textarea>`, `<summary>`).
 *   - The host carries any `role` value at all that is in the
 *     interactive-widget-role inventory (`role="button"`, `role="link"`,
 *     `role="checkbox"`, …) — the agent has done the ARIA work.
 *   - The host has a `tabindex` attribute (focusable in the tab order
 *     when ≥0, programmatically focusable when -1; either way the
 *     agent has thought about it).
 *
 * The accessible-name check is folded into the suggestion text rather
 * than gating emission: `aria-label` without `tabindex` still leaves
 * the element keyboard-unreachable, so the SC 2.1.1 half stays alive.
 *
 * `<a>` without `href` is treated as non-interactive — the spec is
 * clear that an anchor is only focusable when it carries an href.
 */
function isFlaggable(el: HtmlElement): boolean {
  const tag = el.tagName.toLowerCase();
  if (tag === "a") {
    const href = getHtmlAttribute(el, "href");
    if (href !== null) return false;
  } else if (NATIVELY_INTERACTIVE_TAGS.has(tag)) {
    return false;
  }
  if (hasHtmlAttribute(el, "tabindex")) return false;
  const role = getHtmlAttribute(el, "role");
  if (role !== null) {
    for (const token of role.split(/\s+/u).filter(Boolean)) {
      if (INTERACTIVE_ARIA_ROLES.has(token.toLowerCase())) return false;
    }
  }
  return true;
}

// ---------------------------------------------------------------------------
// Emission.
// ---------------------------------------------------------------------------

function buildHtmlFinding(match: SelectorMatch): {
  severity: "warning";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
  confidence: "high" | "medium";
  couldBeWrongBecause?: readonly string[];
} {
  const { element, captured, sites, totalMatchesAcrossHtml } = match;
  const tag = element.tagName.toLowerCase();
  const sample = sites[0];
  const sampleLabel =
    sample === undefined
      ? ""
      : ` (e.g. ${sample.filePath}:${sample.line}, attached via ${sample.shape === "addEventListener" ? ".addEventListener('click', …)" : ".onclick = …"})`;
  const moreClause =
    sites.length > 1 ? ` plus ${sites.length - 1} other site${sites.length === 2 ? "" : "s"}` : "";
  const selectorLabel = describeSelector(captured);
  const tagLabel = tagDescriptor(element);
  const ambiguous = totalMatchesAcrossHtml > 1;
  const confidence: "high" | "medium" = ambiguous ? "medium" : "high";
  const couldBeWrongBecause = ambiguous ? [CROSS_FILE_HTML_TARGET_RESOLUTION_LIMITED] : undefined;
  return {
    severity: "warning",
    location: {
      filePath: match.htmlFilePath,
      line: element.loc.start.line,
      column: element.loc.start.column,
    },
    message: `<${tagLabel}> is wired to a click handler in JS via ${selectorLabel}${sampleLabel}${moreClause}, but it has no role, no tabindex, and isn't a native interactive element — keyboard users can't reach it and screen-reader users hear no role announcement.`,
    suggestion: buildSuggestion(tag, captured, sites, ambiguous),
    confidence,
    ...(couldBeWrongBecause === undefined ? {} : { couldBeWrongBecause }),
  };
}

function describeSelector(captured: CapturedSelector): string {
  switch (captured.kind) {
    case "id":
      return `\`#${captured.value}\``;
    case "class":
      return `\`.${captured.value}\``;
    case "tag":
      return `\`${captured.value}\``;
    case "attribute":
      return `\`[${captured.value}]\``;
    default:
      return `\`${captured.value}\``;
  }
}

function tagDescriptor(el: HtmlElement): string {
  const tag = el.tagName.toLowerCase();
  const idAttr = getHtmlAttribute(el, "id");
  const classAttr = getHtmlAttribute(el, "class");
  if (idAttr !== null && idAttr !== "") return `${tag} id="${idAttr}"`;
  if (classAttr !== null && classAttr !== "") return `${tag} class="${classAttr}"`;
  return tag;
}

function buildSuggestion(
  tag: string,
  captured: CapturedSelector,
  sites: readonly ClickSite[],
  ambiguous: boolean,
): string {
  const siteList = sites
    .slice(0, 3)
    .map(
      (s) =>
        `${s.filePath}:${s.line} (${s.shape === "addEventListener" ? ".addEventListener('click', …)" : ".onclick = …"})`,
    )
    .join(", ");
  const moreNote = sites.length > 3 ? `, plus ${sites.length - 3} more` : "";
  const ambiguityClause = ambiguous
    ? `Note: ${describeSelector(captured)} resolved to multiple HTML elements in this scan; verify ${siteList}${moreNote} is targeting THIS element before fixing. `
    : "";
  return (
    `Best fix: change \`<${tag}>\` to \`<button type="button">\` (or \`<a href="...">\` for navigation) — the platform makes it focusable and Enter/Space-activatable for free. ` +
    `If the markup must stay a \`<${tag}>\`, add \`role="button" tabindex="0"\` and an accessible name (visible text content, \`aria-label\`, or \`aria-labelledby\`), and wire a \`keydown\` listener on the same target so Enter and Space invoke the click handler. ` +
    `${ambiguityClause}` +
    `JS sites: ${siteList}${moreNote}.`
  );
}
